// Auto-generated by Material Symbols SVG Extractor (v0.9)
// FORMAT: KICONS_V1_NO_DECODERS
// Category: search
// Location: E:/apps/3rdParty/material-design-icons/src/search/
// Each icon is Base64(zlib(minified-SVG)). Decode with ZDecompress(Base64Decode(...)).

#ifndef UPP_MATERIAL_SYMBOLS_ICONS_SEARCH_H
#define UPP_MATERIAL_SYMBOLS_ICONS_SEARCH_H

#include <Core/Core.h>
#include <plugin/z/z.h>

namespace search {

using namespace Upp;

enum Style : uint8 { OUTLINED = 0, ROUNDED = 1, SHARP = 2 };

struct BaseSVGIcon {
    const char* category;
    Style       style;
    const char* name;
    const char* source;
    const char* b64zIcon;
};

// bathroom [outlined]  source: src/search/bathroom/materialiconsoutlined/24px.svg
static const char search_outlined_bathroom_b64z[] =
    "eJyVkk1vgzAMhv9KxDkJsUn4mFoO64VLT5V6bykDtI5WhUHVXz87ZdMqTZsmosSx3+dNsLLox1pc345d"
    "vwyaYTg/heE0TXqK9OlSh2iMCUkRiKrb7Y+V2u/K1/pyeu8Oy6CrJmHoQ0sjEE3V1s2wDDge22p6Pl2X"
    "wbf61B6GxpfzRZ0vzruhEeSyNtI0aEe0hdmaWyBe2uORzE9dFYT5Iqwf1akEWxpltHPSaOsUSFDQg99I"
    "2vTqHnFhw2pW8noTa0AJrryzpPgU3hEFysfw5Ss2AF5Cg0l2cP9y2NDxs4GbDVAm2pUKdBJLoyKN5Kwj"
    "oMjGMmpinUViBY7zqU7JI2IlMfKOeou4RM9LJ1GjpcWNUCSjglVCGGUynmJmYjo1k5D+fmvxcO3UK1LJ"
    "3Ny3P/jHv4aZ9+Dcth8MxF99S33f2AGNtIUdIW4g3lq/xxI0IRIJy2hGqpZkr/kASihKFZZbTSqFnKQZ"
    "iaYH5JOcYF2B9PDmx8bPPf8A/Y+07A==";

// bed [outlined]  source: src/search/bed/materialiconsoutlined/24px.svg
static const char search_outlined_bed_b64z[] =
    "eJxtUUtvwyAM/isWdwiYV1YlOWyXXnrtvU2zEC1NqjaDKr9+ptKkraqMjOXvgYHqFnu4n8fpVrOwLJdN"
    "UaSURNJivvYFSikLYjDopsNx7Pjx0H711/l7OtVs6hJICjS0GIRu6MNSs1zHoUvv871mf/A0nJbwgJuq"
    "b6rLYQlALjuiBDQRzVbu5crgcxhHMp+njhVNVfT/2ahASeHLfdlKroSzlLTlOkfgpuXCe8iI8UJzBKJy"
    "YTUXpqQmUkENzHnrPgxJwYIGlwsNZUQCyMMpYckZyNvQhgIxuoCRY1AuYq4cnS9KMtdveQ7PFc+0dacM"
    "+GBaMqC7KxDGUlYk4u4xNAHUy+ZcrTsLz71X2q3dl+uZcE8jPPPVK4FZf18v/1/zA1uId+s=";

// bedroom_baby [outlined]  source: src/search/bedroom_baby/materialiconsoutlined/24px.svg
static const char search_outlined_bedroom_baby_b64z[] =
    "eJxVUk1v2zAM/SuCzxIt6tMakhzWiw/uaUDuqetawTynaDy7yK8fqWRYBxn0Ix/JR8reXddRfP6a5uu+"
    "ysvy/q2ut22DzcLlY6yN1rqmjEoM8+llGtTLqf85flx+z6/7ah42oekYR08l8nAe87KvGK/nYft++dxX"
    "X/jt/LrkQh9242H3flqyoC7PWups3Gpcq4/6Vom38zRR88s8VPVhV4//Z2OE5CQ60K5XGqyTbAhFJBSc"
    "QmCQTIdBogV/RMy4KszKQzBdguBlbMPEWTF0HrxM4Ccq8RK7hh1cLaQ0UdOGpMAFUaQSGRNZKpDxDUup"
    "IkWVHrBHaKIsxoEN0kCSke2VSEvZ2sqoyO++LHETzw240iAiTaEttdSBUINU4lBQ28hb0twWQrgjDxQq"
    "STzgvVByYf+4AI+kxKGYFN2CL+hHYoQBjJX/VGkEo6VbMbTu6Fqji29aJ554BcOnvDml1/Jxw3ciU6gE"
    "pFElqMzRPZlHCTMEibz9/Zj8Ox3+AA5nlAU=";

// bedroom_child [outlined]  source: src/search/bedroom_child/materialiconsoutlined/24px.svg
static const char search_outlined_bedroom_child_b64z[] =
    "eJxVUUFugzAQ/Irls23Wi4lNBRyaC5dcuSeEYlQKUUIhyuu7thK11SJ5dmZ2WNnFbe3Z/WucbiX3y3J5"
    "S5Jt29SWqvnaJwgACTk466bjaezk6dh+9tf5ezqXfOo2BlRo6OPMd0Pvl5IHvA7d9j7fS/5H34bz4qNc"
    "FX1VXI6LZ5RyAAEezYqmhgYenH0M40jh89TxpCqS/r8bQZhV72rTmBqBhR5rs0eVCwwVz+BoQWilBbwE"
    "T1QkBMpISmxo7jkSFIIkPthB71QmNKidbXLWgiQxjEgM5WXWyhgkUURW4KrJ25LHOaLSjHQKUBhPVNho"
    "6wmuofc5dbV2qzRKp3vthNbKWaGtSiMGFL8LsLBOJhwNY52vEmudEWWDjjS2f6I0F1a5nCB5U0pDbxXa"
    "FpShlWgp+gME1xM522jjZR5W0mlNKY/XbYf3rn4Ay3OB5Q==";

// bedroom_parent [outlined]  source: src/search/bedroom_parent/materialiconsoutlined/24px.svg
static const char search_outlined_bedroom_parent_b64z[] =
    "eJxVUkFuwjAQ/IqVs+14NzYmFXAol1y45g4hjVFpQJA6iNd3bBWplSONd2Znd+14dY+DeHydx/u6CNN0"
    "fSvLeZ71XOnLbSjZGFMioxD9uD+ce3XYd5/D7fI9HtfF2M/CYLHFV4jQn4YwrYu0j6d+fr881sUffT4d"
    "p5DlzWrYrK77KQhU2RlpAtvItjGteRbi43Q+o/hl7ItysyqH/9m01JWTRNq6tu6MIk3K6FpxWg1VHaLK"
    "SwPwLI0mVgSoeAsPGA8m2ZHjgdI3Xi9cl+rAlByoJTkyGoit05yb1SSBrF3GSpNvyQfSLsLoAhHChuqo"
    "Kr2stlT/5mJY//L/GfwpdrTIioFZ2ag42DYFUHxquQRvRWSI7TLT5DXybVBE6Nml8zmHaa3D+UhRwGVk"
    "RlJmARjKwslG2kiLxra2YZNjbuyWdS05rYwpQ3Qwp2t4KYEWXSYkq0wqbmH89SQFW4jP149KT2XzA2cd"
    "jkM=";

// blender [outlined]  source: src/search/blender/materialiconsoutlined/24px.svg
static const char search_outlined_blender_b64z[] =
    "eJxlUU1vgzAM/StRzklInA9gAg7rhUN77b1NGUFjUFEGXX/9HLZJlSYnduJnv9hOcVtacv/oh1tJwzxf"
    "X5JkXVexajFObQJSygQjKGmG07lv+Pnk39tp/BwuJR2alUgUMLgoCU3Xhrmk8bx0zfo63kv6hK/dZQ4b"
    "XBVtVVxPcyDIcpBMBjALmFoe5YOSt67vkXwcGppURdJu0c8JygmlmbKo9ypjOnBzBFSLqu1Oi5zpKJu1"
    "i/GSKaGYxDtECSBA91I4wwwy7JxIDUNKaZljKhVGR5svivzLzPx2Z8A3H4eFqx1W8JOFGtwv01OJD3Kw"
    "LD/aoIRW8V1gprboRdSlzPYcgYzldS5S2GdCY9Wk3sAY5BjIOsOHvMRAh9RCW479cR3Abx6JjUZv7PoI"
    "OEIcm+8m3zfE4xcooMR/oc0omdD8TXXb+LfVN+eZf/s=";

// camera_indoor [outlined]  source: src/search/camera_indoor/materialiconsoutlined/24px.svg
static const char search_outlined_camera_indoor_b64z[] =
    "eJxVkM1uhCAURl+FsObnXoRJbNRFVy6c7ewdh4op1cmMhYlPX8Q0afMRQs65+SBUzzCS15efnzV163p/"
    "kzLGKGIhlscoFQDINEGJnfurt/zaD5/jY/mebzWdbSSQonRalDg7jW6t6X4Ok43vy6umf3ycbqvLuqnG"
    "prr3qyOp5QwMnNJB6RYusFHyMXmfypfZUtlUcvw/jZphETgOwEEYkzZtOO5pyyEjBhzZgRkGPaT+TBNh"
    "uMcllglDflCOqdErhgJOgWuBqsv3bOSMihlh/IlpYULZJl12B8uu6DQrAyqHp0sWxfb76v3fmh9/RlvF";

// camera_outdoor [outlined]  source: src/search/camera_outdoor/materialiconsoutlined/24px.svg
static const char search_outlined_camera_outdoor_b64z[] =
    "eJxVkMFugzAQRH/F8tnGu8agJgIOPeVArtwJcTGqC1FC7Yiv75qoUquxRtbb0azl6hFG9vzy86Pmbl1v"
    "R6VijFnMs+U+Kg0AihKc2bm/eCsv/fA53pfv+Vrz2UYGJG3ocObsNLq15ukeJhvfl2fN/8zjdF3dPm6q"
    "salu/eoYtZxBgNMmaHOCDjbOPibvqXyZLVdNpcb/aXwTmA8gISsKMlNITHLSDDsTIFG8uMBgBmrfKRGB"
    "SY7YTgTKF5UYJHotMIMySJOhbtMW02G+sTNqkbPWiENA7ZAC+kR28CUlC18K8oBOd4c2JbffN6dfa34A"
    "0HNb4g==";

// chair [outlined]  source: src/search/chair/materialiconsoutlined/24px.svg
static const char search_outlined_chair_b64z[] =
    "eJx9kk1zgyAQhv8Kw5lFvkTTUQ/NxUuu3hNixanVTGIxk19fkCaTTjsdHITdh/fdFYuL69D1YxgvJbbz"
    "fHpJkmVZ6CLpdO4SwRhLPIFRO+4PQwuHvXnvztPneCzx2C6I+SGUfzCybd/ZucRh7fp2eZ2uJX7KL/1x"
    "tmu6KrqqOO1ni7zKjhFmhXJC1axhN4ze+mHw4tPY4qQqku4nLRjJG20YcKpTP8kUZBh1tk39hkiiiAoL"
    "RbQTZsUIA0kiSqRLDSNrlEc+xLiPMZp6kiqfCAOZGCAcYhC4A265+Av+kzXRm0iITiAdpFshySZsxZrN"
    "SWjohnaaaO8ID13gQcVy9pB+2DlBs9x4VPO1joBSqfxLUCGcqDMHYtXKcz/JTfgIGXAI6UZ7M+FPBLt4"
    "/F4y4bUy3xVA7ATWTtLfhV2eylGWKwfqX6jh+na/zvBDVV9YMJVV";

// chair_alt [outlined]  source: src/search/chair_alt/materialiconsoutlined/24px.svg
static const char search_outlined_chair_alt_b64z[] =
    "eJxdUEtvwyAM/iuIMwTzKtuU5LBdcuk19zRlEC1LqjaDqr9+JtKkbTLC9vcwj/qWArl/zsutoXHbLi9C"
    "5JyrrKv1GoQCAIEKSvwynGbPT8P4Ea7r13Ju6OIzAQxlcFES/RTi1tBSp8nn1/Xe0F98ns5b3Om2Dm19"
    "GbZIcMoRGERlkjId9PCg5H2aZxy+Lp6Kthbhr1o6JmGUlWTAFIfqGXfV2xE4YqXnqkTn3ixymlmmMVtm"
    "kx6B7b7iKRFlQt3Id5ArtpuZSi6qxHWUkHSpHPk/PHKZ8AjpHuTo2FNvd21X2nK9Q+eQRqyXhwIZJtFi"
    "CmZ6qR4/zyof234DEEFlAw==";

// coffee [outlined]  source: src/search/coffee/materialiconsoutlined/24px.svg
static const char search_outlined_coffee_b64z[] =
    "eJxVkU1vgzAMhv9KlLMx+SZMwGG9cOlpEveWMYLGoGoZVP31c4ombUoiv29s+bGS4rb27P41TreSh2W5"
    "vKTptm24aZyvfaqEEClVcNZNp/PYJedT+9lf5+/pveRTtzFBSxnanIVu6MNS8qjXodte53vJ/+S34X0J"
    "z3RV9FVxOS2BUZejABGUWZWpRSMenH0M40jN56njaVWk/f9q6dGCrt3BYA4aDGiKBuxqMZOtIOs1KMwt"
    "ZCg9OMw8KZW3VOdAoFTRqkSjcLvK1kQGgbaVmGuIHWwi0WZPQYe9KYFGE2xnP9hROgLSEI2tpdu9FGvE"
    "K8xcolDRRIkFe0vs01GwhGH7+L6WvrGReZA5ag0WlACLLovRReR+73ekJ4QBmQfpVlWbRuaP36eJn1P9"
    "AMMjcIY=";

// coffee_maker [outlined]  source: src/search/coffee_maker/materialiconsoutlined/24px.svg
static const char search_outlined_coffee_maker_b64z[] =
    "eJxNUclugzAQ/RXL58GMNwIVcGguXHKqlHtCCEalEBFq0nx9x64qRWN7lvfmeSvvvmePr3G6V9yt6+0t"
    "TbdtE5sW89KnChFTYnDWTafz2CXnU/vZL/P3dKn41G0MyZShwZnrht6tFQ+xH7rtfX5U/AXfhsvqIlyX"
    "fV3eTqtjpHJAQKeMV6bBIz45uw7jSOLz1PG0LtM+sl8bZA7Z0Th1VE22N6IABQYUeQPGy6xFkEICRoDM"
    "SeMT5RIjUO/lTiiQhcACSIayzMQg84ltcm9jM9VQ5BJ0oClqA8OauKVXREBhLS3Gggzm8qBKpV1QykIU"
    "/JMdJEZh7TKv/4RtIoW2oBMN+iPAdACiB94z3LYdlnbsWEsvJzVn7U/FC84Wyv7fIk76kfoXb+9wpw==";

// dining [outlined]  source: src/search/dining/materialiconsoutlined/24px.svg
static const char search_outlined_dining_b64z[] =
    "eJxVUk2Pm0AM/SsjzoMZm2EGqiSH5sKhOVXins2yEJWS1YbCan99nyGRWgGe589nj9nd5858/h7G+z7p"
    "p+n9W5Yty0JLTrePLhPnXIaIxLTj+WVo05fz5Vf3cfszvu6TsV2MwyMeb2L69tr10z5RPF/b5fvtc5/8"
    "41+ur1O/ug+77rB7P0+9QZWTs64XP4uvXeO+EvN2HQYUv41tkh12Wfd/NHuKhQ2XlCmP1qVChWUqZAU5"
    "+YuD6kvrKFqhyNBChIPLH+wtCwVpuOqRMqeB8nJw5MoUIjcXR1UE9HFNAsMDaPaRI0lhIxW55UCc22Af"
    "vZhTAHdFFRA7wHDEIWuEs4FEtrNoqrpCkQYQZGASZRaBKJ7fXYV9WgE0C6yadIxaXOuhlxLlow0/w9O2"
    "gWLOqcQlYJYcImDm7Rb0mqr8MbvR4WPExGVYW9CAlDepYcrG/GyeYrkOowxf5iTO+trPHHoOjV91uTCx"
    "xanEkALvugpOV0MKU+2Nro11a2qFlAYL22yqa1wt+Akei9df7/AX9bWcDg==";

// door_back [outlined]  source: src/search/door_back/materialiconsoutlined/24px.svg
static const char search_outlined_door_back_b64z[] =
    "eJxNUE1vgzAM/StRzoHYgYilAg7bhUuv3FuaJWgMKpolXX/9DNLUyrZs+fnj2fUtOnb/nuZbw30I14OU"
    "KaU8FfmyOqkAQFIFZ3Y+nSebnU/Dl1uXn/nS8NkmBiSqJOXM29H50PAtjqNN78u94S94Gi/B73Bbu7a+"
    "noJnNOUIArwqoyo76OHB2ec4TTR8mS2XbS3dXv3agEag6fUAGeaYQW4ytUlXfejciEJoUZDXQkcsuyIq"
    "j2+RYDQPdsSKeruq1x6hp8y2YrVDeLJ/EuWMDjCc/TYc8Z/LbvSR9g+naVbs";

// door_front [outlined]  source: src/search/door_front/materialiconsoutlined/24px.svg
static const char search_outlined_door_front_b64z[] =
    "eJxVT0tvgzAM/itRznnYCRFjAg7rhUuv3GmbJWgsVG2aVPz6hU2TNn2WbPl7WG7vyZHn5xLuHfUxXl+l"
    "zDmLrMV6c1IBgCwKSmyYTovlp+n84W7rI1w6GmwmUKCqUpR4OzsfO7rPabb5bX129A+f50v033Tfur69"
    "TtGTknIEBl5VSVUDjLBR8j4vSwlfg6Wyb6X7r8aGYTOaM3AUyEE0XO0Y6oMRDdPMMF26YSZhNeikPL6k"
    "QmOzkSPWxTvUo/EI489GM0SvioyrEXH7vbj/3H8Bw69OMQ==";

// door_sliding [outlined]  source: src/search/door_sliding/materialiconsoutlined/24px.svg
static const char search_outlined_door_sliding_b64z[] =
    "eJxVkMFuwjAMhl8lyjlpbLdBMLU9cOqFa++lZElFlyIoCeLpl1RC2mTLsj//tizXj2DZ62f2j4a7db19"
    "KRVjLGJZLHerCABUUnBm/HCejTwP49Xel6e/NNybyCAZVck5c2aybm14zsNk4nF5NfxPP06X1W3ttrZt"
    "fRtWx9KWEwhwVAWqOujhzdn3NM9p+eINV22t7H81gsCy2wdJjnos3+yEO4HoJIWNYCKEAg+BujKrsNcj"
    "SCxQQHGQJCgzGjcgKMMUKWDVUZ5FFLrbpdLpXud6LzRzUn/I56b8lfYXCb5XDw==";

// doorbell [outlined]  source: src/search/doorbell/materialiconsoutlined/24px.svg
static const char search_outlined_doorbell_b64z[] =
    "eJxVUctugzAQ/BXLZ9t4F5tABRzaC4fkVIk7IRSjUogSakf5+i5EfcnW7GNmx7acX33Pbh/jdC24W5bz"
    "UxSFEFSI1XzpI9RaR6TgrJua49jJY9O+95f5czoVfOoC07TQ0ObMdUPvloKvuR+68DzfCv6HD8NpcRtd"
    "5n2Zn5vFMXI5aKEdGo+m0rW+c/Y2jCOZz1PHozKP+v9qAAGJsg5bmlPWSq2MFSCp/bpyO6WpfIju7ABU"
    "WC9RxabVEpQ1NJACNVIkQCtjBUmdUUY8eQFBvIp29hfYdQvihxIr0JR9ychIEBiR0bEKcI2okqQGW6Ue"
    "XOolVLDdBYVVdp8I0D5zgF5m+0dv4+IxFYkHrEy99eP79/vXHyi/ADVKawA=";

// feed [outlined]  source: src/search/feed/materialiconsoutlined/24px.svg
static const char search_outlined_feed_b64z[] =
    "eJxVkE1PxCAQhv8K4UzL8CXWtD3ohYN75d7dRWis7Wa3wqa/Xqgxal4SyDMPk8m0t+jR/WOabx0O63p5"
    "ojSlVCdRL1dPOQDQbGDk5uE4ueo4nN79dfmczx2eXUKQw2U+GAU3+rB2uLzj6NLzcu/wn3oaz2vYy33r"
    "+/YyrAHlLgcgELiMXBqwsGH0Nk5Tbr7MDtO+pf6/zR6IMOpF1A0RJfutIpMnIKxmBDLgJSGjHRBe7bDi"
    "9vG1fN/QgTWENUZZFRhEGaRlTaaaMF1AxY22TBePE200ijwoq78N8WuI7WfCsqP+CxMQWVs=";

// flatware [outlined]  source: src/search/flatware/materialiconsoutlined/24px.svg
static const char search_outlined_flatware_b64z[] =
    "eJxVUsFugzAM/ZWIs2NiJxCY2h7GpZeeKnFvGQO0jlYtg6pfPwdaaVOQ7fi9Zxsrq9vYqPv3qb+to3YY"
    "Lm9xPE0TThbP1yZmY0wsjEjV/eF4qvXxUH011/NP/7GO+npSRg47+SLV1l3TDusoxGNXT+/n+zr6g0/d"
    "x9DO8GbVbFaXw9AqqbIzYFp2I7utKc0jUp/d6STFz30dxZtV3PxnUwoeTVYZIPReG8wcWOREs7iMS6ZW"
    "c0kG80oTUiqMxGvWjEY4OnAKQQ2Bw8wCEdoExFuwBTlM03BJn+DS66F25MGOlLU8ajGlL5ggQXZAOfpZ"
    "IgThZcgZ2EqaOjBiPYNBy6/Ii3SbBmfFFCGSqS1DKnwLUkjtk7lESD6jWeTQuUUUogV3SCKfGWD3dkku"
    "9zKfF0TSMwcOZyTZcklUzVkIIwmil0lUkS/qDFNpCctvPF77Dy9g8wulU4OW";

// garage [outlined]  source: src/search/garage/materialiconsoutlined/24px.svg
static const char search_outlined_garage_b64z[] =
    "eJxlU01zmzAQ/SsanYXQt6BjfIgvHNord4cQYEpwxqGQ+tf3rca4mXaAp13th/Y94PCx9uzzbZo/Kj4s"
    "y/u3PN+2TW5WXq59bpRSOTI46+bz89Rlz+f2Z3+9/JpfKj53G1O4jMPN2dCN/bBUnOx17Lany2fFv8S3"
    "8WUZUvh46I+H9/MyMHT5oYQajFuNq1Wjbpy9jtOE5pe54/nxkPcp+2uBUcLU7mRkKQxdaXWrDq0SWmqh"
    "9sCArbQhTJY2M9Og7l5CEZgI3ljqqWrXONQ0BmPg6Ha8tlPHWtAoOWt/V1xbzq5Y/olq/3/4Ma2XsRC6"
    "kH5Q0rlTkMEnV0RatKM1ylA2OiBHqxVzlWCCbA+wDlAQKbQhK7VpAVaotAtqNuxWodmaoVFLNvhKFzKN"
    "JpmTysLyAVYoKaw8QAcCkseUZBG4FDUPsARur1CRUdzSaT7pSuDtX6uOMhpiQB6Nr3QKCnIhAIgEqQIg"
    "RrLIjR6gSR3yjAYEAtAHG8r17JTciJmFBzlR4BgBMUmwFQknf1fUS3vX+CE+XnEhrUW1HyLaTCAMASHF"
    "lKSERhpzh/h9T0NFpN5eN4SMXg1RWfHxlHVMm/q2f6LpwY9y/AOqqcU2";

// light [outlined]  source: src/search/light/materialiconsoutlined/24px.svg
static const char search_outlined_light_b64z[] =
    "eJxNUU1vgzAM/StRzo5xPviagMO4cOm195YxgsagKgyq/vo5XSdVTuxnvZcXKymWrRe373FaSunX9fIW"
    "Rfu+425xvvaRIaKIFVJ00+k8dup8ar/66/wzfZRy6nZBHMbxksJ3Q+/XUga8Dd3+Pt9K+cLvw8fqH3RV"
    "9FVxOa1esMuBgLxxm3ENHekuxecwjmw+T52MqiLqH+rXA9pCgpQcrVdms4xa5TAGwlhl4NBqLhnmtrag"
    "E9RgMQedQoykuTZZS2DQMMY0BxdiceqvUc4bzHNRG8IghiALHqE6ZuoACG3KJN+ZYJzAc567OGgDOm/Z"
    "SwMpowhzzsZz1NqBzoKnDYkHCtLnkbiJRUvKYpbwsNqpFFKVLumjAW4abe7/j/HY/CXVLycDbQU=";

// living [outlined]  source: src/search/living/materialiconsoutlined/24px.svg
static const char search_outlined_living_b64z[] =
    "eJxlUktvozAQ/isWZ9vMjG0MqySHcuHSK/eUsjjalFQNNVV+fcdOorZbGeY93zzszTlO4uPlOJ+3RViW"
    "1z9lua6rXo0+vU0lAUDJEYUY5/3TcVRP++Hf9HZ6n5+3xTyuAviQ5a8QYTxMYdkWSY6HcX04fWyLb/71"
    "8LyE7N5tpt3mdb8EwSiPICGQjWQ76OFSiL+H45HBT/NYlLtNOf2MRq+9kwjauL4ZQKGuKibGKpNOUE67"
    "IVslKCOvHmkiC65lH6ZcX0vGQO0yJ+16rAbgYJSgG0npBAQxZIskla2KojLatdjccrHWtrnhfevrIh4b"
    "TU567ULqBnRtZEJ3jF75LPDPLYFp0eomYyAbbQKmzLkp0SPPYyNXd3lSk/poFHENJpSI9X3T5tK1Rs/E"
    "Uqor7w1wL5j0PB9oqhmCiCWXUBPvvBiSseZ9Xc1EN8HleYdsT7HWKV6fwjNmRbISKfio6HfMcNXlVyjv"
    "mLshkDZi1dnedgRZp862dF975ini931U/19Hz3m3lORhkZ2X+6tJ73b3CY2gqX4=";

// manage_search [outlined]  source: src/search/manage_search/materialiconsoutlined/24px.svg
static const char search_outlined_manage_search_b64z[] =
    "eJxVUcFugzAM/ZUo5yQ4DoFmAg7bhUN3msS9pYygMagKI1W/fk6rSpscvbwnOy92Uixbz67f47SU3K/r"
    "+SVJQggqGDVf+gQBIKEKzrrpcBw7eTy0X/1l/plOJZ+6wIACU1qc+W7o/VryyLehC6/zteR/8mE4rf6e"
    "roq+Ks6H1TNyeQcBHtMN0xoauHH2OYwjmc9Tx5OqSPr/1blwNTa5t427MVIaa9yQpEbSCMo6od0ojdqZ"
    "O7xpq1wmCDMXEVBokilhK1HlmQBpiWBKm10eRERqRRSCBGtBaDopQRlNzGXEdobyud0jGeZ07f55OfWh"
    "qTHdgtQqswTGShNjkUY8lDBLJMLE+IjlSKXifi7OQTZewyZpOtaQ5fMp4mdUv8r/bUg=";

// podcasts [outlined]  source: src/search/podcasts/materialiconsoutlined/24px.svg
static const char search_outlined_podcasts_b64z[] =
    "eJxVUktv2zAM/iuCzxQtUY9IQ5JDc9mlpwG9p65nB/OconHjIr9+n9QM6+AHSZD8HoK2l+ugPn5P82XX"
    "jMvy+q1t13Xl1fH5bWjFGNNiolH9fHyeev187H4Nb+f3+WXXzP2qDB7xeBs19qdhXHZNya+nfn04f+ya"
    "L/319LKMtb3fDvvt63EZFVAeDZlR/FX8d/Nkbo36eZomgJ/nvmn323b4f9p6stJhhzdeG0bFLmmLsJEn"
    "kVHLVSeW1KEZ8bmgLULGjC4znUGwWM9aSLT8KICoqALf1KMViqrTjh2mdCThmBEiOLHvC3Gg2rWcPXn2"
    "k2UvuvwOiYMDEkugRNaxzSUWUmGpIrPGjvYXXwtCoSqyzVCJZcxBMbtCnFOFpgptNwXVhspcwSGmJGgl"
    "SlB5b0YqFj6dyCGyT4SE7omVwiecgMVCgb2FG2sJ8F+deLCTjUWIr46K1urEf66ErEGr0yXVAj5TBZZc"
    "jxsH4yJcw1LgJP+MqIMYBvSmwIgUbGgpiRzkLhPNIFUsye3vLSj3cP8HFZ2cvA==";

// shower [outlined]  source: src/search/shower/materialiconsoutlined/24px.svg
static const char search_outlined_shower_b64z[] =
    "eJyVUstugzAQ/BXLZ9vYBhNcAYf2kktOkXJPCMWoFKKY4ihf37UhfRyqNFrk3dXODOuRczs16PLe9bbA"
    "ZhxPT1HknGMuZsO5iSTnPAIERnW/P3Q1Peyrt+Y8fPTHAve1QxxCJvBhZOq2MWOBfT21tXseLgX+MXft"
    "cTRhXOZNmZ/2o0GgsuGEG5lMMlnzHb9i9Np2HYgPfY2jMo+a32hNxKoCClOKcpYoIqggwlIROkjCzoUf"
    "bAGdepBnXdFGSOgr6smEA+SGtLOSDyu+ZNFWSI8UKQlEL5DeFajmIfnW2cIOi0y6yMA+cpJrNVFZcRoz"
    "FRPJUkFh2ZikkLREu9gAhvHsBfixJoqpFQFmxpKQhfRKUHoJyVYpHDKhyoeliswdUetw9QwoD9w8CxvD"
    "z+BYjPs//eabDr7pxbc7fPS3cToYp6+39+BfZPkJWtKiEg==";

// table_bar [outlined]  source: src/search/table_bar/materialiconsoutlined/24px.svg
static const char search_outlined_table_bar_b64z[] =
    "eJxVUctugzAQ/BWLs1n8Birg0FxyaE6Rek+IC6gUIkJDlK/vmLRqK1vr9XhmPWsXl2vDbh/9cCmjdp7P"
    "T0myLAstmsapSZQQIgEjYn44HHsfHw/1ezONn8OpjAa/MIGhDGbEWt817VxGIb92fnkeb2X053zpTnO7"
    "HldFUxWTr2f21vU9Co2D/6//5SZVkTSr4HyYW4Zrd0rxlOwGiyWbcomN4oZLhP03tjJqwSVlkmvKLYKW"
    "PMdisldptzlpW8eCMsVFLMlaLsgiyRw0yr04rkSreuSxbi05FlKuAQV2rCk1G+kASdwXgoEQiSEXtlup"
    "r7EhoTYyIwFEBCNwnAcbjwbubAfLrjaBILhDSZiAgZRS1CXLghhgRhLduUDLQ5f53sLiAzaksvU1Vsg9"
    "5GjXBaK7/zxf+MPqC5kDduo=";

// table_restaurant [outlined]  source: src/search/table_restaurant/materialiconsoutlined/24px.svg
static const char search_outlined_table_restaurant_b64z[] =
    "eJxVUc1ugzAMfpWIc2ISOwQyAYdx4dA+RH8YQWNQUVaqPv0MUrtNcRLH30+sJL/eWnH/6odrEYV5vrzF"
    "8bIssBCMUxuj1jpmRiSa4XDsG3U8nD7bafwezkU0NIvQPNByRCI0XRvmIlrzW9cs7+O9iP7gS3eewwaX"
    "eVvmU3OaxUfX92w0Ds1//S83LvO43QQcl8McBN+8RwPeSQ8p9cqAJZVUqMEaaYEkZxqllcZDkkpbWyZU"
    "BD7jGkHiNxKBZexlIJPKQOak0UBOIhDLjSReAgLuLJuKgL0Gl6okmHXfmYyrXGQDVL5GU3Fbzq1CRDD2"
    "afbq9SH2DjybEhthqjB4cFsqsV4RJnBvJD0XM6coGAJHYjtJqlfs8XyRbfLXlD/puHDL";

// window [outlined]  source: src/search/window/materialiconsoutlined/24px.svg
static const char search_outlined_window_b64z[] =
    "eJxVUM2OgyAQfpUJ9xGklehGPeypl157t5QFU8XGstD49B1MNrubIQzf30Bon9HCa578s2MuhMcH5yml"
    "Ih2KZbVcCiE4ORgYP1wng9dB3+26fPtbx7xJIKjkkRYDZ0brQsfyOY4mfS6vjv3R03gLbpf71vbtanSA"
    "r3GaaNDizf/8r5f3Lbd74DEEB3TtuWzgcKo0lkUJAiUUDW0ylkctgLiiAZnLEbFbQGLmUF4qLXIKcyLX"
    "NguoHapL5VRU24w1Uj9VGRNSJO44IsEaFPVMUGL7eVj+nf4Nv/NZsw==";

// yard [outlined]  source: src/search/yard/materialiconsoutlined/24px.svg
static const char search_outlined_yard_b64z[] =
    "eJx1U0FvqzAM/isRZyc4ThrC1Pbweullp0m9d4xBNR6dBq9M/fXPDm23appAjmN/3xfbUZbDqVGff7t+"
    "WGXtOL4/5Pk0TWZy5vjR5ISIOSMyVff7567Wz/vqrfk4/utfVllfTwr5I89/ptr60LTjKhP/dKinP8fP"
    "VfYtPx1exjal18tmvXzfj61ilUcEbMmfyG9xh+dMvR66jsWPfZ3l62Xe3KNtBOsq7YyzgDoAmVDyEjZ2"
    "ISFbgiBC8gV6Vo9BGAiJInAIkAgEzOFtmcAOwgxnljXoFFPQxMCmAGsW4ctUaJwDSQen0VjBlexQ7Nii"
    "7C39Th/E6Gtci5l5okV8rqGFSBRsFiJAMZ2QvGoWhZ8aFfI+EBtXcMBKmsuyxlsZTnDSqMwGool+XkmO"
    "E1zS0jetWVDPfYqsk4L0rYruVu7v9CFZuCZSod1tPGpjWQiCKQLXxbLBBPEYKN4mcmspFKEwThapNg01"
    "EEiPID3Og0k9RomxVMFY1vYWLjfJd8p3HQ0G9X169zcz3A8Tvjq4b+2JJa1PanBRZX1C8Ccbtn7nt4Rp"
    "T1u/IVMCyZdWrxhSyeEygkum5VAKgNwcBzXtmHjhSIZdTp6vj0Ge4/o/ut3R4g==";

// bathroom [rounded]  source: src/search/bathroom/materialiconsround/24px.svg
static const char search_rounded_bathroom_b64z[] =
    "eJyVUktvgzAM/itRzgk4WdzHBBzWSw/raVLvLWUEjUFVGKn66+cEkDZpmoQSxY7t7yElSTeU7P5ZN13K"
    "bd9fn+PYORe5p6i9lbEGgJgmOCua07ku5PmUf5S39qu5pLwpHANa2tDmzBZVafuU+3yoCvfS3lP+o++q"
    "S29DO0vKLLmeesuI5QACrDaDNns4woOz96quibxtCh5nSVz+ntYg9N7sdLQV2q8QzaBWOQgVKQFzw1Ip"
    "FISWoSj1kXATxHcopeaDHbZCbXIaQhQgFSUGKSjWjZmgvPPMBgVd3rZ+UG2Eh41o/AP9Lxg9GAms9DJt"
    "pSfxAJwIFshPeAz4YMCzsQUEOBvAyQAuM4CzARwNrIVSr/7IQepovaL30UaiQIkW8lABgaFKAQegh/Zi"
    "cqT0CvvNbh0uWngiL+DjY/4//gdn36J7q4I=";

// bed [rounded]  source: src/search/bed/materialiconsround/24px.svg
static const char search_rounded_bed_b64z[] =
    "eJx9UUtvgzAM/itW7g5xHsAm4LBdeum195YygkahKixU/Po53SZtVTU5cix/DzlOMYUWrqd+mErh5/n8"
    "nCTLssjFyPHSJloplTBDQDPsD32Dh3393l7Gj+FYiqFZQHFoy0eAb7rWz6WIdeia5WW8luIXvnTH2d/g"
    "qmir4ryfPbDLlile26DtRu3UKuCt63s2H4dGJFWRtH/ZmoCUzPJdXiskmTpOxqGJ4dHWKLMMImIzaVAD"
    "U1E6g9Lm3NRccEPHvElfLUvBgYE0FgbyoBlgj5SkY2dgb8uXlloHVyvgrrQOKMZEeKuRApKnNNA/BBaj"
    "zHkU8xSnzpAwmq5bspB5W7OON0XwLQ7aY3p74pdhHAVp3Tq47z3SbtwuX0+MZwH1PZ8eCez6s+v429Un"
    "d3eAiw==";

// bedroom_baby [rounded]  source: src/search/bedroom_baby/materialiconsround/24px.svg
static const char search_rounded_bedroom_baby_b64z[] =
    "eJxNU8mS2jAQ/RWVz7IstRZbKeAQLhyYK3fGw9hUHJgaiD3F16df2yRTRuK519eLV7exU1+/h8ttXfT3"
    "+8ePqpqmyUzeXD+7iqy1FVsU6nQ5vg6n8vXY/uo+r38ub+vicpqU5YcC/wrVn85df18XwOP5NP28fq2L"
    "b/rp/HbvRb1ZdZvVx/HeK47yYrXtKYwUdvZgH4V6Pw8DB79eTkW1WVWdWH93IKtpF7ZksiY88h9Gl1qr"
    "nXHaPhU9i0SgqRRhSQf2W1ygYcjKh3pxpF1tclZtScbX2pbBJMdejS+TCRDGll+954saoAgtHxtKDuUG"
    "rqNlXQ0DDmBquFNmStaJGWtdZoVLfHkgD7J4C0ntG+28CfmQTRxKUcwZiSEhQu3FGaVkvhztk3Yc2LWS"
    "CLbLqUHCeuZlm20CnYbTJJOIAXNIXJbmcqNibSaGTWBhZpBqBjVQzNxPiyKR3AsDJIn1FrGy09l4Qfk/"
    "Qo0NN5wdAtiiNtCmODgTAnc+Krax0ocoiue12PWByaGRcxhR0wLiaMFpHsAsLRfNzqWRgw8WpTg0FDHK"
    "JUtABWhpiV63c5ckay3Iy5Q0poQU82DkIjBtSAaI7XJbx3102BaeowtYFtkc/VyhB9b237KyRcqwo9Dy"
    "POoggy29SWlG0bBokDaDtxtkdKCyLK+JWFi0A3PxJnpBNzIhyjJCFmU6anbGlfbfMj+eX5Ic/p43fwE9"
    "l+Aj";

// bedroom_child [rounded]  source: src/search/bedroom_child/materialiconsround/24px.svg
static const char search_rounded_bedroom_child_b64z[] =
    "eJxVUk2T2yAM/SsMZ5BB5sudOIf6kkP36nvW6zWZps5O1sXb/PoKam/bQSBZ0nuSwIf3NLGPH9f5veVx"
    "Wd6+VNW6rrDWcLtPFSqlKsrgbJzPz9dRPp+H79P99nN+afk8rkzRQkPCWRwvU1xanu10Gdevt4+W/xNf"
    "Ly9LLOHjYToe3s5LZMTypISKaBKak+rVg7PXy/VK5Ld55NXxUE0lm+Q+DsvfIp98jjOq03D2q+UBbMZ8"
    "UmsLzgiNpwC1H6QCE4QiFbxQUDe7FXxUoHSvTWyS1KDrTjuwmpCUJcjWKLJsdI//iqASeDIdQiMwr6JN"
    "0m5QgriIfwtEchWHQFmcEnvCbZAcIZOCD/akPaAV2n/bDVa616V7b+mozW5521NjNsom5Y/Og80tOyc8"
    "aEdY4chNOqrOEa54toyi0SZZQx0GJXO3DukKAgHASgTsG5YDfwaRmLuOdp9jHy5pcH6gmwz5YguWNhZN"
    "HCnTdzpsVWmocop9usf+0mXT/3b8De4knqw=";

// bedroom_parent [rounded]  source: src/search/bedroom_parent/materialiconsround/24px.svg
static const char search_rounded_bedroom_parent_b64z[] =
    "eJyFUsF2mzAQ/BU9nSWhXZBk9xkfysWH5uq7Qwjyq4vzHAqpv74jFdz01Adoh9ldaXZg9z714uPHZXiv"
    "ZRzHty9FMc+zmUtzvfUFW2sLVEjRDafnS6efT+33/nb9ObzUcuhmYXFxhVuK2J37ONYy4enczV+vH7X8"
    "lJ/PL2PM6f2u3+/eTmMU2OXJKhu5mrg62KO9S/F6vlyw+XXoZLHfFX2u/txA3jhFHPW21dY4p6wmZU3l"
    "EGiiSDRpaijkKtAK0Casls572vjWteNfzQ95EArZwbCT4lctN8b9txiHhH+qH0rZKj5UDZut4nTlWE3k"
    "W6vIJNFLIoLKhGKdSc1H9C0tKQOI5F080QbaMNK3FYjkQoVehOCwlNWKgjuSMy5qWJLemjy/N94rb8ij"
    "WTnQiNE2Do2ZWSpyZDfp0tiNaNP2YC0oTYYT8gkFPm6RXMbRnLQfiFroCJgHxzKWZD5CyQ3c4o0KmWHj"
    "SxUUYYmlKd3qwWrMlD4fjjZV+r5/joRx9oECT0ldQ9tFNEzxea7Vnfv6E+UHv/L+N2i9s7c=";

// blender [rounded]  source: src/search/blender/materialiconsround/24px.svg
static const char search_rounded_blender_b64z[] =
    "eJxlUk1v2zAM/SuCzxRNUpJjDUkOy8WH9jSg99R1rWCeUzSeXeTXj1abLcBAm9+P9JO8vcy9+fg1jJdd"
    "kabp7VtZLsuCi8Pze18KEZXaUZhuPD4PnX0+tj/79/Pv8WVXjN1iSEW8PoVJ3alP065Y/fnULd/PH7vi"
    "rr6cXqaUy/ttv9++HadkdMojASXxs/iGnuhamNfTMOjw89gV5X5b9rn7HsAVsgMOqgfGKlomjPWBNxgF"
    "HIYA6voA2lNh7cA17GdqyZLWVPlgeZVkpc05IMvwmQeeqQkHh1HhKtmG2ZuWgHHtiiCrJEFxA2HlweuH"
    "HCrc+HUfBajyfrfaOPN/wLrNMYjNOSuzZXPg+gulWqqvSXdMr+YxQHwKidHxulfAN0GzLLrmH4+//C43"
    "Qup+sgMNfrDkA4qQcSveo2jkm4gbeajRKd+0QecfbpXr7R7yq3/D/g+SH4eS";

// camera_indoor [rounded]  source: src/search/camera_indoor/materialiconsround/24px.svg
static const char search_rounded_camera_indoor_b64z[] =
    "eJxVUcGOgyAQ/RXCeUAGQetGPayXHrbXvbfWFbOuNq2LTb9+B9om3UCYx5uXNy9QXnzPrj/jdKm4W5bT"
    "W5Ks6yrXVM7nPtFKqYQUnHXT/jB24rBvv/vz/DsdKz51K1O0tKHNmeuG3i0VD9gP3fo+Xyv+0l+H4+Ji"
    "uy77ujztF8fIZadAOW28Nlv1qW6cfQ3jSObz1PGkLpP+vxqV3EAqMzuKDIy0jZEpbKRNwUAhUceSW1+0"
    "ClAiKFmADsuhbiMBWkRSaC9IRZcspSMVKHVobQhk5C7InTWopSloIDkjSosP+ExxYzu0UudAZ5Z/oCHg"
    "kWYraS2ZGQsoEHBbtCJQoARGmgp6YeL8QEcqaJ1h7Z0ChLsBoMeR0uUha96EUUC5kFoRpMUD5LmnuFkT"
    "biRCuEut3Fh4iXl7Pmz42voPIrt7Gg==";

// camera_outdoor [rounded]  source: src/search/camera_outdoor/materialiconsround/24px.svg
static const char search_rounded_camera_outdoor_b64z[] =
    "eJxlkUFzgyAQhf8KwxmQBUTpqIfmkkNzzT2xVpxSzSQWM/n1XUw6005mFdfH+vyeVpfYk+tXGC819fN8"
    "esmyZVnEosV07jMlpcxwgpJuPBxDx4+H9rM/T9/je03HbiESSxk8KPHd0Pu5pqmPQ7e8Ttea/tlfhvfZ"
    "r9tN1TfV6TB7gi47yaRXJiqzlXt5o+RjCAHNp7GjWVNl/f9pKBnoVnIp8hwXk3NI5blpV41JDuyuM4im"
    "RfdVRYVBKo/aqjDgd5VD5BBAqALHbEE24IRlYEWZMyVTY+HRKB25EsauALpMBnhahUuh0515S4BmD/pG"
    "diBFybRwgVtmRL4xQrNSFCUzzAld4AVkdAQZQSRox1QqnwI+Icrn0FsbuQuWo3dY3xDwCa8wzTprE5Hm"
    "GCzxldhYJEnTGBFTOGRDCgCRw6N9AN9+v3z6980P6AmDAw==";

// chair [rounded]  source: src/search/chair/materialiconsround/24px.svg
static const char search_rounded_chair_b64z[] =
    "eJyNUcFugzAM/RWUsxMcJ4ExQQ/rpZdde28pI2gMqpaFql8/J9WmHqcHJrznPMdOfQ19dvsap2sj/LKc"
    "X/N8XVe1GjVf+pwQMecMkXXT4Th28nhoP/vL/D2dGjF1a4YMsvyIzHdD75dGxHUYuvVtvjXiSV+H0+KT"
    "vKn7TX0+LD5jl3cE9GQD2R3u8S6yj2Ec2XyeOpFv6rxP2c8bSEPVSq00oCRAVXGkYHcuSNtiFGQiI65P"
    "Ga5F0KpwHIwDExE0c6ic42BZiGgf/xBdIid1kDrzmv6d3KYqCEY+KkkTpNuSgUpVQMQH5w+He2zwr60S"
    "tA7kNQZJqY2Xgk9KL9Ioq6MJE/siKYVLztJE7MqtezRkwcaFhSLwECzTJUGpXAUll9YWYon771TTy3e7"
    "+QGpBX5X";

// chair_alt [rounded]  source: src/search/chair_alt/materialiconsround/24px.svg
static const char search_rounded_chair_alt_b64z[] =
    "eJyNUU1vgzAM/StRzg44IYF1Ag7bhUuv3FvKCBqDqmVJ1V8/m2rSttP0oiR+fn7OR3kNg7h9TPO1kn5d"
    "z89pGmNMYpYslyE1iJiSQop+PhynXh0P3ftwWT7nUyXnPgokGEtDCt+Pg18ryfsw9vFluVXyRz6Op9Vv"
    "6boc6vJ8WL0glz0CemODsQ22eJfibZwmMl/mXqZ1mQ6/1boAjZ1ONCAYhcmOZtO6DhVxHCvDaIpXR7kM"
    "HGS0OnAh6xC2Oq5heB1I16mNVAa2YjAhF6TExDmarAPN8Ng9GOAmzCodFFlgMP9V538P6TePRhd3sS/g"
    "qXVsl4mGY75n3hSPHq3OmbKgqcYyZ1tt7t/vwz9UfwFZt3Nj";

// coffee [rounded]  source: src/search/coffee/materialiconsround/24px.svg
static const char search_rounded_coffee_b64z[] =
    "eJxVUclug0AM/ZXRnD1mdqACDs2FS06Rck8IZVApRAmFKF9fT1ClVrPYfn5+nqW4Lx17fA3jveRhnq9v"
    "SbKuK64Gp1uXaCllQgzO2vF0HlpxPjWf3W36Hi8lH9uVSRra0uQstH0X5pJHf+nb9X16lPxPfu0vc3il"
    "q6KriutpDoxU9hJk0HbRtpZH+eTsox8GEp/GlidVkXT/2SpDB6b2O4s5GLBgyFpwi8NUNZLCzIDG3EGK"
    "KgOPaUaezhvieZCodAy1MCj95qWLUEGiaxTmBqKCEwpd+nJosYOWaA0123o/2V55akiHOLpa+RjHRFar"
    "7Oii0k7laAw40BIc+jRaj+6wwdmmk1GdA5UHZRuqcdRZ0fksYaAWyeguERYbJAisXSM2plAvmAwxd5ZU"
    "Ism+mDnE7fn7dvH3qh9cn3Zt";

// coffee_maker [rounded]  source: src/search/coffee_maker/materialiconsround/24px.svg
static const char search_rounded_coffee_maker_b64z[] =
    "eJxtUU1vwyAM/SuIsyGG0KyZkhzWSy+79t5SFqJlSZVm0PXXzzBNqrTpgfz9bExzDT27fYzTteV+XS/P"
    "RRFjlLGU89IXGhELyuDMTcfT6MTpaN/7Zf6czi2fXGRI0IYOZ94NvV9bnvQwuPgy31r+EI/DefU53DV9"
    "11yOq2fE8oqAXpugzR4PeOfsbRhHIp8nx4uuKfqc/VigtlAdjFcW5WYDCEqgNBsSKqBFkbzZI1TCvtoZ"
    "WYMGA5qkARNUZalKKsAcIHhV/sfG/tJ5UUosd+pJalC1xBpoHLIqk5UqCGISRE41tdAJXlRW5HZCQ/aC"
    "DmUegapQbhWUiUgTMZh9epsOmnrDz0h5nAS/TX3J9ZR6VUlL8p72ZIfFjo5Z2rkqObNfLa85W8j63WK+"
    "9JfdN1ZTe0Q=";

// dining [rounded]  source: src/search/dining/materialiconsround/24px.svg
static const char search_rounded_dining_b64z[] =
    "eJxtUk1vo0AM/SsjzsNgzxfDKsmhXHLpNfc0ZSFqNqkaClV+/T4PVLsrrQDb8/yFn2dzn3r19etyvW+L"
    "YRzff1TVPM9mdub20VeWiCpEFKq7Hl8uXflyPL31H7fP6+u2uHazIjzW4y3U0J37YdwWYk/nbn66fW2L"
    "v/zz+XUcsnu36Xeb9+M4KFR5Jk2D9ZP1ezrQo1A/z5cLit+uXVHtNlX/b7Qlbfe+tabRVp6s/cTxRJoN"
    "a/p2DIAyoG2ZwdIekLemiAcmnA/1zKyZjEMFBDpER49aNZdsAozGqSkasm0jx2Ri1I3hqLnRydSAmoHa"
    "ZJzPyBqRtQ1TKZkn1EwRwlqpWfIiUfkQTWjx6QgfRA2hax3VnQBKgl6McEAXdJOEE0mplN3l6hb9n5w9"
    "U27BtHTAnNahBUtEBGzqJEde3aKDOggdQkwwAYNYE5oLGpC0JDcFExeyPAPF3PJjpYhsgQ32Kx3sVz4W"
    "QwiR7KWaCK+EnKaG8DUoiSJWwxlOmJVNSrJbB8BjfUE0duuSLDevKLhsAOeWa7SRARPaY5ogAzBm+zPM"
    "4/tmyd3e/QaCAq7T";

// door_back [rounded]  source: src/search/door_back/materialiconsround/24px.svg
static const char search_rounded_door_back_b64z[] =
    "eJxVkM1ugzAQhF/F8tl/a+xWRMChXLjkmntCXIxKIQoURzx910ZNW63ltXdG38gu5rUjj89hnEvql+V2"
    "kDKEIEImpnsntVJKooMSN54vg+OXc/vR3aev8VrS0QWisLTBRYl3feeXksbz2rvwNj1K+kcP/XXxSa6K"
    "ripu58UTpBwVU16bVZtGndRGyXs/DAifRkdlVcjuv1srBrnncLKt4iCAK5FzHat5ra3IWcYsy7BbZlcw"
    "jWnRYS1DM1PCWGzQYmSa4Z1BLA8v7T5ikRjHHEitUcrjTScRcpbiN3IE7Nkvmu9ojmj+RMcoDjM8c2rA"
    "TSfSzstY4mw/D41fXX0DqG5jgQ==";

// door_front [rounded]  source: src/search/door_front/materialiconsround/24px.svg
static const char search_rounded_door_front_b64z[] =
    "eJxVkEFvhCAQhf8K4Twgg9DGjXqoFy973bvrWjG1ulmtbPz1Hdh022YIA/NevhfIl61n989xWgru1vV6"
    "SBLvvfSpnG99opVSCTk466bmPHbi3LQf/W3+mi4FnzrPFJU2tDhz3dC7teDhvA2df5vvBf+j++GyuiiX"
    "eV/m12Z1jChHBcpps2lTq5PaOXsfxpHg89TxpMyT/r9bK8DMCTzZVgmUKJTMhA5Vv1ZWZpCChZS6Bbuh"
    "qU1LDmuBzKCksdSwpcg4oztgKIcv7WMEgRjGAlmlScrCTUcRM4jxOzuiAUx/0eKBFoQWT3SIErjgM6dC"
    "ajqSTNxTiJz956Hhq8tvqxpjkQ==";

// door_sliding [rounded]  source: src/search/door_sliding/materialiconsround/24px.svg
static const char search_rounded_door_sliding_b64z[] =
    "eJydkcFugzAMhl8lytkJcUiQMgGHceml195byggag6owUvH0c2jXbdfJkRL/v/05SvJpadntox+mgvt5"
    "vrwkSQhBhlSO1zbRSqmEKjhrhuOpb8TpWL+31/FzOBd8aAJTFNrQ4sw3Xevngsfz0jXhdbwV/JcfuvPs"
    "N7vM2zK/HGfPiLJXoLw2izY7dVArZ29d3xN8HBqelHnS/q3WCtAdbK0EShRKOqFjeGGltgtmnnR7SHdZ"
    "ZaSDFAyktBsgz9RUby1QKyhpLG1Y0/RNoxwwhseM1XcN4oCoC6w0WS4mevPQwXaTle0dYPpDFneyILJ4"
    "kuMkgRM+x1RIzTrabqOlECkEQ/svWvagoX3gNs76/YDxC8svI6V14Q==";

// doorbell [rounded]  source: src/search/doorbell/materialiconsround/24px.svg
static const char search_rounded_doorbell_b64z[] =
    "eJxVUstyozAQ/BUVZ2nQ6AFiy/YhXHLJ1XeHEOQKi1MxgZS/flsym0pKMNOjefbA7roM4uvvOF33RZzn"
    "9z9lua4rrZYuH0NptNYlIgrRT6fnsVfPp+5t+Lh8Ti/7YupXoXGMw1OI2J+HOO+LhJdzvz5cvvbFD/96"
    "fpljdh92w2H3fpqjQJUnLXU0bjHuUR/1rRCv53FE8cvUF+VhVw6/o1lTkJaaUVXSkW8dWRmoDtLJhmwN"
    "xXppOi2ZWGpqpEknsunyhTQqXyqzKETBqCyEVUwmuQJAhdoKtUXLhlyDbqjLTJ43uI1wE09sJNfkO2R6"
    "L7ViAOehOJqWbXJqL1EG3hQot4SU6pNZRVW3Ab0BZZC4BJWsvVh0mxGc9wgPjRz/2CzKkHWYH1M50Awg"
    "BCENGa8scXVsgDI/l9ZgHVCNCSEyum6mdfLbgZzE2RE32GVwqSFoc+4MDlV1ZB/BtNNkAnYJiBeT3YHH"
    "wGBx57DJbCaet/8fM/1Oh3+bxpKL";

// feed [rounded]  source: src/search/feed/materialiconsround/24px.svg
static const char search_rounded_feed_b64z[] =
    "eJylkjtvgzAQgP+K5fkMfganAoayMDRr9oRQjEohSiiO8ut7NqmUSt0qozv83d0nHs6vS0dun8N4Laib"
    "5/NLmnrvE6+S6dKlknOeYgcl7Xg4Di07HpqP7jJ9jaeCjq0nHJfUeFHi2r5zc0HD/dK3/nW6FfSp7vvT"
    "7GK5zLsyPx9mR9Cy48Cd1IvUNd/zOyXv/TCgfBpbmpZ52v3uFhtQtalUsgUVVsxmEbrhIBIBHIEMyyGK"
    "ACSLkMm9fQvjd7KzkDnV8MQYrIchbTCJhaMlULYShqy2pMrCbgsZ2DCBaeFVBpGuAVCIWrSLrLYNW81M"
    "RA+maH7QSILb2b+egFQiA7EJhUcMW4wPv/qnP+rlk15FffgqwoAlezNo0I6pSpj1tQOOnZjvP/8knIry"
    "GxhXiQ0=";

// flatware [rounded]  source: src/search/flatware/materialiconsround/24px.svg
static const char search_rounded_flatware_b64z[] =
    "eJxtUk1v2zAM/SuCzxRN6tMekhzqSw/raYDvqevawVKnaD27yK8fJbfdhhUSQIpPj3zP1u51GdTb03l6"
    "3RfjPD9/K8t1XXG1eHkZSkNEpdwoVD8d78+9vj92P4eXy6/pYV9M/apIlnGyCzX2p2Gc90XKl1O/3lze"
    "9sVf+Hp6mMcMH3bDYfd8nEclXe4IaDRuMe6WWroW6vF0Pkvzy9QX5WFXDv/e5gARqeoIGGPUhJUDi8Zr"
    "I6EyrSGBCL0XyHlgzcAjdTqVgDTnsgRedI3caUYOCYzaaIMkfXTqoxomJAaHlQVmtB4kWrANOwwhHcI7"
    "uAm6qjuu0ERRwVXDEYMDg3UNnEouR4fsv0v81AibRsgaVbeVgD+lLzqO/H+5jY1h8OhlBCGnDxAd/Bkv"
    "WiSvwCbbTlwTRiOzrPnIomnjbUhBqGI2pUK1BoIQLIjBHz63SLX3LJMcOpdJTco2XHwJO98Qnt2K27mt"
    "859imVmDSWup1VfuvzJfd5kJSbaw9aa2qbcBFQZRBZvT68dbSa/18BsW56WN";

// garage [rounded]  source: src/search/garage/materialiconsround/24px.svg
static const char search_rounded_garage_b64z[] =
    "eJx9UsFuozAQ/RXLZ8eMjY3NKslhc8ml19xTSjFaFqKUhTZfv2+sJqpUqYKMX+bNPN4MbN+WTrz/Hca3"
    "nUzzfPlVFOu66rXU07UrLBEVqJCiHc/PQ7t5Pjd/uuv0b3zZybFdBeGyDrcUqe27NO8k46Vv19/T+05+"
    "4df+ZU6Z3m+7/fZynpOAyhMpStYt1h3pRDcpXvthgPg0trLYb4suV+Nu+msztKKBqvFSNB84SymuOLjw"
    "C11/Zy/T8NFNo7hM/Thj1KjLUgXtRdBVUDWAqTiVkeccyNx4t2lJ2aM7WF0ry1c+3WKqhpTRRtGdSEjl"
    "hLKbnNzYE/o+W5gBBHkTT6ZWBgZqAQ3SzqO+9EDRAIWYUQJ0rslRUc5zWXVH0Zxg3R/DAun6B6GjBxIH"
    "z4yJ2qt8GMcnm1g2kAEdrYo6WIV9OGzBVEA+h4Y0sTRSCDydrRnVbO5Q6RBQRREhcCBuysCJA4Si8tob"
    "SEIc6AESzPAW2brHjJryNi3/LfmZjKh8BP8IgdnAFrjDcK912RFvAVvVlnsr9hscXoAt8a4wjMO8pzz1"
    "7f6R5R8+9f1/i0m3Rg==";

// light [rounded]  source: src/search/light/materialiconsround/24px.svg
static const char search_rounded_light_b64z[] =
    "eJxVUU1vgzAM/StRzo5xPiAwAYf1skN77b2lDNAYVIVB1V8/h27SJkexn9+z4yT5tDTi/tkPUyHbeb6+"
    "RNG6rrhaHG9NZIgoYoUU9XA697U6n6qP5jZ+DZdCDvUqiM04XlK0dde0cyFDvHT1+jreC/mHX7vL3G50"
    "mTdlfj3NreAuBwJqjVuMe6MjPaR47/qem49DLaMyj5r/am0hQUqOriJFGMe8uVjpYC1VWwpIaXimQS+G"
    "1ZVyyGmMVQoOrWaXYmZ3FnSCGixmoD3ESFzg9ylvoiIwaBijz8AFm5x6AuV6g1kGtDOEoQKCLjQK3jG1"
    "CwGh9UzywQnGCfwM/hAHbUDHvfJAfAeLacIDaMfYKy8mvyFgtN+Ej99XCP9QfgMLVWnB";

// living [rounded]  source: src/search/living/materialiconsround/24px.svg
static const char search_rounded_living_b64z[] =
    "eJxVUk2TmzAM/SsezraQZRtwJ8mhuexlr9yzLMWZpmRnQ2Env76yCG06xrLQ08eT7N1tHtTXr8t42xdp"
    "mj6+leWyLLA4uH4OJSFiyR6F6sfT26U3b6fu5/B5/T2+74uxXxTyIs9foVJ/HtK0L7I+n/vl+/VrXzzh"
    "y/l9SgIfdsNh93GakuIsr6gxkZ/Jv2CL90L9OF8unPw69kV52JWDeD8H2AqCthZCZxBC0GisRvCBDztT"
    "MvVsqEPBzGrP6/bk1dqq47JATRbEImw7WVTdiuRfs+E53WwchKOt1/KRZQ24UtF/Sd0z639cUVuC0FqX"
    "/JxzMDELjjPGaAhc0AQUWPN1G4V041hUNXuFbScT1mYbl5sVoquH5j1bQKeOEZA7Q7BsxMyE9KP4/4wI"
    "Nb34I0HUlJecfpaJWMgzegCJTWLQZMRoqOW4R0hGWGXwrl5t1Fv85spFatUZSWAkAUuSCUqbUabK9wI1"
    "E11nYIPMwEJVscl547QzLuXmxYbaiZ0Px107vosGfMxd143OJHgcq8JtK77l+/aEZPNDPvwB2v+upQ==";

// manage_search [rounded]  source: src/search/manage_search/materialiconsround/24px.svg
static const char search_rounded_manage_search_b64z[] =
    "eJx1Uk2Pm0AM/Ssjzh5jzwwwUyU5lEsuPVXqPctSiErJakNhlV9fG5IqlVoZeYw/np/Hs7vOnfn4OYzX"
    "fdZP09unPF+WBRePl/cud0SUS0Zm2vH0MrT25dT86N4vv8bXfTa2iyERF+TLTN+eu37aZ2rP53b5fPnY"
    "Z0/x5fw69Wv4sOsOu7fT1BtB+UJAvQuzC0f6RrfMfD8Pg4BfxjbLD7u8+zu7hHT0tcNQQAIHEYtCj5ka"
    "sqQ/JCHLwJZ732we4NUrB89UV1tRqSqB4N2MoLI7+uaOYPkPykymEYIPYIWAZ2C7ee0GzCuvFZkdKKhg"
    "c8IYgSO6NFiP7FalvWKpyKVljEmsGK3Xw5nGOvSVZDDbgEESUilG5UR5riOWMoP3wIwhQYHSLmCspDNV"
    "jSQrWQl7LIQTxgKC2FVsVq/UaF9icNJLmlQSTIOQ0gr2RtOUz0MxktNZMfAgd1E7wsQ6UBlBbFfd7adB"
    "dWxxsyyFsZSbRF9Yr3K1ykD/wF/VAK9ivvJ6faWMooUCIHmpj/+66fuq7bYklf/srnZKR1/IWptAMW+P"
    "Z6UP+/AbGm6vIA==";

// podcasts [rounded]  source: src/search/podcasts/materialiconsround/24px.svg
static const char search_rounded_podcasts_b64z[] =
    "eJxVVE1z2jAQ/Ssen2UhrT7dAQ71pZecOpN74lDMlEImoTjDr+97CzTtANJau9p97+2a5ft523z82h/e"
    "V+10Or1+WSzmebZzsMe37UKccwtEtM3m8PS833TPT+PP7dvx9+Fl1R42c+PwkYhv20yb3XY6rVra591m"
    "/nr8WLX/+Ofdy2lS93q5XS9fn05TgywPzrhJ4lniN/foLm3zY7ffI/nxsGkX6+Vi+3+0j8bLiDu2xM5Z"
    "PNlQO4+tyKN49aRETzKe55MbOx4Z13k9xubPXbFS6cj4haSuvtKFPCNCrUeivhMjnTTfWRWPRqtfmgc8"
    "lGSy9WHsxEpBbMxdtB7xSAwrexNRdbxhrBkhrphgs+DRVXj7OLK2uWK1LtAqsGLQ4GbPtePCQNIN0dys"
    "ypouA6hokVzJ4MpCLOnk3AUb9Cr42ci6CWxsKgDZJ1i1Dh6IelPgMT6b3saeu5dGlawsLxU3M62ScTMI"
    "6ylYlpGeQpUrPTQj7HERRSOhRnL3dAY6E5H7OPhCEB4CBeORHTi9GtIM2KqWVA0TBfpU+yp9DYDhypAt"
    "jVSxIDRDCT3XeG1uSMqUI9EjVS4KH2xLMyokR63v0ue/0mcqzyFy6SrfrU9BRRajXnAdsST2oAaoGQL6"
    "HgpHCOPlMmsU9MB5tN3XDlx6ohRYfRl8In16jDhgcrrrcHvbcy6LwF2Yn+h9Hu8ToKOgA1oVC3VP1J0l"
    "I/Fptz1DUBO0eh2jQfTQZwslhBKDNA0ZsGbr2HyOFl8q86n05f4m8r9g/Qd06OhJ";

// shower [rounded]  source: src/search/shower/materialiconsround/24px.svg
static const char search_rounded_shower_b64z[] =
    "eJx9UU1vwyAM/SuIMxCbfHZKclgvu+zae0oZRM2SKs1C118/SKqpWrXKCFvvPT/ZUJ5nQy6fXX+uqJ2m"
    "00sUOeeEi8UwmkgCQOQVlOi+2Xea7xt1NOPw1R8q2mtHwIdM/KHE6tbYqaKhnlvtXodLRe941x4mu9B1"
    "aery1EyWeJd3YGBlMsvkDXZwpeSj7TpvPvSaRnUZmUWt2lF1mihvWVCiviuKOSWjT0F0x6J8TmeP9O8k"
    "GLNUQLFLFHAQaeqvJOUYwoJaIAYc2QoznNGrt7nI0PelOUtZIZKQUM6o/F5LgxczDGFRqhViyFeYI5k5"
    "bnGzdmIm4s3qdZvl+mf+2/ISni7/H5090uF9ww/XPx7bhyQ=";

// table_bar [rounded]  source: src/search/table_bar/materialiconsround/24px.svg
static const char search_rounded_table_bar_b64z[] =
    "eJyVUk1Pg0AQ/Ssbzssw+8liSg/20oOeTLy3FIGI0LRYGn+9b6lGPRqW3Tc7b948JqzOl0Zc3/rhXCbt"
    "NB3vsmyeZ5oNjacm08ycgZGIetjt+zrd76rX5jS+D4cyGepZMB5tsRLR1l3TTmUS8aWr5/vxWia/8nN3"
    "mNolvV4169Wpribx0vU9hMah/lv/w83+w8yaRRrruJtaAY+PWsuc3AaHI5dLhUBLKxW2p6+7hVGxVBSU"
    "NFQ4bEbJAocNz8ptCzKuSpmClpwqck4yOYDgUaN9j1RRSE02FxtPGl1QYaWnXEnNUDdowi1XTCZIRnWu"
    "UaMNUPBALjwUpGGudeR7qOVRTYOvLDgmNrQhdg1LyYJaFiB4BHChVHrDURCm8pupNJraKB/F8a1xszAN"
    "YMnHcKvMJbXEeqMCMW44DgHTKuIIbsP7+B7t8uJvWH8CCyeKbA==";

// table_restaurant [rounded]  source: src/search/table_restaurant/materialiconsround/24px.svg
static const char search_rounded_table_restaurant_b64z[] =
    "eJyVUktugzAQvYrFehjs8QdchSzKJovkEElKMSqFKKEhyuk7tpS0XVYY8+R5n/GI1eXaidvnMF7qLMzz"
    "6aUolmXBReN07gqSUhbMyEQ77g9Dmx/2x4/uPH2Nb3U2touQ/JDhlYnQ9l2Y6yzia98ur9Otzn7Vl/5t"
    "Dqm8XnXr1bk9zuK9HwY2msb2r/6HW/yHWXTJmtdpPwfBPe5IoXfgsdRDrtDo3DYk0SgwqIGRJDCgPNoS"
    "zMYwodHoKz7TaH0iaTRcexqAbRRWDpRE7YBQs1yB5i0QkogkaaHEqmoMyjJ6J72NcWBRxW+QR4kWJEj0"
    "lLNTGVHFqHJbh45lNnCCKwfmWZYrwwoZacY/Nu4iqhIKUjCBD4DzHRtxXrJUqGirKqy4ww2phgfiXGyZ"
    "iE0f13hO6S52Dj1fR3MylTkFjy5BoE2s3B+DTi//G+tvrhqN/A==";

// window [rounded]  source: src/search/window/materialiconsround/24px.svg
static const char search_rounded_window_b64z[] =
    "eJyVkL1uwzAMhF+F0K5fN4JT2B46Zema3VFU0YgjB44qBX36Ui6KtmNxpEDgOx4Idfcc4HGd471nmNLt"
    "WcpSiiiNWNYgjVJKkoOBj+Np9vw0uktYl/d47ln0BRTJPFExQD8FTD2rc558eVkePfvFy3ROuOGhC0O3"
    "epfgbZpnClqi/7v/45X/ccqwRVPdxoRAN75qDVofm8POcS00KG5A7Okx2WL7cTWgsD3unKqUV1KF3GaC"
    "1XZosnUKiIo9mCq0mX9t5hat21LB8Iq5ydwi0e9jtqb/Gz4BjllkTg==";

// yard [rounded]  source: src/search/yard/materialiconsround/24px.svg
static const char search_rounded_yard_b64z[] =
    "eJx9k8GSmzAMhl/F47NtLOGA6SQ5lMte9rr3rJcCszTZSWjY5ukryUk2M512SISQrQ/9El6fzr36/Dnt"
    "Txs9zPPHt6JYlsUtpTsc+wK99wXt0Krb716nzr7u0nt/PPzav230vluUpwsD/bQaurEf5o1m/zx2y/fD"
    "50Y/rC/j2zzI8nbdb9cfu3lQRHn2xg8Yzhie/Iu/aPVjnCaCH/adLrbropfdjwnoDT6FFl1jkC+5hzNU"
    "yRtwYPxtYaCQBAxaCVp8obxrCq+QS4sX9RxNdIjJ075YEaG24FaVYSOeSt6VJZG8qwIZfktsyGCcKMcD"
    "GfhP/kkeKW7u8Zxncp7DigmRHlfsYZQXiMfvZqj5m5GkIFZXchQ4lcoCF1pYuao0jYu0QJu9CyAOOF9K"
    "WuTN9VeJJuu0WahloVwS2Hsh00PB/wKcxLW3DoiZvhrEHNYA0fqsBqO9t1K1kYHoVo2JXGq83rlkrggN"
    "K7WsNPeHlUYW37iSZkhTjMHkYdJUAQ00yaKLrGjlECihqcmLwQZXgciVWmqeahAg6cDSsmmpbb40ULqa"
    "mkqwykFtMtVn7JWHYJgn5MS0PE2mMVaQYlQLNe8my+QgjAxvLvzBp/GYpk4lOjyAWqXfG92QcK2OFKCW"
    "3Q6F/Olobv8Ard/VLg==";

// bathroom [sharp]  source: src/search/bathroom/materialiconssharp/24px.svg
static const char search_sharp_bathroom_b64z[] =
    "eJyVksFugzAMhl8lyjkhiYdHOwGHnbj0NIk7pVmCxqAqjFQ8/RJKpU2bKqFYii37+/1LSTpMhlw/227I"
    "qB3H84sQzrnIPUX9xQiQUgo/QYnuqmOr+bGqP8yl/+pOGe20I9IfiH1QYnVj7JjRkE+Ndq/9NaM/+q45"
    "jXZp56nJ03M1WuJVDpJJC/EEcSFLOVPy3rStF+87TUWeCvN7GoBBARN4RpYwk8OeqV3NZYTIJFc+idFf"
    "arglLKSKhYL54m0f5tSOBeoG42OY/KUx0OhpBZt2K1iXL9zKb1m/CuAisBjAbQbwbgBXA/i/AfJYYI0g"
    "kHgvRTJxVUsOUfLMIIKYI0OOAy4F80WpYL4/ZvhO+TfL0JTa";

// bed [sharp]  source: src/search/bed/materialiconssharp/24px.svg
static const char search_sharp_bed_b64z[] =
    "eJxVTzFuwzAM/AqhXZFE2U5T2B46ecnq3WlU0YgjB4lCBX59pQIFWpDDHe9wB7YP9vC6LuHRCYrx9q5U"
    "SmmX7G69e4Vaa5UdAlyYTouTp+nz4u/rM5w7EVwCnQervALIzZ5iJwrm2aWP9dWJP3qaz5F+5L71fXub"
    "IkFOOWYLYcVYDXrUm4CveVly+BqcUH2r/H83GjB6rAfL9YB8IGSJZBrGgg4kzXaVb9JSw5ZkM+4LBTvu"
    "y2GoMzNQc9ZN4dX2W1Ge7L8BHq9N2g==";

// bedroom_baby [sharp]  source: src/search/bedroom_baby/materialiconssharp/24px.svg
static const char search_sharp_bedroom_baby_b64z[] =
    "eJxNUstugzAQ/BWLs2286xeugEN7yYFcc09SCqgUooRClK/vGtoqAlbDzj5mMPltbtj9qx9uRdJO0+Ul"
    "TZdlkYuW47VJUSmVUkXC6uF46mtxOp4/m+v4PbwXyVAvTNGFhu6EtXXXtFORRDx39fI63ovkiV+696ld"
    "6TJvyvxynFpGU/aKqxbNjGanDuqRsI+u72n4ONRJWuZps1Y/NyBy3OGM1KYO+GB7QA7ZWaB0hithJWgB"
    "UmnhKRV6gi6+u7OSmgq24IGCsxxkBAGrjIOW9hCkhcpJQ4ySthfEWQGs8txL7yrHfaupj6Z6zfUO/Ayt"
    "gBmpVsnM0DyzLgrUiVlc5AjZLC4S6yIIHEjjG3gSysHJ4DmYqB2oKlp5ROP/diMXYgWaM/nwZhUuSIXb"
    "kJWUikoziOshQqWJI8ubPUtf7FdN4ORSr+iGZHOTSbmIfGBbcwyuetr8+DuL9aE/ovwBI8mI+g==";

// bedroom_child [sharp]  source: src/search/bedroom_child/materialiconssharp/24px.svg
static const char search_sharp_bedroom_child_b64z[] =
    "eJx1kMtuhDAMRX8l8hoSx7yGClh0xWa27OeRJqgpjJg0mfL1DUiddlPFiSz75PrKzd1r9viw070F49zt"
    "RYgQAg8ZnxctCBFFJICp6XS2Kj2fLu96mT+nawuTCgzjoTwGMKNGbVwLW+5HFV7nRwt/+mG8OrO3u0Z3"
    "ze3kDIsqR0zQUO4p73HAFdjbaG0UnycFomuE3ukYi7q43yFPvRJYnFMD+2rhwIvtzz9kvZMVL+QOS9rY"
    "pw2ihHryFM3gQCs7ykMiK5NKXvjtMWk9yKovLaYlz8jGUooc5VCZ2me8rLZKgpFZf3zvN26v+wYTLWO1";

// bedroom_parent [sharp]  source: src/search/bedroom_parent/materialiconssharp/24px.svg
static const char search_sharp_bedroom_parent_b64z[] =
    "eJyFUU1ThDAM/SudnktoAt2uDnDQCwf3yn0/KmVE2GGRrvx6A46rHhynaZo2L++lbXaZanF9bbtLLv04"
    "nu/jOIQAIYF+qGPSWseMkMJ1+0ProsP++FIP/Vt3ymXngtA8KGWTwrum9mMul3hqXHjor7n8kQ/NafRr"
    "usjqIjvvRy+YZaeV9pROlJa60rMUz03bMnnfORkXWVyvaLbBHcdvkRsfohQstAEjxTtvaan6A5uuUAv0"
    "id1yzX9gJLC/0Le+iRSVNBF3ryuaxQ7vFFofIZhpcRxhhbbknWk1bEykwZjKlohHDYlVfHGwxA5JIS8J"
    "PbIabZVdTwg2ibIK2XkDiRFTCql5WlSIeeev11kn/1HxAZ87evA=";

// blender [sharp]  source: src/search/blender/materialiconssharp/24px.svg
static const char search_sharp_blender_b64z[] =
    "eJxNUEuPgyAQ/iuE84gMj6ob9bAnD/a0Se+2tWLW1aa60Pjrd3TTpAGGb/geAfLZd+z5M4xzwd2y3D/i"
    "OIQgghbTo4uVlDImBWft2JyHNjo3l+/uMf2O14KPbWCShjI0OXNt37ml4Bv2fRs+p2fB3/jQXxe302Xe"
    "lfm9WRyjlKME6ZTxylTyJFfObv0wUPg0tjwu87jb1e8GTEG7yJwUFY+V9qkzQulBioMBI1DXB8DEW4fK"
    "R3aIUKTJXurNubKjhexErNC4eRSYytIpKsDsEklhLcgICRhLG7L5HwHhGWFrgJovVJsSM9iNWwDdgjpT"
    "ZSJRdSq0BusSoU39YtbXi/ZF/1r+AayRZAQ=";

// camera_indoor [sharp]  source: src/search/camera_indoor/materialiconssharp/24px.svg
static const char search_sharp_camera_indoor_b64z[] =
    "eJxVj7EOwiAQhl+FMNNynEjUtB2cHOravSpCI1KjCKZPLzUx0dwNl//78yVXPaIhr6vzj5raEG4bzlNK"
    "ZVqU491wBACeG5Ro3x+cLg798WLu49Ofaup1IpAHZV5KrB6MDTWd7zjotB1fNf3haTgF+8FNZZrq1gdL"
    "smUPDCzKiHIHHUyUnAfnsnz0mvKm4ua/LZAtWsnWUaAVqlu3czCRvVBMqBJUKyQTy4i7VSyUVREdFiLn"
    "3YdOX+X8VPMGCExHMw==";

// camera_outdoor [sharp]  source: src/search/camera_outdoor/materialiconssharp/24px.svg
static const char search_sharp_camera_outdoor_b64z[] =
    "eJxVj0GLwjAQhf9KyDltkjEbttL2sCcP9eq9ajZTjKloNpH++p0KCyszPB68jzdM+8iePa8hPjqOKd22"
    "UpZS6rKp57uXoJSSRHDm4ngMrjqOp4u/zz/x3PHoClM0YGg5Qzd5TB1ffZ5c+ZqfHf+Xl+mc8BX3re/b"
    "25iQUcteCYVgMpidOqiFs+8pBCqfo+Oyb6V/p/Wn0CZXgJXNFi25AELXipypNQyvfGF7DWIzGNFkDahX"
    "bEfSBEvUR7CCNGuEQzOs4PJ3af21/wXMUU1r";

// chair [sharp]  source: src/search/chair/materialiconssharp/24px.svg
static const char search_sharp_chair_b64z[] =
    "eJyNUE1vhCAQ/SsTziif1tioh5689OrddSmYpWB2KWz31xc12/TYzMwLzDzevNDeoob7p3W3DpkQ1ldC"
    "UkplEqW/asIppSQzECg3nawqTtN80Vf/5c4dcioBzcFlTgRGLdqEDm3nuKj05u8d+jNPyzmYfdy3um/X"
    "KRjIKu8UU8Nl5HKgI30g+FiszeLeKUT6luidvT3w9lt7B6tfXMhua8wEsCfWwOkBAuReNeTuJvG7iQvc"
    "mELGl6Eam4FFRo2IbM4GyqrKICvMtpiPO2bF0StYLJhh/P9cMTaPp/u98h/2P1MSYGQ=";

// chair_alt [sharp]  source: src/search/chair_alt/materialiconssharp/24px.svg
static const char search_sharp_chair_alt_b64z[] =
    "eJxVT8tuwyAQ/BXE2YTlEdNUtg85+ZIrd6ehrFUXRwmFyF8fiFSp1a60szOjWW13T548vpdw7ynGeH3n"
    "POe8y2q33jyXAMCLgxIXpvPi2Hn6+PK39SdcehpcJlBK6tKUoJs9xp5WnGaXj+ujp3/0PF8ivuSh80N3"
    "nSKSknKCBlDqJPUIFjZKPudlKeFrcJQPHff/3aJtBKCyatwngyrJMg8oE1MoIKmKDsiUFbCRk2ne7P7F"
    "j6aswjSiHU1isnBWtJXSjZDIdOW0FXL7vVm/Hp5SHlF3";

// coffee [sharp]  source: src/search/coffee/materialiconssharp/24px.svg
static const char search_sharp_coffee_b64z[] =
    "eJxVkM1ugzAQhF/F8nkx6z8wFXBoLlxyqsQ9IQSjUogSakc8fe2gSq3W8lrzzaxllw83kOfXND8qatf1"
    "9pam3nvmJVvuQyoQMQ0OSvr5dJ765HzqPof78j1fKjr3nmAoocKixPbjYNeKxrMbe/++PCv6h/vxstoX"
    "rsuhLm+n1ZIw5YiAVignVIMtbpRcx2kKw5e5p2ldpsN/NzdMg2yUMx2CZCYPG5eQx7LYvRSEPNnVJHcJ"
    "n5ApwI6zLKIAioRHKpkWiWB5fhCCyQIUKwwIjDYJ+z0bOfIMNHGyyVrd8CwKkZiGm1ZbZPrACyYl6JAE"
    "HbOhZ0x/7LLZB5mQU8ALyzMnGtXyYvt9XPze+gfYwmPI";

// coffee_maker [sharp]  source: src/search/coffee_maker/materialiconssharp/24px.svg
static const char search_sharp_coffee_maker_b64z[] =
    "eJxNkMFuwyAMhl8F+UzAEJomU5LDdsll195TyiBqllRpBl2ffk6kSRUg2fj7f2zqe/Ts8T1O9wbCut7e"
    "pEwpiZSLefFSI6IkApib+vPosnNvr36Zf6ZLA5NLDGlpQxtYcIMPawNbHAeX3udHAy/1NFzWsJfb2rf1"
    "rV8DI5dP5Bi0idp0eMInsK9hHMl8nhzItpZ+p18FquTHkwn6pDuSYVBFzHTIjMD8Qx2F5qoSWHHCKCvM"
    "HhBy6Mp4sMjVdoeiVDzfME0ybrpic4x5p8rn9qwdFjs6ZmkElQOzvw1UwBbK/pvaD31N+weQelf3";

// dining [sharp]  source: src/search/dining/materialiconssharp/24px.svg
static const char search_sharp_dining_b64z[] =
    "eJxVUctugzAQ/BXLZ2N2/cCmAg7thUuu3BNKMSqFKKEQ5eu7Dq2UCmuY3VlmbFxc157dvsbpWvKwLOeX"
    "NN22TW5azpc+VQCQ0gRn3XQ8jV1yOraf/WX+nt5LPnUbA3qUocVZ6IY+LCWPfB267XW+lfxJ34b3JTzk"
    "quir4nxcAiOXAwgIyqzK1NDAnbOPYRzJfJ46nlZF2v+fVkqoWq2KvoFG3dkBUSBI3ZKNzHUCMjMCpcME"
    "pSWS6wbz2q9JJp1rSfYZgVJRTnDHOJTVLoC0qyZ0tslisTdqBLbXNWITs2KqldYLVNLmI/mBp3R4RKGJ"
    "Wdrv7QgmxuaOwDgKyyL8Ei3Rt0Dck5lETQ0jyDS+WYtkIyDWJFr9ICTgGzqpbDy2zwVm0tq4E1TiaVf3"
    "v58Xr6/6AXm/d5E=";

// door_back [sharp]  source: src/search/door_back/materialiconssharp/24px.svg
static const char search_sharp_door_back_b64z[] =
    "eJxVj8EOgjAQRH+l6Rlot0UjBjh46oUrd9DaNmIhUFvC11tMTDQ7h5282Um2XLxC63OwS4W1c9OZkBBC"
    "Fng2zoowSimJCYyk7fpBpn13fah5fNlbha0MiMZheRRGWhqlXYX33RsZLuNa4R8ezM3pD65LVZdT5zSK"
    "LQ1NqGa5Z7mgLd0wupthiOWjlZjUJVH/aSgSKFouDh6Ognum4eRTJqDYUAOQABdF9Jq1wLfv/f5B/QYN"
    "SENI";

// door_front [sharp]  source: src/search/door_front/materialiconssharp/24px.svg
static const char search_sharp_door_front_b64z[] =
    "eJxVj80KgzAQhF8l5KzmT0st6qEnL169a02zoTaKpon49I2FQsvOYZgZPthidQptz9GsJQZr5wsh3vvE"
    "i2RaFOGUUhIWGEnT9aOM++72UMv0MkOJjfSIhuNpEEYgtQJb4sM7Lf112kr803s9WPjUVaGqYu4soEBp"
    "aESBp46nNW3pjtFdj2OAT0ZiUhVE/a9ZHrG8FXXm2KkWjgM7u5jXLN9Rw7KICYh5CIC3TOxfwPFC9QZR"
    "R0OS";

// door_sliding [sharp]  source: src/search/door_sliding/materialiconssharp/24px.svg
static const char search_sharp_door_sliding_b64z[] =
    "eJxVT73OwjAMfJUoM2kcp/x8qO3AlIW1e4EQV19JEYQE8fSkSCCQPZzvTndydY2O3U+Dv9acQjivpUwp"
    "FUkX48VJBACZHZxZ3+0GK3bd/t9dxps/1NzbxCAPlnk5I9s7CjWfcOxt2oz3mn/pqT8EeslN5Zrq3AVi"
    "OWULMyAsI5YGWnhwduyHIYeP3nLZVNL9uhFm6q/VJJYFzqNakFDFvNWmzNjoiKRWUaBBeLCtyl5tppuw"
    "VXpiFpkhgR/qXTE92TwBvSpL8w==";

// doorbell [sharp]  source: src/search/doorbell/materialiconssharp/24px.svg
static const char search_sharp_doorbell_b64z[] =
    "eJxVkEFvgzAMhf9KlHMwsUkymIDDeumhu3KnlBI0BlXLkopfvwRt0qZEivXe52c55cMN7Pk5zY+K23W9"
    "vaap9x58Bst9SElKmQaCs35uz1OfnNvuY7gvX/Ol4nPvmQyHVLic2X4c7FrxWLux92/Ls+J/fD9eVrvb"
    "dTnU5a1dLQsp71JIS8qROspGbpxdx2kK4cvc87Qu0+E/jSSykxKFQ7JomuIUhY1FHV9Ad4kErYVMMBRK"
    "hwctHTCLptQCKboRFD8NsdUINMfcBRRdQpAp1oUA0EpIyCkoOQkC0kkGaHYMtMMDKsBCFJArgSEPIUbu"
    "M4xpUFts0Gy/O8RfrL8BsMdeSQ==";

// feed [sharp]  source: src/search/feed/materialiconssharp/24px.svg
static const char search_sharp_feed_b64z[] =
    "eJxVT01vwyAM/SuIMy02ISOdkhx24rBeuacrg2iMVC2DKr9+ZFK1TfbB78PPcn/Ljtw/Q7wN1Kd0eea8"
    "lLIvzX65Oi4AgFcHJTZOp2B3p+ntw12Xr3geaLSFQC0ha1Pi7ex8Gug259mWl+U+0D96mc/J/8hj78b+"
    "MiVPasoRGHghs5AaDKyUvM8h1PAlWsrHnrv/bnxijW4ydh47071ucCVHxZRvs9DKqIpQMVRa5Z3wCAYf"
    "VPNLbTvYsoNpg2RSY7s+bm3fjt96EE4p";

// flatware [sharp]  source: src/search/flatware/materialiconssharp/24px.svg
static const char search_sharp_flatware_b64z[] =
    "eJxVkU1vgzAMhv9KlHNiYicQOgGH9dJDe+XeMkbQGFQtC1V//Uy7SZuS2Infx85XcY2duH0O47WUYZ7P"
    "L0myLAssFqZLl5AxJmFCinY8noZWn47NR3eZvsa3Uo7tIgw3ctylCG3fhbmU6zz27fI63Ur5R1/6tzk8"
    "5KroquJ8nIPgKgejTCAXye1Mbe5SvPfDwMWnsZVJVSTdfxoz5cHkjVEI3msDuVMWKNXELqeaMGiq0cCm"
    "0QiYMZF6TZrAMKNXZsuqQeUgtwoRbKrYW2W36CDL1kX2Iz73uosDemUj5oGiZlP7LaFKgZzCDfhHCgPM"
    "5UC5sjsPaRbdLgNPtd2zvk8fAsccOMcxyxKDNq434QYbtqRMRH6MGlE0fPhnaB2c8Sx9/32T9Veqb886"
    "b08=";

// garage [sharp]  source: src/search/garage/materialiconssharp/24px.svg
static const char search_sharp_garage_b64z[] =
    "eJxlkE2PgyAQhv8K4awI41fdqIc9eWiv3q1lgawLxrrQ+ut3NGnSZMOQmczz8maG+u4VefxM9t5Qva7z"
    "R5KEEFhImVtUApzzBBWUSDtcJxlfh/FbLe7X3hpqZSAcD2QYlGhplF4butfeyPDpHg1948HcVn3gtlZt"
    "PQ+rJuhy4RHXkHnIOt7zjZIvM01o7qykSVsn6lBjjGYZJ0lGdBU5JeMTc0rJgmkXvuHqP53d9FTOktkZ"
    "u+KqJ5amUclyUrKijCosRLG3jirfewiPh68xASLowAMOy3vYyEVUkTixXMfgY+hKD13u45Kl4lywUxXl"
    "iARnIM67UDBR9bt8ey11XPza9g/grWkM";

// light [sharp]  source: src/search/light/materialiconssharp/24px.svg
static const char search_sharp_light_b64z[] =
    "eJxVUMtugzAQ/BXLZz/WDzCpgENz4dBccyeE2qgUokBxxNd3oanUalfWjmd2xnI+LZ48PvthKmiY59uL"
    "lDFGEY0Y715qAJCooKQd6kvf8kvdfPj7+DVcCzq0kQCWttiUhLbzYS7oNi9dG1/HR0H/8LG7zmGny9yX"
    "+a2eA0GXEzAI2i7aVnCGlZL3ru/RfBxaKstc+v9qZVgqID2bwPVicDomInN4lxqmBRimlEgUM0Jrptxb"
    "hkcDyGjFlHAHZreaLP8B3PZWuIwBOWolDu65rTKx56DnM28lJ4WGSZU0wI3IUkxQljvmuJvcDhiCSun1"
    "99Xbv5XfG3ZZ4g==";

// living [sharp]  source: src/search/living/materialiconssharp/24px.svg
static const char search_sharp_living_b64z[] =
    "eJxlUcFugzAM/RUrZxocl0CZgMNOXHrl3q4sQWUJahnp+vUzdEitpiT2S57zHMfFdTJw++rdtRR2HIe3"
    "OA4hyLCV/mJiQsSYIwS07nDs283x8HE2F//tTqVwbQDkQQlPAbbtjB1LMeOpa8O7v5XiiQ/dabQLXRWm"
    "KobDaIFV9hihpWSipMYG7wI+u75nce9aEVdFbJbo+YLvf4x3MPjOjfxapaWOFMHDJ1LD7gUQZFLT7NPH"
    "dnFsQGWviOZE/+QxUgiz3YJKVssnqSQd5TLP/yBLcKbsCczkIrmWSBRRTRNxodjQHfYqX4Iatav1tNn1"
    "ioU2KFE1qVVK6mnLbK3y+/oFy+JGVL9duW+s";

// manage_search [sharp]  source: src/search/manage_search/materialiconssharp/24px.svg
static const char search_sharp_manage_search_b64z[] =
    "eJxVUcFugzAM/ZUo5yQ4DoFmAg7bhUN3msS9pYygMagKI1W/fk6rSpscvbwnOy92Uixbz67f47SU3K/r"
    "+SVJQggqGDVf+gQBIKEKzrrpcBw7eTy0X/1l/plOJZ+6wIACU1qc+W7o/VryyLehC6/zteR/8mE4rf6e"
    "roq+Ks6H1TNyeQcBHtMN0xoauHH2OYwjmc9Tx5OqSPr/1blwNTa5t427MVIaa9yQpEbSCMo6od0ojdqZ"
    "O7xpq1wmCDMXEVBokilhK1HlmQBpiWBKm10eRERqRRSCBGtBaDopQRlNzGXEdobyud0jGeZ07f55OfWh"
    "qTHdgtQqswTGShNjkUY8lDBLJMLE+IjlSKXifi7OQTZewyZpOtaQ5fMp4mdUv8r/bUg=";

// podcasts [sharp]  source: src/search/podcasts/materialiconssharp/24px.svg
static const char search_sharp_podcasts_b64z[] =
    "eJxVUktv2zAM/iuCzxQtUY9IQ5JDc9mlpwG9p65nB/OconHjIr9+n9QM6+AHSZD8HoK2l+ugPn5P82XX"
    "jMvy+q1t13Xl1fH5bWjFGNNiolH9fHyeev187H4Nb+f3+WXXzP2qDB7xeBs19qdhXHZNya+nfn04f+ya"
    "L/319LKMtb3fDvvt63EZFVAeDZlR/FX8d/Nkbo36eZomgJ/nvmn323b4f9p6stJhhzdeG0bFLmmLsJEn"
    "kVHLVSeW1KEZ8bmgLULGjC4znUGwWM9aSLT8KICoqALf1KMViqrTjh2mdCThmBEiOLHvC3Gg2rWcPXn2"
    "k2UvuvwOiYMDEkugRNaxzSUWUmGpIrPGjvYXXwtCoSqyzVCJZcxBMbtCnFOFpgptNwXVhspcwSGmJGgl"
    "SlB5b0YqFj6dyCGyT4SE7omVwiecgMVCgb2FG2sJ8F+deLCTjUWIr46K1urEf66ErEGr0yXVAj5TBZZc"
    "jxsH4yJcw1LgJP+MqIMYBvSmwIgUbGgpiRzkLhPNIFUsye3vLSj3cP8HFZ2cvA==";

// shower [sharp]  source: src/search/shower/materialiconssharp/24px.svg
static const char search_sharp_shower_b64z[] =
    "eJx9kctuwyAQRX8FzdrmZfxIZbxoNt10m73jULBC7cihkObrC0lURY0agTSjOVd3rqA9eo1On3Y6SjDO"
    "HV4ICSHgUOB50YRTSklUAFJTv7Uq3/bDXi/z17STMKmAaDxcxAvIqFEbJyH1flThdT5JuONh3DlzwV2r"
    "u/bQO4OiyzvNqOHCc/FGN/QM6GO0NprPkwLStURf1MO4DFahIVo2gIZvCawGtMSSRHeU8ee4esS/SViR"
    "lZg2m8Lk3PPYrWtcsTgr66zMGixSYREZJnzO12x1HbIKF6ur7GZx/rP2lpnTp5n/w9UjTs+SPqb7AdpL"
    "eL0=";

// table_bar [sharp]  source: src/search/table_bar/materialiconssharp/24px.svg
static const char search_sharp_table_bar_b64z[] =
    "eJxVUEtPwzAM/itRzonzaliL2h62CxdOSNy7LksqsnbqQjPx63ELCFD89ufPVurb4sn9EsdbQ0NK10ch"
    "cs6QDUyzF1pKKRBBiRu7Y3T82PVvfp7ex1NDR5eJxKcLFEqCG3xIDV3jZXB5P90b+qefh1MKW7utfVvP"
    "rk/kPMSIRNPo/s//YkVbC78NoFy7FAhuftaa7cAe0FmwO6Yw0axgCs3Ld21D9JIpKBUzUFk0RrEKXVG+"
    "KvtURo7QoKMCzU2w8LBGzGCFa24DNwsvQGpyUCVIy5RcmXBltfJ8XfDxc9+m+FHtJxCJWMs=";

// table_restaurant [sharp]  source: src/search/table_restaurant/materialiconssharp/24px.svg
static const char search_sharp_table_restaurant_b64z[] =
    "eJxVUMuOwjAM/JUo5+blQEtXbQ976gE+okBIKrIpKlmC+HrcIMSubMsjz4wtubneLLn/+HBtqYvx8iVE"
    "SoknzafZCpBSClRQYsKw94bth8PZztNvOLY0mEQkBqwwKXFmtC62dMG30aTv6d7SP3waj9Flumts18zm"
    "EMlp9B4XTcH893+0omuEzQbMyxAdwcs7AK51oZRnwKpe87JCVFT9msN2VYB04CUO2dqppW/V5jVkigOr"
    "+2x/kF3Ja9yiUQsVA1fzMsMC+oV5vI/nwi90TwHJUq8=";

// window [sharp]  source: src/search/window/materialiconssharp/24px.svg
static const char search_sharp_window_b64z[] =
    "eJyNkNsOgyAMhl+FcD+LuotlAS58Ew8MyBgsyqx7+6HGHa5mekiTfn/blA+jJtPN+UFQE+P9DICIGZZZ"
    "6DUUjDFIBCXK141Th6Zur7oPD98J6hUSlqw4JqfEKKtNFHSuR6uwCpOgX320XTRLW3Itea/aSC7WuTQo"
    "ePWr/7AgOehFsGk27vTGUpVWlZQ85wx/uHwvuHL57okrOV+7RHqbfAH0UWWO";

// yard [sharp]  source: src/search/yard/materialiconssharp/24px.svg
static const char search_sharp_yard_b64z[] =
    "eJx9U8FyozAM/RWPz7awZXDtnZBDc+ml195TlwWmLOkkNHTz9SvZbZqZnd0BZGE9ifckszmde/Hxa5pP"
    "rRyW5e1HVa3rCquDw7Gv0BhTEUKKbt4/T51+3qfX/nh4n19aOXerMHRhTbcUQzf2w9JK9s9jt94fPlp5"
    "E1/Hl2XI4e2m327e9ssgqMqjUWbA+oz1g3kyFyl+jtNExQ9zJ6vtpuoz+jYBUeEDnpHSzBNexGNQARCT"
    "0QaCVwbutIXGKzbZSwacU/Qd8DUZS0+IZDBMlGIsGfufdHHK7xRQ10BJVCUR0HOJQK8NexjyF7KXSlH1"
    "d4mUCSGhHO9aziRaFmqxsw14pyIEihDaQG2zY8G4nBcYfffNsVTURahmoczI6iuP6Ybvv/LFKfv6qwXZ"
    "TN8d4kIswgZtihwM+trLXeCCCE1UgZmGz5UZMyNUrFSz0tKerDSw+giOZkhTDLUqw6SpWlQ2Ju3AEW/t"
    "NYKPtPhd5B3rFAOoT1EVpCnQAlMMpIlYn8FNtp/IC5+rNB7T1IlEZ9SiFOl3KyNxlOJIGyTu6+zlh/6A"
    "7R8GMLdV";

static const BaseSVGIcon kIcons[] = {
    { "search", OUTLINED, "bathroom", "src/search/bathroom/materialiconsoutlined/24px.svg", search_outlined_bathroom_b64z },
    { "search", OUTLINED, "bed", "src/search/bed/materialiconsoutlined/24px.svg", search_outlined_bed_b64z },
    { "search", OUTLINED, "bedroom_baby", "src/search/bedroom_baby/materialiconsoutlined/24px.svg", search_outlined_bedroom_baby_b64z },
    { "search", OUTLINED, "bedroom_child", "src/search/bedroom_child/materialiconsoutlined/24px.svg", search_outlined_bedroom_child_b64z },
    { "search", OUTLINED, "bedroom_parent", "src/search/bedroom_parent/materialiconsoutlined/24px.svg", search_outlined_bedroom_parent_b64z },
    { "search", OUTLINED, "blender", "src/search/blender/materialiconsoutlined/24px.svg", search_outlined_blender_b64z },
    { "search", OUTLINED, "camera_indoor", "src/search/camera_indoor/materialiconsoutlined/24px.svg", search_outlined_camera_indoor_b64z },
    { "search", OUTLINED, "camera_outdoor", "src/search/camera_outdoor/materialiconsoutlined/24px.svg", search_outlined_camera_outdoor_b64z },
    { "search", OUTLINED, "chair", "src/search/chair/materialiconsoutlined/24px.svg", search_outlined_chair_b64z },
    { "search", OUTLINED, "chair_alt", "src/search/chair_alt/materialiconsoutlined/24px.svg", search_outlined_chair_alt_b64z },
    { "search", OUTLINED, "coffee", "src/search/coffee/materialiconsoutlined/24px.svg", search_outlined_coffee_b64z },
    { "search", OUTLINED, "coffee_maker", "src/search/coffee_maker/materialiconsoutlined/24px.svg", search_outlined_coffee_maker_b64z },
    { "search", OUTLINED, "dining", "src/search/dining/materialiconsoutlined/24px.svg", search_outlined_dining_b64z },
    { "search", OUTLINED, "door_back", "src/search/door_back/materialiconsoutlined/24px.svg", search_outlined_door_back_b64z },
    { "search", OUTLINED, "door_front", "src/search/door_front/materialiconsoutlined/24px.svg", search_outlined_door_front_b64z },
    { "search", OUTLINED, "door_sliding", "src/search/door_sliding/materialiconsoutlined/24px.svg", search_outlined_door_sliding_b64z },
    { "search", OUTLINED, "doorbell", "src/search/doorbell/materialiconsoutlined/24px.svg", search_outlined_doorbell_b64z },
    { "search", OUTLINED, "feed", "src/search/feed/materialiconsoutlined/24px.svg", search_outlined_feed_b64z },
    { "search", OUTLINED, "flatware", "src/search/flatware/materialiconsoutlined/24px.svg", search_outlined_flatware_b64z },
    { "search", OUTLINED, "garage", "src/search/garage/materialiconsoutlined/24px.svg", search_outlined_garage_b64z },
    { "search", OUTLINED, "light", "src/search/light/materialiconsoutlined/24px.svg", search_outlined_light_b64z },
    { "search", OUTLINED, "living", "src/search/living/materialiconsoutlined/24px.svg", search_outlined_living_b64z },
    { "search", OUTLINED, "manage_search", "src/search/manage_search/materialiconsoutlined/24px.svg", search_outlined_manage_search_b64z },
    { "search", OUTLINED, "podcasts", "src/search/podcasts/materialiconsoutlined/24px.svg", search_outlined_podcasts_b64z },
    { "search", OUTLINED, "shower", "src/search/shower/materialiconsoutlined/24px.svg", search_outlined_shower_b64z },
    { "search", OUTLINED, "table_bar", "src/search/table_bar/materialiconsoutlined/24px.svg", search_outlined_table_bar_b64z },
    { "search", OUTLINED, "table_restaurant", "src/search/table_restaurant/materialiconsoutlined/24px.svg", search_outlined_table_restaurant_b64z },
    { "search", OUTLINED, "window", "src/search/window/materialiconsoutlined/24px.svg", search_outlined_window_b64z },
    { "search", OUTLINED, "yard", "src/search/yard/materialiconsoutlined/24px.svg", search_outlined_yard_b64z },
    { "search", ROUNDED, "bathroom", "src/search/bathroom/materialiconsround/24px.svg", search_rounded_bathroom_b64z },
    { "search", ROUNDED, "bed", "src/search/bed/materialiconsround/24px.svg", search_rounded_bed_b64z },
    { "search", ROUNDED, "bedroom_baby", "src/search/bedroom_baby/materialiconsround/24px.svg", search_rounded_bedroom_baby_b64z },
    { "search", ROUNDED, "bedroom_child", "src/search/bedroom_child/materialiconsround/24px.svg", search_rounded_bedroom_child_b64z },
    { "search", ROUNDED, "bedroom_parent", "src/search/bedroom_parent/materialiconsround/24px.svg", search_rounded_bedroom_parent_b64z },
    { "search", ROUNDED, "blender", "src/search/blender/materialiconsround/24px.svg", search_rounded_blender_b64z },
    { "search", ROUNDED, "camera_indoor", "src/search/camera_indoor/materialiconsround/24px.svg", search_rounded_camera_indoor_b64z },
    { "search", ROUNDED, "camera_outdoor", "src/search/camera_outdoor/materialiconsround/24px.svg", search_rounded_camera_outdoor_b64z },
    { "search", ROUNDED, "chair", "src/search/chair/materialiconsround/24px.svg", search_rounded_chair_b64z },
    { "search", ROUNDED, "chair_alt", "src/search/chair_alt/materialiconsround/24px.svg", search_rounded_chair_alt_b64z },
    { "search", ROUNDED, "coffee", "src/search/coffee/materialiconsround/24px.svg", search_rounded_coffee_b64z },
    { "search", ROUNDED, "coffee_maker", "src/search/coffee_maker/materialiconsround/24px.svg", search_rounded_coffee_maker_b64z },
    { "search", ROUNDED, "dining", "src/search/dining/materialiconsround/24px.svg", search_rounded_dining_b64z },
    { "search", ROUNDED, "door_back", "src/search/door_back/materialiconsround/24px.svg", search_rounded_door_back_b64z },
    { "search", ROUNDED, "door_front", "src/search/door_front/materialiconsround/24px.svg", search_rounded_door_front_b64z },
    { "search", ROUNDED, "door_sliding", "src/search/door_sliding/materialiconsround/24px.svg", search_rounded_door_sliding_b64z },
    { "search", ROUNDED, "doorbell", "src/search/doorbell/materialiconsround/24px.svg", search_rounded_doorbell_b64z },
    { "search", ROUNDED, "feed", "src/search/feed/materialiconsround/24px.svg", search_rounded_feed_b64z },
    { "search", ROUNDED, "flatware", "src/search/flatware/materialiconsround/24px.svg", search_rounded_flatware_b64z },
    { "search", ROUNDED, "garage", "src/search/garage/materialiconsround/24px.svg", search_rounded_garage_b64z },
    { "search", ROUNDED, "light", "src/search/light/materialiconsround/24px.svg", search_rounded_light_b64z },
    { "search", ROUNDED, "living", "src/search/living/materialiconsround/24px.svg", search_rounded_living_b64z },
    { "search", ROUNDED, "manage_search", "src/search/manage_search/materialiconsround/24px.svg", search_rounded_manage_search_b64z },
    { "search", ROUNDED, "podcasts", "src/search/podcasts/materialiconsround/24px.svg", search_rounded_podcasts_b64z },
    { "search", ROUNDED, "shower", "src/search/shower/materialiconsround/24px.svg", search_rounded_shower_b64z },
    { "search", ROUNDED, "table_bar", "src/search/table_bar/materialiconsround/24px.svg", search_rounded_table_bar_b64z },
    { "search", ROUNDED, "table_restaurant", "src/search/table_restaurant/materialiconsround/24px.svg", search_rounded_table_restaurant_b64z },
    { "search", ROUNDED, "window", "src/search/window/materialiconsround/24px.svg", search_rounded_window_b64z },
    { "search", ROUNDED, "yard", "src/search/yard/materialiconsround/24px.svg", search_rounded_yard_b64z },
    { "search", SHARP, "bathroom", "src/search/bathroom/materialiconssharp/24px.svg", search_sharp_bathroom_b64z },
    { "search", SHARP, "bed", "src/search/bed/materialiconssharp/24px.svg", search_sharp_bed_b64z },
    { "search", SHARP, "bedroom_baby", "src/search/bedroom_baby/materialiconssharp/24px.svg", search_sharp_bedroom_baby_b64z },
    { "search", SHARP, "bedroom_child", "src/search/bedroom_child/materialiconssharp/24px.svg", search_sharp_bedroom_child_b64z },
    { "search", SHARP, "bedroom_parent", "src/search/bedroom_parent/materialiconssharp/24px.svg", search_sharp_bedroom_parent_b64z },
    { "search", SHARP, "blender", "src/search/blender/materialiconssharp/24px.svg", search_sharp_blender_b64z },
    { "search", SHARP, "camera_indoor", "src/search/camera_indoor/materialiconssharp/24px.svg", search_sharp_camera_indoor_b64z },
    { "search", SHARP, "camera_outdoor", "src/search/camera_outdoor/materialiconssharp/24px.svg", search_sharp_camera_outdoor_b64z },
    { "search", SHARP, "chair", "src/search/chair/materialiconssharp/24px.svg", search_sharp_chair_b64z },
    { "search", SHARP, "chair_alt", "src/search/chair_alt/materialiconssharp/24px.svg", search_sharp_chair_alt_b64z },
    { "search", SHARP, "coffee", "src/search/coffee/materialiconssharp/24px.svg", search_sharp_coffee_b64z },
    { "search", SHARP, "coffee_maker", "src/search/coffee_maker/materialiconssharp/24px.svg", search_sharp_coffee_maker_b64z },
    { "search", SHARP, "dining", "src/search/dining/materialiconssharp/24px.svg", search_sharp_dining_b64z },
    { "search", SHARP, "door_back", "src/search/door_back/materialiconssharp/24px.svg", search_sharp_door_back_b64z },
    { "search", SHARP, "door_front", "src/search/door_front/materialiconssharp/24px.svg", search_sharp_door_front_b64z },
    { "search", SHARP, "door_sliding", "src/search/door_sliding/materialiconssharp/24px.svg", search_sharp_door_sliding_b64z },
    { "search", SHARP, "doorbell", "src/search/doorbell/materialiconssharp/24px.svg", search_sharp_doorbell_b64z },
    { "search", SHARP, "feed", "src/search/feed/materialiconssharp/24px.svg", search_sharp_feed_b64z },
    { "search", SHARP, "flatware", "src/search/flatware/materialiconssharp/24px.svg", search_sharp_flatware_b64z },
    { "search", SHARP, "garage", "src/search/garage/materialiconssharp/24px.svg", search_sharp_garage_b64z },
    { "search", SHARP, "light", "src/search/light/materialiconssharp/24px.svg", search_sharp_light_b64z },
    { "search", SHARP, "living", "src/search/living/materialiconssharp/24px.svg", search_sharp_living_b64z },
    { "search", SHARP, "manage_search", "src/search/manage_search/materialiconssharp/24px.svg", search_sharp_manage_search_b64z },
    { "search", SHARP, "podcasts", "src/search/podcasts/materialiconssharp/24px.svg", search_sharp_podcasts_b64z },
    { "search", SHARP, "shower", "src/search/shower/materialiconssharp/24px.svg", search_sharp_shower_b64z },
    { "search", SHARP, "table_bar", "src/search/table_bar/materialiconssharp/24px.svg", search_sharp_table_bar_b64z },
    { "search", SHARP, "table_restaurant", "src/search/table_restaurant/materialiconssharp/24px.svg", search_sharp_table_restaurant_b64z },
    { "search", SHARP, "window", "src/search/window/materialiconssharp/24px.svg", search_sharp_window_b64z },
    { "search", SHARP, "yard", "src/search/yard/materialiconssharp/24px.svg", search_sharp_yard_b64z },
};

static const int kIconCount = (int)(sizeof(kIcons) / sizeof(kIcons[0]));

} // namespace search

#endif // UPP_MATERIAL_SYMBOLS_ICONS_SEARCH_H
