// Auto-generated by Material Symbols SVG Extractor (v0.9)
// FORMAT: KICONS_V1_NO_DECODERS
// Category: alert
// Location: E:/apps/3rdParty/material-design-icons/src/alert/
// Each icon is Base64(zlib(minified-SVG)). Decode with ZDecompress(Base64Decode(...)).

#ifndef UPP_MATERIAL_SYMBOLS_ICONS_ALERT_H
#define UPP_MATERIAL_SYMBOLS_ICONS_ALERT_H

#include <Core/Core.h>
#include <plugin/z/z.h>

namespace alert {

using namespace Upp;

enum Style : uint8 { OUTLINED = 0, ROUNDED = 1, SHARP = 2 };

struct BaseSVGIcon {
    const char* category;
    Style       style;
    const char* name;
    const char* source;
    const char* b64zIcon;
};

// add_alert [outlined]  source: src/alert/add_alert/materialiconsoutlined/24px.svg
static const char alert_outlined_add_alert_b64z[] =
    "eJxNULtuwzAM/BVCO2lJtB4ubA/tkiVr98IJLANJE9SGFPjrSwUN0EF31JG6k9SveYbH9fK9Dipt2/2t"
    "aUopVJhuP3NjtdaNTChI52VO26BsqyAv5/J+ewxKgwbbQtXKctrSsz32968twWlQR6NJG7BGcNJgyFDs"
    "hLp/sFbAl44VEjJ1cT8aC36yFLykOLAkSQ5cDoeQMUwan60qo8jo9qvGltwkZgxanBz5UEmcXZbw8BGI"
    "PbQUZR4C+UrGZH9BCzabZGJGIxu0Gb0EMLGTFPboyUgCOSkif7L0hPHP/7XkxgwxyWk+xGwTZ07ixFKg"
    "lUftqhn7+pvjL4XfWkE=";

// auto_delete [outlined]  source: src/alert/auto_delete/materialiconsoutlined/24px.svg
static const char alert_outlined_auto_delete_b64z[] =
    "eJxdUk1vgzAM/SsR52BiJwSY2h7WSy87Tdq9YwzQGFQtK91+/V7STftQEvvFH8+OYXU6t+ryOoynddLN"
    "8+Emy5ZlocXSdGwzMcZkiEhUM+4fhyZ93Ncv7XF6G5/WydgsymCJw05U1/RtN6+TgM99s9xOl3Xyy7/0"
    "T3MX3ZtVu1kdm3pWz/0wgGgam7/5P7HZZpW1MQH7MA3v7TSqw9SPMxrmXItipqgMFKs8Snc1xeMUwiLR"
    "YT93Co3fsddVnRoqtEmZLBRxKpBSPeQ7ObPURjMxLJWWsLqcfFnDBEzWa0u51U57sqJdbakEhy5SS2yh"
    "CrUVq1nCjavgrHSo+aHuAgC5IesgjIXwob4pNe/cQ9GVZ0vit3gOI5ZDHWhLXiIJKMAkXKdChUf/OYA4"
    "qFydrkgDn/B+XDQu91yGSGEdEz/iJP4P0oexSZjUlywU0nzonhWEg4UqdY3zJN/fJR78IJtPOzuPBw==";

// error [outlined]  source: src/alert/error/materialiconsoutlined/24px.svg
static const char alert_outlined_error_b64z[] =
    "eJw9jsEKgzAQRH9l2XuSzTZqKYmH9txTofeCYoRapYZE/PpGkcIe3sy8w9o5drAM78/s0IcwXZRKKcl0"
    "kuO3U0xEKhsIvu07HxyyQYh9m67j4pCAgA1sXeqb4Pe5ttMreGgc3jUD30ppzpABDtA8m400/U8chdD0"
    "0JUseNeA10GDLrzgKNhzzDmrOT6rnMoVVW237+ofFHMzcQ==";

// error_outline [outlined]  source: src/alert/error_outline/materialiconsoutlined/24px.svg
static const char alert_outlined_error_outline_b64z[] =
    "eJw9j0sLwjAQhP/Kknseu01f0vagZ0+Cd1FpClbFhqbk17tpRZIw38xOCGmmuYdlfDynVjjv3zutQwgq"
    "ZOr16TUZYzQ3BLj70DvfCrIC5uEe9q+lFQYMkIWUheHm3TrumvfFO7i14ogImDuayUmaJcXRyIptwfZc"
    "xlHVtcwPhbIlEC+GigVpsilCAzU3WA9Yqpwb6/4z0unHgJiKFI/Izlwl3yfgt2Sm8oqlmjaA9UAykMwG"
    "KYtCd036afcFMiRC0A==";

// notification_important [outlined]  source: src/alert/notification_important/materialiconsoutlined/24px.svg
static const char alert_outlined_notification_important_b64z[] =
    "eJxNUDFuwzAM/AqhnbRIWZIT2B7apUvW7oUTWAaSJqgNKcjrSwUN0EF35JG4I9SveYb75fy9DiZt223f"
    "NKUUKo6uP3Mj1tpGNwyk0zKnbTDSGsjLqbxd74OxYEFaqFpZjlt6jsf+9rUlOA7mwJYsg7DiZIGJqdsp"
    "7f7BWgFfOlZI6GjXPQ4sECahGDTFg5AmefA5fsSMcbL4HFUZVUb/uFhsyU9q5sCqk6cQK6mzzxoe3yO5"
    "AC11ug+RQiXmHM4oIJkTdxlZG5SMQQMcOa8pLmAg1gTyWnTu0+lMGf/8X08vZuiS5Dah6DUQtJZam2bs"
    "6zeOvxSUWDw=";

// warning [outlined]  source: src/alert/warning/materialiconsoutlined/24px.svg
static const char alert_outlined_warning_b64z[] =
    "eJwdzUEOgyAUBNCr/Pw9AiOrBlx0bQ/RRMMnKdVUAsbTV12+mUnGbzXSnj/fLbCUsj60bq11re+WX9Qw"
    "xuhzwSRzilICwzHVNLfnsgc2ZAiOrqylqchdD359F6Ep8MsSrACjBYEuHNlC9aJQFQQVRzbK3XQn3cF6"
    "8Nff8AdfySsj";

// warning_amber [outlined]  source: src/alert/warning_amber/materialiconsoutlined/24px.svg
static const char alert_outlined_warning_amber_b64z[] =
    "eJwtjjsOgzAQBa+y2h5/liWRI0yRKgU5RCQQixQCAstGnD44Sjkzr3j1FgfYp/dn8yghLDetU0oqlWpe"
    "B03GGH0uEKQfBwkeiRHi2Kf7vHs0YIAYsktjF+SXm3p5BYHO49MSVMq51jpVlWDdgxVf27/NlVoLZIUo"
    "SzomC5aloEhCsTjZFJeMnJEP1E2d3zRfcdYxeQ==";

// add_alert [rounded]  source: src/alert/add_alert/materialiconsround/24px.svg
static const char alert_rounded_add_alert_b64z[] =
    "eJxVUk1vgzAM/SsRZ8fEITRlAg7rZZeeKu3eUkrQGFSFQdVfPwc02ilf5vn5+SUi7cdK3L+bts8CNwzX"
    "tzCcpgmnCLtbFWqlVMiMQJTt8dSU8nQsvqpb99Oes6AtJ6F4aMMzEK6sKzdkgY/Hupzeu3sWvOSn+jy4"
    "OZ2nVZ7eymIQl7ppWKhry//1T26Yp2E1Fyzzehyc4OZ70qB1QUigQEuFCe/aSbMj/vYwzZiGmfh4EXpK"
    "JEDWSRqlLZTUaBNJmJCMkYw0GHOw/Yww3hFvoHFjWQy3ESyiPbNjUAzPAa9Rod1ZlgCD2w1swKImPkiN"
    "9iMWBduMuUKyZzQxH9T7AMgPR6ZY8kBygSUdKPEQcWdv9iH2ZIAib5oKBZ6/cllNLpV88KWIWS8910z/"
    "15wZnsZ3Xzgr3C8GvauROautFT2QmW1FMNtZX3dd/M/kv10qklI=";

// auto_delete [rounded]  source: src/alert/auto_delete/materialiconsround/24px.svg
static const char alert_rounded_auto_delete_b64z[] =
    "eJyVU02Pm0AM/SuI82DGng+gSnJYLjlsT5V6z7IUolKySlhY5df3GRRt21s1YD+P7fGzB3a3uUs+fg3j"
    "bZ/20/T2Jc+XZaHF0eXa5WKtzRGRJu14ehna7OXU/Oyul/fxdZ+O7ZJYLPF40qRvz10/7VPF87ldni4f"
    "+/QP/3J+nfrVfdh1h921babkx3kYcNBlbP/O/4zN/ycy79aj8bydpj4Bx68cTdVklgpjMyYHRZwJpFTf"
    "i0b3GN4qE11HXwtVJhgxAVpMMbNtrEEQMnQDqw8UywZbwOSicRSc8SaSE+OTxlGJIqbIHLGDKmpxhkUN"
    "rtRXGeV0T5SacJMJFRHkAoB4qHDbgFEIKjDAKHzjUgOFzZp3134/u/TGN5ZCQGXtxwcoRnu6t9oZ6+pR"
    "JAw6Dl5FzZYia38QlhzSVFtwPGICXKNX3Qvkqi0qkDLA9JJnT2B3lJq1nCBK1rrGYWIbl83GOrL/h3Cg"
    "Aj55foAawHkAw2queAVFmJ0OXM/EtHF9FUQstQTeMg5oCVnkcZ3k3COiUK9VVEX0KpLMuEoSBwOHI0qA"
    "Sp0Dps1kwSXiSAiZcXk+1Ju9cYmEsa/sNr73x/e2vvhFDr8BHR7E1Q==";

// error [rounded]  source: src/alert/error/materialiconsround/24px.svg
static const char alert_rounded_error_b64z[] =
    "eJw9j0FrwzAMhf/Kw3fbkupsZSQ5rOeeCr2PtMSBpS2LsUt+feVQBkJ87326qF3yiOf8e1s6E1N6fHlf"
    "SnFl5+5/oxci8nphEK/TGFNnJBjk6Vq+78/OEAgSULsyXVLcdN8+flLEpTNHFsjhw4U9FPAGliVUYvof"
    "+y4s04k/XSPbGWSd1fJgXdNApXWh0c3n/UC12yK0WBjKUM5hIKiyW652nRkhWslWomRZje/b+lL/Aimk"
    "PVw=";

// error_outline [rounded]  source: src/alert/error_outline/materialiconsround/24px.svg
static const char alert_rounded_error_outline_b64z[] =
    "eJw9UM1qwzAMfhXhu2xJsZdkJDms550Gu4+0xIFmLUuIS55+sjuGbX2/BuNu3Sd4LNfvtTdx2+6vzqWU"
    "bKrs7WdyQkROGwbiZZ7i1hvxBvb5kt5uj94QEIiH7KX5vMUSD939a4tw7s07C9SjDUFrDNYHnbz7kUA9"
    "LBrVWZGz0MmfzUioYZE5PRa0xBhOL9bXILqUNAosq88WE7S2bRVPXNugjbL/OcvHHwfmXJQjP0toRL0v"
    "QNhgZUOj0KxPAuVAFpDFk2TvWBiriLKjRNnlMG7o8vcMv03cTKk=";

// notification_important [rounded]  source: src/alert/notification_important/materialiconsround/24px.svg
static const char alert_rounded_notification_important_b64z[] =
    "eJxFUE1vwjAM/StW7nbjpE4aRDls13HlPhVEkOhAa5Uifv2cbmhS4q/3/OxkO5UzPMbr19SbPM/3TdMs"
    "y0KLp9v3uXHW2kYZBvLpcs5zb1xroFxOy9vt0RsLFlwLtbZcjnNe4d32/jlnOPZmzw6cH5hYeUwpIXXp"
    "N6gmo6fUDRXiF/BvnmNHLmFLkT9YS7FgGKy2eEFHPmAgFhQSDTp/8IqpRwpRxeV1p2r+aiorRWfF96j9"
    "0FInIBApVMdcwlVZrk53aVAhrwepztYdKK4us6jAQGl9kW+1w3Zaxwo+9+yBQ0ZX0GVX3HO0KPpAEkFq"
    "dQgysK5UE7V8SHVrkTWt6MSw8oC12TS7bf383Q+zhWGQ";

// warning [rounded]  source: src/alert/warning/materialiconsround/24px.svg
static const char alert_rounded_warning_b64z[] =
    "eJwlj82OgzAMhF9llHtM7ASyrIBDz+1DrGhFkLY/WhCpePo67Mnj+ca23C3bhPf997H0Jq3r67uqcs6U"
    "PT3/pkqcc5UmDNJtntLaGwkG23zLp+e7Nw4OElC8PF/XdOChe/2sCdfeXAKFCOHENblmZKpDGaDaMjUR"
    "TNFbf2avFYHadrQUozLvrVDT/itPoYE7C8UA/joiKIC4hT92wO8XFnBQWNdwli0FvWF5szK6Yh491FkY"
    "qqF6UwRF9ugL3e+MkKzoVJJNdlMNXXl++ADmUUZM";

// warning_amber [rounded]  source: src/alert/warning_amber/materialiconsround/24px.svg
static const char alert_rounded_warning_amber_b64z[] =
    "eJwtUEluwzAM/AqhO2lRi1UVtg899WA/onACy0DTBLUgBX59JTXgZTgLB+BwpA2et++fYxQhxsd71+Wc"
    "KWu6/26dklJ2xSEgXPctxFEoIyDt1/xxf45CggRloHJ5v8TQ5Gl4fMUAl1EsrMCS9zN7shrYfxoybn6x"
    "iyJngN9WJOeASWtiD8VGToMObEn2K5M1tYQsMvWuiahn1tVkypWWxppGRb3/R5pMD3J+FZwLMzAntUog"
    "a8lY4DoHY8PICYuGRasEcp0DGdoCfN4k2KCSCqhO0U1D/cj0B8MTSqY=";

// add_alert [sharp]  source: src/alert/add_alert/materialiconssharp/24px.svg
static const char alert_sharp_add_alert_b64z[] =
    "eJxFTzFuwzAM/AqhnbQoWrIc2B7apUtX74UTWAbiJmgEKfDrK7UouhyPvMORHB5phed+/XyMKsR4PzVN"
    "zpmy0O1rbYzWuikOBeGyrSGOyrQK0nbJL7fnqDRoMC3UWd7OMfzI03D/iAHOo3pnA0YWJi4+pr5H8v0v"
    "qRBQqPdLlfhP+Idj79AldIsuNrFoSBw6YouWbCFeZiZbMpIh1712RYaWvAULHblamJO7YjkhcWCfkEuD"
    "5thR6uK6PklAk1De/MwcZPbBlFFN1HyoZhrq79M3lgpJiw==";

// auto_delete [sharp]  source: src/alert/auto_delete/materialiconssharp/24px.svg
static const char alert_sharp_auto_delete_b64z[] =
    "eJxdUU1vgzAM/SsW52CwE0KZgMN22WWnSbu3lAY0Bqhlpeuvn5Nu2odI/Oz4vdgO5ens4PI2jKcq6pZl"
    "vkuSdV1x1TgdXcJpmibCiKAdt7uhjXfb5tUdp/dxX0Vju0IqHxtZEXRt77qlirx/7tv1frpU0a/82u+X"
    "LqTr0tXlsW0WOPTDIBdNY/tX/8NN6jJxQSBrnoYPN40wT/24SMOUKQYiDJAKEGTBmttR2AaEFi6at0sH"
    "0vgTWVU0cYq5SmNCLYAUs1guXrJHPpPpcrSbhpBYMWqrNGZaGWVRszKNxo1oVB5rJC2QP7BWxD6gwucK"
    "5UtcwVdigiZmzK0Uy8RhI5Cdbo7yrvQqgZLgmTaeyKSC8Bq6/j+09SOyn+rL5iAy60sTiDFyggXceBb5"
    "+w3Dlp9ZfwItf32K";

// error [sharp]  source: src/alert/error/materialiconssharp/24px.svg
static const char alert_sharp_error_b64z[] =
    "eJw9jsEKgzAQRH9l2XuSzTZqKYmH9txTofeCYoRapYZE/PpGkcIe3sy8w9o5drAM78/s0IcwXZRKKcl0"
    "kuO3U0xEKhsIvu07HxyyQYh9m67j4pCAgA1sXeqb4Pe5ttMreGgc3jUD30ppzpABDtA8m400/U8chdD0"
    "0JUseNeA10GDLrzgKNhzzDmrOT6rnMoVVW237+ofFHMzcQ==";

// error_outline [sharp]  source: src/alert/error_outline/materialiconssharp/24px.svg
static const char alert_sharp_error_outline_b64z[] =
    "eJw9j0sLwjAQhP/Kknseu01f0vagZ0+Cd1FpClbFhqbk17tpRZIw38xOCGmmuYdlfDynVjjv3zutQwgq"
    "ZOr16TUZYzQ3BLj70DvfCrIC5uEe9q+lFQYMkIWUheHm3TrumvfFO7i14ogImDuayUmaJcXRyIptwfZc"
    "xlHVtcwPhbIlEC+GigVpsilCAzU3WA9Yqpwb6/4z0unHgJiKFI/Izlwl3yfgt2Sm8oqlmjaA9UAykMwG"
    "KYtCd036afcFMiRC0A==";

// notification_important [sharp]  source: src/alert/notification_important/materialiconssharp/24px.svg
static const char alert_sharp_notification_important_b64z[] =
    "eJxFj0FvgzAMhf+KlbtN7JAQJuCwnXftfaIVQSprtUZJxa+f2TTt8uzP78myh0dZ4LldPx+jSTnfX5qm"
    "1krV0e1racRa22jCQLqsS8qjkdZAWS/19fYcjQUL0sIxq+s5px97Gu4fOcF5NO8sIG5mYs0x9T1S7H+b"
    "QxI66uN8WPxn/Mu+dRgKhtlqzHkUcgEDsUdPXpvoTkxedxSh0L11akNL0YOHjsJRmEu4op5QOHEsyAoo"
    "+4YBOaEUlCRF2WKreIpK7W6aaTg+nr4B0gRHVw==";

// warning [sharp]  source: src/alert/warning/materialiconssharp/24px.svg
static const char alert_sharp_warning_b64z[] =
    "eJwdzUEOgyAUBNCr/Pw9AiOrBlx0bQ/RRMMnKdVUAsbTV12+mUnGbzXSnj/fLbCUsj60bq11re+WX9Qw"
    "xuhzwSRzilICwzHVNLfnsgc2ZAiOrqylqchdD359F6Ep8MsSrACjBYEuHNlC9aJQFQQVRzbK3XQn3cF6"
    "8Nff8AdfySsj";

// warning_amber [sharp]  source: src/alert/warning_amber/materialiconssharp/24px.svg
static const char alert_sharp_warning_amber_b64z[] =
    "eJwtjjsOgzAQBa+y2h5/liWRI0yRKgU5RCQQixQCAstGnD44Sjkzr3j1FgfYp/dn8yghLDetU0oqlWpe"
    "B03GGH0uEKQfBwkeiRHi2Kf7vHs0YIAYsktjF+SXm3p5BYHO49MSVMq51jpVlWDdgxVf27/NlVoLZIUo"
    "SzomC5aloEhCsTjZFJeMnJEP1E2d3zRfcdYxeQ==";

static const BaseSVGIcon kIcons[] = {
    { "alert", OUTLINED, "add_alert", "src/alert/add_alert/materialiconsoutlined/24px.svg", alert_outlined_add_alert_b64z },
    { "alert", OUTLINED, "auto_delete", "src/alert/auto_delete/materialiconsoutlined/24px.svg", alert_outlined_auto_delete_b64z },
    { "alert", OUTLINED, "error", "src/alert/error/materialiconsoutlined/24px.svg", alert_outlined_error_b64z },
    { "alert", OUTLINED, "error_outline", "src/alert/error_outline/materialiconsoutlined/24px.svg", alert_outlined_error_outline_b64z },
    { "alert", OUTLINED, "notification_important", "src/alert/notification_important/materialiconsoutlined/24px.svg", alert_outlined_notification_important_b64z },
    { "alert", OUTLINED, "warning", "src/alert/warning/materialiconsoutlined/24px.svg", alert_outlined_warning_b64z },
    { "alert", OUTLINED, "warning_amber", "src/alert/warning_amber/materialiconsoutlined/24px.svg", alert_outlined_warning_amber_b64z },
    { "alert", ROUNDED, "add_alert", "src/alert/add_alert/materialiconsround/24px.svg", alert_rounded_add_alert_b64z },
    { "alert", ROUNDED, "auto_delete", "src/alert/auto_delete/materialiconsround/24px.svg", alert_rounded_auto_delete_b64z },
    { "alert", ROUNDED, "error", "src/alert/error/materialiconsround/24px.svg", alert_rounded_error_b64z },
    { "alert", ROUNDED, "error_outline", "src/alert/error_outline/materialiconsround/24px.svg", alert_rounded_error_outline_b64z },
    { "alert", ROUNDED, "notification_important", "src/alert/notification_important/materialiconsround/24px.svg", alert_rounded_notification_important_b64z },
    { "alert", ROUNDED, "warning", "src/alert/warning/materialiconsround/24px.svg", alert_rounded_warning_b64z },
    { "alert", ROUNDED, "warning_amber", "src/alert/warning_amber/materialiconsround/24px.svg", alert_rounded_warning_amber_b64z },
    { "alert", SHARP, "add_alert", "src/alert/add_alert/materialiconssharp/24px.svg", alert_sharp_add_alert_b64z },
    { "alert", SHARP, "auto_delete", "src/alert/auto_delete/materialiconssharp/24px.svg", alert_sharp_auto_delete_b64z },
    { "alert", SHARP, "error", "src/alert/error/materialiconssharp/24px.svg", alert_sharp_error_b64z },
    { "alert", SHARP, "error_outline", "src/alert/error_outline/materialiconssharp/24px.svg", alert_sharp_error_outline_b64z },
    { "alert", SHARP, "notification_important", "src/alert/notification_important/materialiconssharp/24px.svg", alert_sharp_notification_important_b64z },
    { "alert", SHARP, "warning", "src/alert/warning/materialiconssharp/24px.svg", alert_sharp_warning_b64z },
    { "alert", SHARP, "warning_amber", "src/alert/warning_amber/materialiconssharp/24px.svg", alert_sharp_warning_amber_b64z },
};

static const int kIconCount = (int)(sizeof(kIcons) / sizeof(kIcons[0]));

} // namespace alert

#endif // UPP_MATERIAL_SYMBOLS_ICONS_ALERT_H
