// Auto-generated by Material Symbols SVG Extractor (v0.9)
// FORMAT: KICONS_V1_NO_DECODERS
// Category: toggle
// Location: E:/apps/3rdParty/material-design-icons/src/toggle/
// Each icon is Base64(zlib(minified-SVG)). Decode with ZDecompress(Base64Decode(...)).

#ifndef UPP_MATERIAL_SYMBOLS_ICONS_TOGGLE_H
#define UPP_MATERIAL_SYMBOLS_ICONS_TOGGLE_H

#include <Core/Core.h>
#include <plugin/z/z.h>

namespace toggle {

using namespace Upp;

enum Style : uint8 { OUTLINED = 0, ROUNDED = 1, SHARP = 2 };

struct BaseSVGIcon {
    const char* category;
    Style       style;
    const char* name;
    const char* source;
    const char* b64zIcon;
};

// check_box [outlined]  source: src/toggle/check_box/materialiconsoutlined/24px.svg
static const char toggle_outlined_check_box_b64z[] =
    "eJxNj7FuwzAMRH+F0C6JoqWkKqIMnbxk9V44rmXAsYNGsAJ/fUlPBYEb7t4R5OW1jfB+zMsrqVzK89Pa"
    "WqupjVl/R0uIaJlQkIdpzCUp8gq2aahf6zspBATyIF6d7iUf8fXy/C4Z7kndOM/kN/Itdrgr+JnmOall"
    "XQZl/2EuQtOGXjvjADWBiSy0Od8jsGcikExm40CAtHiautCjtLQ0ZPYHN05t6ALDvGC/ubOJEeLMmHci"
    "pE8mRBDRZMKHyPkIQBDw0HBjlwPl8+sfv69I4w==";

// check_box_outline_blank [outlined]  source: src/toggle/check_box_outline_blank/materialiconsoutlined/24px.svg
static const char toggle_outlined_check_box_outline_blank_b64z[] =
    "eJxNjrEOgzAMRH/F8p7EcZOBijB0YunKXgElSBRQiQji65swVSdZ1t072eW2D3B8pnlz6ENY70rFGGW8"
    "yeU7KCYilQgE34+DDw7ZIOxjHx/L4ZCAgA1kL45d8FdclesreOgcPlPu2exsamroRHiP0+RwXuYe1R+m"
    "C7C7NrVtrNfmQ4Jr2wotNaQVZJEGp7wlSJ4sgLMS2V4IsMie4Ma2lFsiN7LOfCW/X/0ArBg8yw==";

// indeterminate_check_box [outlined]  source: src/toggle/indeterminate_check_box/materialiconsoutlined/24px.svg
static const char toggle_outlined_indeterminate_check_box_b64z[] =
    "eJxNj7EOgzAMRH/F8p7EMaEVVcPQiaUre0UpQaKASpRUfH0TpuokD+/ubPm6hQG+72neLDrv14tSMUYZ"
    "C7l8BsVEpFICwfXj4LxFNghh7ONt+VokIGADmcXx6d1h19f14R08Ld6T79gENg3tCK9xmizOy9yj+gvp"
    "Coqm7ISWGkgwyCoNDtp0BInJCjjLJXBEgEVmgtuyo9wSuZG1v1Pj1JRtmcJpwX4/g9ZOU+DmvOej+Zf6"
    "B5hmQFU=";

// radio_button_checked [outlined]  source: src/toggle/radio_button_checked/materialiconsoutlined/24px.svg
static const char toggle_outlined_radio_button_checked_b64z[] =
    "eJxNj0FrwzAMhf+K0D22rDqrKXUP3WWXnQa7DzeNDWlSEhN3+fWzkzIKEvr03jtIx2lu4XHr+smij/F+"
    "kDKlJNJODGMrmYhkTiD4JrQ+WmSNMIcmnYeHRQIC1lC0FC7Rr/bpeP+JHi4WP7PvWc+sP+ibFoRr6DqL"
    "/dA3KF9iioHf34Q2kAGeoHjShRT9V/UUKkVfai9qXmPAyy27xhWbgSpT7URt8jDTBrA2lAXKskHRlnKH"
    "C6PrGnD5IcUI7nebo8W62OX/0x/rNkoi";

// radio_button_unchecked [outlined]  source: src/toggle/radio_button_unchecked/materialiconsoutlined/24px.svg
static const char toggle_outlined_radio_button_unchecked_b64z[] =
    "eJxNj0ELwjAMhf9KyH1tGqsWsR704sWT4F3cXAtzE1dW2a+3nUOEhHx57x2SbT/U8H40bW/RhfDcSBlj"
    "FHEhulctmYhkSiC4ytcuWGSNMPgq7ru3RQIC1pC16MvgJnu3fV6Dg9LiKfmO9cD6SBcaEe6+aSy2XVuh"
    "/IspBj6shDaQAGZQ3OtMin5VzEKh6KzWYslTDHh8JNfcss1AhSkWYmnSMP0XYGrIC+TlC1kb8x35wd0H"
    "ZuhCAA==";

// star [outlined]  source: src/toggle/star/materialiconsoutlined/24px.svg
static const char toggle_outlined_star_b64z[] =
    "eJyNkLtuwzAMRX+F0G5KpBU/CttDpwzu2t1pVMmoKgeJYgX5+spFA7RbIQ4k78EhoO6yWrh9+nDphYvx"
    "9CRlSglTicvZSlZKyUwIMGE6eFMcprcPe16u4diLYBKo/FjnEuDMbF3sxdavs0nPy60Xv/I0H6P7jofO"
    "Dt1pig6y5SUjjvXKeq9e1V3A++x9li/BCPlvTNq/UmKgGrkGapAaYPIFYaWLGlU5MkOLrH2eqC2wojHj"
    "245aaLAq4Sffoa5AY12OO2wyQfDQ3h83t88ZvgBPwVZj";

// star_border [outlined]  source: src/toggle/star_border/materialiconsoutlined/24px.svg
static const char toggle_outlined_star_border_b64z[] =
    "eJxNkDFuwzAMRa9CaBctUoolF1GGTh2ctXuBuJYB1Q4awwp8+lJGhg5c/nv8hHR+bCM8f/L8iCqt6/2t"
    "aUopWCwuv2PDxphGDAVpmMa0RsVOwTYN5X15RmXAADuoWZluazrw5Xz/WhPcoroKT+w2dh/m0+wKvqec"
    "o5qXeVDNP40ZOmSXtUfqNLbcE0PNqIOArYUXP6FrwaG3/QmDGATikUf2QAEpSJI1yYIUGdu/avdrtWQ3"
    "a4u+BT587ZCDBJY1YwhSa4OWqadbpEzoSULjDlJhdeFwK+DDrLV7fUv9pMsfylNPzA==";

// star_border_purple500 [outlined]  source: src/toggle/star_border_purple500/materialiconsoutlined/24px.svg
static const char toggle_outlined_star_border_purple500_b64z[] =
    "eJxNkDFuwzAMRa9CaBctUoolF1GGTh2ctXuBuJYB1Q4awwp8+lJGhg5c/nv8hHR+bCM8f/L8iCqt6/2t"
    "aUopWCwuv2PDxphGDAVpmMa0RsVOwTYN5X15RmXAADuoWZluazrw5Xz/WhPcoroKT+w2dh/m0+wKvqec"
    "o5qXeVDNP40ZOmSXtUfqNLbcE0PNqIOArYUXP6FrwaG3/QmDGATikUf2QAEpSJI1yYIUGdu/avdrtWQ3"
    "a4u+BT587ZCDBJY1YwhSa4OWqadbpEzoSULjDlJhdeFwK+DDrLV7fUv9pMsfylNPzA==";

// star_half [outlined]  source: src/toggle/star_half/materialiconsoutlined/24px.svg
static const char toggle_outlined_star_half_b64z[] =
    "eJxNj7FuwzAMRH+F0G5apBRLLqIMnTo4a/cCcS0Dih00ghX460sVHgoQHO7eHcjzc5vgdU/LM6iY8+Ot"
    "bUspWAyuP1PLWutWCAVxnKeYg2KrYJvH8r6+gtKggS1Urcy3HP/sy/nxlSPcgrqKH9lubD/0ruB7Timo"
    "ZV1G1f6DmKFHtqlxSH2DHQ/EUDXqwWNn4PBPaDuw6MxwQi8EgXDkkB2QR/KipIYkIEXaDEftfq2UZD87"
    "pEToSDq0lWW8TGPQSBd6D9VgPxz4Xm+sr19+AXYzR5A=";

// star_outline [outlined]  source: src/toggle/star_outline/materialiconsoutlined/24px.svg
static const char toggle_outlined_star_outline_b64z[] =
    "eJxNkDFuwzAMRa9CaBctUoolF1GGTh2ctXuBuJYB1Q4awwp8+lJGhg5c/nv8hHR+bCM8f/L8iCqt6/2t"
    "aUopWCwuv2PDxphGDAVpmMa0RsVOwTYN5X15RmXAADuoWZluazrw5Xz/WhPcoroKT+w2dh/m0+wKvqec"
    "o5qXeVDNP40ZOmSXtUfqNLbcE0PNqIOArYUXP6FrwaG3/QmDGATikUf2QAEpSJI1yYIUGdu/avdrtWQ3"
    "a4u+BT587ZCDBJY1YwhSa4OWqadbpEzoSULjDlJhdeFwK+DDrLV7fUv9pMsfylNPzA==";

// star_purple500 [outlined]  source: src/toggle/star_purple500/materialiconsoutlined/24px.svg
static const char toggle_outlined_star_purple500_b64z[] =
    "eJxNj7sOwjAMRX/F8l4ndkMfiHRgYigrOxKlqRRaRKMG8fWkCCRG33N0r7yblx6eNz/OFl0I961SMUaK"
    "OU2PXonWWiUDwXVD74JFMQjL0MX99LSoQYMYWLM4XIL74GZ3PwcHF4vHxJ2YRcxBn/QL4Tp4b3Gcxg7V"
    "n8YCXJKULVfEFQj7jKkwWUk6b0WgJjE+XVxnVHCb9DXjGioqcvjyDZkCDJV5u6EqGQy/2tc6tn7RvAH9"
    "wD0g";

// toggle_off [outlined]  source: src/toggle/toggle_off/materialiconsoutlined/24px.svg
static const char toggle_outlined_toggle_off_b64z[] =
    "eJxNkL2KwzAQhF9lUb/S6gcZH1GKq9KkTX84Psvg2CESVvDTnzZqji3m88wwIJ/SPsH7sawpiJjz80up"
    "UoosVm6vSRkiUrUhII7zFHMQxgnY57F8b+8gCAiMA/bKfM/xE59Pz58c4R7EtebRuN24C93oEPA7L0sQ"
    "67aOQv2r6Q78pRvQSquB0IORvq/iEwN4vqhpaDl4bDb6hK3JdzwINPGMkYZnHGrZ9VVcagAVeabl4IDt"
    "Ki5hI64c1w76oRre1w1bO9ZVsYkBbDtsH9gAGezBT+J/df4DnRxSTw==";

// toggle_on [outlined]  source: src/toggle/toggle_on/materialiconsoutlined/24px.svg
static const char toggle_outlined_toggle_on_b64z[] =
    "eJxNkL1uwzAMhF+F0E6J+oGMFFGGTln6EEXiWgYcO4gEK/DTl6yWgsN94h0OoM5ln+D9WNaSVK71+WFM"
    "a003r7fXZBwRGU4oyOM85ZqUCwr2eWyf2zspAgIXQHZtvtf8Z1/Oz++a4Z7UF/vZhd2FKx0KfuZlSWrd"
    "1lGZfyE7QLwON/TaWyCM4HQ8scQiAFEmW7p1HyL2NcaCPSlzPAgsSY3TTmoCWj2cWELpAIxS030IIGuW"
    "ULCTRLgGucPqGLnDc8YHFl8EwPfB/sAOKOAPOUl+6vIL7l5R7Q==";

// check_box [rounded]  source: src/toggle/check_box/materialiconsround/24px.svg
static const char toggle_rounded_check_box_b64z[] =
    "eJx1kEFvwyAMhf+KxR3HOGQJVdPDTj1s196nNAuRaFKtUajy64dpN+0yGR7o+XsCeX9bB7hfwnRrlV+W"
    "664oYowYS5y/hoKJqEiEAt+Pg19axVbBOvbxdb63ioCALYgXx/Pic/uwv34sHs6tek99z3Zle6QTbQo+"
    "xxBaNc1Tr4o/mHFQHqtOGzRAmgFdEl6N7QiShw5YyicjI8BaPM2nqiNJaUlIbRfdIDswZdJOY+nSSgTx"
    "47Qp/VZhbcAw1hn43UIBZehpgVjPS06a9B+Lpg4v2DRapPsHhcfTPx2g7AddY9VAErfJBGS0h2/1g1rZ";

// check_box_outline_blank [rounded]  source: src/toggle/check_box_outline_blank/materialiconsround/24px.svg
static const char toggle_rounded_check_box_outline_blank_b64z[] =
    "eJxNkLFuxCAMhl/FYgdsF6KmOm7olKVr9iqXhki55NRDcMrT1zBVln7E58+AuDzzAq/7tj+Diik9Pqwt"
    "pZjyZo7fxTIiWjEUxHldYgqKnYK8zuXzeAWFgMAOKivrLcXWvl4e3ynCLagv6Ud2md2AI54KftZtC2o/"
    "9lnZfxq9A/VDN2njPaAmbZyXpLGbsLK2BQGReGoOEAiUpCwIQaBuoHrnXZZu8JMmQ3Ieg+klOJMTVZjp"
    "gWtFAU0B1pVpHr3cKEjXiVpnfWj9gesf1WlKAw==";

// indeterminate_check_box [rounded]  source: src/toggle/indeterminate_check_box/materialiconsround/24px.svg
static const char toggle_rounded_indeterminate_check_box_b64z[] =
    "eJxNj0FvwyAMhf+KxR0wDkjNVHrYKZddd59oFiKlSdWgUOXXz+Y0WXq23veM8HU/Jng/lnWPKpfy/LC2"
    "1mpqZ7bXZAkRLScU5HGecomKvIJjHuvn9o4KAYE8iFfne8kN367Pn5LhHtUX80z+ID/gqeB3Xpao1m0d"
    "lf0Xcj10Q0jaGQeoCUzPQofzCYE90wNJZTZaBEiLp+k7JJQtLRtS50N34HC4JG1C4McY+cDq9taBp3xJ"
    "jYED9ljdrtsg+JSPyb23P7i5Rhg=";

// radio_button_checked [rounded]  source: src/toggle/radio_button_checked/materialiconsround/24px.svg
static const char toggle_rounded_radio_button_checked_b64z[] =
    "eJxNj0FrwzAMhf+K0D22rDqrKXUP3WWXnQa7DzeNDWlSEhN3+fWzkzIKEvr03jtIx2lu4XHr+smij/F+"
    "kDKlJNJODGMrmYhkTiD4JrQ+WmSNMIcmnYeHRQIC1lC0FC7Rr/bpeP+JHi4WP7PvWc+sP+ibFoRr6DqL"
    "/dA3KF9iioHf34Q2kAGeoHjShRT9V/UUKkVfai9qXmPAyy27xhWbgSpT7URt8jDTBrA2lAXKskHRlnKH"
    "C6PrGnD5IcUI7nebo8W62OX/0x/rNkoi";

// radio_button_unchecked [rounded]  source: src/toggle/radio_button_unchecked/materialiconsround/24px.svg
static const char toggle_rounded_radio_button_unchecked_b64z[] =
    "eJxNj0ELwjAMhf9KyH1tGqsWsR704sWT4F3cXAtzE1dW2a+3nUOEhHx57x2SbT/U8H40bW/RhfDcSBlj"
    "FHEhulctmYhkSiC4ytcuWGSNMPgq7ru3RQIC1pC16MvgJnu3fV6Dg9LiKfmO9cD6SBcaEe6+aSy2XVuh"
    "/IspBj6shDaQAGZQ3OtMin5VzEKh6KzWYslTDHh8JNfcss1AhSkWYmnSMP0XYGrIC+TlC1kb8x35wd0H"
    "ZuhCAA==";

// star [rounded]  source: src/toggle/star/materialiconsround/24px.svg
static const char toggle_rounded_star_b64z[] =
    "eJyNUctOwzAQ/JWV716/H0FJDpw4wJV7moYkIk2qNsRVv551AAluyJa99s7OzNrldevhdprma8WGdT0/"
    "CJFSwmRwufRCSykFIRh0c3OYOn5o2vf+snzMx4rNXQJJQ1uaDIZu7Ie1Yjnexi49LreK/cqn8bgOe7ou"
    "+7o8N+sAxPJCkEHbTdsn+SrvDN7GaSLyZe6Y+DdM9H9IT0qDCqgDWFQONDrVYvBoPSj0BUdNebQFVyjj"
    "RKviFoMGgz5wgyq2OUAX0SjK+khxoCC4iYDRcLT5PhZ0sr7laCzHmK/c9x4tyOcCVQERvfmqoiKCxogy"
    "c9GzkG5WCbAzZ3HI4tkPZD+E1hg9BkMIZ3fLsFvObXFq6/7TfP6l+hNtZ3IN";

// star_border [rounded]  source: src/toggle/star_border/materialiconsround/24px.svg
static const char toggle_rounded_star_border_b64z[] =
    "eJxNkTtvwzAMhP8KoV20HtTDRZyhU4dk7V6kaWxATYLGiIP8+h6NDl1sivcdebI3t/uJHt/tfBvMOM/X"
    "l65bloWXyJefUxeccx0IQ+NxOo3zYIIYuk/H5fXyGIwjR0FIe8v0OY+rvN1cP+aRPgezhz4GuQd5c+/u"
    "aehram0w58v5aLp/mO85J+rZSbPCVSxLsJ5rj5Okg+WIVvVopb93FXK7nn1PlXNcXZHFA62VXQGBWJ59"
    "sZwKipJa5Fwosq8QPQmXADpwzVwiiKS89Hi42oR9soETaUEo/IFLZsmQcw9bWGG7wjoPATBFV1hdcdCC"
    "U+Wo98gVdbaa4rn3sCbGRSMmYnRAPLhDRQM0AlVsjbDEugOc2Tc4NbGTVVFRWVpZFcJK6tinflf9Ydtf"
    "+aNr9Q==";

// star_border_purple500 [rounded]  source: src/toggle/star_border_purple500/materialiconsround/24px.svg
static const char toggle_rounded_star_border_purple500_b64z[] =
    "eJxNUU1zwiAQ/SsMZ9jAQgh0jIeePOi1d7VpyDRNHE2N46/vQqzjhDA7vI99C6vLtWW3n3641DxO0+mt"
    "KOZ5htnAeG4LVEoVxOCsGfaHvpGH/fG7PY+/w2fNh2Zmij60tDiLTdfGqeapvnbN/D7eav6Cz93nFDO8"
    "XrV5nfZTZGS0U0JFtFe0G/Wh7px9dX1P/uPQ8GK9Ktrlf1VoFB582GqEYIXGiOCxlwhYCQ0OewXBCANK"
    "E0VoC1VIqKUavM2ozKgHfOq3D1e2C1B6odWmBI3sKIleCSU1mOSOJR0kHLzuDTgrEFxPqDXCgtOJj0Hk"
    "BIoap0CJXTraVMiBKjBZG0jrNTsSjzpAmcg++WuXFTIpFm+ZvHM/GsQlRUg5kswEmcLkWLmKRLZLpopK"
    "b5dMaZCSDp35r4IWim0f496ft01Pvv4D5YaAuA==";

// star_half [rounded]  source: src/toggle/star_half/materialiconsround/24px.svg
static const char toggle_rounded_star_half_b64z[] =
    "eJxNkbtuwzAMRX+F0C5aD0qiijhDpw7J2r1I0tiA6gSNEQf5+pJGhi7SFe/hQ9Lmdj/D46dNt94M83x9"
    "67plWXCJePk9d8E51wlhYDiN52HuTSAD9/G0vF8evXHgIBBobBmP87Da2831ax7g2Ju9+EOge6AP9zTw"
    "PbbWm+kynUz3D/IVc4KKjpolZLJIwXrkKidKB4tRQuwllF47E7hdRV+BMcc1KyJ5QZnRFSFkKI++WExF"
    "REktYi4Q0bOYHghLEDogZyxRiKQ8VVkcN0KfbMAEKkCEP2DJSFnsXCUtrLBdYa0nA0gVbWG1xUEFJsao"
    "98gsOlud4rn3kpqQPjP6JhGdxJEsUWCW5BikHzOoEXj3wp/6XvoN2z/1iGO5";

// star_outline [rounded]  source: src/toggle/star_outline/materialiconsround/24px.svg
static const char toggle_rounded_star_outline_b64z[] =
    "eJxNkTtvwzAMhP8KoV20HtTDRZyhU4dk7V6kaWxATYLGiIP8+h6NDl1sivcdebI3t/uJHt/tfBvMOM/X"
    "l65bloWXyJefUxeccx0IQ+NxOo3zYIIYuk/H5fXyGIwjR0FIe8v0OY+rvN1cP+aRPgezhz4GuQd5c+/u"
    "aehram0w58v5aLp/mO85J+rZSbPCVSxLsJ5rj5Okg+WIVvVopb93FXK7nn1PlXNcXZHFA62VXQGBWJ59"
    "sZwKipJa5Fwosq8QPQmXADpwzVwiiKS89Hi42oR9soETaUEo/IFLZsmQcw9bWGG7wjoPATBFV1hdcdCC"
    "U+Wo98gVdbaa4rn3sCbGRSMmYnRAPLhDRQM0AlVsjbDEugOc2Tc4NbGTVVFRWVpZFcJK6tinflf9Ydtf"
    "+aNr9Q==";

// star_purple500 [rounded]  source: src/toggle/star_purple500/materialiconsround/24px.svg
static const char toggle_rounded_star_purple500_b64z[] =
    "eJxNUU1zwiAQ/SsMZ9jAQgh0jIeePOi1d7VpyDRNHE2N46/vQqzjhDA7vI99C6vLtWW3n3641DxO0+mt"
    "KOZ5htnAeG4LVEoVxOCsGfaHvpGH/fG7PY+/w2fNh2Zmij60tDiLTdfGqeapvnbN/D7eav6Cz93nFDO8"
    "XrV5nfZTZGS0U0JFtFe0G/Wh7px9dX1P/uPQ8GK9Ktrlf1VoFB582GqEYIXGiOCxlwhYCQ0OewXBCANK"
    "E0VoC1VIqKUavM2ozKgHfOq3D1e2C1B6odWmBI3sKIleCSU1mOSOJR0kHLzuDTgrEFxPqDXCgtOJj0Hk"
    "BIoap0CJXTraVMiBKjBZG0jrNTsSjzpAmcg++WuXFTIpFm+ZvHM/GsQlRUg5kswEmcLkWLmKRLZLpopK"
    "b5dMaZCSDp35r4IWim0f496ft01Pvv4D5YaAuA==";

// toggle_off [rounded]  source: src/toggle/toggle_off/materialiconsround/24px.svg
static const char toggle_rounded_toggle_off_b64z[] =
    "eJxNTzuLwzAM/itCu23FjxqOusNNXbp2L2kaB3JJOZu45NfXqpcihL4XQjqmbYTX37ykgDHn549SpRRZ"
    "jFz/R6WJSNUEQhymMeaA2iJs01B+11dAAgJtgbUy3XP82Kfj85Yj3ANeqh+13bQ905V2hMc0zwGXdRlQ"
    "fcU6D/7se6GlPwAJB1pqW4dLDMBxxY765oMTTRYuiZbk2i8eOteLTh54ianA2DpMagAMNzABJg2wtvMx"
    "/OXpDQRvQ4o=";

// toggle_on [rounded]  source: src/toggle/toggle_on/materialiconsround/24px.svg
static const char toggle_rounded_toggle_on_b64z[] =
    "eJxNT80KwjAMfpWQe9usP07EevDkxYeQOdfB3MSWVfb0NvYiIeT7IyTHuA7weU5z9BhSeh2UyjnLbOTy"
    "HpQmIlUSCKEfh5A8aouwjn0+Lx+PBATaAmt5vKfws0/H1y0FuHu8Fj9ou2p7oQ3hMU6Tx3mZe1R/oaaF"
    "9tJ2Qst2ByQcaKltGS4yAMcVGuqqD05UWbgoapJrexLsO9HIHe8wBRhbhokVgOEGJsCkAtY2voVfPH0B"
    "NlZC7w==";

// check_box [sharp]  source: src/toggle/check_box/materialiconssharp/24px.svg
static const char toggle_sharp_check_box_b64z[] =
    "eJxNjj0LgzAURf/K4+35jmiKcejkoKt7odYIqUoNifjrazp1ucO5h8ut9zjB8fbLbtGFsN0YSynRpOj6"
    "mZjknLPLQHDjPLlgUWqEOI/pvh4WOXCQGjJL8zO4X93U2yM4eFrsr95JHaVu+cBPhNfsvcVlXUZkf5oU"
    "oFoVReVENaizFxxE6UlBChBUC5Kjy1DTi5e0MCRHJwxUnhgwZ57LP5svhms4jQ==";

// check_box_outline_blank [sharp]  source: src/toggle/check_box_outline_blank/materialiconssharp/24px.svg
static const char toggle_sharp_check_box_outline_blank_b64z[] =
    "eJxNzrEOgzAMRdFfsbyXOCZItCIMnVi6sleC4khAEEQJ4usLnbq+e4ZXbXGAfRrnzaKEsDyUSillKc/8"
    "OigmInUKBOndIMEiG4To+vT0u0UCAjZwbcl1QX65rpZ3EOgsvs4ubCKbhlo6ED5uHC3Ofu5R/TF9hyJq"
    "0xRtIdpMfOMmj7oUXbb5ccnrQv0FEm4xTw==";

// indeterminate_check_box [sharp]  source: src/toggle/indeterminate_check_box/materialiconssharp/24px.svg
static const char toggle_sharp_indeterminate_check_box_b64z[] =
    "eJxNzrsOgzAMheFXsbxDHCdSUUUYOrF07V4JiiNxE0QJ4ulLOnU9/zeceo8DHNM47w4lhPWuVEqpTKZc"
    "tkExEalLIEjvBwkO2SJE36fHcjgkIGALeUu+C/LLTb2+g0Dn8Hl1YRvZtnQifPw4OpyXuUf1h1iDaU3U"
    "lejqZc6psKCpvcWCRVPkM+P8ofkCRk4xoA==";

// radio_button_checked [sharp]  source: src/toggle/radio_button_checked/materialiconssharp/24px.svg
static const char toggle_sharp_radio_button_checked_b64z[] =
    "eJxNj0FrwzAMhf+K0D22rDqrKXUP3WWXnQa7DzeNDWlSEhN3+fWzkzIKEvr03jtIx2lu4XHr+smij/F+"
    "kDKlJNJODGMrmYhkTiD4JrQ+WmSNMIcmnYeHRQIC1lC0FC7Rr/bpeP+JHi4WP7PvWc+sP+ibFoRr6DqL"
    "/dA3KF9iioHf34Q2kAGeoHjShRT9V/UUKkVfai9qXmPAyy27xhWbgSpT7URt8jDTBrA2lAXKskHRlnKH"
    "C6PrGnD5IcUI7nebo8W62OX/0x/rNkoi";

// radio_button_unchecked [sharp]  source: src/toggle/radio_button_unchecked/materialiconssharp/24px.svg
static const char toggle_sharp_radio_button_unchecked_b64z[] =
    "eJxNj0ELwjAMhf9KyH1tGqsWsR704sWT4F3cXAtzE1dW2a+3nUOEhHx57x2SbT/U8H40bW/RhfDcSBlj"
    "FHEhulctmYhkSiC4ytcuWGSNMPgq7ru3RQIC1pC16MvgJnu3fV6Dg9LiKfmO9cD6SBcaEe6+aSy2XVuh"
    "/IspBj6shDaQAGZQ3OtMin5VzEKh6KzWYslTDHh8JNfcss1AhSkWYmnSMP0XYGrIC+TlC1kb8x35wd0H"
    "ZuhCAA==";

// star [sharp]  source: src/toggle/star/materialiconssharp/24px.svg
static const char toggle_sharp_star_b64z[] =
    "eJyNkLtuwzAMRX+F0G5KpBU/CttDpwzu2t1pVMmoKgeJYgX5+spFA7RbIQ4k78EhoO6yWrh9+nDphYvx"
    "9CRlSglTicvZSlZKyUwIMGE6eFMcprcPe16u4diLYBKo/FjnEuDMbF3sxdavs0nPy60Xv/I0H6P7jofO"
    "Dt1pig6y5SUjjvXKeq9e1V3A++x9li/BCPlvTNq/UmKgGrkGapAaYPIFYaWLGlU5MkOLrH2eqC2wojHj"
    "245aaLAq4Sffoa5AY12OO2wyQfDQ3h83t88ZvgBPwVZj";

// star_border [sharp]  source: src/toggle/star_border/materialiconssharp/24px.svg
static const char toggle_sharp_star_border_b64z[] =
    "eJxNkDFuwzAMRa9CaBctUoolF1GGTh2ctXuBuJYB1Q4awwp8+lJGhg5c/nv8hHR+bCM8f/L8iCqt6/2t"
    "aUopWCwuv2PDxphGDAVpmMa0RsVOwTYN5X15RmXAADuoWZluazrw5Xz/WhPcoroKT+w2dh/m0+wKvqec"
    "o5qXeVDNP40ZOmSXtUfqNLbcE0PNqIOArYUXP6FrwaG3/QmDGATikUf2QAEpSJI1yYIUGdu/avdrtWQ3"
    "a4u+BT587ZCDBJY1YwhSa4OWqadbpEzoSULjDlJhdeFwK+DDrLV7fUv9pMsfylNPzA==";

// star_border_purple500 [sharp]  source: src/toggle/star_border_purple500/materialiconssharp/24px.svg
static const char toggle_sharp_star_border_purple500_b64z[] =
    "eJxNkDFuwzAMRa9CaBctUoolF1GGTh2ctXuBuJYB1Q4awwp8+lJGhg5c/nv8hHR+bCM8f/L8iCqt6/2t"
    "aUopWCwuv2PDxphGDAVpmMa0RsVOwTYN5X15RmXAADuoWZluazrw5Xz/WhPcoroKT+w2dh/m0+wKvqec"
    "o5qXeVDNP40ZOmSXtUfqNLbcE0PNqIOArYUXP6FrwaG3/QmDGATikUf2QAEpSJI1yYIUGdu/avdrtWQ3"
    "a4u+BT587ZCDBJY1YwhSa4OWqadbpEzoSULjDlJhdeFwK+DDrLV7fUv9pMsfylNPzA==";

// star_half [sharp]  source: src/toggle/star_half/materialiconssharp/24px.svg
static const char toggle_sharp_star_half_b64z[] =
    "eJxNj7FuwzAMRH+F0G5apBRLLqIMnTo4a/cCcS0Dih00ghX460sVHgoQHO7eHcjzc5vgdU/LM6iY8+Ot"
    "bUspWAyuP1PLWutWCAVxnKeYg2KrYJvH8r6+gtKggS1Urcy3HP/sy/nxlSPcgrqKH9lubD/0ruB7Timo"
    "ZV1G1f6DmKFHtqlxSH2DHQ/EUDXqwWNn4PBPaDuw6MxwQi8EgXDkkB2QR/KipIYkIEXaDEftfq2UZD87"
    "pEToSDq0lWW8TGPQSBd6D9VgPxz4Xm+sr19+AXYzR5A=";

// star_outline [sharp]  source: src/toggle/star_outline/materialiconssharp/24px.svg
static const char toggle_sharp_star_outline_b64z[] =
    "eJxNkDFuwzAMRa9CaBctUoolF1GGTh2ctXuBuJYB1Q4awwp8+lJGhg5c/nv8hHR+bCM8f/L8iCqt6/2t"
    "aUopWCwuv2PDxphGDAVpmMa0RsVOwTYN5X15RmXAADuoWZluazrw5Xz/WhPcoroKT+w2dh/m0+wKvqec"
    "o5qXeVDNP40ZOmSXtUfqNLbcE0PNqIOArYUXP6FrwaG3/QmDGATikUf2QAEpSJI1yYIUGdu/avdrtWQ3"
    "a4u+BT587ZCDBJY1YwhSa4OWqadbpEzoSULjDlJhdeFwK+DDrLV7fUv9pMsfylNPzA==";

// star_purple500 [sharp]  source: src/toggle/star_purple500/materialiconssharp/24px.svg
static const char toggle_sharp_star_purple500_b64z[] =
    "eJxNj7sOwjAMRX/F8l4ndkMfiHRgYigrOxKlqRRaRKMG8fWkCCRG33N0r7yblx6eNz/OFl0I961SMUaK"
    "OU2PXonWWiUDwXVD74JFMQjL0MX99LSoQYMYWLM4XIL74GZ3PwcHF4vHxJ2YRcxBn/QL4Tp4b3Gcxg7V"
    "n8YCXJKULVfEFQj7jKkwWUk6b0WgJjE+XVxnVHCb9DXjGioqcvjyDZkCDJV5u6EqGQy/2tc6tn7RvAH9"
    "wD0g";

// toggle_off [sharp]  source: src/toggle/toggle_off/materialiconssharp/24px.svg
static const char toggle_sharp_toggle_off_b64z[] =
    "eJxNTzuLwzAM/itCu23FjxqOusNNXbp2L2kaB3JJOZu45NfXqpcihL4XQjqmbYTX37ykgDHn549SpRRZ"
    "jFz/R6WJSNUEQhymMeaA2iJs01B+11dAAgJtgbUy3XP82Kfj85Yj3ANeqh+13bQ905V2hMc0zwGXdRlQ"
    "fcU6D/7se6GlPwAJB1pqW4dLDMBxxY765oMTTRYuiZbk2i8eOteLTh54ianA2DpMagAMNzABJg2wtvMx"
    "/OXpDQRvQ4o=";

// toggle_on [sharp]  source: src/toggle/toggle_on/materialiconssharp/24px.svg
static const char toggle_sharp_toggle_on_b64z[] =
    "eJxNT80KwjAMfpWQe9usP07EevDkxYeQOdfB3MSWVfb0NvYiIeT7IyTHuA7weU5z9BhSeh2UyjnLbOTy"
    "HpQmIlUSCKEfh5A8aouwjn0+Lx+PBATaAmt5vKfws0/H1y0FuHu8Fj9ou2p7oQ3hMU6Tx3mZe1R/oaaF"
    "9tJ2Qst2ByQcaKltGS4yAMcVGuqqD05UWbgoapJrexLsO9HIHe8wBRhbhokVgOEGJsCkAtY2voVfPH0B"
    "NlZC7w==";

static const BaseSVGIcon kIcons[] = {
    { "toggle", OUTLINED, "check_box", "src/toggle/check_box/materialiconsoutlined/24px.svg", toggle_outlined_check_box_b64z },
    { "toggle", OUTLINED, "check_box_outline_blank", "src/toggle/check_box_outline_blank/materialiconsoutlined/24px.svg", toggle_outlined_check_box_outline_blank_b64z },
    { "toggle", OUTLINED, "indeterminate_check_box", "src/toggle/indeterminate_check_box/materialiconsoutlined/24px.svg", toggle_outlined_indeterminate_check_box_b64z },
    { "toggle", OUTLINED, "radio_button_checked", "src/toggle/radio_button_checked/materialiconsoutlined/24px.svg", toggle_outlined_radio_button_checked_b64z },
    { "toggle", OUTLINED, "radio_button_unchecked", "src/toggle/radio_button_unchecked/materialiconsoutlined/24px.svg", toggle_outlined_radio_button_unchecked_b64z },
    { "toggle", OUTLINED, "star", "src/toggle/star/materialiconsoutlined/24px.svg", toggle_outlined_star_b64z },
    { "toggle", OUTLINED, "star_border", "src/toggle/star_border/materialiconsoutlined/24px.svg", toggle_outlined_star_border_b64z },
    { "toggle", OUTLINED, "star_border_purple500", "src/toggle/star_border_purple500/materialiconsoutlined/24px.svg", toggle_outlined_star_border_purple500_b64z },
    { "toggle", OUTLINED, "star_half", "src/toggle/star_half/materialiconsoutlined/24px.svg", toggle_outlined_star_half_b64z },
    { "toggle", OUTLINED, "star_outline", "src/toggle/star_outline/materialiconsoutlined/24px.svg", toggle_outlined_star_outline_b64z },
    { "toggle", OUTLINED, "star_purple500", "src/toggle/star_purple500/materialiconsoutlined/24px.svg", toggle_outlined_star_purple500_b64z },
    { "toggle", OUTLINED, "toggle_off", "src/toggle/toggle_off/materialiconsoutlined/24px.svg", toggle_outlined_toggle_off_b64z },
    { "toggle", OUTLINED, "toggle_on", "src/toggle/toggle_on/materialiconsoutlined/24px.svg", toggle_outlined_toggle_on_b64z },
    { "toggle", ROUNDED, "check_box", "src/toggle/check_box/materialiconsround/24px.svg", toggle_rounded_check_box_b64z },
    { "toggle", ROUNDED, "check_box_outline_blank", "src/toggle/check_box_outline_blank/materialiconsround/24px.svg", toggle_rounded_check_box_outline_blank_b64z },
    { "toggle", ROUNDED, "indeterminate_check_box", "src/toggle/indeterminate_check_box/materialiconsround/24px.svg", toggle_rounded_indeterminate_check_box_b64z },
    { "toggle", ROUNDED, "radio_button_checked", "src/toggle/radio_button_checked/materialiconsround/24px.svg", toggle_rounded_radio_button_checked_b64z },
    { "toggle", ROUNDED, "radio_button_unchecked", "src/toggle/radio_button_unchecked/materialiconsround/24px.svg", toggle_rounded_radio_button_unchecked_b64z },
    { "toggle", ROUNDED, "star", "src/toggle/star/materialiconsround/24px.svg", toggle_rounded_star_b64z },
    { "toggle", ROUNDED, "star_border", "src/toggle/star_border/materialiconsround/24px.svg", toggle_rounded_star_border_b64z },
    { "toggle", ROUNDED, "star_border_purple500", "src/toggle/star_border_purple500/materialiconsround/24px.svg", toggle_rounded_star_border_purple500_b64z },
    { "toggle", ROUNDED, "star_half", "src/toggle/star_half/materialiconsround/24px.svg", toggle_rounded_star_half_b64z },
    { "toggle", ROUNDED, "star_outline", "src/toggle/star_outline/materialiconsround/24px.svg", toggle_rounded_star_outline_b64z },
    { "toggle", ROUNDED, "star_purple500", "src/toggle/star_purple500/materialiconsround/24px.svg", toggle_rounded_star_purple500_b64z },
    { "toggle", ROUNDED, "toggle_off", "src/toggle/toggle_off/materialiconsround/24px.svg", toggle_rounded_toggle_off_b64z },
    { "toggle", ROUNDED, "toggle_on", "src/toggle/toggle_on/materialiconsround/24px.svg", toggle_rounded_toggle_on_b64z },
    { "toggle", SHARP, "check_box", "src/toggle/check_box/materialiconssharp/24px.svg", toggle_sharp_check_box_b64z },
    { "toggle", SHARP, "check_box_outline_blank", "src/toggle/check_box_outline_blank/materialiconssharp/24px.svg", toggle_sharp_check_box_outline_blank_b64z },
    { "toggle", SHARP, "indeterminate_check_box", "src/toggle/indeterminate_check_box/materialiconssharp/24px.svg", toggle_sharp_indeterminate_check_box_b64z },
    { "toggle", SHARP, "radio_button_checked", "src/toggle/radio_button_checked/materialiconssharp/24px.svg", toggle_sharp_radio_button_checked_b64z },
    { "toggle", SHARP, "radio_button_unchecked", "src/toggle/radio_button_unchecked/materialiconssharp/24px.svg", toggle_sharp_radio_button_unchecked_b64z },
    { "toggle", SHARP, "star", "src/toggle/star/materialiconssharp/24px.svg", toggle_sharp_star_b64z },
    { "toggle", SHARP, "star_border", "src/toggle/star_border/materialiconssharp/24px.svg", toggle_sharp_star_border_b64z },
    { "toggle", SHARP, "star_border_purple500", "src/toggle/star_border_purple500/materialiconssharp/24px.svg", toggle_sharp_star_border_purple500_b64z },
    { "toggle", SHARP, "star_half", "src/toggle/star_half/materialiconssharp/24px.svg", toggle_sharp_star_half_b64z },
    { "toggle", SHARP, "star_outline", "src/toggle/star_outline/materialiconssharp/24px.svg", toggle_sharp_star_outline_b64z },
    { "toggle", SHARP, "star_purple500", "src/toggle/star_purple500/materialiconssharp/24px.svg", toggle_sharp_star_purple500_b64z },
    { "toggle", SHARP, "toggle_off", "src/toggle/toggle_off/materialiconssharp/24px.svg", toggle_sharp_toggle_off_b64z },
    { "toggle", SHARP, "toggle_on", "src/toggle/toggle_on/materialiconssharp/24px.svg", toggle_sharp_toggle_on_b64z },
};

static const int kIconCount = (int)(sizeof(kIcons) / sizeof(kIcons[0]));

} // namespace toggle

#endif // UPP_MATERIAL_SYMBOLS_ICONS_TOGGLE_H
