// Auto-generated by Material Symbols SVG Extractor (v0.9)
// FORMAT: KICONS_V1_NO_DECODERS
// Category: home
// Location: E:/apps/3rdParty/material-design-icons/src/home/
// Each icon is Base64(zlib(minified-SVG)). Decode with ZDecompress(Base64Decode(...)).

#ifndef UPP_MATERIAL_SYMBOLS_ICONS_HOME_H
#define UPP_MATERIAL_SYMBOLS_ICONS_HOME_H

#include <Core/Core.h>
#include <plugin/z/z.h>

namespace home {

using namespace Upp;

enum Style : uint8 { OUTLINED = 0, ROUNDED = 1, SHARP = 2 };

struct BaseSVGIcon {
    const char* category;
    Style       style;
    const char* name;
    const char* source;
    const char* b64zIcon;
};

// auto_mode [outlined]  source: src/home/auto_mode/materialiconsoutlined/24px.svg
static const char home_outlined_auto_mode_b64z[] =
    "eJxVk01zmzAQhv+KhrO0aPWJOrYP4ZJDeu3dIRSYUvA4xKT59d2VcV0PoNmR9n3e1Urs3i+d+Pw9Tu/7"
    "ol+W07eyXNcVVgvzuSuN1rqkjEK00/F1bNXrsfnVneeP6W1fTO0qND3G0VuIvh26ftkXHF+Gdn2aP/fF"
    "f+vr8Lb0efmw6w67c9ss4ucwjgSap/ZRf88tD7uyywJ6T8elF+T8HRNoKy340CiEEGmwSVmIThmwKtAq"
    "BR4vBjQ2CNFKDZhIYZGiqpIOAkqEZF7urC92u3sgTerwA0H7uoLI6cbLAMFJAxgJkWLWjQjOSB7qCIFd"
    "kpMJDK+SYgM90klcEcumFyZkVp2pmU9OQW6emgk9b6TOuA1MFtnsH+iRbzRnbMJGaTBIHTGJOoVGObAh"
    "Nyi3alT3DZBOhyuZwrjZ3WhXj3n8082TOM3DtNC1iRKNQA2OMngzAokVRY5vM9ec6wxnck68iXh8bL2R"
    "hoq2QK3TykPlqUKfVAQXlHuOF2We8RJ6QwFEOt9E1ULlpOdiHUTJfYmNgypKLflmcAXsQww6MMKlQE1x"
    "XtR0/nxIFbhKoqcbQd4yV/B1u335o9/g8Bf3mL9q";

// blinds [outlined]  source: src/home/blinds/materialiconsoutlined/24px.svg
static const char home_outlined_blinds_b64z[] =
    "eJxVUMuSgyAQ/BXKsyCMiLqlHvbEJVfvxrBixdWUupDK1+9g9llQXT09Pc2j2txA7u/TvNWR3ffbS5J4"
    "75lP2bIOCXDOE3RExMzdeTL03PXXYV0+5ksdzcYTjgsk7ohYMw52r6PA3Wj863Kvoz99P152e7Sbamiq"
    "1fQ7eRunCYOW2fyf//UmTZUMx8Ct2y3BY0/AY1G2qZZOKA0OLHBHQQN/kJNQcWmDRqEtQy1jIbRqS1u0"
    "QgShiPPQzCy0+dOQOUBHpoXEWmG2o8oWTrACSE85k1nMWQrI8sAK+WSCybTnKJQ5Ql6gcKhfsAWgPw0a"
    "oOcoZCVCirV4RtIQ1IoUr620eny/OHx78wktHGzv";

// blinds_closed [outlined]  source: src/home/blinds_closed/materialiconsoutlined/24px.svg
static const char home_outlined_blinds_closed_b64z[] =
    "eJxVkM1uhCAURl+FsFaB63+jLrpiM1v3jkPF1OpEKUzm6XvRtraB3MC5nI9AtdmBPD6meaupNub+wphz"
    "LnJxtKwDA845wxOUqLm7Tiq8dv37sC6f862ms3KE44AEJyVajYM2NfVrOyr3ujxq+qfvxpvRe7uphqZa"
    "VW/I2zhNGLTM6r9/nmVNxYZduHdGE7z2AjwQZRvLxIpMggUtRARpzwMelTmWvAhElKdn2XwJfxuhLxLA"
    "hiCBP8lFIBc6hLbU0ArhSYJEZgiKE8QWZOYlkXiSIdH+ehRFfMTkfpNiSn44qVfa9DBQKFHXhYffCTvA"
    "ECmy589b/Yc3XxYHbkA=";

// broadcast_on_home [outlined]  source: src/home/broadcast_on_home/materialiconsoutlined/24px.svg
static const char home_outlined_broadcast_on_home_b64z[] =
    "eJxlU01z2kAM/SsezrtrS/vl7QCHcsklV+6J49pMKWSA2pn8+j4JEpp21pK10u6TnmQvz9NQvf3aH86r"
    "xXi5vH6r63me3ezd8TTU3DRNjROLqj88Pe97+/zU/RxOx9+Hl9Xi0M9Vg8UBz6Ia+90wXlYLsaddP38/"
    "vq0Wf8Xn3ctl1PB6OayXp767VD92+z2Ajof+6/372Xq9rAe9gOf16TJWyPzIbFLXWHJkG1csy3oIE4+U"
    "JnaxdI3L3jSOiyEXYKRiGCblbXoXzE+k1pQH3wElGuDhZISmCQhGfRCSNcZO94b0LFmabNkUU7BpIcUA"
    "6b16zIZaVGLz6LfUfs1F2WVcTa5kgHkAsdeMkHwzJGSlXnEmMOR4V2fV5jNiRGmlwpEhOd7KLnnLXI3k"
    "4lYT/luJIe9iR8634MTCyBGrAVFILYFbBLxwRj/J5bQn1yQjasPIhHutI8PoUL69ZTDsGB1yudggq+rU"
    "gw4Hc/WagBxIKaVLStLhwGi9ZrCiZCwhfqjsxdl+WDlvKEjdwSWMNqr24rhy+48wJtVZBArKSMqzkBpJ"
    "CUtdRml6F+RbKQbI92I2hMYkoZvQCRa+6J0YV8I5AZGDjSbaWJ2j7gx2iu2zzhPOxIALCVkiC3rWZnZC"
    "X75n6XeLL9rdDFBsN6y82AV0uBEG5cqz3GjKH6KCX3X9B9hW34c=";

// broadcast_on_personal [outlined]  source: src/home/broadcast_on_personal/materialiconsoutlined/24px.svg
static const char home_outlined_broadcast_on_personal_b64z[] =
    "eJxlU0tz2jAQ/isenyUhrd4d4FAuPaTX3onj2ExdyICLM/n1/XYDTTsZrNVqJX0PSawv16F5/TUdL5t2"
    "nOeXL6vVsixm8eZ0HlZkrV1hRdv0x/3j1OvHffdzOJ9+H5827bFfGosfBXxtM/aHYZw3LefXQ798Pb1u"
    "2n/ml8PTPMr0dj1s1+e+m5vnwzQB6HTs/9//sXa1Xa8G2YDvZT+PDZi/B+XqVdcp6WDiFIwtyhubOmuK"
    "09Z4Us6kiiw6RSZxLYYHZ5V/IFWvjsZicupQDgUhoZWinaGM4LKmb+GNqf8SuqxcMDnyllSV5bVRATW9"
    "Zxw6i0JAI7Qss2g1/yAanYlXHY31kOiBQZ6nWVa+JTU3O1cEKxrvlMtMJKTqzv5ZE3WaDDkIwpGYXNEF"
    "6IAJ1hJh3vEgIyl+cjgjzUGcx3vInovlnuXcsT9feCcBn2Ei982FB1xVt6p4lpMmXu6dgLCUJGyKw45g"
    "EfsKxJA4e+8xgeghG9fJLoArpj75rGDS3kQ++STM1UmSRAI7V0LsTeC7ryqY9GF35yA1sYDk30nEHRI8"
    "GRjLCYgUdFRRw2SUkcJIsH3me+IliQAXElgiMXoWe508GQQ+gVKBd0vwNsuOPB8ZmQDPlh1UIxeK7u3+"
    "uqXhb7b9A/tNzyE=";

// curtains [outlined]  source: src/home/curtains/materialiconsoutlined/24px.svg
static const char home_outlined_curtains_b64z[] =
    "eJxVkU1vgzAMhv9KxNkJ+SCBTNDDeuHSK/eWMYLGoGoZVP31s1N1HwKhxH5e268pr2vPbp/jdK2SsCzn"
    "lzTdtk1sRsyXPtVSyhSJhHXT8TR2/HRsP/rL/DW9VcnUbUziozN8Exa6oQ9LldB5Hbrtdb5VyZ/8Nrwt"
    "IaZ3Zb8rL127sPdhHLHQPHX/9b9suivTPgrOxyUwbHvQEpRvTJ2tytV61UHLletayzs7qAKUFIVruRbS"
    "cilswY1wGV69wZPPuMV0rYomciTBgAKloyQDJYxF0EKEjcgd5CxgJelb/GqHMem4ErnGUs5GhOctiTmJ"
    "UWhjJ3hkAkn3SgujoEApKIznNKaz8GyOc3iSWLb3OC7kOC7Rljidg3vYamxNGNKxjMqorQWyCWQTyGac"
    "HKJN10SKXGaxtW+lMHEZaLTw6ACL/6yFNcrXkbw/F09/f/cNm0eErA==";

// curtains_closed [outlined]  source: src/home/curtains_closed/materialiconsoutlined/24px.svg
static const char home_outlined_curtains_closed_b64z[] =
    "eJxVT70OgjAQfpWmM9j2Skk0wODUhZUdsLZELARqa3x6i9GouRsu32+uWL1G9+to1xIb5+YDISGEXeC7"
    "adEEKKUkKjBStu1GlXZtf9HLdLOnElsVEI0DWVyMjBq0cSXebj+ocJzuJf7hw3By5kVXha6KRfUOnYdx"
    "jEGTVf/+r5ZUBdEvw9w6g2JtDTRh+4bLzLNcggcD1KcggT5QzXgiPMtMCo2QjEckT4ThEZJ5IzaB2Mxv"
    "iInHp2D7snoCoi9NaA==";

// electric_bolt [outlined]  source: src/home/electric_bolt/materialiconsoutlined/24px.svg
static const char home_outlined_electric_bolt_b64z[] =
    "eJxVkdtuwyAMhl8F5ZqDIeQ0JbnYbruHSFMWorKkSrNS7elnU03dhBG/5d98HNrrbWL3z7Bcu8zv++VF"
    "qRijjLlct0kZAFDoyJhbhmNw4jiM52lbv5ZTly0uMsBhLEbGvJsnv3cZ6dvs4ut677I/9Tifdp/KfTv1"
    "7ebGnX3MIeBG6+L+9z+9qm/VlBowLsPuGZLftZVlw400+mBlnnOtpW1GAbK0HGRRozI117IsUoqqyg8a"
    "fTYIK+uCl7IqyW8MGnKNSjeoKmoH8oP2wEas8cesqmSkSk0eEzTmpWgQNBJXJBBxBXFTKh5c7IJAWJGw"
    "RBVpM6IKogqiCqIG4MDedCFthawGj1zQavjzyt+/j5Im/k7/A2G4btY=";

// electric_meter [outlined]  source: src/home/electric_meter/materialiconsoutlined/24px.svg
static const char home_outlined_electric_meter_b64z[] =
    "eJxVUU1zgyAQ/SsM5wVZENGOemjPOXWm98RYdWrVURuT/PoupEnbAXbffrxlWfLl1LDzZz8sBW/XdXqK"
    "om3b5GbkODeRVkpFlMFZPewPfS0O++qjmcev4Vjwod6YoqVj2py1dde0a8E9PnX19jyeC/4nvnXHtQ3h"
    "Mm/KfK6rlb13fU+FxqH+z//Njco8agKB9rRfW0Y37zQCYqVELDNHQhmR+bWIDG4WZJUCIzMNWloEJ3UM"
    "CaQyTt+0bvVJaKmSSkljQEkVk0gSjxLAoBZyOEFIA3qVsAfP6hekQhmQpKq+lThc5Hu6sh0SJa2EkSlV"
    "FI4AxqTccgPgoQNvABmvaH0iphB4V//gMJrHOB7TSDk7B3kpuPN509hfmnFg09gNK/0fauksoGJZ0IZh"
    "6E3bH4eVllxkAzoWAhRmaCAQ7x6U9j71cOj7y2/oOIkX";

// energy_savings_leaf [outlined]  source: src/home/energy_savings_leaf/materialiconsoutlined/24px.svg
static const char home_outlined_energy_savings_leaf_b64z[] =
    "eJxVUstu20AM/JWFzrvUvh+F7UN9dT7CUVTJ6FYOHDUK/PUdLtykhaQRsSRnhpR2b++T+PhVl7d9N6/r"
    "67e+37aNNkfX29RbrXWPik6My/m5jur5PPycbtffy8u+W8ZNaFzW4+7EPF6med13HL9fxu379WPf/ZPf"
    "Li/r3NKH3XTY3cZhFT8utYLouoz/93/V9oddP7UG3K/ndRZQfjJWuiOD/IRBecpSqyId5YhXGbS0hJSm"
    "5KUnnaShkmSgaE7oKRTKyZM30prKGcVwTFSctJpslIVyRpLprRGDJSc1iKJRmjORXFSWoj+iHDUmItXq"
    "PSpbX4WfE7u7iydTcABPhnICQXIwGh0IdABpCUcDZ/CVycIphgByC1AMiofCdAmB8XilQbPfNhzOYuZZ"
    "sYJSjpm8xZQJBuArysAkoSapT43wzkv9XCWqIw4hXT1b0eQrTHkPew5bBYWRzMMRAoclk/aAgGnIcEcD"
    "36r4nEGbGrgJ63ICdc6h37Va3h4Dn+RSFcsqlmVV1VRZVD3oOHBZsahqoupB0sCrh7fAAFXFsrLJ4ltm"
    "z7PBbiZtOQxFfk18//t7tQf/+eEPv1CyOg==";

// gas_meter [outlined]  source: src/home/gas_meter/materialiconsoutlined/24px.svg
static const char home_outlined_gas_meter_b64z[] =
    "eJxVUUFygzAM/IqHs2wsxVDTAQ7NJZdcuSeUYqYUMgmFNK+v7KS0HRsh70q7WOSXuRXXj364FJGbptNz"
    "HC/LopaNGs9tTFrrmCsi0QyHY9/I46F+b8/j5/BaREOzCM2LDO9IuKZr3VREPp+7ZnkZr0X0h1+618kF"
    "uszbMj839STeur5noXFo/vf/1sZlHrehgffpMDnBzntMwTiJFTlJsw8V7bKZdnabqKcMDK9HYmfUtQZS"
    "hIA/nHG2DogGI++oNJXdkr63ofWkAW9zE3u0jAhWQYVSqwxIErBZzb2sIcmDHKmytb5j/uzL2CicgSA0"
    "AlVob/5W610ylQAmKjHbkKVchlqlBN7WxwupJKj6NymTBhOdsavxhEHpmQ1/OUtkG0CjMIGgZrgcVodg"
    "HAa/DnudtY3ENcQvHx9jDw////IblS+JbQ==";

// heat_pump [outlined]  source: src/home/heat_pump/materialiconsoutlined/24px.svg
static const char home_outlined_heat_pump_b64z[] =
    "eJxVU8GSmzAM/RUPZ9tYNmZxJ8lhueTSU2e4Z1kKmVKyk7Cwk6+vniFkOwYsS+9Jelayu02t+PrbD7d9"
    "0o3jx480nedZz05frm1qjTEpIxLRDKe3vlFvp/pPe718Du/7ZGhmYXjZjJ9EdM257cZ9Ans6N/Pr5Wuf"
    "fIvP5/exi+HDrj3srk09it/nvudEl6H5n//Epodd2kYCPx+nsRNc+ScF6Y6+dJp3rLj7ibLaSNIkDTss"
    "Vseu6JBWRaeylS8tRYo1HHESye4COSkcfeWZU1G4o/SzoJVU1E47pMqV1XngLb9FS+Uq2rlcTjL/VQBA"
    "hYw8JCdtvSSvg625Ee/5Q4q0geEsWzBy28PgV1QRC6bVLytz4mpEgLBIX5LTBQI5STYdzILLPfFge7RM"
    "GVfv1Zq7QxZRrvCVuSSJ+R6EhR4Yg+a7rbiKxReK0fZR1+gX+Q2/tV5oU4gamiXuG5olNEODjJrVqqgC"
    "NPI4xcqQGGbGYckeud4czoo9N0XxxBuVRCiM0PqNl0/b5SP5FDWoTQTaL7QLS/eFxsQ2MDPjGAOreFz6"
    "EYFyAS6UhYw0KxQFWWhYJrGJw9gdus0wf/QdlpEDcIyM++PXHl/+2x3+AQEg00g=";

// mode_fan_off [outlined]  source: src/home/mode_fan_off/materialiconsoutlined/24px.svg
static const char home_outlined_mode_fan_off_b64z[] =
    "eJxVVF1z2jAQ/CseniVx+rAsdYCH+jX5EYlLgakLmYSGTH59d09Okw5wOlu6u729FZuX10P39ns+v2xX"
    "x+v16dt6fbvd3C26y/NhHURkjROrbn9+eJz39vFh+nV4vvw5/9iuzvtbJ/iEhO+qO+5Ph+N1u6L/etrf"
    "vl/etqsv+7fTj+tRt3ebw27zvJ+u3c/TPCPR5bz/P/7z7Hq3WR80AN+nh+uxQ+V7X0yZrHeSjWDJyYgL"
    "1UZXvfHO18kKLE2C4S8MMDnAxGHCY8/oiLDs4fURYTHa4CR1o+/x1mQXkCyb3qXENbl+xBJdKAYnpDfB"
    "+OiSCRMKSwGS5CreuTTY3sXAo3kOyGtoRi9OBqTN1XjBGouu3cQW0BECLYNgRySug0HdhLoptLWfxCyd"
    "oDr6imyHXu7JRhjgVjiF7VSPdhRwrDNDAnb9PKB3Q4M+i6uZvdTe+OpCYJtw8JQnz2cB8h6xOEAnuDzi"
    "bSXNAcm8AWqM4r27b2FpUqpBxYJOGJ17xdlxsypOq/AI1BKeAuWuMCZwSlKYgp7XFKBkYEGQ6IFzcElZ"
    "JG0yKX1ilHujFHZjENNIJLJCAheI79TUp5JQHtSGMEdXqqEZMdxkCjlObkB7pN6UUSdfkL8oH4QCOpDR"
    "SQskfblxR2EaCpP9cFfb9RXDhuUgKFmVLYeWORsIk6eBsfGQqeU+Wt8UJGksBIveh6rEuz5zrSqMNq9l"
    "Uvhlrt3UlGmoTEtlGirTqjIBmeooecYG4SV/F1zBaGHu/hHD4SJVoFBSnkSvDSpJ/hCVVPVmId00neo3"
    "Emr0Sv3AFukUheqL1VHZ5f6I65to8sfU6aCtRU5NR4n3NTZFoQTo1RLUcNALlF1N5gtYQAdJy6sFeaOJ"
    "pPBeUV7K/5h1gKCj4Gr2ijqroJu4rNJnFXE3Jg4f2drdFBUIdNjAmgWptJupmJEemmqQB6qjIf5E9/7x"
    "T6c//OXu/gLMgzGf";

// nest_cam_wired_stand [outlined]  source: src/home/nest_cam_wired_stand/materialiconsoutlined/24px.svg
static const char home_outlined_nest_cam_wired_stand_b64z[] =
    "eJxVUk1vozAQ/SsW5/Hg8Re4SnLYXPbQXntPKYWoLKkSFqr++j47Wu2ujJivN2+eB3a3dVCfv6b5tq/G"
    "Zfl4qOtt23hzfLkOtTXG1EBUqp9PL1OvX07d+3C9/J5f99Xcb8rgWI+nUmN/HsZlX2V/Pffbj8vnvvqn"
    "vp1fl7GUD7vhsLv23aLeztMEosvc/9//F1sfdvVQGj5Oy6gw9kkiSacNSyBDMALfWO3Ztgi9PbbsGxJu"
    "AkXy7FuYBtHN5nykwI2lyM5NwikTpAkMIcJtgzqK5UZIAhtP8B2mBTh4dxolwHQgy9bDhNV2WUMIeTJg"
    "+Yxtd89QVpazWlYNoBaODVKt0w7qwWYSZJs4GU4Nqj4otGJu5jRZm5Es0BWvk5IjmykSjH12R2lxU0TS"
    "5CKmQ+6XeoJkKz/TquU+FiLYBe0Io7sSG3IlB+Oebe5py5aAx+UyPmZxIuQ45e06/whyNxqoNY4Sh6nU"
    "ddl5ApwEUiJBkaE72def75d/osM3OzeRoA==";

// oil_barrel [outlined]  source: src/home/oil_barrel/materialiconsoutlined/24px.svg
static const char home_outlined_oil_barrel_b64z[] =
    "eJyFUslugzAQ/RWLs2083hIq4NBcuOSae0IoRqUQAcVRvr5j6KpKiWbs2d6bsWWn41yT61vbjVnkpuny"
    "FMfee+4V74c6lkKIGBERqbrjqa3Y6Vi+1kP/3p2zqKs8EShSo0bEVU3tpiwK/txU/rm/ZtGvum/Ok1vK"
    "eVrn6VCVE3lp2hYb9V31l/+DjfM0rhcC6uU4OYKT9wkFxYXZodXcbikIrjQFS0HiPioGXEmqmOSJKUWI"
    "gAluQt4mTDHNDZK5QTTWtjQJdmPoZ99bGPs9TArMlkg3FD3sow0aGBePQRDH4GAc3AcVeqdCWgVZHT2u"
    "wCAOZltoUrK1CQO6Uin8Az3C2IennZktpLiRPWwoJMUGY3KfFO4nZnt/9AGS29eTLQv/Tv4BVF+TiQ==";

// propane [outlined]  source: src/home/propane/materialiconsoutlined/24px.svg
static const char home_outlined_propane_b64z[] =
    "eJxVUMFugzAM/ZWIsxPiJIQyAYftsktPlXqnNEvQGFTASNWvXwKqtsmR3rP97JeknFdL7l/9MFeJW5bb"
    "S5p675mXbJxsKjjnaVAkxAzNpTf00rSfdhq/h2uVDMYTHkKocBLiTGfdUiWRr53xr+O9Sv70fXdd3Nau"
    "S1uXk2kX8tH1fVg0Dub//K82rcvUbgO3ZnEk2B4xB+0onrOWU2RIOSuoiOGoejuwAiQcQAY8QLbie95S"
    "ySQCpxoE00UAPUcCOsYqnVipdE/S7mLQdNdQTU6Cx5qG6PwgR+SQObVi8DtnMc8BdfQRTEQfFa6VFwHU"
    "vBMI1CFv9z4oiOUA6oRFLOG2GvXj+dz45/UPEjhqLQ==";

// propane_tank [outlined]  source: src/home/propane_tank/materialiconsoutlined/24px.svg
static const char home_outlined_propane_tank_b64z[] =
    "eJxVUcFygyAU/BXG8wMBEaGjHurFS665J8aKE6uZxEImX9+HSaftLCrD2327T8qbH8j9c5pvVeLW9fKW"
    "piEEFjK2XIdUcs5TZCSknw/HqafHQ3cersvXfKqSuQ+EI6TClRDXj4NbqyTu/diH9+VeJX/qYTytbivX"
    "5VCX175bycc4Tdhomfv/+l9uWpfpsAkuh9URtN2JAjQTaq86TgUTlDNLZURrm4JZkFCAxG8Bykskdsgq"
    "JHCmcpqBxCdjRnvTcaRJAVi1oCKc6bYTDoo+T6ny1JBGcjDYCYSJnTTLLbxSPMgOaU576ajEQJzlOd2s"
    "RMSNiqcx2rR2H+kGDPpgcLSJqWJg6bNWe5o1Gn0sNrZgIpAuNEjemjgEKnDM17jIdgJ1jTAgLNZEgS8M"
    "ugkePz8u3l79DURxeL0=";

// roller_shades [outlined]  source: src/home/roller_shades/materialiconsoutlined/24px.svg
static const char home_outlined_roller_shades_b64z[] =
    "eJxVUMlugzAU/BXLZ7yzVsChJy65cifEtVEoRODaUb6+z6SrbI3mzZs3XurdG3R/n5e9wda52wtjIQQa"
    "FF03wyTnnIEDI70M51mT8zBezbZ+LJcGLzogDkumsDGyejLWNThyP+nwut4b/KcfpouzR7utTVtvenTo"
    "bZpnCFoX/X/+18vamplj4DY4i+DYk+SJqHrVpV7knfTSSu6J7CR/oJMok8znXd5nnSihzsHqSW4zL2gp"
    "R8JpmiWcKgmsiKxMn0zQVI0chKoAKEoQDvUL0B6R/HRIhJGDkFUACmrxzCQxqRfKHvd4fD8g/mL7CW60"
    "YEU=";

// roller_shades_closed [outlined]  source: src/home/roller_shades_closed/materialiconsoutlined/24px.svg
static const char home_outlined_roller_shades_closed_b64z[] =
    "eJxVUMuOwjAM/JUo5zYPl7Rl1fbAKReu3EsJSbUlRW1IEF9PgrQLyNbI8szYlpvVa3S/THZtsXHu+kNp"
    "CIGEgsyLpsAYo1GBkbL9cVL5sR9+9TLf7KnFVgXEYsAmJkZGjdq4Fqfajyrs5nuLP/gwnpx50V2ju2ZR"
    "g0PncZrioNmqb/9bS7uG6pfh2juD4to9sIxvD4XceF5K8GBqAmJgGSPbKkJVZ5xU4g1rgvyfyBNIAJ+D"
    "BPZAe15nwnMmy4OQvI6NMs6PrBEeZJkExUeDF4+/o9JnuielxFgx";

// sensor_door [outlined]  source: src/home/sensor_door/materialiconsoutlined/24px.svg
static const char home_outlined_sensor_door_b64z[] =
    "eJxVkEtvgzAMx79KlHPIi8DoBBzaC4ftNGl3StMEjUIFGan66WeztxIntv8/O49yWR25XYZxqagP4foo"
    "RIyRx5RPsxNaSimAoMSO7XGwybHt3tw8vY+nio42EglDG5iUeNs7HyqK/trbuJ9uFf2jx/4U/CbXpavL"
    "2XaBnPthgEbTaP/X/7KiLq9t8ATOe1YFM6vKm/zVNKogGOsmPxi+Y5oZpmE3SBReAXLQckupHVegI/yE"
    "yx0KM54xJXnWJZIXKZOJgoTk+cPmgJEFI/YVoXWfJLrJt4b0i8p5mm7d2E/fO95bwCvx8+oPuQxbWw==";

// sensor_occupied [outlined]  source: src/home/sensor_occupied/materialiconsoutlined/24px.svg
static const char home_outlined_sensor_occupied_b64z[] =
    "eJxdU02PmzAQ/SuI82A8NsZQJTkslx7aU6TesywLUdlkldCwyq/vm6FNNiuMPR7PvA8LVudLn3y8jYfz"
    "Oh2m6f1bns/zbGZvjqc+d9baHBVp0h12z2OXPe/a3/3p+Ofwsk4P3ZxYPK7ASJOh2/fDtE4lvuy7+en4"
    "sU4/nc/7l2nQ482q36xOXTslr/txBNDx0D3232vzzSrvtQHjfTcNCZh/siPmlk1ZkiWfsfEFFn/WKPPy"
    "bGsqJV1TtWUrETNp3zWR/thaEwLamawpAhY+Z0uUacy6w8LJllkOovTHq2h6UOJa8FYF2cybAEUmZMFY"
    "TxATG4goib2JjrAWxtey4rz+xXFgd0Fvza0FW8TrS/FQIqojouiSBsVAZWeC4IBHOTFgpDKMfcBVcIWe"
    "MhDKxAAKgYS8F4/OlBV0IUYeMN+l79GIY+M8IR9GmAkiJ4ov5zIHgWJNbLmQlaYodRq1iKS84cq4CPRY"
    "k7PGMQUTPd1BH8kkA1Ex/ojGi7LaNYUpInLwo5Nu5YCkRDWR0DXKoeg66faG98WTygtoHbMbQCueSDyR"
    "eCLxRGJHp1FKtLhZHKgZJVks3jG/fAiSWgyPt2tp9eqUUK9OCT/d3+2mm4VnofhHtGTusNf/P4O++Cs3"
    "fwGMltty";

// sensor_window [outlined]  source: src/home/sensor_window/materialiconsoutlined/24px.svg
static const char home_outlined_sensor_window_b64z[] =
    "eJxVkMFuwyAMhl8FcYYAHiLtlOSwXnLZtfc0ZRAtI1XKoOrTz3DZJiOM/P3+bdHdkyOPrzXce+pjvL0K"
    "kXNu8kuz7U6AlFKgghIbpstq+WWaP92+fYdrT4PNRGKAxkOJt4vzsaflnRab37ZHT//wvFyjr3jo3NDt"
    "do7kY1lXNNqC/d//qxVDd5uiJzjvXR0YjOakmyMDphlg1kwnZWbJVKOYrADDK5hrgQGvRQ5nfQJZW9QR"
    "CbBi9iTFU6fWc524KrcazVmP6oDIMJAk8RbdUjuaZ9lF4OblQ4Yf97FUfg==";

// shield_moon [outlined]  source: src/home/shield_moon/materialiconsoutlined/24px.svg
static const char home_outlined_shield_moon_b64z[] =
    "eJxVUstygzAM/BWGsy0sv+kAh/aaXHNPKAWmFDIJhUy+vhKd9DEYWfauVouG4rq0ye1jGK9l2s3z+SnL"
    "1nWF1cB0aTOtlMqIkSbNeDwNjTwd6/f2Mn2Or2U6Nmui6NGWVpp0Td92c5lyvvTN+jzdyvQPvvavc7fB"
    "VdFWxaWp5+StHwYSmsbmf/0vN6uKrN0KaJ2Pc5dQ5z1qoXdWuMWDymslHCgnDFgUOQQvokAFOdYWXC4R"
    "0IkoHUQC5AYc3I4V7skeiYrfGlZqcE4ECJKIEE1SS5J0LGCklxaipo2RhQ5h8FSg3eAFb4dN5s5+f1zm"
    "oFCgBWNqhOCIh4GscmvQVnjIvVCgQq1AG0kh8DFS5jloTyHYmgzonM9IDS0jeSRnGLk/mSQSMkdzxpee"
    "xYwmTvSkjQwYvkNW9BwccvYSwXj6Yq/JTEQehecRPmzfH+PfXvoPqi99ZoYM";

// solar_power [outlined]  source: src/home/solar_power/materialiconsoutlined/24px.svg
static const char home_outlined_solar_power_b64z[] =
    "eJyVUsFOwzAM/ZUoJ5BSN3HSJEXrDnDZYTvxBWWUtqJrUVfWsa/HKRtjgIRQ0zjxe/Zz4sy2u5LtN027"
    "zXg1DC83cTyOI4waur6MUUoZE4Ozos0fmiJ6yNfPZd+9to8Zb4uRSfrQ0OCsKuqyGjIe1ru6GG+7fca/"
    "4GP9OFQTPJ+V81lfrAf2VDcNJera4jL+zI3ns7icAmi85EPFSHmFUihcmCUKxArlctof2Ep50FYo00gw"
    "AhdK7yKagzOAipAdLhLAiRAgRX4D3gjlaUOgAWOWR0+I0QIlJWGVBWU/0x5CXdMJTlXrc9Gc0cGV4uwt"
    "4/434tDn7fap6zcZ3+RDX++vJDjpFIuO9tKQF6VPmTJgpU+uvytZSPQkZkHaH3r4fz1Nd+CZBee/qulJ"
    "zUDqjmLJr2IX7I+68E+e8mfiZ5MVCrdGcFZIkURIXSOTVBGuqdtgk0iBToSOtND3qdDkESl1x905YUJU"
    "GiKcCGkOp3c0/fSg5+/rK8aD";

// vertical_shades [outlined]  source: src/home/vertical_shades/materialiconsoutlined/24px.svg
static const char home_outlined_vertical_shades_b64z[] =
    "eJxVT70OgjAQfpWmM9D2KE00wODUhZUdtbZELAZrS3h6C9GouRsu32+ufHiN5ttgHxU2zt33hIQQspBn"
    "46QJUEpJVGCkbHccVHrsTlc9jU97rrBVAdE4wONiZFSvjavwevtehcM4V/iHD/3ZmY2uS12Xkzo5dOmH"
    "IQaNVv37v1pSl0RvhnvnDIq1DdCE7dpccs+EBA8GqE9BAl1Qw3hSeMZNyttCMh4RkRQGIiRFW6wCsZrf"
    "EBPLp2D9sn4BovRNbA==";

// vertical_shades_closed [outlined]  source: src/home/vertical_shades_closed/materialiconsoutlined/24px.svg
static const char home_outlined_vertical_shades_closed_b64z[] =
    "eJxVkM2ugjAQhV+l6VrbTqHkYoCFq27cskftbYlYDNbW+PQOGKNmZjE/3zmTTHWNltzPg7/W1IVw2XCe"
    "UmIpY+NkuRRCcCQoMb7bD2a97w4nO403f6ypN4kIDJljUuJMb12o6VzH3qTteK/p1z71x+CWdVPZpprM"
    "IZD/fhjQaPTmV/9heVNxuwguXXAEz+6kWEHZZjqPUGgZpZMirqWW4kF2kK2UA6Yi5BqyVs0jQFyXTLVK"
    "A7RQ4qz4UMULKpiaXRH5W7TYP97H5w80T0SGU5Q=";

// wind_power [outlined]  source: src/home/wind_power/materialiconsoutlined/24px.svg
static const char home_outlined_wind_power_b64z[] =
    "eJyFVE1z2jAQ/Ssen2UhrSRL7gCHcukhueaeOBQzdSGTUJzm1/e9BSfpodMB5JX09uPtW7N8Oe+q15/j"
    "4WVVD6fT05fFYpomOwV7fN4txDm3AKKutof7h3HbPNz3P3bPx1+Hx1V92E6Vw0civnU1bPe74bSqaZ/3"
    "2+nr8XVVf7qf9o+nQa/Xy916+bztT9X3/Tgi0PGw/dv/A7tYLxc7dZh93nHvsLaukApuv1d1oMc/cElx"
    "XnH5v7igON8R+HR/GipQvhWx4o0vtvVjA7s00fq+cVYylliw5IClhMZbaWF1mcC2g9lmIp0QSbiPvOc2"
    "ZMBDGIPt2qa1qat6wBMOXTG4RoRL7NIE6wPDBAYXOmfGCgKwv1i8Tq1xPBG4i4fFA9vKiAAxmIDDjQeB"
    "YJLNBrCWtj5zqc4A9VomnDRq6WBFVgQYtvINIcpGQMd4dASuahrP894Zzy05w+pwDDpGrO/GaBO3ohw9"
    "6blEjkylbFNSqydH42BnsqSPY2ulG1F3ZMNizy0ZKjkWFvN7Zn8nkAY9QCd40GGVoUVaHjZ6wM8ZGkpB"
    "Xa03XHoSVbaaciaBW5UQBaJKc+22iF6puoOrNhgQ1C9Mb2BnlN3ZZD7NzVt1m0HJ+GhLvEG32LKUNoHs"
    "aYoJfMbLA03Wp6donibFI3KAVAFsKJG2jAWyXK05xpuPNMhJV9WU7W1YMNVswPZ6pnuDkxd/JW8wIvFS"
    "3bxyi5XxYHKE7zgwI4eq4VD1lLO5auo59TqCgaPuqJcPs86qvSiOiMLRzJGDGG/m6EiEXkZhFzup+jmy"
    "5pBIX74HMEaoWJIurIFvi+vm+0sq1gChoQq3rc5RgeR+gxwpMEfbUbukqpVgPuV+m/+K9If/xPUfgZ4q"
    "fg==";

// auto_mode [rounded]  source: src/home/auto_mode/materialiconsround/24px.svg
static const char home_rounded_auto_mode_b64z[] =
    "eJyVVMtyGjEQ/JUtzpLQ+5EyPmQvPpCPsNcEqGzAZRNw5evTPbvgOLfUgnZWmhl1T49093bedu8/x8Pb"
    "arE7nV6+LJeXy8Vcgjm+bpfeWruEx6LbHB6fxo1+ehx+bF+Pvw7Pq8Vhc+ksHh/xW3S7zX67O60WtM/7"
    "zeXr8X21+Gv9sn8+7WT5/m57f/e6GU7d9/04ItHxsPkc/+G7/B/P5VZS4/fyeNp1wPjNVWOz8qaGQTvj"
    "kramFO1NzPgMXgdTaWXXu2BSVfBRLuCVCt/eeHe2g1UWERiCw1ArhsLPVroBEQWmF2dOFhUQhRQhDoho"
    "XBRn/F3DvA9A4eKIrD3w5YyAhj2rSQ2mq+oD9W/y+mDjBNF6fg8WiXLEkCrZOQweX62RbOTGDVyLgI7C"
    "VZHrwAhPOqxHIiZHSIm8BVdH5EHNQ2WqKMjJgbRalq0Bw0ZuLZxZ0tg7LJCHRV7izEXNeD+TiSZUlUxp"
    "65vVSyESskx1SCZ6liHCarHHZkUVSWySU5XFFVDN1F6UswxwIuS0Jd47YUP5RDs9q9gKeyEPlE7PIrIz"
    "fBbpUC3v+4huUZlEYcFwXt3AfmbjHaaw2/pqIHFGuZToQoW4J2XyLD+EgUJadIFC0oIiEBcnWbyeZGF/"
    "pij6TNLomzbaispVVieBBpGFAkkvo2RJ+Cjh47EgZYJCAIo0rNOM+DMhlJDHZMQQhQS6DjiUY8kc2Uhr"
    "l3C1kNiOwpYha5enBHIG9C1ETyHsUjeKp3RutxZnVQdx1TfXqyXZxVVJeioMOH1B4WgWryYTClY1g//n"
    "9KCX0PuBOaxOpiZWtunC2yA+EGlKVIxlRdW0HH1KkWRGOz4Poh8dNduI08qdo9wRnJVQPlPf/ZsRWxbc"
    "Ga1d+9oX6a3GcYh0s+hsz1aEkM7qbCJV9TxxiU1rpYuIKbOLQru1ReQkN2tyUHkgHc856oQrBa2MsULz"
    "JEeXxVLzqeTVKX/c9vd/ALdUVeg=";

// blinds [rounded]  source: src/home/blinds/materialiconsround/24px.svg
static const char home_rounded_blinds_b64z[] =
    "eJyVUstuwyAQ/BXkM2AW8IMqzqG9+JKr74nrGquuHSUujvL13TV9HqtFyzI7DANidw09u72N07VK/LKc"
    "H9J0XVe5Gjlf+lQrpVJkJKybjqexE6dj+9pf5vfpuUqmbmUKQ1scCfPd0PulSqgOQ7c+zrcq+dVfh+fF"
    "b+39rt/vLl27sJdhHFFonrq/+3+46X+Yab9Jn4+LZ2jwoBUH12StEiBBKOmEpqjzJysdN9xyg7PlWQBb"
    "mxYZWcaRzJW0GU4QVKt4RBHhQOGhbCPESZNggUSGpxAs4l6KWqs7O0DOnddBe6EbR2vLAeq8cb5sAAgo"
    "eUHNzOumiIQsoMkmq8HiOsdLBJH7MoAsNWvjoUoajVVBVWljBdKazbArMBUlAhv6ma6UxHdDUIquHSZD"
    "jxQlBQk1YNB2Xuf3r6eln7D/AE+ujq0=";

// blinds_closed [rounded]  source: src/home/blinds_closed/materialiconsround/24px.svg
static const char home_rounded_blinds_closed_b64z[] =
    "eJyVksFygyAQhl+F8QzIImjsxBzai5dcvSeWilOrmcRCJk/fXU2b9thZZsFv9/8Bh+0ldOz6MYyXKvHz"
    "fHpK0xijjJmczl2qlVIpdiTMjYfj4MTx0L535+lzfK2S0UWmMLTBkTDv+s7PVULr0Lv4PF2r5Fc99q+z"
    "X8q7bbfbnl07s7d+GNBoGt1f/aM3/U9n2i3Wp8PsGR5wrxWHsrGtEiBBKFkKTVHnL0aWPOOGZzgbbgOY"
    "Omuxw1qOzVxJY3GCoFrFV4qEA4UHJbVlS6EsMBUbDrKwj3ShJH4KglKtoV2NOJ2EzMRiv2wq1g0paq1u"
    "bA8oBS90U3rdABAxSOocwQYBu5Ms4G0CXgkMkRyJ10GTErLVp6APizbFqrEkaeyqQEGJcr8heHdYAJrU"
    "kN++/yo9gt0X7WCQFQ==";

// broadcast_on_home [rounded]  source: src/home/broadcast_on_home/materialiconsround/24px.svg
static const char home_rounded_broadcast_on_home_b64z[] =
    "eJyVVMty2zAM/BWNzyRNgO9OnEN9ySXX3BPFtTx17Uziypl8fReQHPdx6siEIQIEFgtQN2/jtnv/sT+8"
    "rRbD6fTyZbk8n8/uHNzxdbtk7/0SHotuc3h82m/s02P/fft6/Hl4Xi0Om3Pn8XDEb9ENm912OK0Woo+7"
    "zfnr8X21+M1+3j2fBjXf3mxvb143/an7ttvvEeh42Px5/uq7/B/P5VZD4/fyeBo6YLxnNrn3lhxZ75pl"
    "ee7SOrqYTJRnUtLoe2+8SwkCOyTPQGlkl1rvXQnY52bIRSi5GYZK5SF/SN7PbNW0u9AjE8JYkniQNLYp"
    "tq4pcur13ZD6kqXRtnUzDS8VqxlE+ujui6F6F0dbhvBA9c9cVFzB0exaQbCAQBw0I1aZFTFZwSubGSxw"
    "uoo3lebTYkQoUqmRsUqaYbcyRse1m6xSWIgX+yz2MPWTUd/tp48V8aBA/6kgRUMBAHCyVckKclzJED5A"
    "tGDYeYaVJGmOiKUGnuPDOQrfpIelTBISshBAUkIjAdb1M5og1nbpJWU5IOGTNKJqzQFkVGUyWHZNosuW"
    "kgTBMNqAUyLCmpJjwICpohItJqiSJ7KKApNpEZoyyiFCPuVdidRUMSsaBT0TyVIrx0tZWdxIh5h7O5tD"
    "FVEEepg0coG6NUUZKh1t4GsKSzBc+f6rEVkAYfjAJUqeiLLJBQbeXKFh4iGon6aMJqrAIWJJxwLuURUe"
    "WYgPUpzUHYqUJa4+X9rAAlfdWNCL4jGPErkCvtfZBIooFbUElmvT7mFvmgnZQ4MDJsZGHFhT0+pkVOWf"
    "dWx4bgEAKDdVqNcMjKOe+8uF0ZtDZr7jHp2YOxB0zrVHyoiEkgb4vBYOqqvFcBCmi4ttVnO3nhSWfjJ6"
    "VkAsmSvFH5cvlS58XG9/AcW4OLU=";

// broadcast_on_personal [rounded]  source: src/home/broadcast_on_personal/materialiconsround/24px.svg
static const char home_rounded_broadcast_on_personal_b64z[] =
    "eJyVU0tv2kAQ/iuWz+vx7uzLWwGHck2vvRPHtVEoRODiKL++30xASZVThb0z+/oeM2Z1uY7V6+/D8bKu"
    "p3l++da2y7LQ4ul0Hlu21rY4UVfDcfd4GJrHXf88nk9/jk/r+jgslcWPA566mob9OM3rWvLrfli+n17X"
    "9af9Zf80T7q9WY2b1Xno5+rX/nAA0Ok4/Hv/42z7PyfbUaHxvOzmqYLGHy6brreUjTWOfGcsOcNkGQnn"
    "B8fGPwRTro6nRDltC6VkHEZvinGZuiIR68Y5ip1xLCMiYN+E8jORC5Rj31hKxdjGEUewxPSeydBbLASh"
    "xpt1F2/JP5knwF+bSNZDrQcGe9lGEvMtKbnauk6xInkn8kCkpObO/lUT9w0TOwgK0JALQuilGE60RBTD"
    "ySQj6fzBkRW9NomNEO9D9rLY3bOce/GHcuImA19gosTqIhNZNbdV9ZyKOJLj3imISEnKZmTYMiziXifd"
    "UWfvERsYPWRLUyRntcpffBYwNZ6iVD4pc3GaJJUgzo0SewrAoGICpQ+7W2lsEgHovJKoOyQJVhligcih"
    "iSY2MBl1ZjBTbJ+lT3IkMeBCAktkQc9qr5cCY8NJBboCvFsS8DVt2UvJmAI8W3FQSBuK8Hb/qvXFH3Hz"
    "F4o82c4=";

// curtains [rounded]  source: src/home/curtains/materialiconsround/24px.svg
static const char home_rounded_curtains_b64z[] =
    "eJyVUUtvgzAM/isRZyc4LyhT6WG99NLr7m3KCBqDqmWk6q+fXTZtO06O5Ojz97CS9XVuxe29H651Fqfp"
    "/JTnKSWVrBovbW4QMSdGJprhcOwbeTyEt/YyfgynOhuaJJDKODqZiE3XxqnO+D53TXoeb3X2a5660xQf"
    "48263awvTZjEa9f3ZDQOzV/9Dzf/DzNvH9bnwxQFLbg3CLp68QGlVlqiqqTh2hVbpyqw4MBSd+Bn7XY2"
    "EMN7IDKgcp6anjEgLCghoLmiXoUFAvZkWBJRUArDctFy7QzexX6ldAXaBKPQ0R7WU6iXFMzpZSHLiAor"
    "sjQFAViAVqUBrwr/mEMZJEuBpSRjtHJyGUXJWrHVWhUU4tlUk5MFbTnpK/v+/Tj8l5tP4ud9Qg==";

// curtains_closed [rounded]  source: src/home/curtains_closed/materialiconsround/24px.svg
static const char home_rounded_curtains_closed_b64z[] =
    "eJyVkMtOwzAQRX/F8nr8jI1olWQBm2y67T51jR0Rkio1cdWvZ9wIAUt0Lc3ozpmHXF/XQG4f43RtaEzp"
    "shci58xzxeclCC2lFEhQ4qf+NHp26t17WObP6dzQyWciUdrgoyT6IcTU0JKvg88v862hv+p5OKf4KLd1"
    "aOvFu0TehnHEQfPk//b/sOI/pAiP0Zc+RYIHHrQEtTtaJ5niikm+Y7qoe3o1fAcVGKgwGrCrMl3lkLAW"
    "EAbJjcWgVukkbC46oIqienabBWVmsRmCBLcUm229RZ2Wd3JQCmzUuCEyfbT37zvLt7Zfg8Vmgw==";

// electric_bolt [rounded]  source: src/home/electric_bolt/materialiconsround/24px.svg
static const char home_rounded_electric_bolt_b64z[] =
    "eJyVkd1uhCAQhV+FeA04IKI26kV7u30I16ViSnXj2mXTp+8Mm2bbywYIZzJn5uOnvVwndvsIy6XL/L6f"
    "n/I8xihjIddtyjUA5OjImFuGY3DiOIzv07Z+LqcuW1xkgEMbnBnzbp783mWkr7OLz+uty37l43zafUr3"
    "7dS3mxt39jaHgI3Wxf2tf3jz/zjzKbXGeR52z/CMr8pI23AttToYWRRcKWmaUYC0hoMsa1S65kraMoWo"
    "quKg0GeCMLIuuZWVJb/WaCgUKtWgqqgcyA/KAxsxx++rqpKRMjV5dFAYW9EgaCSuSCDiCuKmUNy5WAWB"
    "sCJhiSpSM6IKogqiCqIG4MBeVClNhawGj1zSrvnjyl8/j5IW/mP/DVKwe8w=";

// electric_meter [rounded]  source: src/home/electric_meter/materialiconsround/24px.svg
static const char home_rounded_electric_meter_b64z[] =
    "eJyVU01zm0AM/Ss7nIVY7SfbsX0olxySa+8OoeApxRmbQia/vhLExDlmYLQa6elJegu769Sqt7/9cN1n"
    "3Ti+/iiKeZ5xtni+tIXRWheMyFQzHJ/7Jn8+1n/ay/nf8LLPhmZWmh/j+M1U15zabtxn4k+nZv55fttn"
    "d/n59DJ2S/qwaw+7S1OP6vep75noPDRf6z+xxXeQRbtQvx7HTvGAT0QYLZgqovZgkBxYJA8BtQULpDFS"
    "nWskCw61Y4QzEJEBUGKMvwzVGjR6z8Z5IHk6Xa8RoHyN5jTlhDooTljLUGbSGIJ4gUvkuHIgMl6bpUyH"
    "b3F7W1t0iT3jIOQOfeSjRBdVZQg8JoYGLJkcS3bXrd/VE1n0Dsjxno9kBGO8LOxkKkcydrp53Jb7L8k7"
    "syIk3fNoHPO9GLcYJXCb7gzJhgJ3a0NW2NcbGwjbzeN+PStQb9PABhEBPhqJRNJZJOWGFW+U+OYshhI+"
    "fIfWwN2msreH9JCqUjRMUPJtsqp8TNwu30TPSQTuwib6dhWTriisVeTFJhBK9X77yOSfOPwHfNu/HQ==";

// energy_savings_leaf [rounded]  source: src/home/energy_savings_leaf/materialiconsround/24px.svg
static const char home_rounded_energy_savings_leaf_b64z[] =
    "eJyVUj1T6zAQ/Csa16ezvqxYb5IUpKGhpQ/G2JknHCYYzPDr2VPCV8lYPp21e7vSWevn10G9PebpeVON"
    "8/z0r66XZeHF8/E01M4YU4NRqX7a3+Ve3+27/8Pp+DLdb6qpX5TB4wJGpcb+MIzzppL89dAvV8e3TfUD"
    "Xw7381jg7XrYrk99N6uHQ84QOk797/pvbv0XZj0UaYyn/Twq7PHGOvKdDtyS0Yk8txFT6gw5BmR4FSiw"
    "WZHltKKGo83acmxJQqcN+0QSzpllgxpMwXZf0GX1nAVLRmUpLjK7FSdPzrCLlLhtyVmCrbOdYw+lAENI"
    "A4jso3Ycww5sUGwEVOgBzFJ223QGqlKQtJPn2rp3dWMbbj1wmKisG7ZRdL3sHilCg0w2xjYgayKCsQUO"
    "X0EWfUEKx2XHIWjP3md0zxQJKQnhkxO9EEtn5AhJZbHWxfoiaBsS52JC4kzF+fJ5DrLmC1AoLmtxpuIs"
    "xqKgdjhjwk8pDUZrUIU8IX6f/f3zBpQXl3b7AX6WqwA=";

// gas_meter [rounded]  source: src/home/gas_meter/materialiconsround/24px.svg
static const char home_rounded_gas_meter_b64z[] =
    "eJyVUstugzAQ/BWLs23WDxKoQg7lkkuuuScuxagUooRClK/vGPJopV4qW8uyM+sdD6zOQ8Uun017ziPf"
    "98eXOB7HUY5Gdqcq1kQUgxGxst0fmlIc9u6jOnVf7VseteXICEtb7Ij5sq58n0chH+pyfO0uefQDH+u3"
    "3k/welWtV6fS9ey9bhoc1LXl7/4nN/4PM66mo4/73jMI3KoFt16onXEkSCYJgk2ECsuTm0qchOJzmatB"
    "eaH/ZhcZXrjmGdchybgZ1CYtErnMuMW6JSkbFDkCSeO8O2h96qYKcSvmqrC7tNA096k0gJYHvVe2VRoV"
    "B6JJIU9LiJBqemL2AuqUJA3RJg0cqJJKC4OMOZIasrUBmizu2RK3dBhroCjLJjqCsXMWGgtlZYLxElpM"
    "GKuwg4qgBgBtsqddD18GYjerHg7CKgicKnz2lQdfqcDVslBWyRSBhni9f7Xwk62/ATMmnPA=";

// heat_pump [rounded]  source: src/home/heat_pump/materialiconsround/24px.svg
static const char home_rounded_heat_pump_b64z[] =
    "eJyVU7FygzAM/RUfs20sGwfcSzKUJUvX7CmlkCslvYRCL19fSRjajj2DLUt6z3oWbG9jI77eu/62S9ph"
    "+HhI02ma9OT05dqk1hiTYkYi6v703NXq+VS9NdfLZ/+yS/p6EgaHzfBJRFufm3bYJWSP53p6vHztkl/x"
    "6fwytBzeb5v99lpXg3g9dx0SXfr6L/4nN/1PZtow9cdpaAUW+ARBuoMvncaVBq9+hKwyEjRIgw5Lo0UX"
    "O6RV7FT26EsLDLEGI04S2V08gdW5l7k2haiMLiySgEU2n6OVZdJqcgXoFFn4HimXgKDtDBydhjlObxn0"
    "pkC/RxZkcGiitSYjMtchyKCN7yLlgY8vOTFCEB15Yi7jTCG53nY9keDlfFimnZ0Pc1T9T/ZaLGx0sKJS"
    "pFORTkU6Fenk6llnlHHkZL4gJCSM99IooGyPC1Qm+ngv0XMD3kjclODobAzHmbY4rxfO7KNiHYuMWQFG"
    "siJqQDtqkGs5G22AxAa/XjlfRzknLzjiWPgWAMGdLmBux6IU255RszcZTnnA3rvALefWMOC+fI308+y/"
    "AQSpyVE=";

// mode_fan_off [rounded]  source: src/home/mode_fan_off/materialiconsround/24px.svg
static const char home_rounded_mode_fan_off_b64z[] =
    "eJyVk9GOm0AMRX8F8ewxY3tmGKokD81r+hFZlkK0NFll6bLq19eGbLJ9rADrSh5fz7kSm7f3vvj4NZ7f"
    "tuUwTa/fqmqeZ5wFL9e+Yu99pSfKojsfn8bOPR3bl/56+X1+3pbnbi68Phz0LYuhO/XDtC1Nv5+6+fvl"
    "Y1t+6c+n52lY2rtNv9tcu3Yqfp7GUY0u5+7f+cfZ6n9OVv1ivb6vx2ko9Jo/KKEEyChpdIzcgMfMrfNI"
    "2YpoEVMctURTElpt1Kqy6OkkjrQBpBbq4NNeLXOEiCGASsrAQILSABetE/QZvAvY6ESoXUQBQU4HylgL"
    "UMSmVT811gFt2J5Iq2JVe2bQ0YxNAzVSggfAny+Udz5GG450+BTGJs3ivypCz+DtNnSIuka9aC9Y1+pf"
    "690zJjIERaXWQ8CgPp4gIQelTEmLl9HCs0wU0sIDC8+2mGLjiaY0PIu1tpgt26TIFqulB0t6ChWNLybd"
    "nxn4tlpFu4anV2ichaeLxVl4o1gSVmz5je4GtqpA4EcPvn1wL2o94xZ4WYOORk8MS2EMzadam/eU75/+"
    "Aru/sRC8Ew==";

// nest_cam_wired_stand [rounded]  source: src/home/nest_cam_wired_stand/materialiconsround/24px.svg
static const char home_rounded_nest_cam_wired_stand_b64z[] =
    "eJyVUctOwzAQ/BUrZ3vj9TNBTQ/kzJV7m5okwiRVG+KKr2edgoAjsuUdz84+vN5d157d3uJ0bYphWc4P"
    "ZZlSgqRhvvSlklKWpChYmA7HGMTx0L32l/l9OjXFFBKTtJShXbAhjP2wNEXG6xjS43xril/+NJ6WYXPv"
    "d/1+dwndwl7GGCnRPIW/8T/a8j/Kst9Snw/LwKjBJ7RQaY4gMQoDiFyCUW0FxhPpLXfcgKnIeLpdVeYd"
    "t+AVd6B1RKgpAusoJFhHsLItKvDIKbE0nLB2hAnQyTpBPpIJyxUoQ8auqpMUZ22uTLq8hqq7MxzFnRW4"
    "ChIKBOeJqrTQgJayyZrali5KqD15jWUtepBUzeSGsOKowd2BAvus24y2N3uqWG+Nfk3g43tA+T/3n0Ee"
    "fXE=";

// oil_barrel [rounded]  source: src/home/oil_barrel/materialiconsround/24px.svg
static const char home_rounded_oil_barrel_b64z[] =
    "eJyVks1ugzAQhF/F4mwbr/+UVMChuXDJtXdCXIxKIQKKozx916CorSo1qtbCI/vbmZVFNi0Nub53/ZQn"
    "fp4vT2kaQuBB8WFsUimESJFIiOurU+fYqarfmnH46M950rtABJbUuBLiXdv4OU+iXloXnodrnny7D+15"
    "9ut1kTVFNrp6Jq9t16HR0Luf/V9s+h8ybVbrSzV7ggMepaCgasGNoaiY4NrgBtOqGMTyDF6Mh7+hUh9U"
    "PFaxNqGnDYzlYbGlJjXbTBjQrZXCL+gRYx9OuzBbSnEjR5AULIYCtxYNFQolcZN8b2oM4GBjBnZxs6OS"
    "S80UtzsM0NHRUiTkXRmcpwa+kwiK/Urjx8hNxT5yABxHo8I3jZFov45wu798/FGKT0q2kOQ=";

// propane [rounded]  source: src/home/propane/materialiconsround/24px.svg
static const char home_rounded_propane_b64z[] =
    "eJyVUcFuwyAM/RWUsyEYAqFT08Nyba+9txkL0bKkajOo+vUzraZtt01GxrLfs59hfYk9u76P06UpwrKc"
    "nsoypSSSFvO5L5WUsiREwfx0OI6eHw/dW3+eP6aXpph8YpJMVXQKFvzQh6UpchwHn57na1P8qKfhZQn3"
    "8mbdb9Zn3y3sdRhHajRP/jf/G1v+B1n299anwxIYCdyhFbUBu0ULdm86yVEgl2LFVbbAq9aJFWhwoOl2"
    "YCJua6GI0lKiBgtEACeMBgRE4VRLbEAjFBLFKkAHNbmoWCdBCmPIVSajAYPsHhnIQ3OWY6SxNqo/gzst"
    "tKOkJeFK1CuwnELHWqWy4qxMSSF1lvpY9sZ2KMGEKiItuDe3r4fJ/7j5BBTTfc4=";

// propane_tank [rounded]  source: src/home/propane_tank/materialiconsround/24px.svg
static const char home_rounded_propane_tank_b64z[] =
    "eJyVUU1vgzAM/SsR5yQkTviagMN24dJr75RmBJVBBSyp+uvngLSP4/RsJ7Lfsx2lXF1PHh/jtFaR3bb7"
    "Sxx777lXfF76GIQQMTIiYqb2Mhp2abtbv8yf07WKJuOJQIBGi4g1Q2+3Kgp3Nxj/Oj+q6FfdD9fN7uW6"
    "7OtyMd1G3odxxEbzZP7qf7jxf5hxv7dGu7ebJbjjSVOZONUJChwklTwrqA6webdnBNXsyDLtmGr0MzT6"
    "loOgUmG+E8jKUwyQM8W1ZAqPPD3rvSKZ4AWDgKZ4y3hBgWY4ssCoHXCpuzAFqOA6YYoCepA71YB4khOO"
    "t6kDy4BgP8GThO1MGbAyeehw/6Y4HxuGp+6Ov1N/Aftad3Q=";

// roller_shades [rounded]  source: src/home/roller_shades/materialiconsround/24px.svg
static const char home_rounded_roller_shades_b64z[] =
    "eJyVUctugzAQ/BXLZz/BWCQCDu2FS665E+LaqBQioDjK13cX1LQ9VmtrVrOzO34U8+rJ/aMf5pKGZbkd"
    "pYwxipiKcfIyUUpJUFDihubSO35p2nc/jZ/DtaSDi0RBJAYWJcF1PiwlxXztXHwZ7yX9VY/ddQlbuSp8"
    "VUyuXchb1/cwaBzc3/4frfyPUvpt9K1ZAoEDnhLF9OGctYprobkSB55g1PbViANLmWEpoGHZqk2dtqDI"
    "MgZipoTJAPSqWsV2FhimMYLO251iOBNpDkICLkjzvRejTtSDnCycYeU2gInI0cPAsBQwB8w31MKAD9pi"
    "/tyzftZzjs3oYDl27/dB1px1GjKy2to+vt8Av6z6AkmkeXA=";

// roller_shades_closed [rounded]  source: src/home/roller_shades_closed/materialiconsround/24px.svg
static const char home_rounded_roller_shades_closed_b64z[] =
    "eJyVUU1zgyAQ/SsMZ76FWDvqob14ybV3Yyg4tZpRKpn8+i46bdJjZ5e3sPt4uwzlsjp0/RzGpcI+hMsz"
    "5zFGFjM2zY4rIQQHBkZ2bE+Dpae2+3Dz9DWeKzzaiASY0uAYeds7Hyqc9mtv48t0rfBDPfbn4LdyXbq6"
    "nG0X0Hs/DCA0jfbv/TuX/4fJ3SYNfmmDRzDjUQkiizfTCSqZpIIVVCVrDq+aFSQjmmQQNTGr1E3WAcMY"
    "AmQimDYQ5Co6QfYsZIhM5nOmDNryRQ6QPxHJcnOHJQH9LdAEjZLdrkPSIEmLbupbT7r3S9YocUPHA8y9"
    "UuXNCsPCWWYPCZmh28+DtwV/VH8DhmV3tQ==";

// sensor_door [rounded]  source: src/home/sensor_door/materialiconsround/24px.svg
static const char home_rounded_sensor_door_b64z[] =
    "eJxVUE2PgyAQ/SuE8wgMom036qG97KWnJnu3lopZq42y0vTX70j2MzPA472Zx0cxLy173PphLrnz/v4i"
    "ZQhBhFSMUyu1UkpSBWd2qM+9Tc51895O48dwKflgA1MU2lBy5mzXOl/yFS+dDfvxUfI/eugu3kW5Ktqq"
    "mGzj2bXrezIaB/u//7dWVsW99o7ReUfcgn7ND0bsQIMBTasBs2DeKECBoKJA4VA3kQCdRDLRb+agVWzB"
    "HSkaVrMnO2ImMsBUZKyh0m0KKkGREcw3EdCYvzfwRZxwA0j+NFPqE+YiTaMJ/Ng915tLeuf6fdUn9tlb"
    "Hg==";

// sensor_occupied [rounded]  source: src/home/sensor_occupied/materialiconsround/24px.svg
static const char home_rounded_sensor_occupied_b64z[] =
    "eJyVlM1y4jAQhF/FxVkS+rMlbUEOy5U95QkSxYupsJBK2DiVp9/usRNCbls20qCfUX+ahtXL6655+3M4"
    "vqwXw/n89GO5HMfRjMGcnndLb61dYsWi6Y9394de39/Vx93z6e/xYb049mNj8fiId9EM/X43nNcLxq/7"
    "fvx5elsvvsyP+4fzINM3q93N6rmv5+b3/nBAotOxv95/Wbv8n5XLnaTG+3R3Hhpo/OW8cq4603XKqqCd"
    "CRFdeJFIBz63RXUcLirfOsvIOSX73pn0KpWv2JijsjqYFilNq1tjg0K2tEGWTrlgUlDoowmFPebLFn1X"
    "Lde3aGKrHJ/B2ToNKaenYe0OFmFxTWWf8AkdxXYcTYiS3yAnDnfetDwOckQa3mvB3huQJJPK9hLKgcjl"
    "A4SkjChn4XAmOtK5oLHYo8kJlLnT0ZQiTcXq1nNz5kKKs5EbmeDVNpx3hYAyBUJjPb/ygnyLMiTOFpTA"
    "+E55E72KxjtpNh6rCzRmhaiLiArCT+HXbBxB0ly2n1EVKj3zZaIl6owc2uCIhBNbPzWRAqgcRcuyU26B"
    "cBa3apx85QoURAGNUBjyH0xC53lSDJVMWujIpIWOTFrABAklnYnokk/R3yyGETgFm7aXUG6dthG4RGEC"
    "J+oqC6ZYMMWC4WLRtKplmSkTWKwUBUc138UHkCt6prLwHbAERkuphEYLF2m0cF2QBIfqJhxE1quL5G9U"
    "HJoquf0S19mEwiYmTFnNZqpiQWEjkZhR4bdWxXszm3hPXCjuHSYDiveANgMJmpdfXagCpARNzCdoFwdO"
    "QGLDiWgy4hfN7x9/M/LBP+PNPy7yKqA=";

// sensor_window [rounded]  source: src/home/sensor_window/materialiconsround/24px.svg
static const char home_rounded_sensor_window_b64z[] =
    "eJxVUMFygyAQ/RWGMwpLKMaOemguHpqrd2MoOLWaMRQy+fouXNrOMiy89/btQnMPljy+lvXeUuf97ZXz"
    "GGMZD+W2Wy6FEBwVlJh1vCymuIzTp9237/Xa0tVEIjCkwkWJM7N1vqXpHGYT37ZHS//wcb56l+musV2z"
    "m8mTj3lZ0Ghbzf/6Xy3vmtvoHcF+ZzgyFUD3elA9HEm6y16fVFkzyRSTmFVWTIJBCUxkAsOBnDLAZJHB"
    "Qg7qJEUugRoZyZLZe9qe5Fwh6ECEQvcVGaBGCNBSODR3h+Glr4LGDOKZ5uP4mvRJ3Q+3wVkP";

// shield_moon [rounded]  source: src/home/shield_moon/materialiconsround/24px.svg
static const char home_rounded_shield_moon_b64z[] =
    "eJyVUstOwzAQ/BUrZ3vj9TNGbQ/0zEeUEJKKkKISmoqvZzaAgCNKsl5rZndn7GxeL726Po/T67Ya5vnl"
    "pq6XZaHF0+nc185aW4NRqW463I+duT+0T/359DY9bKupW5TF4wLeSg3dsR/mbSX55dgtt6frtvqFL8eH"
    "eVjh3abfbc5dO6vH4zii0Wnq/tb/cOv/MOt+bf1ymAcFgXfM5LUjl0aTZI37QNHpQA3roCPFiCWRL5dA"
    "ubUCeO2JvS7ks84UvGZLObZW9pbYIeSvjImDtqoN5A0GNSvfRCr8ma2VF7O2NhatEaIDNTbCx9dkCDOr"
    "MJYIjbZoqM4/6aeBd3XH6Jw1BwqsWikOQDhjoGPJTKKSMMLmFi25IGSHfYpAsgMlFZPJezEThJjgI3kE"
    "J44iy7YFEBK8OZHri5TBJXmHg2mSQnFmgcV/A4VUihxZIzL3nMhGzV7mIXciF4f0S/r79z3Jb7X7AEUk"
    "l3o=";

// solar_power [rounded]  source: src/home/solar_power/materialiconsround/24px.svg
static const char home_rounded_solar_power_b64z[] =
    "eJyVVE1zm0AM/SsMZyFW+8FCx/ahXDjQa+4OoeAptTMOhUx+faXFdmK7k7bDArL09PatJLx6mbro9eew"
    "f1nH/Tg+f0nTeZ5xNng4dqlWSqWMiKN2v30c2uRx2/zojodf+6d1vG/nSPGlLa846ttd14/rWOxp185f"
    "D6/r+EN83j2NfQhvVt1mdWybMfq+GwYmOuzb6/x3bPo/yLQL1Lyet2MfscZvBo0ByiqiKTGVw6xJFBYW"
    "VELoHSjMHFuFA0Ln6xP6TcguFCSu3mPmB841mvHWlFohWSDDBEBFyOOVo/gqMg+3LJqQiAEcm2yfoaOG"
    "UOegQKM2zEk5iJBEM3t9Rl9zWLQFaB0OYyuNeREULeJL5smAZeUaDGpiIJwSbs6jIa/lIaVwTkrBdbBc"
    "B6CJGgWLlz1AcvWqWTxAyeJN6KEo+bh5+KUlyOKZ8WajHF3BoEzX7yZzmUJUFxAsQqVDNyzV5DHPgWvT"
    "JBdUAJwty0on1XxID9bCARKPBoVezuOpZDrnoUAllUR9sU5KrsVmUjdxB4JEHp9IHbhKn4msnbw86r9o"
    "BVU6zBdlGTf+bJ20XEt0oCtbGik6t5jnhg0Dhgty3zO679mkymxJchLSwPfNjPIw9gn9aS7+fQ+ZvCBR"
    "LbsI6d0A+kajzzhV5l1bfrnKl54Hlr2FeLwMlH87f9bh5n+izW9cpBgZ";

// vertical_shades [rounded]  source: src/home/vertical_shades/materialiconsround/24px.svg
static const char home_rounded_vertical_shades_b64z[] =
    "eJyVUMtOwzAQ/BXLZz/WjoMISnKASy69ck9dY0cEp0pNXPXrWTdCwBGNpV3Nzs6O3F42T64fc7x0NKR0"
    "fpIy5yxyJZbVSw0AEhWUuDgeZ8ePo3336/IZTx2NLhNAaIOPkuAmH1JHS79NLj8v147+mufplMJ93Le+"
    "b1dnE3mb5hmNluj+7v9o5X+U0t+tz2MKBAMeNDDVvNYWuBKKg2i4LhgeXoxoWMUMq7AaVm/KDJVFRV0z"
    "FDMQpsaiNrDAdhYZpgqCerQ7xYpnoTkKCV4pNN93CwYNN3JQe4hgyhEFt++g5V/7L+aIZps=";

// vertical_shades_closed [rounded]  source: src/home/vertical_shades_closed/materialiconsround/24px.svg
static const char home_rounded_vertical_shades_closed_b64z[] =
    "eJyVkU1vgzAMhv9KlHO+TAhqJuCwXbj0yr2lWYLGoKKMVP31c0BTt+PkSE7ePH7tKOVt9eT+OYy3ioZl"
    "ub5IGWMUUYtp9jJTSkkkKHHj6Tw4fj51H36evsZLRUcXicLIclyUBNf7sFQ07dfexdfpXtFf97G/LGG7"
    "rktfl7PrFvLeDwMaTaP7W/9k5X9I6Tfr62kJBAc8ZoqBbU2nOAjgSliepWiKt1xYplnONOacmRXyRndI"
    "GMMQZkrkBhOsqlNsV1FhkCLAodslljyTzBEk2CXJfK9N0WTqQY6gmQkgth6gW5MktLGNFaY1DUALFrXi"
    "SRU7VAizjd/AYavF8+PnlelT6m/6UnVS";

// wind_power [rounded]  source: src/home/wind_power/materialiconsround/24px.svg
static const char home_rounded_wind_power_b64z[] =
    "eJyVVMtu2zAQ/BXBZ5ImlxQfRZxDdfGl194TRbWMqnaQuFaQr+8MhSZ2kB4KSfRqd7kzO0v55vm8a15+"
    "TYfnzWo8nR6/rNfzPJvZm+PTbi3W2jUyVs1wuLufBn1/1//cPR1/Hx42q8MwNxaXBNyrZhz2u/G0WdE+"
    "74f56/Fls7qIz/uH01jDtze725unoT81P/bThELHw3C9/z13/T+Z610tjfvx7jQ24PitKL9tu2BCq7wK"
    "ytMIKpxtb5U1bYsFHsdrDP3iUU4vXu3OtnN22VUY8woFX4n1htCqtJXOMSWhTFrq5U8R/KcIcdnUMpQU"
    "nmuAoOQfO3ur6a0e7XhtQ6+XRO3U4laE8Eqqu3YiTrHmNYrzJnnlrIkOUIm0Be/Gw0gZRovuTIhTMJJ0"
    "Mo5pEfWNzUjxWkzImrnaG+dJIydyEaSUQo4OOYn1pDQTsoIHH3GdE0K1BgCiYoXlb8pnb4pn2Ecya7GK"
    "KZm2x/rO+EMrdDFVEji6WFlQDfIrEVYuICVpC/jcibGiXB3QYrKyZIzP8RXF2HmBG/0qMa5Ag5av6INj"
    "YUsOIzGU3FatiCRuEhOJFNEjyoB+MF4q/YqR1AXV6x4ELgQywhNkk6yDcRRVKOqitKfGnp2wxZKoqWME"
    "3I0lK4DxEEbGSa6AsK5utBa5k2xTAoIv1WIYjHiw6tAE46s/3wXwtUVNTQpWGSNOIHy6vvM6g6Zk6IMa"
    "XKhPLlVxKOf9YqF11OjQI46kVEDYCf3iI1MXrX+Yq9QjgI+ZX0NiWQmcCoVgSzhwPJUSqE5lr2sUHwZi"
    "/Zs3VLda4hlTaDrnqireeAySQhDHFXWB+fr3L6Y++Fe8/QMZvS3R";

// auto_mode [sharp]  source: src/home/auto_mode/materialiconssharp/24px.svg
static const char home_sharp_auto_mode_b64z[] =
    "eJxVk01zmzAQhv+KhrO0aPWJOrYP4ZJDeu3dIRSYUvA4xKT59d2VcV0PoNmR9n3e1Urs3i+d+Pw9Tu/7"
    "ol+W07eyXNcVVgvzuSuN1rqkjEK00/F1bNXrsfnVneeP6W1fTO0qND3G0VuIvh26ftkXHF+Gdn2aP/fF"
    "f+vr8Lb0efmw6w67c9ss4ucwjgSap/ZRf88tD7uyywJ6T8elF+T8HRNoKy340CiEEGmwSVmIThmwKtAq"
    "BR4vBjQ2CNFKDZhIYZGiqpIOAkqEZF7urC92u3sgTerwA0H7uoLI6cbLAMFJAxgJkWLWjQjOSB7qCIFd"
    "kpMJDK+SYgM90klcEcumFyZkVp2pmU9OQW6emgk9b6TOuA1MFtnsH+iRbzRnbMJGaTBIHTGJOoVGObAh"
    "Nyi3alT3DZBOhyuZwrjZ3WhXj3n8082TOM3DtNC1iRKNQA2OMngzAokVRY5vM9ec6wxnck68iXh8bL2R"
    "hoq2QK3TykPlqUKfVAQXlHuOF2We8RJ6QwFEOt9E1ULlpOdiHUTJfYmNgypKLflmcAXsQww6MMKlQE1x"
    "XtR0/nxIFbhKoqcbQd4yV/B1u335o9/g8Bf3mL9q";

// blinds [sharp]  source: src/home/blinds/materialiconssharp/24px.svg
static const char home_sharp_blinds_b64z[] =
    "eJxVUMuSgyAQ/BXKsyCMiLqlHvbEJVfvxrBixdWUupDK1+9g9llQXT09Pc2j2txA7u/TvNWR3ffbS5J4"
    "75lP2bIOCXDOE3RExMzdeTL03PXXYV0+5ksdzcYTjgsk7ohYMw52r6PA3Wj863Kvoz99P152e7Sbamiq"
    "1fQ7eRunCYOW2fyf//UmTZUMx8Ct2y3BY0/AY1G2qZZOKA0OLHBHQQN/kJNQcWmDRqEtQy1jIbRqS1u0"
    "QgShiPPQzCy0+dOQOUBHpoXEWmG2o8oWTrACSE85k1nMWQrI8sAK+WSCybTnKJQ5Ql6gcKhfsAWgPw0a"
    "oOcoZCVCirV4RtIQ1IoUr620eny/OHx78wktHGzv";

// blinds_closed [sharp]  source: src/home/blinds_closed/materialiconssharp/24px.svg
static const char home_sharp_blinds_closed_b64z[] =
    "eJxVkM1uhCAURl+FsFaB63+jLrpiM1v3jkPF1OpEKUzm6XvRtraB3MC5nI9AtdmBPD6meaupNub+wphz"
    "LnJxtKwDA845wxOUqLm7Tiq8dv37sC6f862ms3KE44AEJyVajYM2NfVrOyr3ujxq+qfvxpvRe7uphqZa"
    "VW/I2zhNGLTM6r9/nmVNxYZduHdGE7z2AjwQZRvLxIpMggUtRARpzwMelTmWvAhElKdn2XwJfxuhLxLA"
    "hiCBP8lFIBc6hLbU0ArhSYJEZgiKE8QWZOYlkXiSIdH+ehRFfMTkfpNiSn44qVfa9DBQKFHXhYffCTvA"
    "ECmy589b/Yc3XxYHbkA=";

// broadcast_on_home [sharp]  source: src/home/broadcast_on_home/materialiconssharp/24px.svg
static const char home_sharp_broadcast_on_home_b64z[] =
    "eJxlU01zm0AM/SsMZ61Yab/Yju1DfcklV98dQsFT187Y1GTy6ystSdy0AyveStonPQGr622oXn8dT9d1"
    "PU7Ty7emmecZZ4fny9CwtbaRjLrqT/unY2+e9t3P4XL+fXpe16d+rqxc7OWuq7E/DOO0rhXfDv38/fy6"
    "rv+Kz4fnaSzhzWrYrC59N1U/DsejEJ1P/dfz99xms2qGckDul/00VlL5kRkyprjzD/7GI8UbY8hbtpgc"
    "tNi2wIReUljQkvqmTJ/nM+QHvhGNaZffqscE1AqTSaPbUfs1lRKmABQxp86iMxbZgcUgIKR3oCF5xKzO"
    "aAg53M21WPiMgJrOisPLYlmpREF5dszVSBh2peC/nQA5DB2ha8GCSBYq4gJkFcrSgqiWHDJlHCTij4Q2"
    "ghqdUZBzLZLMCETc8owigJFJOkzZeL2qrnjAGg+LF7zUkJLaupYk3SQBrSsVjJrOaPTDJKfO9gOltCWv"
    "fXuMDBSKdepYtP0nOIsuI4EsbcSiM1MBsQjWvqDIdOiFCjMI872ZLclgosqNMglWvTI7BYvgFIWRvQkQ"
    "TKiuoexAdoXbpfI+xRlZ6HyUKoGVPZVhdipfAqTzbrPwvQOR2G656GL0MmGrCvKiM7/L1M+6LPm/Nn8A"
    "kkrQgg==";

// broadcast_on_personal [sharp]  source: src/home/broadcast_on_personal/materialiconssharp/24px.svg
static const char home_sharp_broadcast_on_personal_b64z[] =
    "eJxlU01v2zAM/SuGzzItUl/WkOSwXLvr7qnr2cGypEjcuOiv76OaoB2K2CQlSu/xkc7qch2r13+H42Vd"
    "T/P8/KNtl2WhxdHpPLZirW1xoq6G4+7xMDSPu/7veD69HJ/W9XFYKoufeDx1NQ37cZrXtcbX/bD8PL2u"
    "6y/5Zf80TyW9WY2b1Xno5+rP/nAA0Ok4/H//82y7WbVjuYDneTdPFZh/cTJdbykZa5hcZyyxEbKCQNID"
    "i3EP3uQryxQpxW2mGA3DOpMNJ+qyeuwbZgqdYVELD9g3pfxKxJ5S6BtLMRvbMEkAS4gfkZreYsMrNd5U"
    "snhz+i0yAf7aBLIO1TpgiNM0gpBuQU7VlruCFcixlgeiQmru7N9rkr4REkZBHjWkDOd7bQZrLQHNYF0k"
    "BJ07MFmt10aV4cPdJKeb3T1KqVd9aCduCvAVJqivLrrQXXPbLZpjVkV63HEB0VJiYTNqtgKJuNfpdIqy"
    "D48ErEPZOhSNpUiVbzozmBpHQTsfC3PmEsRSgio3hdiRBwZl4yl+yt3qYKMWgMkXkqIOQYRUQbFAFN8E"
    "ExqIDGVlsCrYLumc9EgUwPkIliCKnoq8XhuMBGsHugy8W+DxNW3FacuEPDRbVZCpDBTu7f5Vlxd/r807"
    "3HXM2A==";

// curtains [sharp]  source: src/home/curtains/materialiconssharp/24px.svg
static const char home_sharp_curtains_b64z[] =
    "eJxVkEFPxCAQhf8K4QwDDC21pu1BL73s1ftuF6Gxtpsuls3+eqFq1MwcJvPme4/QXDdHbu/TfG2pD+Hy"
    "KESMEaKGZXUCpZQiXVBi5+Npsvx0HN7cunzM55bONhKZCovUlHg7Oh9amudttPFpubX0jx7Hc/C73DWu"
    "a1Y7BPI6TlMyWmb7n/+9FV0j3A5cjsGTFHtAyVT9ovtiU6bHDT3KjWOP8k4OD6BqpnBAkAVXoEumoeQa"
    "6iINleGVlyDrQQKatJCGKaiQlWDKXWcVGXhmWWYTl9d1wb80zzP8rBSYFFJmU5WcNFM6J31n33/enD+u"
    "+wTqM1uE";

// curtains_closed [sharp]  source: src/home/curtains_closed/materialiconssharp/24px.svg
static const char home_sharp_curtains_closed_b64z[] =
    "eJxVj8EOgyAQRH+FcFaBVZu0EQ49efHqXS0FU4tGKRi/vmjStM3uYZOZN5MtFqfQ+hzMwrG2droQ4r1P"
    "fJqMsyJAKSXBgZE0TTvIuG26h5rHl7lxbKRHNAxkYTHSslfacrzfrpf+Oq4c/+i+v1l9yKJQophlZ9G9"
    "H4YQNBr5z3+9RBREHcDUWI1CbQU0Yuc6LTPHTiU40EBdDCXQDVWMRbkGxzIdQ51vH3z/QbwB+mZExQ==";

// electric_bolt [sharp]  source: src/home/electric_bolt/materialiconssharp/24px.svg
static const char home_sharp_electric_bolt_b64z[] =
    "eJxVT9sOwiAM/ZWGZxyUbUYN24N/sgsyIsKy4Zh/L1ti1PQ0aXouaeW8aFgf1s0VGUIYL4zFGLOYZ37S"
    "THDOWVIQUK5prTq0TXfXk3+6viJOReCpRJFAYFBGD6Ei27wYFa9+rcgPH00fhp2upa7lpLoAN2NtCvJO"
    "/fu/WlZLpndDwujtS3sHozcupIOxpAJEVlLMAXOKBZyoQDhTkda47REQKXLAI80/WXunp+o3kyNHJA==";

// electric_meter [sharp]  source: src/home/electric_meter/materialiconssharp/24px.svg
static const char home_sharp_electric_meter_b64z[] =
    "eJxVUbtuwzAM/BXBM0XrZTkqbA/t0iFZsyeuahlV7SBxoyBfX8pA+oAeR/B4R0JqLteB3T7jdGmLsCyn"
    "p7JMKWHSOJ+HUgkhSqoomJ8Ox+j58dB/DOf5a3pri8knJmgpQ7tgwY9DWNoix9fRp+f51hZ/+DS+LWGl"
    "u2bomrPvF/Y+xkhG8+T/639ry64ph1VwOiyBUdudVKB6btBZENyBQWEIXC9Ao5OgsJJQozJgYYOm3isV"
    "1JUrFLYXqDUIEtBlbY4syBUulKg5RQpkBvsjqzTrNRrH5epJjauaIFu/KAk2u0mbpyEpjXZnO2lQVSBN"
    "5Bp0JGGVz1ZKWJmtw5poHTXXkQhYSU1qym8f4uxjwb1u2L4Om727P94if0j3DY6mbmA=";

// energy_savings_leaf [sharp]  source: src/home/energy_savings_leaf/materialiconssharp/24px.svg
static const char home_sharp_energy_savings_leaf_b64z[] =
    "eJxVkctugzAQRX/FYj0ePH6BK2DRbLog2+4TQgHVhSihIcrXd6Cq2sqPsXXPvbbl4nrrxP0jjtcy6ef5"
    "/JSmy7LgYnC6dKlWSqVMJKIdD8fYyuOhee8u0+d4KpOxXYTipi33RPTt0PVzmazr29Auz9O9TP7oy3Ca"
    "+02uiq4qLm0zi7chRg6axva//5dNqyLtNgP382HuBZ+8Jw2mkRZzUDKAwdxzCY0CjSwpzCxYVBkQhgwc"
    "eqoNUEAXaouWQFNcFblOuwyDAa1QewiY5ywCZ2gSjUYDioM8SbUqHo2XGr3dMc4MeZY23jK5+V7NC+mH"
    "2JNCB5TVpFbKRY1OGq7ScZSLXjp0NVnI1kIrS9HxxXn37RSPn6dvg/+g+gLEyGqb";

// gas_meter [sharp]  source: src/home/gas_meter/materialiconssharp/24px.svg
static const char home_sharp_gas_meter_b64z[] =
    "eJxVUE1vhCAU/CuEM8ID0cVGPbQXL3v17roUTK1uXCqb/fV9mDRtw4P3MTMMob7vjjw+5+XeUB/C7UWI"
    "GCOPOV83JxQACGRQYpfhMtvsMowfblu/lmtDFxsJ4FIagxJvJ+dDQ1O9Tza+ro+G/sHjdA3+gNvatfVm"
    "x0Dep3nGi9bF/tf/ckVbC3cIbkPwBG3PCpj2WdErn6k9Hb3qql11epfGy7LXT3KWikkzZpLnhkGmeIGl"
    "PLLiuhwBW6gYcJ0nTsUSkvNTRUbFocAWdTjDfTpywt6kxkqWvGIyTwSJkXySX8kkdKY33vQSnj/PTn/X"
    "fgNdGV1j";

// heat_pump [sharp]  source: src/home/heat_pump/materialiconssharp/24px.svg
static const char home_sharp_heat_pump_b64z[] =
    "eJxVUk1zgjAQ/SsZzmHJBwjpiIdy8eLVu1IKTik4SsHx13d3CdiOEjbZ997uy7K9j7V4fLfdPQ+aYbi+"
    "RdE0TTBZ6G91ZJRSESICUXWnc1uF51P5Vd/6n+4jD7pqEgp/JsZ/IJrqUjdDHlA8XqrpvX/kwZ/8dPkY"
    "Gk7vtvVue6vKQXxe2haF+q76z39ho902qplwPQ2NwLIHo6Xd21Fnjc6O9ikO2kCayBRUVirIjFSgjdSQ"
    "pBjFsTRAR063IUX4HAlKPA1m5o0W9JynRxQONhkmEpRBCYshRisaqSk4Jx2opPWae0oUjPMMJHsZD2Wa"
    "yiS326wVJVeci8VgzVzMUvsv+Nqt3oAzZUg+Q/IZks+QfHL37NPbODKW7wf1iJMkUoWa0Am+tCiVP+QD"
    "iUd3zRuJm0Jbqo1pv9IW1/XCWX4M2Yj3UcwOMBNn3gPG3oNc+9mA0mTWJeud830UM3jhkcaitxCIbiHT"
    "8zgWqzj3mKa9iXFJHQ7fOp45j4YJz+VTou959wtke68w";

// mode_fan_off [sharp]  source: src/home/mode_fan_off/materialiconssharp/24px.svg
static const char home_sharp_mode_fan_off_b64z[] =
    "eJxVUttuo1AM/BXEs485x+dKleRh85r9iJRSiEpJlbKl2q/fcbJKWwHWSGOPPSM27x9D9fk6ze/belyW"
    "t4emWdeVV8/ny9CItbZBR1318/Fx6s3jsXsZLuc/89O2nvu1sngk4K2rsT8N47KtFX+c+vXX+XNbf+PX"
    "09MyXundZthtLn23VM+naYLQee5/zn/1NrtNM1wHbu/bcRkrLP/tEvtAhX2ajLC0ZLlIZyy7osWjeEUS"
    "UaIiHzoQGah4dCdvHAhykICCTXtIlkiRQyBAV0jIefYtSdUZz7aQNYFbTIRsInvyLOngCmdPLnLbQQ/C"
    "GAChe6K7IQHaixBGC7ctZXaJvgz8/eby7k+4ONJycKoYWOQQIYYJt/ecM1QyLiycnB4KQ66z6AvYaR0l"
    "lgAvKaFYP2lE6hxWNCLSiPRWRaJXR0WISMPLGqYmmGBMw9OM6JoRTo/qIibsL0LyfzVAd4sIJ7RGI8Ji"
    "bzSiyXPJpKWaQDhl3eFu8G7//uGP2/0DNbebFg==";

// nest_cam_wired_stand [sharp]  source: src/home/nest_cam_wired_stand/materialiconssharp/24px.svg
static const char home_sharp_nest_cam_wired_stand_b64z[] =
    "eJxVkE1vwyAMhv8Kyhkc8w1TksN27a67t2mWRGVJ1Wal2q+fqTRtEwgbHr+vgeZ6G9n9Iy3Xtpq27fxU"
    "1zlnyBrWy1grRKypomLDsj+kQRz2/Wm8rJ/Lsa2WITOkoQzNik3DPE5bW5X8Ng/5eb231R+e5+M2PXDX"
    "jF1zGfqNvc8pkdG6DP/1v7V119TjQ3DebxOjtq8ycIRgd1JCDFyCeQkQLSWeO9CeGwpouAfUvUDQkWuw"
    "nitQBFzkFlwo1CQyICsZE5VZ93BlRRKCKMdCQtAlC0IRIq4s9VKSS1dWzyXtLEWFYOSOop4k3oTukbTO"
    "FystNEhLBhiFAXQJIXqihh5Atzfg1Vtp/PXz1PLf3TdZ2GW0";

// oil_barrel [sharp]  source: src/home/oil_barrel/materialiconssharp/24px.svg
static const char home_sharp_oil_barrel_b64z[] =
    "eJxVUE1vwjAM/StRzvl0mlCmtodx4cKVeylZUq1rUQkJ4tcvYZo2ZEvP1nt+ttxco0P3r2m+ttiHcHnj"
    "PKXEkmLL6jgIIXhWYGTn/jRZeuqHT7cut/nc4tkmJHJAlRMjb0fnQ4tLHUeb3pd7i//xaTwH/6S7xnXN"
    "aoeAPsZpykbLbF/n/7S8a7h7Dlz64FFeewBJpIoUPIWj9nBUexXBQzQvKOsfSaRmD/KBDhKINAOVzBgi"
    "qMqFggzAtnoQpSOCaSj8hihaMa3RAKzaEGC1IYooBlWGQuykJrJips6HFDuZs7g/fs8tP+u+AVA3XKw=";

// propane [sharp]  source: src/home/propane/materialiconssharp/24px.svg
static const char home_sharp_propane_b64z[] =
    "eJxVUMFugzAM/ZWIszFxAgEm4DAuO7TX3inNEjQGFWVJ1a9fYJu2yZb1ZPu9Z7m6OcPu7+N0qyO7rten"
    "JPHeo5c4LyYRnPMkbERMT9151PG569/MMn9MlzqatGc8hEhDRszqwdi1jjbsBu2f53sd/Zn74bLafdxU"
    "pqkW3a/sdRjHIDRP+j//dzdpqsTshGu3WhZsj6Qwz0AdSIE6yZfCyUOOInRaiWUOCggJCswkEBBhIVqO"
    "JVCGgkCiEkAF5KE4aYWLpVXfoJcoC+CgkGKBeQkqDrBgrRCBvwsKjlxuDl8nPNiROGQ2dWTj9JQ9fs7d"
    "ftZ8AhL6W84=";

// propane_tank [sharp]  source: src/home/propane_tank/materialiconssharp/24px.svg
static const char home_sharp_propane_tank_b64z[] =
    "eJxVUEmPgyAU/iuEMzto7UQ9zMlLr96tZcDU0cYy0PTXz8Mms+QtkPctj1Dfo0OPz3m5N9iHcHvjPKXE"
    "kmbr5rgSQnBgYGSX4Txbeh7Gq9vWr+XS4MUmJCCUgcTI28n50OB8j5NN7+ujwX/wNF2C3+G2dm292TGg"
    "j2mewWhd7H/9L5e3NXe7API2BI9g88kQWUQ9CqKYkkSyw5GYHL4a94kghr6m1ESqO/PMRj9yJYjUMB8F"
    "sKoSmqqoZkZSDUdV9qo7RMOkGbOLIoKZgmqioDIcdafEE53A3pdRear6AlqU3bF/bcpP3gv+rv0GtP5f"
    "5Q==";

// roller_shades [sharp]  source: src/home/roller_shades/materialiconssharp/24px.svg
static const char home_sharp_roller_shades_b64z[] =
    "eJxVkMFuwyAQRH8FcTawYIrcyvahJ19yzd1xKFh1cWQTiPL1Wbtq2gpWs+jtDIh6TY7cvqawNtTHeHkT"
    "IufMc8nnxQkFAAInKLGhP02Wnfrh0y3zNZwbGmwmgEtp3JR4OzofG7r1abT5fb419A/P4zn6Hbe1a+vF"
    "DpF8jNOEQXOw//2/s6KthdsNlz56gtceFBTy9Vh2OknTqaS8gsRUp+BODgZRYsa/JMmrgQHXBfAStUKt"
    "dpVcD5hQfPfPWuWTVwyLDIBHwza75HJDqPooSww3nbn/PG37n/YBnQBXsg==";

// roller_shades_closed [sharp]  source: src/home/roller_shades_closed/materialiconssharp/24px.svg
static const char home_sharp_roller_shades_closed_b64z[] =
    "eJxVUMmOgzAM/ZUoZ8hiCrQj4NBTLr3OndI0QWVCBWlS9evHIHWT7Sfbz5tczcGQ+9/g5ppa768/nMcY"
    "WczYOBkOQgiOFZRo1x4HnR7b7mKm8eZONXU6EoECG1RKrO6N9TVd/NDruB/vNf3gY3/ydqWbyjTVpDtP"
    "zv0w4KDR6e/+dy1vKm7WBtRr6y3BzQcQidz9ZmoTZKEggN0yyDuRCLYrEcptIlmZv2FeIH0R6QIKIKSg"
    "QDzIocBxGNg8gCowltlHQmaP5xmr4T+af2F1VeA=";

// sensor_door [sharp]  source: src/home/sensor_door/materialiconssharp/24px.svg
static const char home_sharp_sensor_door_b64z[] =
    "eJxVT8kOgjAQ/ZWm59JV0Bjg4MmLJxLviLUlYiFQqeHrHYhrZsmb7c1MOowGPW6NGzJsve+2jIUQaFC0"
    "7Q2TnHMGHRhpV54aHZ3K6mr69u7OGXY6IA4iV6AYWV0b6zM847HWYdc+MvxTD/XZ26WcpyZPe115dKmb"
    "Bohap//nv70sT7vSWwT7DpITuV+NkluRHOWEDiKmMRGKxlXE6UYRHgkaA0zWCwAb3gF5JQqxJkLQ2YPK"
    "QiRUqYWDfNimeSuDG+fX8ycJ503H";

// sensor_occupied [sharp]  source: src/home/sensor_occupied/materialiconssharp/24px.svg
static const char home_sharp_sensor_occupied_b64z[] =
    "eJxdU8FyozAM/RWGsyxsGWPYSXJYru2pM3tPKQuZ9ZJOwoZOv34l0SZNx8aWZek9PQGb82XI3v6m6bzN"
    "x3l+/VEUy7Lg4vF4Ggqy1hYckWf9tH9OvXned3+G0/Hf9LLNp37JLA8qeebZ2B+Gcd7mYl8O/fLz+LbN"
    "v9wvh5d51OvdZthtTn03Z78PKTHQcerv82+xxW5TDJrA83U/jxkzPzoC5zqHVQUWvHHoS978WS3jZTw1"
    "UIm7gfrJWbGcA817F9A7KOo4sS7BGo+BITGYgNYDo8WWUSpwHiMB7yX6Rna+b365ODq6cG7jOmssRn58"
    "JUVUbDWRrUhZy8GM6giD4DCPcvK8r4QckocaXUhcTRC8KIURGWIGqU3qomAqLCtdkgaBhLeuRorAdTZA"
    "FslBwOjhBnpPJh4gTn6I6GuW3FBbYhnZ58p10aNcgIRoTSB0rXIoui56vOJ906TlBU5N5grQiSYQTSCa"
    "QDSByNElSYgGt6sCFaMkq8Qb5rc3Ka5VcLq2pdPWKaG2Tgm/9O/a6XblWSk+iFbPDfb983PUh/+L3X87"
    "tsGJ";

// sensor_window [sharp]  source: src/home/sensor_window/materialiconssharp/24px.svg
static const char home_sharp_sensor_window_b64z[] =
    "eJxVT81uwyAMfhXEOS02ZaSdkhx24pJr7mnLcLSMVCmDqk8/Z5dtsiVb/n5sN/ccxONzjvdWUkq3V6VK"
    "Kfty2C9rUBoAFDOk8HE8z353Hi8fYV2+4rWV0RcBHNpwSkF+CpRaufV58uVtebTyD16ma6IfuGtC16z+"
    "ksT7NM9stET/X//LVV1zGxMJ3tfjsTIZrbODcXgUval01kBoB+3MU/R1hSdCyDvr6gFPPEGoEIhFdBhe"
    "XJ0tV4Tn5qr4hu217htKdUp3";

// shield_moon [sharp]  source: src/home/shield_moon/materialiconssharp/24px.svg
static const char home_sharp_shield_moon_b64z[] =
    "eJxVkc1ugzAQhF/F4mwvXv/iCji01+Tae+JQQKUQJTSO8vRdI1VNhTVa882s11Bfbz27f03ztSmGdT2/"
    "lGVKCZKG5dKXSkpZkqNg3Xw4Tp04HuJnf1m+51NTzF1ikh5laBVs6MZ+WJsi17exS6/LvSmeeBpP67Dh"
    "tu7b+tLFlX2M00SNlrn7n//zlm1d9lvgfFgHRsfuUXG1M9zeHMgQJbcgLddgkAfwjlccJQSMBmwQCGh5"
    "JSxUBMQG3u0ud3iwPVoInqOhaCRnZbgC9GRWmCvhIDghQXoWBe0DiVf0wllCnnqAC8KD1lGCNtnpOFFN"
    "ojyJxbyNBIzjCEpTpUOOGQJa0dCVo6zHTBVJFUhCIIAV+RR7Q5dvhzqfR7XK46LhT6M/fr9R/lHtDzEU"
    "cHQ=";

// solar_power [sharp]  source: src/home/solar_power/materialiconssharp/24px.svg
static const char home_sharp_solar_power_b64z[] =
    "eJyVkktugzAQhq9iedVKxPiFDRWwaDfd9BAkIYBKbETckPT0HTtJk7RIVYWZsWa+8e/H5Lt9gw7b3uwK"
    "3Do3PMXxNE1kEsSOTcwppTEQGNWmWvb1Ylmt3pvRfph1gU09IQoflzAwauuuaV2B/Xzf1dOzPRT4Jj91"
    "a9eGdJk3ZT7WK4c2Xd/DQtbU9/VXNi7zuAkFMAbbHxtr0GA742DDgggRMYUYu1iBJBhf9ZNlgeSUKH2a"
    "eNgHZ2nOiF8uDUSwnCPOwc7SPgv8yQLPSZqB92w45+Vs4no0jOB6GMPoWOBZ0I2V2W3suC3wtnJjd3ig"
    "RFPN0OLs7x1EOU0zxCRRNE0efyopkoggpghVv/T4//UEkTJFiuj0Vk0ENUkyfRZLZsXu6NO++J8cXOg3"
    "OFSuRdCEb4xHesWJVhGNkgUnXIJLXvWLjqSPZj4CTw7Y56Wbwg9tXX4Bzg7MwQ==";

// vertical_shades [sharp]  source: src/home/vertical_shades/materialiconssharp/24px.svg
static const char home_sharp_vertical_shades_b64z[] =
    "eJxVj8sOwiAQRX+FsLbl0WqioSxcsenWfR8IxApNi9D066VNjJqZxSTnnpkMm4MCy3OwcwW19+MFoRhj"
    "HovcTQpRjDFKCQikbdpBZm3TPdTkXravoJUR4FS0TA2BlkZpX8FtDkbGq1sq+MOj6b3eMWeKs0l2HtzN"
    "MKRFzsp//5tFnCG1C2PjNUhna4oP5HwrRBnISdBANcUho4LiFdRkZ0edWCkIXj/+9gR/Azt6RN0=";

// vertical_shades_closed [sharp]  source: src/home/vertical_shades_closed/materialiconssharp/24px.svg
static const char home_sharp_vertical_shades_closed_b64z[] =
    "eJxVkM2ugjAQhV+l6VrbTqHkYoCFq27cskftbYlYDNbW+PQOGKNmZjE/3zmTTHWNltzPg7/W1IVw2XCe"
    "UmIpY+NkuRRCcCQoMb7bD2a97w4nO403f6ypN4kIDJljUuJMb12o6VzH3qTteK/p1z71x+CWdVPZpprM"
    "IZD/fhjQaPTmV/9heVNxuwguXXAEz+6kWEHZZjqPUGgZpZMirqWW4kF2kK2UA6Yi5BqyVs0jQFyXTLVK"
    "A7RQ4qz4UMULKpiaXRH5W7TYP97H5w80T0SGU5Q=";

// wind_power [sharp]  source: src/home/wind_power/materialiconssharp/24px.svg
static const char home_sharp_wind_power_b64z[] =
    "eJyNUk2PnDAM/SsR58TESYBJNcyhe+lheu19NksBNWVWLIXd/vq+pJ2PSlupCtgP+z3bSdi/rL14/R6n"
    "l7YYluX5Q1lu20abpfPcl0ZrXYJRiG46PcZOPZ7Ct34+/5ie2mLqNqGxjMNTiKEb+2Fpi4TXsds+nl/b"
    "4i6/jU/LkNOHfX/Yz11YxNcxRhQ6T93f+hu3POzLPgv6m+xKvTLrQqAblG9tYe9E/6BXmc6Z3vwv3WY6"
    "+zv+82kZBI7iM1dkjWRD2seKnFGetDtyk6NHNrIi36yOGhc0WVaa2EpNtQMyLDm7B3aka8maKgnoAZkY"
    "9lb857vNs8AGjSo7g7JOMVVOMmlW5hOvLjbSREvOKRSpHyDYNamF2/3pZqnxF/huD4OJUcQejZUZR2XR"
    "Q9Vk6wT9TnHQ6I0NwKQp2FyRR4rJgpOihirMUSUfMLKFAq72MBqUfBZfDIuQ6MilEh7WDDX2iJjK32mt"
    "ymGW42W6+9HDOIfYiZAuGlcX3n77GY6qC+/64ic//AL59cL2";

static const BaseSVGIcon kIcons[] = {
    { "home", OUTLINED, "auto_mode", "src/home/auto_mode/materialiconsoutlined/24px.svg", home_outlined_auto_mode_b64z },
    { "home", OUTLINED, "blinds", "src/home/blinds/materialiconsoutlined/24px.svg", home_outlined_blinds_b64z },
    { "home", OUTLINED, "blinds_closed", "src/home/blinds_closed/materialiconsoutlined/24px.svg", home_outlined_blinds_closed_b64z },
    { "home", OUTLINED, "broadcast_on_home", "src/home/broadcast_on_home/materialiconsoutlined/24px.svg", home_outlined_broadcast_on_home_b64z },
    { "home", OUTLINED, "broadcast_on_personal", "src/home/broadcast_on_personal/materialiconsoutlined/24px.svg", home_outlined_broadcast_on_personal_b64z },
    { "home", OUTLINED, "curtains", "src/home/curtains/materialiconsoutlined/24px.svg", home_outlined_curtains_b64z },
    { "home", OUTLINED, "curtains_closed", "src/home/curtains_closed/materialiconsoutlined/24px.svg", home_outlined_curtains_closed_b64z },
    { "home", OUTLINED, "electric_bolt", "src/home/electric_bolt/materialiconsoutlined/24px.svg", home_outlined_electric_bolt_b64z },
    { "home", OUTLINED, "electric_meter", "src/home/electric_meter/materialiconsoutlined/24px.svg", home_outlined_electric_meter_b64z },
    { "home", OUTLINED, "energy_savings_leaf", "src/home/energy_savings_leaf/materialiconsoutlined/24px.svg", home_outlined_energy_savings_leaf_b64z },
    { "home", OUTLINED, "gas_meter", "src/home/gas_meter/materialiconsoutlined/24px.svg", home_outlined_gas_meter_b64z },
    { "home", OUTLINED, "heat_pump", "src/home/heat_pump/materialiconsoutlined/24px.svg", home_outlined_heat_pump_b64z },
    { "home", OUTLINED, "mode_fan_off", "src/home/mode_fan_off/materialiconsoutlined/24px.svg", home_outlined_mode_fan_off_b64z },
    { "home", OUTLINED, "nest_cam_wired_stand", "src/home/nest_cam_wired_stand/materialiconsoutlined/24px.svg", home_outlined_nest_cam_wired_stand_b64z },
    { "home", OUTLINED, "oil_barrel", "src/home/oil_barrel/materialiconsoutlined/24px.svg", home_outlined_oil_barrel_b64z },
    { "home", OUTLINED, "propane", "src/home/propane/materialiconsoutlined/24px.svg", home_outlined_propane_b64z },
    { "home", OUTLINED, "propane_tank", "src/home/propane_tank/materialiconsoutlined/24px.svg", home_outlined_propane_tank_b64z },
    { "home", OUTLINED, "roller_shades", "src/home/roller_shades/materialiconsoutlined/24px.svg", home_outlined_roller_shades_b64z },
    { "home", OUTLINED, "roller_shades_closed", "src/home/roller_shades_closed/materialiconsoutlined/24px.svg", home_outlined_roller_shades_closed_b64z },
    { "home", OUTLINED, "sensor_door", "src/home/sensor_door/materialiconsoutlined/24px.svg", home_outlined_sensor_door_b64z },
    { "home", OUTLINED, "sensor_occupied", "src/home/sensor_occupied/materialiconsoutlined/24px.svg", home_outlined_sensor_occupied_b64z },
    { "home", OUTLINED, "sensor_window", "src/home/sensor_window/materialiconsoutlined/24px.svg", home_outlined_sensor_window_b64z },
    { "home", OUTLINED, "shield_moon", "src/home/shield_moon/materialiconsoutlined/24px.svg", home_outlined_shield_moon_b64z },
    { "home", OUTLINED, "solar_power", "src/home/solar_power/materialiconsoutlined/24px.svg", home_outlined_solar_power_b64z },
    { "home", OUTLINED, "vertical_shades", "src/home/vertical_shades/materialiconsoutlined/24px.svg", home_outlined_vertical_shades_b64z },
    { "home", OUTLINED, "vertical_shades_closed", "src/home/vertical_shades_closed/materialiconsoutlined/24px.svg", home_outlined_vertical_shades_closed_b64z },
    { "home", OUTLINED, "wind_power", "src/home/wind_power/materialiconsoutlined/24px.svg", home_outlined_wind_power_b64z },
    { "home", ROUNDED, "auto_mode", "src/home/auto_mode/materialiconsround/24px.svg", home_rounded_auto_mode_b64z },
    { "home", ROUNDED, "blinds", "src/home/blinds/materialiconsround/24px.svg", home_rounded_blinds_b64z },
    { "home", ROUNDED, "blinds_closed", "src/home/blinds_closed/materialiconsround/24px.svg", home_rounded_blinds_closed_b64z },
    { "home", ROUNDED, "broadcast_on_home", "src/home/broadcast_on_home/materialiconsround/24px.svg", home_rounded_broadcast_on_home_b64z },
    { "home", ROUNDED, "broadcast_on_personal", "src/home/broadcast_on_personal/materialiconsround/24px.svg", home_rounded_broadcast_on_personal_b64z },
    { "home", ROUNDED, "curtains", "src/home/curtains/materialiconsround/24px.svg", home_rounded_curtains_b64z },
    { "home", ROUNDED, "curtains_closed", "src/home/curtains_closed/materialiconsround/24px.svg", home_rounded_curtains_closed_b64z },
    { "home", ROUNDED, "electric_bolt", "src/home/electric_bolt/materialiconsround/24px.svg", home_rounded_electric_bolt_b64z },
    { "home", ROUNDED, "electric_meter", "src/home/electric_meter/materialiconsround/24px.svg", home_rounded_electric_meter_b64z },
    { "home", ROUNDED, "energy_savings_leaf", "src/home/energy_savings_leaf/materialiconsround/24px.svg", home_rounded_energy_savings_leaf_b64z },
    { "home", ROUNDED, "gas_meter", "src/home/gas_meter/materialiconsround/24px.svg", home_rounded_gas_meter_b64z },
    { "home", ROUNDED, "heat_pump", "src/home/heat_pump/materialiconsround/24px.svg", home_rounded_heat_pump_b64z },
    { "home", ROUNDED, "mode_fan_off", "src/home/mode_fan_off/materialiconsround/24px.svg", home_rounded_mode_fan_off_b64z },
    { "home", ROUNDED, "nest_cam_wired_stand", "src/home/nest_cam_wired_stand/materialiconsround/24px.svg", home_rounded_nest_cam_wired_stand_b64z },
    { "home", ROUNDED, "oil_barrel", "src/home/oil_barrel/materialiconsround/24px.svg", home_rounded_oil_barrel_b64z },
    { "home", ROUNDED, "propane", "src/home/propane/materialiconsround/24px.svg", home_rounded_propane_b64z },
    { "home", ROUNDED, "propane_tank", "src/home/propane_tank/materialiconsround/24px.svg", home_rounded_propane_tank_b64z },
    { "home", ROUNDED, "roller_shades", "src/home/roller_shades/materialiconsround/24px.svg", home_rounded_roller_shades_b64z },
    { "home", ROUNDED, "roller_shades_closed", "src/home/roller_shades_closed/materialiconsround/24px.svg", home_rounded_roller_shades_closed_b64z },
    { "home", ROUNDED, "sensor_door", "src/home/sensor_door/materialiconsround/24px.svg", home_rounded_sensor_door_b64z },
    { "home", ROUNDED, "sensor_occupied", "src/home/sensor_occupied/materialiconsround/24px.svg", home_rounded_sensor_occupied_b64z },
    { "home", ROUNDED, "sensor_window", "src/home/sensor_window/materialiconsround/24px.svg", home_rounded_sensor_window_b64z },
    { "home", ROUNDED, "shield_moon", "src/home/shield_moon/materialiconsround/24px.svg", home_rounded_shield_moon_b64z },
    { "home", ROUNDED, "solar_power", "src/home/solar_power/materialiconsround/24px.svg", home_rounded_solar_power_b64z },
    { "home", ROUNDED, "vertical_shades", "src/home/vertical_shades/materialiconsround/24px.svg", home_rounded_vertical_shades_b64z },
    { "home", ROUNDED, "vertical_shades_closed", "src/home/vertical_shades_closed/materialiconsround/24px.svg", home_rounded_vertical_shades_closed_b64z },
    { "home", ROUNDED, "wind_power", "src/home/wind_power/materialiconsround/24px.svg", home_rounded_wind_power_b64z },
    { "home", SHARP, "auto_mode", "src/home/auto_mode/materialiconssharp/24px.svg", home_sharp_auto_mode_b64z },
    { "home", SHARP, "blinds", "src/home/blinds/materialiconssharp/24px.svg", home_sharp_blinds_b64z },
    { "home", SHARP, "blinds_closed", "src/home/blinds_closed/materialiconssharp/24px.svg", home_sharp_blinds_closed_b64z },
    { "home", SHARP, "broadcast_on_home", "src/home/broadcast_on_home/materialiconssharp/24px.svg", home_sharp_broadcast_on_home_b64z },
    { "home", SHARP, "broadcast_on_personal", "src/home/broadcast_on_personal/materialiconssharp/24px.svg", home_sharp_broadcast_on_personal_b64z },
    { "home", SHARP, "curtains", "src/home/curtains/materialiconssharp/24px.svg", home_sharp_curtains_b64z },
    { "home", SHARP, "curtains_closed", "src/home/curtains_closed/materialiconssharp/24px.svg", home_sharp_curtains_closed_b64z },
    { "home", SHARP, "electric_bolt", "src/home/electric_bolt/materialiconssharp/24px.svg", home_sharp_electric_bolt_b64z },
    { "home", SHARP, "electric_meter", "src/home/electric_meter/materialiconssharp/24px.svg", home_sharp_electric_meter_b64z },
    { "home", SHARP, "energy_savings_leaf", "src/home/energy_savings_leaf/materialiconssharp/24px.svg", home_sharp_energy_savings_leaf_b64z },
    { "home", SHARP, "gas_meter", "src/home/gas_meter/materialiconssharp/24px.svg", home_sharp_gas_meter_b64z },
    { "home", SHARP, "heat_pump", "src/home/heat_pump/materialiconssharp/24px.svg", home_sharp_heat_pump_b64z },
    { "home", SHARP, "mode_fan_off", "src/home/mode_fan_off/materialiconssharp/24px.svg", home_sharp_mode_fan_off_b64z },
    { "home", SHARP, "nest_cam_wired_stand", "src/home/nest_cam_wired_stand/materialiconssharp/24px.svg", home_sharp_nest_cam_wired_stand_b64z },
    { "home", SHARP, "oil_barrel", "src/home/oil_barrel/materialiconssharp/24px.svg", home_sharp_oil_barrel_b64z },
    { "home", SHARP, "propane", "src/home/propane/materialiconssharp/24px.svg", home_sharp_propane_b64z },
    { "home", SHARP, "propane_tank", "src/home/propane_tank/materialiconssharp/24px.svg", home_sharp_propane_tank_b64z },
    { "home", SHARP, "roller_shades", "src/home/roller_shades/materialiconssharp/24px.svg", home_sharp_roller_shades_b64z },
    { "home", SHARP, "roller_shades_closed", "src/home/roller_shades_closed/materialiconssharp/24px.svg", home_sharp_roller_shades_closed_b64z },
    { "home", SHARP, "sensor_door", "src/home/sensor_door/materialiconssharp/24px.svg", home_sharp_sensor_door_b64z },
    { "home", SHARP, "sensor_occupied", "src/home/sensor_occupied/materialiconssharp/24px.svg", home_sharp_sensor_occupied_b64z },
    { "home", SHARP, "sensor_window", "src/home/sensor_window/materialiconssharp/24px.svg", home_sharp_sensor_window_b64z },
    { "home", SHARP, "shield_moon", "src/home/shield_moon/materialiconssharp/24px.svg", home_sharp_shield_moon_b64z },
    { "home", SHARP, "solar_power", "src/home/solar_power/materialiconssharp/24px.svg", home_sharp_solar_power_b64z },
    { "home", SHARP, "vertical_shades", "src/home/vertical_shades/materialiconssharp/24px.svg", home_sharp_vertical_shades_b64z },
    { "home", SHARP, "vertical_shades_closed", "src/home/vertical_shades_closed/materialiconssharp/24px.svg", home_sharp_vertical_shades_closed_b64z },
    { "home", SHARP, "wind_power", "src/home/wind_power/materialiconssharp/24px.svg", home_sharp_wind_power_b64z },
};

static const int kIconCount = (int)(sizeof(kIcons) / sizeof(kIcons[0]));

} // namespace home

#endif // UPP_MATERIAL_SYMBOLS_ICONS_HOME_H
