// Auto-generated by Material Symbols SVG Extractor (v0.9)
// FORMAT: KICONS_V1_NO_DECODERS
// Category: file
// Location: E:/apps/3rdParty/material-design-icons/src/file/
// Each icon is Base64(zlib(minified-SVG)). Decode with ZDecompress(Base64Decode(...)).

#ifndef UPP_MATERIAL_SYMBOLS_ICONS_FILE_H
#define UPP_MATERIAL_SYMBOLS_ICONS_FILE_H

#include <Core/Core.h>
#include <plugin/z/z.h>

namespace file {

using namespace Upp;

enum Style : uint8 { OUTLINED = 0, ROUNDED = 1, SHARP = 2 };

struct BaseSVGIcon {
    const char* category;
    Style       style;
    const char* name;
    const char* source;
    const char* b64zIcon;
};

// approval [outlined]  source: src/file/approval/materialiconsoutlined/24px.svg
static const char file_outlined_approval_b64z[] =
    "eJxVkE1vgzAMhv9KxNkJ5GMBJuAwLj20190pTRM0BhVkpOqvn8M2bZPtyLGf11ZSrZsl9/dxWuvEeX97"
    "TtMQAguSzYtNRZZlKRIJMVN3Hg09d/2bXeaP6VInkwkkQxMKPSHODNb5Oon5NpjwMt/r5E8/DBfv9nZT"
    "2aZaTO/JdRhHHDRP5r/+l02bKrW7AP3WeUdw80kB15t2eFDdZ5QzTjNWUhHtoFvFSuAKkIpZhB/kxAvg"
    "xQEVwnHxyotYEiDakgkFAnJQMckhH59i0Jy0/LuIY3KNTOS/ZJwfS8j31VoDZ1JRCZLKVe4XwMtxxx4/"
    "L9gDv7L5BMc3YKc=";

// attach_email [outlined]  source: src/file/attach_email/materialiconsoutlined/24px.svg
static const char file_outlined_attach_email_b64z[] =
    "eJxVUcFygyAQ/RXGMyC7YKod9dBeckhOnck9MVScUs1EK5l8fReTpu0sDA9233sLlOPcssun78cqcdN0"
    "ek7TEIIMWg7nNkWlVEoVCbP9/uCtOOybj/Y8fPXHKultYIoCDY2EOdu1bqqSiOfOhpfhUiV/8qE7Tm5J"
    "12Vbl2fbTOy9856Eht7+5//WpnWZtguBxmk/OUbOW81XPueZz0U2a4c70ygBEoSShcAYa/0KsuDIQSrg"
    "SHABZgMcVo2iHXC1FFA4UHOk7FZXtoWCGy9IfKO5WUNxjS08jJH4ZjY3BbEoCFIYyfPuPQsjM2pHSczJ"
    "AmMiI5DFdbxhRH4/3EHuHhSQOo/XIBUqv0/2BhkHpFMegV445I8y9iKfqN0YoxG3jTAkt0a4/jzdMukP"
    "62/bp3tZ";

// attachment [outlined]  source: src/file/attachment/materialiconsoutlined/24px.svg
static const char file_outlined_attachment_b64z[] =
    "eJxNUMFugzAM/RUr95g4JBSq0sNOXHaa1PtEGUFiUC2IVP362dBNPbz4ObafX3KKaw/373GKtQrLcjtm"
    "WUoJU47zT59ZY0zGHQpCN/RhqZV1CtahS2/zvVYGDFgHcpeG6xK28vl0+1wCXGv1zvVg3WpdYy7moeBr"
    "GMdaTfPUqeyljUr0QEVzaLVFS2C004SHioOLOwGmgSz6ljAvZa2MINmNMD6swbIEyoEqKeVN1Wr0nsVI"
    "o/N8UtwiMAvcc2FI0y6o/wT1UzC+qgsCGV6/G4TdoLiK/1a1kxfkaBzL+W3IFRthREngmQgCEXug4iFf"
    "IX98/gU29l1k";

// cloud [outlined]  source: src/file/cloud/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_b64z[] =
    "eJxNkU1vwyAMhv+KxR0HsDFhanpYL73suvuUdU2k9ENr1FT99bOzHSYUbMzL6weyud2P8DhN51vnhnm+"
    "vjTNsiy4EF6+j00KITSqcDAcxuMwdy6xg/t4WF4vj84FCJAYrLaMn/Owbm831495gM/Oven+kPieeB/e"
    "w9PB1zhNnTtfzgfX/JPFBNInlKR2jG0LEVuBjFR1yTQhaSXbRxhjr1EwQsJiSv7LElbR8xEl+4iUgTwB"
    "7aX3CVOE4FnLpWpgXSQMv4aesAiQWmpWyxQxFK9dMHuseddiaKFgZKhYGQSM9aTnd1VFoBU0UmHDzaBy"
    "fQ4k1oxWnIA1WuQ+aBcyWKnqo2OIpLcuJssGqR4+r2zCK6BnvZhOYlmVXWxRinbMFeLakw2Hn/aY9pe2"
    "P7BkZ1o=";

// cloud_circle [outlined]  source: src/file/cloud_circle/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_circle_b64z[] =
    "eJxNUk1rwzAM/SvCdyuW/BF7ND1sl156Kuw+sq4ppB8soSn59ZOSMQax9KQnnp8db4bHCZ6X/jo0phvH"
    "+0tVTdOEk8fb96li51wlEwa64/nUjY3hYOBxPk6vt2djHDjgANqbzp9jt9Dbzf1j7OCzMXvhOw4PDjv3"
    "7mYDX+e+b8z1dj2a6t8YMfBbwpBBAPwC4iEoIvf32d+GJXegGiMvY8DzRdjcKk3gbLYeY5GUhxVA1gVa"
    "gBYr0N58CcjFFszUWgyW0ZEESjrDdiEXRJiKSHukiEXZLB7RJ7HtExRkgijOsNbEGDWJHS+niTVQgiw9"
    "Sp24zq2Ikd4cFhX2tCINsgVhDBK0rosGNZTLvBcRCjvREafZr5MWU71kWYdaCiBat6IOS4+hCONiKxdj"
    "RQ5EV7dkNU+0IkLyixsiXA7lpVWoX7nAO0otxigjBBhEGmiwC7ACZ/2T+kS2P2SZgXA=";

// cloud_done [outlined]  source: src/file/cloud_done/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_done_b64z[] =
    "eJxNkbtuwzAMRX+F0C5alChKKuIMzZKhXbsXaRoHcB5ojDjI15c0OhQGLimRvDi0Vrf7AR6n8Xzr3TBN"
    "15eum+cZ54SXn0MXQwiddjgY9sfDMPUusoP7cT+/Xh69CxAgMtjdfPyahqW8Xl0/pwG+eveu9SHyPfI2"
    "fISng+/jOPbufDnvXfevjRqmDBQw8IYqSgHB3IAyCgMDRZWGRBoEBZbrbCNVJyBiYs2SKIx6NLLIuwAJ"
    "E2lVGoh9A6VdxGJt2UdU7uwzBE2FVUL2jKWqiGVNnsoFVLeys2519ewJS9PAy1hQZszJJzNNmEWzVkbC"
    "ULzSYvbY8kYZKxQkW6HpAraOKIhEBWGsVU2qLZWaHjmNmMx2sVaXnUZB26NYJ/9lUQFtT4Ml+xWKAel5"
    "8k0hahwNry3yJmaWTLS/jIKB/CLmtsjTXsOeef0LQiB0xg==";

// cloud_download [outlined]  source: src/file/cloud_download/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_download_b64z[] =
    "eJxNkbluwzAMhl+F0C5aFympiDM0S5au3QsnjQ04BxrDDvz0JY0OhQGS4vHjI717zhd4XcfbszX9ND3e"
    "mmZZFlwi3n8uTXDONdJhoD8Pl35qTUgG5uG8vN9frXHgICTQ3DKcpn4r73ePr6mHU2s+pN6HNId0dJ9u"
    "NfA9jGNrbvfb2TT/2nzFSOAdunTwBTkDI1XwhJwggQ9iKnovjpFhS5OOFJmAgDFJFFlgRKN69alzEDF6"
    "qXIF1q/3sQuYtY1sQOEmS+Ak5CTGkU2YixjWqPIqXODLkTvtFlWbrMdcxaVtzAkzUrRRRSMSS1Tz6NFl"
    "K7RIFisdhLFARq8rVFlA12EB4SAgCUsRkaJLxSrPFEeMKrtJi0onnlH3yNqZ/qIggLqnwno9hWBAXK+W"
    "kMiWXvDqHI9l1AMKsCaIVj27/s/9LxyEcPQ=";

// cloud_off [outlined]  source: src/file/cloud_off/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_off_b64z[] =
    "eJxNUU1PwzAM/StW7nUT5xutHNhlB3bljspYJpUNsWpF+/U8FwmhqvZT/D4cZXO9Hen7YzpfB9Pm+fOh"
    "75dl4cXz5evYi7W2B8NQO5yObR6MBEO302F5unwPxpIlCaRny+ltbuv4cfP5Ojd6G8we8ybhJmFnX+zd"
    "0PtpmgZzvpwPpv9Hg4WLo+2EU0CxsQucC0pSVNPWFU6ZEscKIkgEgVAYO8fekwpjZp86DwXXPDkOYKJs"
    "neXooHSZnGPxlFSZRs82YPnIkYRDWgH+G8edq6PjlDD18PABDRnEtXYcCo5KRK44FWqS0yQHjQWhihKw"
    "kOQVeC7uvg/KAkzPHimSJ+GcSUuDp2xFYwpugBxsXJ32MGID9pqTKvbG13CH7CchWTM7Lc9/5vc9LldG"
    "DYdBFzDOFS1cfwEBttWgUNmlu76BPu7jDz0BdOs=";

// cloud_queue [outlined]  source: src/file/cloud_queue/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_queue_b64z[] =
    "eJxNkE1vwyAMhv+KxR0HgzFhanpYL7nsuvuUdiVS11ZLlFT99TPpZULYj/z5wm5azvD4uVynzpR5vr81"
    "zbquuAa8/Z4b75xrtMJAOY3nMnfGs4FlPK3vt0dnHDjwDDW2jse5bOn97v41Fzh25kPzxfPiuXef7mng"
    "e7xcOnO9XU+m+VdGGUMEcuj4QC1KAsGYgSIKAwN5NRmJ1AkKbOFYW1rtAI+BlYKoGJ2RqXoeHAQMpFnJ"
    "IPUUCoPHVMui9ai6o43gFIXVuGgZU6tGKmV5qi6gtpehVutUy5YwZXU8vQAUCyY6JAwJUl2VkVvdpppl"
    "CFWebsOoMlg20Ltg7CkPhFK1BKD6gABhsi+yys/6QfXn93/E+l/J";

// cloud_sync [outlined]  source: src/file/cloud_sync/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_sync_b64z[] =
    "eJxVUk1zm0AM/Ss7nIXY74WO7UO49NCeOuO7Qwh4SuyMTSGTX9+npU3agV0J9CQ9vd3dfRnU28t0ue+L"
    "cZ5fv1TVuq68Or7ehspqrSsgCtVfTo9TXz6eup/D7frr8rQvLv2qNB7r8RZq7M/DOO8L8Zdzvz5c3/bF"
    "P/H1/DSPOXzYDYfdre9m9XyeJhS6Xvr/8z+x1WFXDTkB7+tpHhU6f7eGAxnPTd2VmrUlLcZtJhA20wJj"
    "yTh2ZBpOkQy+auxdadgDaTkCWLvSsYlkUaUF2kapazI6ACc2qU6T4YgQO09OnilyyK07/KtJo0BAYcDF"
    "wfphLdf1RpI++b6rTB4N6m8fjkEwTxLAvTRwPIqVRt03j+CPGCcsCNnQyZhNAvtUo2dCNrbs3fOnBOgj"
    "cDQJ/PX2IxsM3qGQ0EZPLGv/OEG1VibmlIS0lNnYC09wN5o8NFogV9MmjokSAxGpYdeQiJylShs5cqKX"
    "RYr3R+NHu8SvfintaDk51QbWyICQnryok41tPdVsE0VRI7BoszUV6TTFsZRsyO5xsnJelr1BJ23g4YzC"
    "VNp8JVSLOWINatFLG5xDDTnhgnSIR6NR6ujHeIzvf+9ZXrjwh9/7T7UV";

// cloud_upload [outlined]  source: src/file/cloud_upload/materialiconsoutlined/24px.svg
static const char file_outlined_cloud_upload_b64z[] =
    "eJxNkcFuwjAMhl/Fyj1uEidOMlEO48KF6+5TYbRSB2hULerTz652mCrZTvz71+d095yv8Poeb8/W9NP0"
    "eGuaZVlwIbz/XJvgnGtEYaC/DNd+ak2IBubhsrzfX61x4CBE0LtlOE/91t7vHp9TD+fWnKTfhziHeHQf"
    "bjXwNYxja27328U0/2S+IiXwDl08+IKcgTFV8Ak5QgQfJFT0XhIjw3addKTIBASkKBWxwIhH9Zpj54CQ"
    "vHS5AuvXe+oCZpUlG1C4k03gpOQowSUbMRcJrFXlVbjAlyN3qhZXG63HXCXFbcwJMyaypKaEiaWqefTo"
    "shVaTBZrOghjgYxeV6iygK7DAsJBQCKWIiZFl6Iqx0gjktpu1uLSSWbUPbIq418VBFD3VFivTyEYQOtJ"
    "NNQHTGnWVGdLR8+jIq/65Pov979iF3Bh";

// create_new_folder [outlined]  source: src/file/create_new_folder/materialiconsoutlined/24px.svg
static const char file_outlined_create_new_folder_b64z[] =
    "eJxNUEFqxDAM/IrwXbasummybPbQUw7tNfeSTaOAkyxdYy95fe20hSI0gpnRIHS+xwkei1/vrZIQbidj"
    "Uko6PentazJMRCY7FMg4TxJaxU5BnMf0uj1aRUDADgqX5muQQ76cbx9B4Nqq96wLu8iuo552BZ+z961a"
    "t3VU5p+NCSrB2iMjd25Aq60FyqNpdN0cE/iNwdYDQREzC1xKbDX8uIHxYJH77DoiClEikfcl7+XovpJn"
    "bV983uyYoqV9wRqdcOTc+Av4hwX2cml5weUbqENN5g==";

// difference [outlined]  source: src/file/difference/materialiconsoutlined/24px.svg
static const char file_outlined_difference_b64z[] =
    "eJxVUE1zgyAQ/SuMZ0QWDGhHPbQXD8mVuzFEnFrNGCuZ/PoudDptB/Zj9r19u1Dd94E8Pqb5Xidu224v"
    "Wea9Z16yZR0ywTnPkJEQO3fnyabnrn8f1uVzvtTJbD3heESONyHOjoPb6iTk+2j96/Kokz+4Hy+bi3BT"
    "DU212n4j13GaUGiZ7f/+X27WVNkQG27d5giOPUFBhWzzPgUGlKci5axEL4x2YofcQW6EfJIT5OxAtTm4"
    "VOzi20UzJZpuAxxYClkgXaoQUwZiJ1bagrwpVlKginGggGlM5FFR0D2ncTorSioCiKGFso9FGleicaVj"
    "0AqSqKTbwkinGGC1pJoV0oB+/jwx/HPzBTniaUg=";

// download [outlined]  source: src/file/download/materialiconsoutlined/24px.svg
static const char file_outlined_download_b64z[] =
    "eJxNjrsOgzAMRX/F8g6JQ3hVDUOnDO3KXgmKkSigEiWIr2/oVHm58jmy73XzA+zvad4MsnPrRYgQQhqy"
    "dPkMQkkpRTQQuB8HdgaVRvBjH27LblCCBKXh3IWxc/zDzXV9OobO4CNyVtorbWUrD4TXOE0G52XuUfxp"
    "VEPNiW4zW/vC5lMJcZLyeCcVqDZn5QumlMo7KaAsBqjTKgMiSxSlAkqm+MXmx3n27Nt8AYcKO7o=";

// download_done [outlined]  source: src/file/download_done/materialiconsoutlined/24px.svg
static const char file_outlined_download_done_b64z[] =
    "eJxNjrsOgzAQBH/ldL3P5jAQIkyRioK06SOFYEvmoWBhxNcHUqXYZna02mpZe9gGPy4GbQjzVcoYI8WU"
    "pk8vWSklDwPBdq63wSBrhNV18TZtBhUoYA0ni+4V7K+uq/kZLLwM3o/esl5ZN+qhdoS3897gOI0dyj8t"
    "g+Rik8NrslXwPmjKBVPRHlxR4VkkVAJTfqZNCtCegUVJGkpK93Pq/Fh/AbQCN6Y=";

// download_for_offline [outlined]  source: src/file/download_for_offline/materialiconsoutlined/24px.svg
static const char file_outlined_download_for_offline_b64z[] =
    "eJxVUMFygyAQ/RXGMwhLiJiOemgvPdhTZnI3hohTqxmlksnXdyHppB2W5S3v7duBYlk7cv0axqVMrHOX"
    "F86996nfpNPccSmE4KhIiBmb42DYsWk/u3n6Hk9lMhpPBC6pMBJiTd9ZVyYBr73xr9O1TP7wvj85G+mq"
    "6KpiNq0j534Y0Ggazf/+p5ZXBe9iA8alcZbg5A+QVL5lqdpRBPQBQC4qIBD3WECwxwUDsQedbiHKqLyR"
    "aCHaIAAqWM426XaHR77cAQ0wp6GgWJA9ZEEpRewXwUBFDlMNGc4YmKIKE1MDoJSFVAMgk4I+ZFauCkH9"
    "bAsemoJ+1yuTFsQB9O33vXHjx1c/+lpqew==";

// downloading [outlined]  source: src/file/downloading/materialiconsoutlined/24px.svg
static const char file_outlined_downloading_b64z[] =
    "eJxVkk1TgzAQhv9KhnOyZPMBjdP2INd6csZ7rQgdI3VaLI6/3jfB2jrAsmx2n32TZXk6d+LrPQ6nVdGP"
    "48ddWU7TRJOlw7Erjda6REYh2mH7HFv1vN29dcfD5/CyKoZ2EhqXcbgL0bf7rh9XRfLP+3a6P3ytipv1"
    "af8y9nl5vezWy2O7G8XrPkaADkP7v/6aW66XZZcLcH9sx16g8wMvyBrpyFQNV7Rw0pL2kj1ploYMXIu3"
    "9mcYs2NyldTEC8TqAK+uUBAkU2U2V9S3eOBAwUrmPtWJndJkFFxWrCzawDesPApyGcuauEEN13KBFQm3"
    "9jKQd/JCStCcCp0hQgmCMNAEErykSSc6RPzRRZ+6mmbmsUv65zbYInZwJSa8nZvNe800yJZZL8uEy7Jj"
    "6mazEc0vZkZe8HU+tsxKWE8eKRp2k8IWuU81hJ0reBFMH7LZAGGilz565Tc3ZQnCN9pwnhiQhzqvgnKY"
    "Al5Y9ScMAyFyOLscyOlNnWbqyFfS4aADhoRGjzkKqMPXL/378pfkB7/r+gdrd6ig";

// drive_file_move [outlined]  source: src/file/drive_file_move/materialiconsoutlined/24px.svg
static const char file_outlined_drive_file_move_b64z[] =
    "eJxVkMFugzAMhl8l4uyE2E0pTMBhvXBgV+6UpgQtg4oyUvXpl6BW2+TIcX5//qMkv609u3/Z8VZEZlmu"
    "b3HsnBNuJ6a5j0lKGXsiYnpsT1bzU9t99vP0PZ6LaNSOSR+k/IqY0UNvliIK9Tpo9z7di+hP3w3nxWzt"
    "Mu/LfNbdwi6Dtd5oGvX/+V82LvO43wau7WKYv/aDJCSGp5YTp0odSWSggED5nSBZkToJKBDkJvgwmHSb"
    "AMQ3kVOTHsnD4RA6CQTTBwvemFaqScxe4MGiUAghsRo9d4C0Itlg6kkkgQkgVelKRvnachT7DEIKcObL"
    "Qx2QnZD4VLIAPS3rl8Pj9cjw0+UPPxFmvg==";

// drive_file_move_rtl [outlined]  source: src/file/drive_file_move_rtl/materialiconsoutlined/24px.svg
static const char file_outlined_drive_file_move_rtl_b64z[] =
    "eJxVUM1ygyAQfhXGMyC7ojUd9dBcPNir98QQcUo1Y6hk8vRdvDSdhQW+Pwaq+zayx7eb73Vivb+9p2kI"
    "QYZMLuuYolIqJUXCzHw6OyPOp+FrXJef+VInswlMUaGmkTBrptH6Oon7bTLhY3nUyQsfpou3O91Uqxk8"
    "u07OUcoym//mP2HaVLeTt4wu+0TFCytKJ1Bgq48oD1xz5JpW5MUGOCgOErjaASoLxbADHMUOCuzLI5I4"
    "HiJT8Bj6ZDEbylb3hc0lvDkyt6h6KImCTGrgkMv80AFyYoUW2sUJO0OtA5BlxgFbKDa0QlNI92J8xofE"
    "b2x+AW6WXt4=";

// drive_file_rename_outline [outlined]  source: src/file/drive_file_rename_outline/materialiconsoutlined/24px.svg
static const char file_outlined_drive_file_rename_outline_b64z[] =
    "eJxVUU1vwyAM/SsoZ0IwgXxMSQ7bZYf0unubMRKNQdSy0vXXz0SrugrzbOT3bAPd6WzI5cu6U5/NIaxP"
    "RRFjZLFk/mgKwTkvkJER7fYHq/PDfvo0R//t3vvM6Ug4LiHRMjLrxcyhz1J8XnR89pc++5ePy3uYt/TQ"
    "maE76imQj8VaLOSdftTfucXQFWYToK3e/hjvyOoXF3BgUBQqAkAFdrkhVEm07sNMcMgdCMYrWjNoxxJz"
    "TKg3weeS1cq2mMkTjHfSlewUawWF5lWdc46hrRMtgU1HmmD841wfWzWsBtowLifOyjZPQLcIGEchOgk2"
    "F6yUG7zgOFBTyXhLYasok68qKicUC4USzhRgDcCgRi9ai1UavAkCsekaNMF47329vdm28fOGX8emel8=";

// drive_folder_upload [outlined]  source: src/file/drive_folder_upload/materialiconsoutlined/24px.svg
static const char file_outlined_drive_folder_upload_b64z[] =
    "eJxVUMFugzAM/ZWIsxNiN03DBBzWSw/syr2lGUHLoKKsqfr1S9CmbrJlPfvZz07K661n908/XqvMLcvl"
    "Jc9DCCJsxDT3OUkp89iRMTseT97y07H76OfpazxX2WgDk9FIRc+Ys0PvlipL+DbY8Drdq+wPH4bz4la6"
    "Lvu6nG23sPfB+yg0jfb//LM3r8u8Xwcux8WxuPaNJGjHjefE6aD2JApQQEIiqAhXoBsCNJ0EFAgyVZM5"
    "1N1aAOJrkVNr9kSgU5IYDUn8wdIONI2KodVuK3DHfBQ4kGzRRLoQCgGVUNRgBCSManHn6MaVQO1RbAtI"
    "oUENuIkXNbjeVTTmJ38qPH7fmD66/gaXLGYw";

// file_download [outlined]  source: src/file/file_download/materialiconsoutlined/24px.svg
static const char file_outlined_file_download_b64z[] =
    "eJxVkM1uwyAQhF8FceZvwW7syvahpxyca++OQ8EKxZFDIcrTFyNVbbUIjWa/2UV092jQ49P5e49tCLdX"
    "zlNKLCm2boZLIQTPBEbaT2en6Xmar2Zbv/ylx14nJHLJKh+MrF6MDT3edVx0elsfPf7TT8sl2NIeOjN0"
    "m54D+licy4NWr//nf1k+dNyUwG0KFuW1J2gI1FEdXyJVxyqqWRBgQARridzLgpyLQSQtJpU7Cc0TneBA"
    "ABwFVkG5RlAEJIPDe2Uz1mQ1NtknLavbscA1qdFYcs+f1+xfMnwDJ2VU+g==";

// file_download_done [outlined]  source: src/file/file_download_done/materialiconsoutlined/24px.svg
static const char file_outlined_file_download_done_b64z[] =
    "eJxVkNtuwjAMhl/FynXmnBpop7YXexMOWRotJFXJCLz9TLUxkG3J1u/DJ/fni4frKabzwKZS5nchaq1Y"
    "DebFCy2lFNTBwKXdPrq3/e7w5Zf8nY4DS66CJNMNOYPJBT+Vgd3zS3D1I18H9qTXcCzTKo+9H/vFHQp8"
    "hhhpUU7udf6/V4y98OsA+ZzjzecEcw6pELCWqAy32ChQLW41b6BDa7gyqDqwqFveYmfBYLvlSqLZ/Oob"
    "lPq+eoV4HH7cVYRA8JbBjYr2D2IN+sb4AxVuVfk=";

// file_download_off [outlined]  source: src/file/file_download_off/materialiconsoutlined/24px.svg
static const char file_outlined_file_download_off_b64z[] =
    "eJxVUU1vwyAM/SuIMyGYkK8pyWGnHuh19zRlISpLqjQLVX/9DNrUTkYPy37v2YLmto/k/uXmW0vttl3f"
    "0tR7z33Gl3VMpRAiRQYlZu5PziSnfriM6/I9n1s6G08EhlR4KLFmGu3W0pDvk/Hvy72lL30/nTcb212z"
    "mmEjn5Nz6LLM5r/4SUy75tpvluCwI1QMcg7lB+RW7hIz/Vd6kCPeChhIntcaSgbgEsBKBA0KC1HwZAVN"
    "xkAER2UTuatI+C1hV6KiZhGDV1lF0JJXwAJo4FnNFJfSFYEZQMfJOcudwBGJiNuEDRlUh2JPsoPas0Ew"
    "NGWCo3sIG3dzkhfBuACiX0Y/whuEH+h+ALIta20=";

// file_open [outlined]  source: src/file/file_open/materialiconsoutlined/24px.svg
static const char file_outlined_file_open_b64z[] =
    "eJxVUMluwyAQ/RXEmXVq01DZPvTkQ3PN3XEoWKF25FCI8vUdp6raitHTMG9hRHPNntw+4nxtaUjp8iJl"
    "KUWUJ7GsXoJSSqKCEjcPx+j4cRjPfl0+51NLZ1eIwgMVFiXBTT6klm59nlx5XW4t/cOX6ZTCg+4a3zWr"
    "GxN5n2LEoGV2//2/Wtk10j8MlyEFgs/udc0AejNyLTRTHLgSFhEO1ai+Z9ud4STsomEmm4CkDbw+VL3J"
    "2gR7ALiTvbYMtDAmYoiAKoKwGI0Qtag03+ANFCLTOxI2SebQ6+dco6nX9v6z3fZF3ReY5VlH";

// file_upload [outlined]  source: src/file/file_upload/materialiconsoutlined/24px.svg
static const char file_outlined_file_upload_b64z[] =
    "eJxVUE1vwyAM/SuIM1+G0KZTksNOPaTX3tOUQVRGqpSFqr9+EGnaJlvW0/N7tuXmsVr0/PTh0WIX4/2N"
    "85QSS4rNi+VSCMGzAiMThos39DKMN7vMX+Ha4mASEjlklRMjZybrYosLXieT3udni//003SNbmt3je2a"
    "xYwRfUze50FzMP/9v1reNdxuhvsQHcprT1AT0Ks67laqjtWqRkGAARHsQGQJB3LcCCLpRlJZlFC/0GlP"
    "Dh5YBaSUHoDsWa3OsHPyXJCXTGcD03UPRUo11X0Gr587yjO6b0B6VAY=";

// folder [outlined]  source: src/file/folder/materialiconsoutlined/24px.svg
static const char file_outlined_folder_b64z[] =
    "eJxNT01vgzAM/SuW70kcL2OlIj30xGG9cp8ow0gpVCMiqL++CafpSX56H5bsZt1G2B9hXj1KjM+zMSkl"
    "nT708jcaJiKTGwgyTKNEj+wQtmlI12X3SEDADoqXpnuUI740z58ocPd4y7mw29i11NEL4XcKweO8zAOa"
    "f7Va2y+oAgO3TJul1nWVfGbzZglc63pltQXKs651fRDwN4M99QQ50lkWiK36owmsiqe4y42ynKXiAlGn"
    "UPhVDiifXd4/FUJ4";

// folder_copy [outlined]  source: src/file/folder_copy/materialiconsoutlined/24px.svg
static const char file_outlined_folder_copy_b64z[] =
    "eJxlkM1uhCAUhV+FsEZ+rjrURl10Ni46W/eOQ8GU6sShMpmn78WkaZsGwiU55zuHUN82S+4ffr411IVw"
    "fRYixshjzpfVCpBSCnRQYubh7E12HsZ3uy6f86Whs4lE4oICNyXOTNaFhqb7Npn4stwb+kuP0yW4XW5r"
    "29arGQN5m7zHoGU2f/kfr2hrYXfgOgRHsPaUM1U5pTfo8jFTXDGZQSZ5hSf0Bwe9qh7kBDk7bNUoGTqS"
    "ylBl0Ol/yGvJpWLFcR+AxjKZmWbgSo+I0+QIgEzBMLNIIkZjg2aqdKrAykzzp9ynsE73qnx8vzp9XfsF"
    "w5pddA==";

// folder_delete [outlined]  source: src/file/folder_delete/materialiconsoutlined/24px.svg
static const char file_outlined_folder_delete_b64z[] =
    "eJxVUcFugzAM/ZWIcxJiN6TpBBzWC4ftyr2lKUFjULWMVP36ObBqmxxbtp/9XpTkt7ll989+uBWJn6bL"
    "S5qGEGTYyPHapqiUSmkiYW44HHsnjofmo72OX8OpSAYXmCJDTSdh3nWtn4ok5nPnwut4L5I/eOhOk1/g"
    "Mm/L/OqaiZ27vieicXD/939n0zJP22Xhcpg8I9l3MDLjoOqdFzhDBRRk5mHWjeJK2g0Fs+UQh1b32Kz9"
    "WIgnKshnoT3UoKrI+WA/1BmtEDVhWMeCAFTceGF7gQIrvUdpd1xzlAq4jvmSmTfkYJsoAxCvQv1oHkyz"
    "tjiKtS2wtntEbpZqAQ2PIqsW2ErXxmcStqwnhgpVDfbxfI34JeU3QIZwyw==";

// folder_off [outlined]  source: src/file/folder_off/materialiconsoutlined/24px.svg
static const char file_outlined_folder_off_b64z[] =
    "eJxVkU1vgzAMhv9KxDmYfJHCBBzWCwd67b2lKUFjULWsqfj1s+mmborjvIntx1FS3O4de3wO462M/Dxf"
    "3pIkhABBw3TtEiWESDAjYm48HAcXHw/tR3edvsZTGY0uMIFDGbSIedd3fi4j0vfehffpUUZ/4qE/zX4N"
    "V0VXFVfXzuzcDwOCptH9r3/lJlWRdGsB2uUwe4add0pw6+NsiFWs6g3IzWC4qZW456QlbCwnt1UScsll"
    "BjblSpHQ5in22RZXCznHHMktJ+RC7V5N8BxnI8DmXEMqEZwSOEUwxlLQSAVBytqnsg3BW8EJKohOw0tN"
    "99KgJSeHICNjcs1Pk4XtDBayvYVMNzLFdNzWZvl9gHXiT1Tfzpdt7g==";

// folder_open [outlined]  source: src/file/folder_open/materialiconsoutlined/24px.svg
static const char file_outlined_folder_open_b64z[] =
    "eJxNj00LwjAMhv9KyL1tGsvYxHrw5EGvu8uc62BuoqWV/XrTnSSQkLxPvg6fNMD3Oc0fjyHG196YnLPO"
    "O728B8NEZIRACP04hOiRHUIa+3xavh4JCNhBqeXxHsMmHw+vWwxw93gVPbBL7M7U0orwGKfJ47zMPZo/"
    "jAmqoOpJseKz65TVFkh80+hmC8AXBlt3BCJpSYsFW3UbCaxKTXErRGmWtIxSvD6lQ0a2tcDJygmytvxz"
    "/AGaLkCn";

// folder_shared [outlined]  source: src/file/folder_shared/materialiconsoutlined/24px.svg
static const char file_outlined_folder_shared_b64z[] =
    "eJxdkLFuhDAMhl/Fyu7gmMBBddzQiaFd2SuOEqQAp4KSE09fh0pVVUWK89v/Zyu+bmGE5+yXrVFu3x8v"
    "WRZj1DHX69eYMRFl4lDghml0e6PYKgjTEF/XZ6MICNhCysXpvruzfLs+PnYH90a9S92xDWxb6uhQ8Dl5"
    "36hlXQaV/bExQemw8sjIre3RaAMkd13r+gzAbwym6gmkpEWm40zZn05gTDnkThwJFplaIR+zENKyK12h"
    "zcUL1TIFQ8eMBRb/8O2XQ4b0hBR+hglgwboqoDln5DmyLi9itQm0kIRsIpgjfS3t7PYNvUFV9w==";

// folder_zip [outlined]  source: src/file/folder_zip/materialiconsoutlined/24px.svg
static const char file_outlined_folder_zip_b64z[] =
    "eJxVUMluwyAQ/RXEmXVKqVvZPjSXHJqr745DGKvUjhxqon59wVKUVoPQ4y0zQH1dPbl9henaUIzx8iZl"
    "SkmkJzEvXoJSSmYHJW7qj8HxYz98+mX+nk4NnVwiKheYvChBN3qMDS14HV16n28N/aOn8RRxk9vat/Xi"
    "hkjOYwi50Ty5//mHV7a19Fvg0kckeewBFLPIq8CBw97sQLwyw0AozUyGG7AfwHQ1KKaFZqqwpVDbYSMY"
    "8I3k0FU7AGbLoSiWleY/5KAt0xZh5YC87OSOuwrNqhVy0+mHMXvyVTqLz0K/hDxqr80KObPFMyjm+1vK"
    "h7a//elkrA==";

// format_overline [outlined]  source: src/file/format_overline/materialiconsoutlined/24px.svg
static const char file_outlined_format_overline_b64z[] =
    "eJxVUE1vgzAM/StRzs4XAaVUwGG79NLTpN1bmgU0BhVkpOqvn003bZOT+Nl+70VJtayB3T6Gcal5F+N1"
    "r1RKSSYrpzmoTGutkMGZH0/nwYvzqX0P8/Q5Xmo++sQ0Rpbj4qzzfehizQmvvU9P063mf+apv8RuGzdV"
    "aKrZt5G99cOARtPo/+t/uaqpVNgE11PsGF57NCXYNTsUr/Zgyjs7mgxcK6zcOdDCgZXGYnKthq1HNTiK"
    "xYlHIdwzmhhNhSmI5IBcHmZmJwvWikzmJRrmskCozQZwv5SyMIAHKTAt2AMiAAEimJyU5ALfbvefZ9Bf"
    "Nl9wfF78";

// grid_view [outlined]  source: src/file/grid_view/materialiconsoutlined/24px.svg
static const char file_outlined_grid_view_b64z[] =
    "eJxVkEEPgiAYhv8K46wiYZs25NDJi1fvVgQuA2cErl/fp5XVgA32PO8Lg9+8QtO1N7cSa+eGHSEhhCSw"
    "xI6KbNI0JWBgJE176GV8aI8XNdq7OZXYyIBSGJsMJkZadkq7Es9738mwt1OJf3joTk4vWHAl+CiPDp27"
    "vocia+R//usSwYlaAq85tE4juLxmEfO5zhtWsQeqi6iots1WZ00BJxbRBfo4f1MK2McZcDoL9Jums0Ah"
    "r+NsLaC/DR+Dzspa8nnZuuCbxBPQ4182";

// newspaper [outlined]  source: src/file/newspaper/materialiconsoutlined/24px.svg
static const char file_outlined_newspaper_b64z[] =
    "eJxdkE9vgyAYh78K4QzCC/6pi3rYqQd79d5aJqZMG8uk6acfMJd2y0vIy8Pzg0B1Wwd0/zTTrcba2usb"
    "Y865xMlkXgYmOOfMGxip6Xgyip6O/WVY5q/pXONJOcR9idQPjLQaB21rHPp1VO59vtf4Zd+NZ6vjdlMN"
    "TbWo3qKP0Rh/0Dypv/mny5qKDTFwPVqN/LUHIYg0FJK8IGFqYRda2UJB0rjOEik3Jd+Uf5EtsQV+/FYG"
    "GIG3V8hRz70NhCclEaEM5IT3ERFBI6aikw90ACBQ7tOV5rrooPRE+GypabFS8YqyJ8o2BPu022nIO4DH"
    "73PDnzffeqZrGw==";

// request_quote [outlined]  source: src/file/request_quote/materialiconsoutlined/24px.svg
static const char file_outlined_request_quote_b64z[] =
    "eJxVUMtugzAQ/BXLZxt7jaGlAg7tJYfmyp04LotKISLUjvL1XZNDW43lXc3OjB/1NQzs9jXN14bjtl1e"
    "lIoxZjHPlnVQRmutSMGZn/vT5OWpd5/DunzP54bPPjJNMJYWZ+jHAbeGpz6MPr4ut4b/mcfxvOE+buuh"
    "rVfvNvYxThMFLbP/7//Vqra+9BsyOu8IVphD+WazShhBPVUrbIDSaQEZCL0PCAjG7YQwciel6Z7fk/3O"
    "jqUwurP4FCwWASiQOAABFZogAYE5nRUFeYG8tqACQeZOy0TvlIQElHnS2yANUn5FWyASnHz4ZbpQEgsI"
    "ZBcPdk9MwDzAoQoGTQfVPb1T0a+kz25/AA6aaew=";

// rule_folder [outlined]  source: src/file/rule_folder/materialiconsoutlined/24px.svg
static const char file_outlined_rule_folder_b64z[] =
    "eJxVUcFuwyAM/RWUMxAMhCZTksN66YFee28zFqJlSdVmperXz9BO7WRkPZ6fn5Gpz5eeXL/H6dxkflmO"
    "b3keQuBB8fnU51IIkaMiI27aH0bHDvvuqz/NP9NHk00uEIEhNZ6MeDf0fmmyiC+DC+/ztcle6mH4WHwq"
    "t3Xf1ifXLeRzGEc0mif3v/+pzdv6uF88wXnbFS8VBWMLCorDagSugcWUEE1I8UKzmJ6cffTdyBZWiVQW"
    "KgqaF5VFpqiiKZjIoDplZIgF9SfSSaQSAy8ikdrgxUgk67vmMQznSkGNZ+XIJJMbvZa8oppKLoBqhAkY"
    "KymUpBP4ZqAi0jE8mC4RVLJEMrkr11JSEy+xYmh0vw+B0mpMO+OLuCDs30ixg/IW95jj1uNntr8QeHo9";

// snippet_folder [outlined]  source: src/file/snippet_folder/materialiconsoutlined/24px.svg
static const char file_outlined_snippet_folder_b64z[] =
    "eJxVkMFugzAMhl8l4uyE2EAKE3BYLz2wa+8tzQhaBlXLSNWnn8OlmxxFtr/fduL6vg7i8e2ne5O4Zbm+"
    "pWkIQYVMzbchJa11yopE2Ol09laeT/3XcJt/pkuTTDYIzUY5n0Q4Ow5uaZLor6MN7/OjSf7wMF4Wt+G2"
    "Htr6ZvtFfI7ec6N5sv/rX9q0ra+nxQme90EajJOllyTpkO9JVZADKY2Qs7s5piPAsteACkHHbDSHpt8S"
    "QHJLSjqWeyIwMYjEQGz+FHEGll3O19G4QuFOeG5wIH3EkjHuVAFICmnNVMZPyUCvsnDIQfeCUZlBtZbe"
    "bFwVHRqG1QGzZ/xTyhuIi21/AS4YY4A=";

// text_snippet [outlined]  source: src/file/text_snippet/materialiconsoutlined/24px.svg
static const char file_outlined_text_snippet_b64z[] =
    "eJxVUE1zhCAM/SsMZ0QCMtaOeuhePHSv3l2XilOrOy6Vnf31Daz9mjBJ3ssjgZTXbSC3j2m+VtQ6d3lO"
    "U+8994ov65BKIUSKCkrM3J0mk5y6/n1Yl8/5XNHZeCLQZIaHEmvGwbqKhnwbjX9ZbhX9U/fj2dlYrsuh"
    "LlfTO/I2ThM2Wmbz//6vNq3LS+cswXlHyDjkTL9CwQr+pFooGt0i/KYfkew61eiD4gVTwWLUG2S9YMCB"
    "CSRkMItUJJhMIpnINjQnvUCsFToJCXCRBVhglsGUZKiI7gAa69gfHY7FqWyfvj9H3ckxZ6AtiE02eQv6"
    "QcAPAZHIbR5hfg9fTnFBYe/1F/4eadI=";

// topic [outlined]  source: src/file/topic/materialiconsoutlined/24px.svg
static const char file_outlined_topic_b64z[] =
    "eJxVUMtugzAQ/BXLZz83xLgVcGguHNIrd0JcjOpCRFwc5evrTQ5ttdZqNDO7Y7u6biO5fYX5WlMf4+VV"
    "ypSSSDuxrKMEpZTMDkrc3J+C46d++BzX5Xs+13R2iahcUORDiXfT6GNNEW+TS2/LraZ/9DSdo3/ITTU2"
    "1eqGSD6mEPKiZXb/53+9sqkuffQk572DYsZzGzhwaIsDiBdWMBBKsyLDBzBHYNoOimmhmUIWy2sjynJQ"
    "wliGEuy4EnvzRNg6ewBgBv04aBhG3QkmansscuuM3wtdhrytBdVpm1VtmYbWbDwHQKcBqew1T8p22tzx"
    "/jK/Fj+x+QGRvl8q";

// upload [outlined]  source: src/file/upload/materialiconsoutlined/24px.svg
static const char file_outlined_upload_b64z[] =
    "eJxNjksLgzAQhP/KsnfNwxi1GA89edCr94LWFXxRQyL++saeysIOzDfsbHm4Ec5lXg+DZO3+YMx7H/sk"
    "3j4jk5xzFhIINEwjWYNSIbhp8M/tNMiBg1Rwe37qLf1wVe4vS9AbbAMnqZxUNe/4hfCe5tnguq0Dsr9Y"
    "AUKTdpEmNUfZPZCRcvpakkjwWGSNUGFDXovEaYpkl9dFnCeNkJAGvdoURE4iNNXpdZ++f66+gm488A==";

// upload_file [outlined]  source: src/file/upload_file/materialiconsoutlined/24px.svg
static const char file_outlined_upload_file_b64z[] =
    "eJxVUEtvhCAQ/iuEMwJD0WqjHtqLB/bqfdelYGp141LZ7K/vYNu0DcPMZL4Hj/q6OXJ7n+ZrQ30Ilych"
    "Yow8PvBldUJJKQUyKLHz8TTZ7HQc3ty6fMznhs42EolLaQxKvB2dDw1N/Tba+LzcGvoHj+M5+B1ua9fW"
    "qx0CeR2nCY2W2f7X/3JFWwu3CzAux+AJnnwAzVRXvGheMcU0l8AUtnujDWJykAw4MMnLxABeYemgHPYh"
    "U5lMykz1pUlWd3KAElVd0Wv/uOU+75XEYckgR08yAdfAUjKAVfNS91B5tWWaQ4FoXrGUDBRfCgMq3QXA"
    "fFvcfx6yb/zR9hP/AGIo";

// workspaces [outlined]  source: src/file/workspaces/materialiconsoutlined/24px.svg
static const char file_outlined_workspaces_b64z[] =
    "eJyNkc1uwyAMx18FcTbfpEunJIft3FOfIE0ZiZYlVcJK1aefIZq2STtUgDHgn/8YqvXqye1jnNaa9iFc"
    "noWIMfJo+Lx4oaWUAiMocVN7Gh07td27X+bP6VzTyUUisWmLnZLeDb4PNU3+dXDxZb7V9Nd5HM6hz8dN"
    "5ZtqcV0gb8M4YqJ5cn/5n1jRVMJnAPulDT1B5cMOVNEprkCCBsn3aPXKssOyq9MCrT5a3FQFJIIkznRM"
    "c4SYBcVLtHbFGWxqq2XZZ/ZYYowyCTN3clAaCvKgoEq7BWQkgeZ1jzkNYF6cS3j6V09ZFDSJynpluu6j"
    "grutxA3K7INFarlVmZH791vngZ/efAHcYoIj";

// approval [rounded]  source: src/file/approval/materialiconsround/24px.svg
static const char file_rounded_approval_b64z[] =
    "eJxVUdFygyAQ/BXGZ0RAQO2oD/UlL/mIxFhxajWTWM3k67tHkmk7h8e6LHcLlNe1Z7evcbpWkV+W81uS"
    "bNsmtlTMlz7RUsoEioh10+E4dvHx0H72l/l7OlXR1G1MIrTBiJjvht4vVUR4Hbrtfb5V0Z/1bTgtPizX"
    "ZV+Xl65d2Mcwjig0T93//b/apC6TPmzAOB8Wz9B5b7hyq2klV0JxKQquKbzSbSC4jgMZ6zWGKgZJRKwp"
    "dq4xWFSGowohKnZne5Vxle+yFkprOTYBGItJrZKhyIMOFAfplWwfFFeBxgRlo3KuMuKfmX6RqQEsNoWw"
    "Bl4zYXKeiqwAkhl3QqWscaIoAJ0FqVJKOQkJuRFix63QDl0NGlqHw+v0hRxQ0MRPTUr2NTkzdHaynsK6"
    "MBlrlBNWP9rjBoyDITJ3f912+PDs9Q8e9YID";

// attach_email [rounded]  source: src/file/attach_email/materialiconsround/24px.svg
static const char file_rounded_attach_email_b64z[] =
    "eJxVUstu2zAQ/BVCZ5LiLkk9CtuH+pKDcyqQu6OoklFVDixVCvz1naWapMGK2OFjZ5ZD7aalU2+/h3Ha"
    "Z/08v37L83Vd7ert9dbl7JzLcSJT7Xh+HlrzfG5+dbfrn/Fln43tqhyCA75M9e2l6+d9Jni5tOv369s+"
    "+29/vbzMfdo+7LrD7tY2s/p5GQYQXcf2a/3n2fywy7tU8PG9nudeQf+RSZN7Co0zZMk4WxuWePBHsrVm"
    "TdaRZsAEwgnHi8ZhRtqlA4ieaDExURQFtnwwXnvjH5ju6pHIRg8RW5SqgYJnVDJAGRIAcaHdydugC8vx"
    "6C1FIFdrr6OtOKXoQS8UKCm91JQiJCx8ItL1UNjSBEu1OlJludTBBvRSI1cpbxyiWKMKEs7GAkiaSBwf"
    "Xd7FsE+D4EGQviNKjNw6RCRa/GaDSTYY2DAZfjdwQSsxdcyVSMpGUpQ8bZjFh7T4RHBGWhMJ0GuSmIRa"
    "Jgbuerv56yt5JyiA6t/4gbsQY1EL8EJXgY2tPK0t4YDEFMw2MQFs6si4bBB6ZpGloNNF7+8/y5eBv/fw"
    "F9eHrDo=";

// attachment [rounded]  source: src/file/attachment/materialiconsround/24px.svg
static const char file_rounded_attachment_b64z[] =
    "eJyNUrFugzAQ/ZWTdx8++2zjKmRoF5au3StCY6Q0iQoKUb6+Z4hQxw7g5/Pj3XuHd+PtCPfv03lsVJ6m"
    "60tVzfOMs8PLz7GyxphKGApyPxzz1CjLCm5DP79e7o0yYMAylNo8HKa8HO93188pw6FR73KeLd8st+bD"
    "PBR8DadTo86Xc6+qPzSKGD1QaCNS7LRFk8Boh8lrQu80I3nZBnqzGBOQQUPAGALUEKHOZNGFjtBR8YMe"
    "k3jC4ORly7cgKqJkrBRiEH1OC2pTp9F76UUaWSiaxmUFQbkWUx1y0RSk0fGyRD8WrJ+b8rQJiTu9GtCr"
    "Ab0Z0E8HsDmAzUGWLM51a2LYEsOWGK0TJZekHFgGIUhY9YJkXNaVcdVR2nrkkpoExDKdFMSmSNrSyQYI"
    "aBiEVC+oNP5vvEf5WeUW7H8BOqx73g==";

// cloud [rounded]  source: src/file/cloud/materialiconsround/24px.svg
static const char file_rounded_cloud_b64z[] =
    "eJxNTzFuwzAM/Aqh3TQlUbRVRBmapUvX7kXiWgZcO2gMK8jrQ2UqCBwPvCNxPNz2Ee6/83JLJm/b9a1t"
    "SylYPK5/Y+uIqFWHgTxMY96ScWxgn4byvt6TISBwDHVWpsuWX/LxcP3eMlyS+VQ9O94df9AXPQz8TPOc"
    "zLIug2n/2WxEH8ASEp9sj9KBYIhgAwoDg3UKEa3VJijwGoe60usGOPSszIuG0RvR1s5nAo/eqioRpFa2"
    "/uywq7bQONTcoQlASoUVKDSMXa8glUV51Iz1+eMTb+5Gcw==";

// cloud_circle [rounded]  source: src/file/cloud_circle/materialiconsround/24px.svg
static const char file_rounded_cloud_circle_b64z[] =
    "eJxNkMFqwzAMhl9F+B7FlhUnKXUP26WXnQa7jzSLA2lSFhOXPP3kroyBjD7+X7IsH9dtgPt1mlevQoy3"
    "Q1mmlDBZXL6HkrTWpVQoCP04hOgVsYJt7NPLcvdKgwZiyFoaLzE87NPx9hkDXLx6Ez8Qb8Rn/aF3BV/j"
    "NHk1L3Ovyn9lhoBeHXIDAvAEQytnMvoviqdQGP1uaqzoUQa0XxkrMHxuusKgc6ALK2BZkl1/AQQDGu6Q"
    "WbzagsG2zTo2ThIhGdmGRa5bSRyw6qS1ySvm2zFPEpCThzfyECeRLbfndfI/nX4Ae5NP9A==";

// cloud_done [rounded]  source: src/file/cloud_done/materialiconsround/24px.svg
static const char file_rounded_cloud_done_b64z[] =
    "eJx1UcFuwyAM/RWLO44BQ0LV9LBddtiuu09pVyKlabVGTdWvn5120y4Twrbee+YZWJ8ve7gehvHcmjJN"
    "p1VVzfOMc8Dj177yRFSJwkDZ9fsytcazgUu/m5+O19YQEHgGxeZ+O5WF3qxPH1OBbWvehC+eL55f6J1u"
    "Bj77YWjNeBx3pvojcxlDBEdI/OwaTDUkjBlcxMTA4LyEjM5JSphggaO2NNIBHgNLFZIMI2dkp5k7goDB"
    "CZsyJF3Fhc5jrbJoPcrc0UYgKRNLoGgZ60ZC0iqn28E26pTQx85ikCGzdUj+nll8Xmv04oV+4X+3iuRg"
    "1TwgUOhRLI1OZ0TXDIysntx0/0jh7vzD6OUEH2yUbtBw07fUT9p8AzJBZ60=";

// cloud_download [rounded]  source: src/file/cloud_download/materialiconsround/24px.svg
static const char file_rounded_cloud_download_b64z[] =
    "eJxNUE1vgzAM/StW7hg7cQKpSg/bZYf12vtEGUFiUK0IKn79HE5TpGfrfThOzs+1h9fPOD0bk5blcSrL"
    "bdtwczj/9qUlolIdBlI39GlpjBUD69Btb/OrMQQEViBz23Bf0iFfzo+vJcG9MVfVk5XVygfdaDfwPYxj"
    "Y6Z56kz5z8YRnQcmJHnnGkMFAX0E9hgEBNgqRGTWEjDAQfscqTUBFp1o54IuozMi5yotgUPHqoYIIZ/E"
    "rrVYZZsvLOrevvBA2gZRIF8IVrVCyF0M+5UrYDceDGRoC9RcgZ4zVnrRZ3Ykd4tJVkluz8/K/3X5A3lt"
    "Ug8=";

// cloud_off [rounded]  source: src/file/cloud_off/materialiconsround/24px.svg
static const char file_rounded_cloud_off_b64z[] =
    "eJxNUk2Pm1AM/CsW92ee/b5Xyx6aSw7NtfeKTUMkmqwaFFb59R2HrlQJngfb4xkDr7f7iT5/z5fb0E3L"
    "8vHS9+u68hr4+ufUq/e+R0dH0/F8mpah09jR/Xxcv10/h86TJ41kufX8vkzP8tvrx89lovehO6A+abxr"
    "3Psf/tHRr/M8D93lejl2/X9tGCFp9E45Rxw+ucil4siGWt5J5Vwoc2poRBOBoBRHJxwCGTEVDtkFMLiV"
    "WTiiE8dOPCcBUwqJsAbKxsxjYB9hPnEi5ZifAPed017aKJwzqgEzQkSABnFrjmNFqiboqhjRlMSUBByP"
    "hqbWAENaniBwlcchcBGKnPLoODRcFlD3isHGnrF1JjsmiOgInlYOySUumQJcAGnDIqXtzK8UrnDG0kg9"
    "0qqIE1ZMAk9qw7WNm9hTaIswi002fQubBWeF74ntnX6ZdF/lf8CYjwOE62jb4clFpEtDiLcNEOAEGOZK"
    "dZ8f9pHt73n7C13Uh9Q=";

// cloud_queue [rounded]  source: src/file/cloud_queue/materialiconsround/24px.svg
static const char file_rounded_cloud_queue_b64z[] =
    "eJxNkE1vwyAMhv+KxR0HgzFhanpYL7nsuvuUdiVS11ZLlFT99TPpZULYj/z5wm5azvD4uVynzpR5vr81"
    "zbquuAa8/Z4b75xrtMJAOY3nMnfGs4FlPK3vt0dnHDjwDDW2jse5bOn97v41Fzh25kPzxfPiuXef7mng"
    "e7xcOnO9XU+m+VdGGUMEcuj4QC1KAsGYgSIKAwN5NRmJ1AkKbOFYW1rtAI+BlYKoGJ2RqXoeHAQMpFnJ"
    "IPUUCoPHVMui9ai6o43gFIXVuGgZU6tGKmV5qi6gtpehVutUy5YwZXU8vQAUCyY6JAwJUl2VkVvdpppl"
    "CFWebsOoMlg20Ltg7CkPhFK1BKD6gABhsi+yys/6QfXn93/E+l/J";

// cloud_sync [rounded]  source: src/file/cloud_sync/materialiconsround/24px.svg
static const char file_rounded_cloud_sync_b64z[] =
    "eJxlUstS6zAM/ZVM1rZi+ZncabugGxaXLfsSQtK5IWWa3Ibh6zkyA5RhnFiyHkdHsjfzpS9en8dp3pbD"
    "srz8qap1XWl1dDr3lTXGVIgoi246PIydfji0//rz6f/0uC2nbi0MlvX4ymLojv2wbEvRL8duvTm9bssr"
    "/3p8XIbs3m363ebctUvxdBxHAJ2m7mf+d2y121R9TsD3cliGApXvrFecyNetUUyu1kxslaWg8Yv8yxCm"
    "hT1GZbSD4jyEa43YkGQjYhvE1l6Ues+BAIqzUxwlxCqusRctUwKIcmSlGKSXGk3TGjIWDginsbFoIWt7"
    "CyBkeyArIRuJ1Sfpt+KOwTuAi6EgCT5oljVrwZCT4guT94W0YK30py14xgTh4UCuReNCqBFDpqXRwr6h"
    "lFQkD7IG0niRgaLL5RLLJvNgmZpLONb1PlDdSLBTXtWUGuVz5wZ9QiMTlafgcUpOxdvQZuIY7DfdWRTF"
    "sgawy27F+sOq+Z6DtI0iv33z1QQGLT3/Qr8AUn1Yv8rMV+iJggBj2EY6wRVj7GRkPo2V0fjR5ssSbAtI"
    "XJ9MFi+CkjyAGHW45ebt873lHw9/9w6i9LVE";

// cloud_upload [rounded]  source: src/file/cloud_upload/materialiconsround/24px.svg
static const char file_rounded_cloud_upload_b64z[] =
    "eJxNUMFuwyAM/RWLOw4GA2FqetguPazX3ac0K5GypFqjUOXrZ6odJkvPT37P2Phw367w+J7me6fyut5e"
    "mqaUgsXh8nNtrDGmEYeCPIzXvHbKsoJtHMrr8uiUAQOWodbKeFnzUz4ebp9rhkunzqJny5vlk/kwu4Kv"
    "cZo6NS/zoJp/NkroPJBBw2/UYogQ0Ccgj4GBgaxAQiJJAQM8y762tNIBFh0Lc0GWkTcS1cy9AYeORA0J"
    "Qo1MrrcYq81ri7K31x6M0MACxmvG2AqEylLYzySz3cZZ86b5FKc/KfgerUaLnipGGfhOUaxZu71+rF7s"
    "+As32FJ2";

// create_new_folder [rounded]  source: src/file/create_new_folder/materialiconsround/24px.svg
static const char file_rounded_create_new_folder_b64z[] =
    "eJxNUE1rwzAM/SvCdzuW5nTJaHrYLj1s195HmlWBNClzsEt+/STDuiF4Qu89faB9TBe4X6c5dobX9fZS"
    "VTlnl5/c8n2pyHtficMAD+OF185QMJDGIb8u98548EABlMvjeeUiH/a3z5Xh3JkP0ZlConD0J78Z+Bqn"
    "qTPzMg+m+mcjDzu2zWTRBSzwht4RQlBo3TMEQZR0DL3oiOAlta1r2pKB3gmw6T2oKCyQBuOuF0KPtE44"
    "Syfx6AApLWlsV0vQsKVE0u3q2rpQgxwBGC1qIYjJklh6K7pu/qVjyepmEouMFsODiwhlFmAipr70woOL"
    "f4s2fYZ++fADdSpfDg==";

// difference [rounded]  source: src/file/difference/materialiconsround/24px.svg
static const char file_rounded_difference_b64z[] =
    "eJyVUsFugzAM/ZWIswlxIECm0sO49NBee28pI2gMqpZB1a+fE1q105i0CWQ79svzc5LFeajY5aNpz5ln"
    "+v74EgTjOPIx5N2pCqQQIiCEx8p2t29Kf78r3qtT99keMq8tRybokxH9HjNlXZk+82w81OX42l0y76k+"
    "1ofeuPJyUS0Xp7Lo2VvdNETUteX3/Q9s8B9kUDnq4643jARuQkgKwZUCAQiCR4ocDhgaDH/mz/4U+RSv"
    "osJHTjVfUlaTlds0l5BYhLQmASK/sg0qrjQgGZZTLGmzMxFPwDkkv0rzmBMKYi4sQE9BuI4BSSG4VjzV"
    "IG2R3Ap14ZLg+oPtn/CUVNNShWQk6eQisktNUYRs/ZBy0wWojE+TTKP66AYkh4OYiBRMGTu0iWaOSuQY"
    "W57IVigUlhNu3Pcu2vjIBqQ5LMHTKRox03tr4X/VhNt4JivY3K0a/H2A9KFfT/L19f5g7PtefgGJebb/";

// download [rounded]  source: src/file/download/materialiconsround/24px.svg
static const char file_rounded_download_b64z[] =
    "eJxlkE1vgzAMhv+KlXuMHRLaTKWHnbj02vtEGUFiUA1EKn594/TQSZMTW3offyWnZevh8TNOS63Cut4/"
    "iiLGiLHE+bcvDBEVKUNB6IY+rLUyVsE2dPFzftSKgMBYEC0OtzVkfD7dv9YAt1pdEg/GbsY2dKVdwfcw"
    "jrWa5qlTxZ80rtB58A27q21Jo3MardMsFrRtRQHSDFkF3lxzQMtJP3rRsbTASEeNh0STG600FNdi6dMR"
    "bF7RMlDm+sWrUqeL7LVUphY57hcH7FuCNDpNBRYLbNq8CrDOoublvWlT/Vt0l2fK/52fGkVWeA==";

// download_done [rounded]  source: src/file/download_done/materialiconsround/24px.svg
static const char file_rounded_download_done_b64z[] =
    "eJxNkE1vgzAMhv+KlXtMEsxXVXrYqYfuuvtEGUFKoRqIVPz62aGHSYlf4/eJHXJetgFejzAtrfLr+jxl"
    "WYwRY47z75A5Y0zGhALfj4NfW+VIwTb28WN+tcqAAUcgtTjeV5/sy/n5vXq4t+qTfe9oc3Q1X2ZX8DOG"
    "0KppnnqV/cNKsLW3rsOi4IYWkAqOdtEp0Zxey04nV1spcrRLUrH3R4HGakLLUFVjVWmHhg6tnWbzxiMs"
    "VqnJe5O2SIQmZ20q+cbCAddYWRpu4W4NpoMUSqRcS+gOkoS076ThiwWZaEjsYwmQZgtQBl1BiU2+y4/L"
    "i17+AOrhWZo=";

// download_for_offline [rounded]  source: src/file/download_for_offline/materialiconsround/24px.svg
static const char file_rounded_download_for_offline_b64z[] =
    "eJxtkcFugzAQRH/F4mybXQcwqYBDc8klp0q9J46DUSlEgUKUr+/aULWVIqzx8Ly7HkExTDW7f7bdUEZu"
    "HK8vcTzPs5w3sr/VsQKAmCoiZrvjqbXidDQf9a3/6s5l1NmZAT0qoRUxZ5vajWXk/dTY+bW/l9Gf87k5"
    "jy4cV0VdFTdrRnZp2pYG9Z393/9bG1dFXIeG63F0jK49oOJql8lky8nw1aAaEu8QljUgiBUIhDfUMsVQ"
    "xtWDHRCJv2sDAmSacpBJKggJdGAWwjFQ2nDaMIdSb00AQDzTJGlCsvHNedoKRQXci6GRiqDyo3E1msxS"
    "E2SX+24MM3KpMx95K5UPtUf0+Qjpfc7Mmk+gWDIKnOBJ6vxJatih5ph5vqp/JX38fFT/Z6tvNNl8FA==";

// downloading [rounded]  source: src/file/downloading/materialiconsround/24px.svg
static const char file_rounded_downloading_b64z[] =
    "eJxdVE1z2jAQ/SsezrLw6sOyOsChvuSQXHtPHBeYUsgEijP59X1vbUPTAcTiXa3ex4rV+botPn4fjuf1"
    "Yne5vH1bLodhsIO3p/ft0lVVtUTFouiPzy+Hvnx57n5t309/jq/rxbEfigovF/BeFLt+v91d1gvG130/"
    "fD99rBf/5If962Wn6c1qu1m9992l+Lk/HNDodOy/7r/XLjer5VY34P32fNkVOPlJkvXeeBtjV1Y2Byx1"
    "KTZnLFUovRWHyLeCkmycFTHi8Y0fwn3OX6uuMpUNEYvHp0lYUsCSU9FhFYTOiE1MxJqbPX5WEUmfmeTW"
    "hpEkJJwDCKkP6NoCXg4m2DoYhGjtWXgH/Vk8uYqdRR7ngIeivkIr8WgV2Tk3oOGEJB0JCg9JJQgl8lOi"
    "THoqEAMrKIUgiPGGRysciXI7OTZekwqbBwcepkybiIe1U6bKuZVsgR1pA6geQoqZMYOHNFaZhfx4D7tJ"
    "2MBmjkr6xsyQojJV24y6Rd/MxEaQE7WTUH1U+uVNiJ1yYe9ysoxE8uidqkTRuCHSk0TNJh5FC3zAU9sa"
    "vBE2xErrbrBJx4/kHudAp4S+6OzAmplRbrrJD8fhgCGUiBToDDnGoM6YyRBuklqduZsyL2pImNmKjnWq"
    "KSFHuhZ1przNIAcbkTrjZ18mxCMLcT+ajiqp6AFC8jXqF6mfmPGxkWt4yDbokHGcCV+daYhBKKMc3HiP"
    "Yp6n31ONys1RQLtCq8qpqiajmldL6F0S7abRg3iClFlq+SJ1eZO6nKXObeTVYRXMpIcYP3y74gwdfNnw"
    "ebIplxlRi2EFnvHWy3Tr5cut5/h5FTXNQufUYjSSiSaYxkrGl7iz46NkausCDmgK9q7zpLz8dyM+538r"
    "/eBvc/MXGXcnPA==";

// drive_file_move [rounded]  source: src/file/drive_file_move/materialiconsround/24px.svg
static const char file_rounded_drive_file_move_b64z[] =
    "eJxVUcFygyAU/BXG8wN5BDB21EO95JJr7om14pRqJrGSydf3wTRNO8iy7C7wwOq6Duz26adrnbllOb/k"
    "eQhBhI2YL0OupJQ5JTLWT8eT7/np2H0Ml/lrequzqQ9MUlOavoy5fhzcUmeRr2MfXudbnf3xw/i2uGQ3"
    "1dBUl75b2PvoPW00T/3/9c9s3lT5kBacj4tjdOxeSbCObz1HoTFBi1IoBB2hFAVoQqRhp1slSpoq8kpC"
    "u6LqJKBAkEmg5tB2SQDFk8jVYctaRek4i5aFeOad7VEBGlGUB9S7sqO4MSA5EtGGBlxlJ3/UpABpbrNS"
    "kUWZHB0do4nZgtjWENsYr8iHCKyjm8Czm1iXFAV6/ptpUdEWgFZoC7EiK5SGR2n3x5PF/9Z8A3WbdPQ=";

// drive_file_move_rtl [rounded]  source: src/file/drive_file_move_rtl/materialiconsround/24px.svg
static const char file_rounded_drive_file_move_rtl_b64z[] =
    "eJxVUcFugzAM/ZWIcxJiN6RjKj2Myy699t7SjKBlULWMVP362Zm0dgo8x8/28xNsrksvbl9xvDZFmOfz"
    "a1mmlHRa6enSl2iMKamjEH48HKNXx0P32V+m7/HUFKNPwtBBS08hgh/6MDcF35fBp7fp1hRP9TSc5pDL"
    "283Fd7P4GGIklWn0/4cfjeV2cz7MQdCyHRrpgnqJCrSFDC0YjSAtQ63X0hIChXfboq4pRarVhG4B7IwE"
    "DdJkgk4A12VCosqkwv2LaJG6OeOSk7zzLnZAWSXBEUaFel1n6GgOn96KxCisIf61tDRpHdmqrARkk45j"
    "9r0HDCvR0VxFJtiZpR0SFkNWmVW/jCIuqNUCWQ/ZBpJaFqY748PenT8Z/7DtDy+Tclg=";

// drive_file_rename_outline [rounded]  source: src/file/drive_file_rename_outline/materialiconsround/24px.svg
static const char file_rounded_drive_file_rename_outline_b64z[] =
    "eJxdUU1vgzAM/SsR58Q4IUCZgMN22aG77t6mjKBlULWsVP31s6N1bJOTZye238tHfb704voRxnOT+Hk+"
    "PqTpsiywZDCd+tQgYkoViejG3T50ar9z7/1p+hwPTTJ2i0AyY2kkwndD7+cm4fgydMvjdG2SX/llOMw+"
    "ptu6b+tT52bxNoRARNPY/e1fa9O2TvvYQOO4m70g5RedS10EZaX1G6dBS5RGIVSE5oIOFe3xWhm2Z53f"
    "mGhtN4CFLEFXQW2gLCXDUwZaEy1oKzP2364oXnXlUCLkOYElaTZvILMOwZQy5lif+hFKVjZVYM7ILrar"
    "3r9zUFqTODJRVikGGSMNaCRfw+qgWCmCUz9lseIeWdIN5Dd0YIKQQZlLhu2qcLs/ZZz0p+0Xq+Z9gA==";

// drive_folder_upload [rounded]  source: src/file/drive_folder_upload/materialiconsround/24px.svg
static const char file_rounded_drive_folder_upload_b64z[] =
    "eJxVUU1vgzAM/SsRZyfEJnxNwGFcelivu7eUEjQGVcug6q+fTTVtU9Cz896z44TitnTq/jmMtzLw83x5"
    "CcN1Xc0amenahWStDdkRqHY8HIdWHw/NR3edvsZTGYztqiwvcvwFyrd95+cykHzp2/V1upfBH33tT7Pf"
    "5KroquLaNrM698PAjaax/V//6w2rIuy2gsth9oqP3ZOFxOts0GgcblCjNYTgBHKTgmNEDjtXk8l5S8aK"
    "nD+T5I0As8YCGgQrrCyPSbMRQHojNb1nqiaCRHYiJSBnP9QeI8BoibiFNXHMdhcDjwLobaOFAqtxozng"
    "oqNdzrM1T6PlkKRicwyRlGfxQCbTZNJcNXwXpkhaSw/MOUt5rkFkEKgxNi4BpA1jQw5kImcyjjuMHj/P"
    "Jv+u+gbplXVe";

// file_download [rounded]  source: src/file/file_download/materialiconsround/24px.svg
static const char file_rounded_file_download_b64z[] =
    "eJxVUcFugzAM/ZWIsxNiSAqZgMN66aXX3duUEVQGVcuaql8/m65aJ0dPL/az/ZRUl2snbl/DeKmTMM+n"
    "tzSNMaqYq+ncpZnWOiVFItpxtx9aud/5Y3eevsdDnYxtFJoiM3QSEdq+C3OdML/2bXyfbnXyUo/9YQ5L"
    "uam6pjq3fhaf/TDQoGls//f/adOmSrul4bSbg6C1W1wp68Bt0H4Yr6VW1hIYK5EjSLN2dIMcHORMHJir"
    "3RTKoCdd6UBLVLkBVLqkRIHEChwMT2UQXqucVAykyZ7MIOhFJRnWWCiXAWqaAsRNSYt+rd3F1gI6r4HN"
    "AZsD5AiY+UcKUD7SEi8v7jcrsbZLvgQGpjzq/nwI/o3mBxNzbD0=";

// file_download_done [rounded]  source: src/file/file_download_done/materialiconsround/24px.svg
static const char file_rounded_file_download_done_b64z[] =
    "eJx9UcFuwjAM/ZWoZyd1QgJkansYlx3YR0DJ2oquRdARxNfPDgO2yxTHebKfn+OkOJ0bcfnsh1OZtdN0"
    "eMnzGKOKMzUem9wgYk6MTIRhs+2D3G7qfXMcv4ZdmQ0hCqRlLFkm2tA17VRmjM9diK/jpcx+5WO3m9qU"
    "roqmKo6hnsRH1/ckNA7hb/2Tm1dF3qQCssNmagV1ftdeWQNWLfT6CWuJauZvTis0d2Q1YC+Xyi6BnF87"
    "5T14NZ//W4CA4kaABwuYBQhM6a0yFtjVD9JP/oaSilfaS3YruufSgFOLGdyhhuflrzzpY745GGy1IWXn"
    "uB91t44OfcYaJUdTRGpeb2kQJkpqmcJAxJVjeQo7rjUILHq9P2ja9LPVN1nefN0=";

// file_download_off [rounded]  source: src/file/file_download_off/materialiconsround/24px.svg
static const char file_rounded_file_download_off_b64z[] =
    "eJxVUsFygjAQ/ZUM5xCygUjSEQ/tpQe99q6IhGkKjlLj+PXdDWDbAR6P3bfZlw3r661l9y/fX6vEjeP5"
    "JctCCCLkYri0mZJSZqhIWNPvD75JD/v6s70M3/2xSvomMImXKvBOmGu61o1VQvzWNeF1uFfJn3zojqOL"
    "6c360tQjO3Xe4ypD3/wv/hVmm/V5PzqGzXaWrwSUH0UtUym05lIUOgUOKTiMxQiHGMUX3LQDoS0mjKWE"
    "yHMEaVBQIinBpyCM4QTbaekH2ykstzwi2+ZCAyeosWFuJ8A11MIKbDfl+FNATVRsWIAvhOb4kEatSFMS"
    "Iw+WnKJN/CKVJZll6DanjUUwJlaQpkQm7RY0uuRg3lf1PIIUnmO4Ljvn4ABQ6EGQGxrBbHD2NjEyz95U"
    "7KOAtjrzBZdBPOgU6B/Y/ADVQoLM";

// file_open [rounded]  source: src/file/file_open/materialiconsround/24px.svg
static const char file_rounded_file_open_b64z[] =
    "eJxlUstugzAQ/BWL89r4BQkVcCiXHNJr7gmhGJVClFCI8vUdQ9K0qozWy86sZ9aQXsaaXT/b7pIFbhhO"
    "L2E4TZOYjOjPdaillCEYAau6/aGt+GFfftTn/qs7ZkFXTUxiaYsnYK5qajdkgc/Hpppe+2sW/MKn5ji4"
    "Gc7TOk/PVTmw96ZtcVDfVX/7n9wwT8N6bjjtB8cg+6aMUCvSm7iwIiFNljR2S3ZUcSlJCUVyBrBcMnIU"
    "+b3IUeLamd1arA3KUkQGQSsQpPWvCTKrWm5BmAMrlAUBGgiQhjLdHdwYvNB6Z0S0VWsRUbJRtgBokZKH"
    "RBTNO5haizgmtYJDyETQAgu6pBwktW0h4CfBbZVSmISeAd40+cFgDN0l/4H4Ai2ZxYhbBXqyEP2p/9V8"
    "N1zhSuYiNrVTK7ZcBupzzVOdgeFCL3PHdPcf+4Mes9wen8f/I/k3NHeK6Q==";

// file_upload [rounded]  source: src/file/file_upload/materialiconsround/24px.svg
static const char file_rounded_file_upload_b64z[] =
    "eJxtUUFugzAQ/Irls1lsgwFXwKG59JA8ghDXRqEQAcVRXt81KGqrVmuNRjsz3pVdzqsl949+mCvqluX2"
    "Esfee/AJjJONJec8RgclZmjOvYnOTXu10/g5XCo6GE84lkzxUOJMZ91S0cDXzvjX8V7RH7rvLovb5Lq0"
    "dTmZdiHvXd/jReNgfue/vXFdxnYL3JrFERx7yiFlgjsBSq+q5YyDUgipYiKUS9u9w0S0dyOxRmrzo1Lo"
    "oECSRgJ4gbkcdYSjkJCzBHLSYizRO6BHPlkqGD9maCpA6kMGPDAtWQYKx3K27/UgJxyp/9lLyL+LzRuL"
    "RKi3jBzU1i9YgEDDVY/nI4SfqL8AgPhrYw==";

// folder [rounded]  source: src/file/folder/materialiconsround/24px.svg
static const char file_rounded_folder_b64z[] =
    "eJxNj70OwjAMhF/F8p7EMeEnqGGAhQFWdlRKU6m0CKIG8fQ4nZClz/bdWUqq99TC59EP74AxpefWmJyz"
    "zgs9vlrDRGQkgRCbro0pIDuEqWvyfvwEJCBgB0XL3S3F2d5Vz2uKcAt4Fj+ym9gd6UJfhHvX9wGHcWjQ"
    "/MUs6aUHJzjIyFZGgddrcEIr7ehqZbUFEnqv/dyATwx2UxOIpWUtFe2qnpPAqmiKL5Iox7IqLhXVphfB"
    "2Rnf8pTyx90PQIhDJQ==";

// folder_copy [rounded]  source: src/file/folder_copy/materialiconsround/24px.svg
static const char file_rounded_folder_copy_b64z[] =
    "eJyVUcFuwyAM/RWUsyGYEKJWSQ7LpYfu2nubshAtS6o0C1W/foZq6qadJoMxz8/2E5TXtWO3j2G8Volb"
    "lss2Tb33wmdimrtUSSlTYiTMjsfTYPnp2L538/Q5nqtktJ5JMqVpJczZvnNLlYR47a1/mW5V8iPv+/Pi"
    "Yrouu7qcbbuwt34YqNE02t/1T276H2baxda0LsfFMdL4qsDsaTcodA4GEEwIEIoVVSsBBYIUG1DBHJpW"
    "ijwHwrmMPI6rbCUPaEQ4Bttlh6LJHq1UKDBUbu5BwnMwgna8GDhNxugaVILQ6BBFQTV0IJ27osmjiFzI"
    "QNg8Ar0nBflflbqNACgeQa4OhjUqAx1uilIawvT795PETb9YfwG9PX1r";

// folder_delete [rounded]  source: src/file/folder_delete/materialiconsround/24px.svg
static const char file_rounded_folder_delete_b64z[] =
    "eJx9Uj1zgzAM/Ss+ZttYju1ADxjKkqFZ2RNCMVcKuYRCLr++kpuPdumZk2W9pyfJJjvPLbt89sM5j/w0"
    "HV/ieFkWuazkeGpjrZSKkRGxZtjt+0bsd/VHexq/hkMeDc3CFC5t8IuYb7rWT3lE/tw1y+t4yaNf+NId"
    "Jh/gImuL7NTUE3vv+h6FxqH5m//kxkUWtyHhuJs8w7JbcNJysNJ6oWdhvK7ocGVbrbjzIukFSAPBlKCk"
    "Bm7IpHLNDVrAbWNKLVM8aqkITn8c96Y5JLXiIIEritLy4FgdIlyLEBW6SkqtuaMDIY5TbWwBEqmxOZB2"
    "A8lsUErJZIVZbo2iFpuytGPntSCEKwoFXNxwGgkD2jKiGCyL25o4K3P31rZWN/Ae5Q/IA5oKx7UlGKyX"
    "IoWjl+D0dG/YYOqVRIkgwG/ZSHroVKBYkPmHU0JKg4LDK5POhaH5c/7r/eno/ym+AUISkPo=";

// folder_off [rounded]  source: src/file/folder_off/materialiconsround/24px.svg
static const char file_rounded_folder_off_b64z[] =
    "eJyVUstuwjAQ/BUr52XjdYJJKsKhufRAr71DMHFUN0GQEsTXd9cIaI+V7fFI+5qxvDydW3X5Cv2pSvw4"
    "Hl7SdJomnDIcjm1qtNYpZyTK9ZttcLPtpvlsj8N3v6uS3k1K8zI570R517V+rBLh585Nr8OlSn7Fp243"
    "+hheLdvV8uiaUe27ELjR0Lu/9c/c9D+ZaRtb8z5sRq9Y47vBgkCgmWnMyhsQanNnOYGuCTI0IFhkQByA"
    "HI0JGos5CNQGCeaYzbmVFmbtjdk1lxWq0VzFjbAEI8tThrQIBq0Mt9TIMIggs+9MZjcPWfDQBjoKWz/E"
    "X8Xd05MG62dFiEkRatJoSEQTlLiAnJH4erNsKFCOJdsSrA1hSSwZLXsR7ZjlN/JR1HxbsSBe2CCPud6f"
    "NR7+CasfBA2KUg==";

// folder_open [rounded]  source: src/file/folder_open/materialiconsround/24px.svg
static const char file_rounded_folder_open_b64z[] =
    "eJxNkMFuwyAQRH9lxR28u8VpXIUcmosP7dX3irjGkmNHjWUif312OVVIs5qZBwhOj22A522aH8Gkdb1/"
    "VFXO2eU3t/wNFSNiJYSB1I9DWoNhb2Ab+/y5PINBQGAPmuXxuqZSn0/3nzXBNZhv6RP7jX2LHe4Gfsdp"
    "CmZe5t5U/zBGOCR7nCw5T0UuhI4JvErj3sGLkozWR+kJULRpXFMG8BcDHSOCVE6srkSHWEhgq5nlTgjd"
    "LNayrv1mCYjbOlpX13qmdb4Wpa4RVLJiQYJEPhYGCCQUpU0vlMwWr9iuj9LfOr8A5xpSlQ==";

// folder_shared [rounded]  source: src/file/folder_shared/materialiconsround/24px.svg
static const char file_rounded_folder_shared_b64z[] =
    "eJxNkEFvgzAMhf/KU+4JifEoVKWH9dLDdu19oowgUagGIhW/vk7WSZOV59jvc5TkMK8dHrdhnGvll+W+"
    "z7IQggm5mX66jKy1mRAKvu07v9SKWGHt2/A+PWplYUGM2Av9dfHJPh7uX4vHtVaf4nvilfhsL3ZT+O6H"
    "oVbjNLYq+4eRReF1OWhn2CU5OWvIgaNUZgcWdZLO3IjvYEWrylQpgT4IrmwsxDJSxvCuaBIJ0rGn6SJE"
    "HJZSU4ztpt+Q/1H4nZxfdFwvEjEhDTBKueiqXToqz0Gm2InJmmaG7OWmtLotPi/+2/EJFLZU5Q==";

// folder_zip [rounded]  source: src/file/folder_zip/materialiconsround/24px.svg
static const char file_rounded_folder_zip_b64z[] =
    "eJxdUE1vhCAQ/SuEM18zNVYb9VAvPXSv3l2XginVjUtls7++QNv0IwOP9+bNMIHmshtyfXPLpaXW+/OD"
    "lCEEEe7EuhmJSikZKyjRy3h0mh/H6dVs6/tyaumiA1ExsIiLEqtnY31LE99nHR7Xa0t/+WE+eZvtrjFd"
    "s+nJk5fZuXjRuui//T+1smukyQ3n0VsSxx5QsdLyynEQBWToQQkEViSoxT0rIkI8nooeRR0lCpXs+pOU"
    "z8igmhQDAUylbAoL5ZQTDHlOchwq0iOyMqlklSzNvpEDVAzQctzRps2/gCfJ/9GhyjU4AN6+n5P+tPsA"
    "czpj7Q==";

// format_overline [rounded]  source: src/file/format_overline/materialiconsround/24px.svg
static const char file_rounded_format_overline_b64z[] =
    "eJxVUcFugzAM/ZWIsxNiIEuZgMN62aWnfkGbZgSNQQWsqfr1s2HTNjmJ7efn5yip5lsr7h/9MNdJWJbr"
    "c5rGGFXM1Ti1aaa1TomRCD+czr2X55N7b6fxc7jUyeCj0GRZQSsRwXdtWOqE41vn48t4r5M/9dhdlrCW"
    "m6ptqsm7Rbx1fU9C4+D/9/9y06ZK27XhelqCoLEHA4XTUitjQKvCSASUGDBzGwS4wuRwllvElNenveGE"
    "rWAiuYc4YAbWyVztLGhpIVeYk7PCaVhBBsCyzVZuibR7LAE1J2iYZIFlNjXcKeNkpoqSBGkQhRrXgPax"
    "VAaBDm4gNxMGTOAr8RZHLLiVVeBb7fHzCPwTzRcl5mr/";

// grid_view [rounded]  source: src/file/grid_view/materialiconsround/24px.svg
static const char file_rounded_grid_view_b64z[] =
    "eJyNkk1zgyAQhv8KwxmERT20ox7qpZdeezeEihOrGUMl01/fXZK2aZpDZheV/XjYd6Q6rD07vo/ToeY+"
    "hP2jUjHGLObZvPTKaK0VVnDmpm4zOrnp7K5f5o9pW/PJRabRTIHOmXdD70PN6XsdXHyajzW/yMdhG3xK"
    "N1XfVIuzgb0N44igeXJ/+39rVVOpPjWg77vgGZ78UgoAX1jIQGhhpM4e8GleS6slxmgvDdlz2eaYy8nS"
    "u1yLNhegsZECAIJQn3TMBdzcgK+y+E+3MlVJI1JQmIQ333hDeHOFhzSF1SK1UhXZPWq8LFo46YCTIGJd"
    "0e+eHmm3xofz/HAWAD8K6D+khRei+QJ1FYvK";

// newspaper [rounded]  source: src/file/newspaper/materialiconsround/24px.svg
static const char file_rounded_newspaper_b64z[] =
    "eJyVklFvgjAUhf9Kw3MpvaUUWMSH+eIDvvKu2FEyBkYZNf763RadLtlMlpJLc/rd05MLi9PUkPNH15+K"
    "wIzj4SWKrLXMxmw4NpHgnEdIBET3212nw922fm+Ow2e/L4JeW8JxCYlPQIxuGzMWgdtPrbavw7kIHs5t"
    "ux+NP14umuXiqOuRvLVdh0ZDr3/239noP2TUeOvDdjQEA24EMEhozLKkCznLBHXFbfPEFVVjjfO5AOPi"
    "tpNIlpBSyVTqcfUbHj/iZLaljvu75X4DUD5jvqPMWZxh0BSeRpoTlYpx6WHyLFEZIzs3CJyAH8NKsMS1"
    "YhHOQeFLMgEV5DWnOC2XBjVcHWC02kvUpUA5FJWDyUrcmvEmdbX7HvWFbAAo5Gs5hcqkaI2KQPfchOkU"
    "ikcpuUvJVYK1rDIDqgK43L6p+wWXX4YXpSY=";

// request_quote [rounded]  source: src/file/request_quote/materialiconsround/24px.svg
static const char file_rounded_request_quote_b64z[] =
    "eJxtUsFugzAM/ZWIc2LiJAyYgMN66aG99t4yRtAYVIVBta+fDZPaqRXIL355tl+UZMNUi+tX2w154Mfx"
    "/BqG8zzDbKG/1KHRWoekCETVHU9tpU7H8rO+9N/dex501Sw0fcbRHwhfNbUf84DXU1PNb/01D+725+Z9"
    "9Mt2kdVFdqnKUXw0bUuN+q76X3/ThkV2Po5e0Lw9puBQxhRa5SCxS9igA4PScEALsTQMSLh92ThIKXeg"
    "WZCuC7dz0uhSSwSUGhJWIKQEW0zKhZRGaa5URhwSnmG0TMBKMhCnZIDCzcuP2KOjmaWGKKJabuoiApyI"
    "k8yqlVHEeYWP5KBwyQhYIEq19rqjS/3HLTmXeTux2j4RT8Q+6p/0GG5mPY19OMEz/3bCLbr11MmT4QcL"
    "0Q5jiGTCOr7BkO6bn1HxC8qWkkE=";

// rule_folder [rounded]  source: src/file/rule_folder/materialiconsround/24px.svg
static const char file_rounded_rule_folder_b64z[] =
    "eJylUz1vgzAQ/SsW89n4jPmqgKEsHcjaPSEUUF2IEhqi/Pr6nISkS4ZWRo+z3/nd88nODseWnb7McMi9"
    "bpp2L74/z7OYAzHuW19JKX2b4bFmWG9Mwzfr+rPdj9/DNveGZmbSDqXt57Gu6dtuyj2Kj30zv46n3Hvg"
    "5347dY4usrbI9k09sY/eGCs0Ds3v/fdcv8h266ljtt5KSYg6nhiOQqODEqVQCJogFTFoi2h/b7pUIrVT"
    "JSTR6SWIKgWY1BJQIEhapdFhVLsFUNwtcvWesFIpiGhGVARU+8xWsUArEQqVPrio7bYgfQAUUoF0nJEg"
    "64UBYm6RtiWNFDFZidEokQScgD3Nv8rBHS7VXILhgQg1EJSJQE1WowRiEeIS3g5gT4MxiWJgXSQJELBn"
    "4lSbL9T1lJeIvFUYAWrnYtF7lk967FnvKqsWpuTPCfK74J967fyhVTSL2j9aXd2ad6Y76tsbTQ+l+AGI"
    "lb54";

// snippet_folder [rounded]  source: src/file/snippet_folder/materialiconsround/24px.svg
static const char file_rounded_snippet_folder_b64z[] =
    "eJxVUbFygzAM/RUfs2wsgR3cgwzNkiFZuyeUAlcXcgmFXL6+EhnankDSPT/pPUx5m1t1/4rDrUq6abq8"
    "pOmyLGbJzHhtU7LWpsxIVDOczrHR51P92V7H7+G9SoZmUZaDcn4S1TV9201VIv3cN8vreK+SP+dL/z51"
    "6/G2bLfltakn9dHHyIvGofk//8tNt+XlNHWK9Y7oTFEAWuMiGk8gac5MVkSdgZ2126+MhzoSQTGjrS1z"
    "UFsTgDQB7fNaMwBWk4Cc6UDGIvjdWnIh8ptLdM7gRtWsxst5j83BGkLuct5gXDggge+KHclKD6zpZZ6l"
    "2QEGQDQBa8tKtOGEYsSJMAVOG4xaCGtSO/TGIwRmAbeZgyDVBgh7ZNc86di2COeOC86eP+6JMgIoEdlh"
    "/cRAxATX+Lb6eMhNpnzv8ju3P/jBeYs=";

// text_snippet [rounded]  source: src/file/text_snippet/materialiconsround/24px.svg
static const char file_rounded_text_snippet_b64z[] =
    "eJytkjFvgzAQhf+KxWwbH9gyVMBQlgzN2j0hFKNSiBIKUX59n52oaaWO1Vl39vO775BMcV46dvkYxnMZ"
    "uXk+PsXxuq5yTeV06uJEKRXDEbF23O2HVux3zXt3mj7HQxmN7coUItFYEXNt37m5jPx+6dv1ebqU0Y/7"
    "tT/MLlxXRVcVp7aZ2Vs/DABNY/u7/+GNq+K4mx3DvC1pSZanG1OnMuepj1DNQrpRnCRxBSHx4SAFgSci"
    "iCJ5zWWWNgpHkyIlJEgq7Y85dpoGoWEIidVkYAAfCWMxld+nv9zrlW0zTsZlDQAGc/xwbVBoUfgar4qb"
    "IqBtskbcjIKCjAJjbcHwJhuchnvmDU3/gKYHmjyaAto68xeZ/YWuQ3fOLc98B0og228wFG6v/p1ivKr/"
    "WaovZF6NXA==";

// topic [rounded]  source: src/file/topic/materialiconsround/24px.svg
static const char file_rounded_topic_b64z[] =
    "eJyNUU1PwzAM/StRz24aZ2naobYHdtmBXblvITQVpZ22skz79dgZEiBxQI6e7WfnOR/N+dKL6/s4ndss"
    "LMvxoShijDKu5HzqC62UKqgjE37aH0afH/burT/NH9NLm00+CkWmDa1MBD/0YWkzji+Dj4/ztc1+1OPw"
    "soRU7pq+a07eLeJ1GEcSmif/e/93b9E1x/0SBM3baQU25PWYozSYYINKagTDsJYVGEIktzUbLdeUaqm4"
    "vL4H9kkD1k4BSgTFLFtA6xIBOk9krp9rsdEaLGdcssCzb2KHK0C7rRw1liWoHCkwJTl06otLORATrLsz"
    "gIklRwc2gCWzuEpoIUmydAWot5X4nzaqv8RrQEyyVUK6LYve+BULenP+yu4T6up3bA==";

// upload [rounded]  source: src/file/upload/materialiconsround/24px.svg
static const char file_rounded_upload_b64z[] =
    "eJxNUE1vgzAM/StW7jFxPoBUpYedOHTX3SfKCBKFaiBS8evnRK00JXmO/F7s55zXfYDnfZrXRoRte5yK"
    "IsaI0eDyOxRaKVWwQkDoxyFsjdBWwD728WN5NkKBAm0h5eJ420KmL+fH9xbg1ohP5oO2u7at+lKHgJ9x"
    "mhoxL3Mvin8yUkBlsB06xwVJonWMtEsXCJ3vsPYpj8ZKQlVjxSTDlTQjGKw6icbnw7x+XSyBupZJUaP2"
    "LCkNb4nkIb3GKofW765TwK1z17SOu+SZAum3IXhR69sZUFtywcTKbJeR1hwTfaTp0rdd/gAEhVSk";

// upload_file [rounded]  source: src/file/upload_file/materialiconsround/24px.svg
static const char file_rounded_upload_file_b64z[] =
    "eJxVkU1vgkAQhv/KhvMw7OyH7DbAoV446NW7IgVSCkapGH99Z7HGNmzed5b5egLZ5dqI21c/XPKonabT"
    "W5LM84yzxvHcJEpKmXBFJOphf+jr+LCvPpvz+D0c82ioZyH5UYZPJNq6a9opj0J87er5fbzl0Z/83B2n"
    "dkkXWVNk57qaxEfX9zxoHOr//a/apMiSZmk47adW8NoteTQEKUsfG3R6kTUZVAQqCGlMQQUj9nK1Nuj5"
    "blCGAv8IzMaAkpUEQgKJLlQQeraSXLW8BBXL0BkrsXNhh5LgUAMDpJ4BWF4sd7FlBAdkS9JXzYMlWssD"
    "jAWKGeoS03Jjo2usS8+o1SMv2VYpizUsOnQ52yt0seIlopIYSMiHkfSMUibsQx6CrMmiWQEjBLWoDCv8"
    "Ei1s4MM2G7a9QHYa7YYcWvAlmfvzc4d/XvwAPeqA2g==";

// workspaces [rounded]  source: src/file/workspaces/materialiconsround/24px.svg
static const char file_rounded_workspaces_b64z[] =
    "eJyNkM9uwyAMxl8FcTbhr7ZsSnJozz31CdKUQdSMVAktVZ++hmraJu0w2diWvu+HEc16deT2OYW1pT7G"
    "8zvnKaUq6WpeHFdCCI4OSmzoD5Nlh344uWW+hGNLg01EYCiDSYm3o/OxpXm+jjZt5ltLf+hpPEZf5K5x"
    "XbPYIZKPcZrwojnY3/y3l3cNdwXAPPfRE9y8ewGpB6YqBYIZkFWN1azYweRYDSszM/saPVJDBu5kJxXo"
    "7RtKGlDGXsPrn5g0yGnI/ozViJP/LVTiubEw96/3l4Mf2T0AWHBfBQ==";

// approval [sharp]  source: src/file/approval/materialiconssharp/24px.svg
static const char file_sharp_approval_b64z[] =
    "eJxVT8EOwiAM/RXCmY2BKGi2HfTixav3qQiLyJaJw/j1lkWjpq/Ja/val5a30aDH1flbhW0I/YrSGGMe"
    "Z3k3GMqLoqCgwEj75uB0dmiOFzN0d3+qsNcRFRBcADCyujU2VDjxsdVx3T0q/DOP7SnYaVyXpi4HfQzo"
    "3DoHhzqv//e/WlqX1EwLgL4JFoHzThAmRmXZYszUVjzRjinC1BZKbhnfM5VanPDNMueCcCKJSEQS6eYp"
    "M7lh7x4TuVyAJMmfH7sp4e/6Bd3oT60=";

// attach_email [sharp]  source: src/file/attach_email/materialiconssharp/24px.svg
static const char file_sharp_attach_email_b64z[] =
    "eJxVUUtzgyAQ/iuMZ0B2QWs66qGnHJJTZ3JPDBGnVjPRQia/votJH5l9sM9vFygn37LrZz9MVeLm+fya"
    "piEEGbQcL22KSqmUKhJmh/2ht+Kwbz7ay/g1HKtksIEpIjTECXO2a91cJdH2nQ1v47VK/uVDd5zdkq7L"
    "ti4vtpnZqet7AhoH+9z/V5vWZdouDcTn/ewYTd4icFA7XIOH3IH2ImuUAJnnHKQ2QnMt9BrhxrZAlbDR"
    "PN+ZvuBZX4jM42aJ3iL4E6TxplEEAULJFUeBHCeB0SGNXhgZ5yiJBScVExkZWTynu43IH8EdFO63hbYq"
    "SAGhUPlD2DtkHJCiPBp66aH5KOMu8mXFTaTJiLsjDMHFW/08yiL0O/U3yXxznw==";

// attachment [sharp]  source: src/file/attachment/materialiconssharp/24px.svg
static const char file_sharp_attachment_b64z[] =
    "eJxNUMFugzAM/RUr95g4JBSq0sNOXHaa1PtEGUFiUC2IVP362dBNPbz4ObafX3KKaw/373GKtQrLcjtm"
    "WUoJU47zT59ZY0zGHQpCN/RhqZV1CtahS2/zvVYGDFgHcpeG6xK28vl0+1wCXGv1zvVg3WpdYy7moeBr"
    "GMdaTfPUqeyljUr0QEVzaLVFS2C004SHioOLOwGmgSz6ljAvZa2MINmNMD6swbIEyoEqKeVN1Wr0nsVI"
    "o/N8UtwiMAvcc2FI0y6o/wT1UzC+qgsCGV6/G4TdoLiK/1a1kxfkaBzL+W3IFRthREngmQgCEXug4iFf"
    "IX98/gU29l1k";

// cloud [sharp]  source: src/file/cloud/materialiconssharp/24px.svg
static const char file_sharp_cloud_b64z[] =
    "eJxNTzFuwzAM/Aqh3TQlUbRVRBmapUvX7kXiWgZcO2gMK8jrQ2UqCBwPvCNxPNz2Ee6/83JLJm/b9a1t"
    "SylYPK5/Y+uIqFWHgTxMY96ScWxgn4byvt6TISBwDHVWpsuWX/LxcP3eMlyS+VQ9O94df9AXPQz8TPOc"
    "zLIug2n/2WxEH8ASEp9sj9KBYIhgAwoDg3UKEa3VJijwGoe60usGOPSszIuG0RvR1s5nAo/eqioRpFa2"
    "/uywq7bQONTcoQlASoUVKDSMXa8glUV51Iz1+eMTb+5Gcw==";

// cloud_circle [sharp]  source: src/file/cloud_circle/materialiconssharp/24px.svg
static const char file_sharp_cloud_circle_b64z[] =
    "eJxNkMFqwzAMhl9F+B7FlhUnKXUP26WXnQa7jzSLA2lSFhOXPP3kroyBjD7+X7IsH9dtgPt1mlevQoy3"
    "Q1mmlDBZXL6HkrTWpVQoCP04hOgVsYJt7NPLcvdKgwZiyFoaLzE87NPx9hkDXLx6Ez8Qb8Rn/aF3BV/j"
    "NHk1L3Ovyn9lhoBeHXIDAvAEQytnMvoviqdQGP1uaqzoUQa0XxkrMHxuusKgc6ALK2BZkl1/AQQDGu6Q"
    "WbzagsG2zTo2ThIhGdmGRa5bSRyw6qS1ySvm2zFPEpCThzfyECeRLbfndfI/nX4Ae5NP9A==";

// cloud_done [sharp]  source: src/file/cloud_done/materialiconssharp/24px.svg
static const char file_sharp_cloud_done_b64z[] =
    "eJxNUDFuwzAM/Aqh3bQoUbIVxBnapUOzdi8S1zLg2kFjWIFfXzJDUQg6EndH4qTjfRvg8T3N987kdb0d"
    "6rqUgsXj8jPUzlpbi8NA7schr51xbGAb+/KyPDpjwYJjUK6M1zU/5dPx9rlmuHbmLHp2vDl+sx92N/A1"
    "TlNn5mXuTf3PRgl9ALJo+ZVajA1EDAkoYGRgICeQkEhKxAhPOuhIKxPg0LN0PkoY2ZFIK18sePQkakwQ"
    "9WTyF4eN2kLlUHKHKoCVNrKADRVj0wpE7VLczySLmqnyGPQCIVOl8K4CI7UaUTBNysKf1Oz6PP230y/n"
    "H1Jy";

// cloud_download [sharp]  source: src/file/cloud_download/materialiconssharp/24px.svg
static const char file_sharp_cloud_download_b64z[] =
    "eJxNUDFuwzAM/Aqh3TQpUbJVxBmapUvW7EXiWgZcO2gMK/DrQ2UqCBwPvCNx4OGxDfD8neZHZ9K63j/q"
    "OueM2eHyN9SWiGp1GEj9OKS1M1YMbGOfP5dnZwgIrECZ5fG2prd8PNy/1wS3zpxVT1Y2K190od3AzzhN"
    "nZmXuTf1PxtHdB6YkOTELYYGAvoI7DEICLBViMisLWCA99iXlVY3wKITZS5oGL0RuXS5Ejh0rGqIEEol"
    "dleLTbH5yqLm9pUHUhpEgXwl2LQKobAY9jM3wG5Skxorn9wlJtkkub2kL285vgDi000Y";

// cloud_off [sharp]  source: src/file/cloud_off/materialiconssharp/24px.svg
static const char file_sharp_cloud_off_b64z[] =
    "eJxNUU1PwzAM/StW7nUT5xutHNhlB3bljspYJpUNsWpF+/U8FwmhqvZT/D4cZXO9Hen7YzpfB9Pm+fOh"
    "75dl4cXz5evYi7W2B8NQO5yObR6MBEO302F5unwPxpIlCaRny+ltbuv4cfP5Ojd6G8we8ybhJmFnX+zd"
    "0PtpmgZzvpwPpv9Hg4WLo+2EU0CxsQucC0pSVNPWFU6ZEscKIkgEgVAYO8fekwpjZp86DwXXPDkOYKJs"
    "neXooHSZnGPxlFSZRs82YPnIkYRDWgH+G8edq6PjlDD18PABDRnEtXYcCo5KRK44FWqS0yQHjQWhihKw"
    "kOQVeC7uvg/KAkzPHimSJ+GcSUuDp2xFYwpugBxsXJ32MGID9pqTKvbG13CH7CchWTM7Lc9/5vc9LldG"
    "DYdBFzDOFS1cfwEBttWgUNmlu76BPu7jDz0BdOs=";

// cloud_queue [sharp]  source: src/file/cloud_queue/materialiconssharp/24px.svg
static const char file_sharp_cloud_queue_b64z[] =
    "eJxNkE1vwyAMhv+KxR0HgzFhanpYL7nsuvuUdiVS11ZLlFT99TPpZULYj/z5wm5azvD4uVynzpR5vr81"
    "zbquuAa8/Z4b75xrtMJAOY3nMnfGs4FlPK3vt0dnHDjwDDW2jse5bOn97v41Fzh25kPzxfPiuXef7mng"
    "e7xcOnO9XU+m+VdGGUMEcuj4QC1KAsGYgSIKAwN5NRmJ1AkKbOFYW1rtAI+BlYKoGJ2RqXoeHAQMpFnJ"
    "IPUUCoPHVMui9ai6o43gFIXVuGgZU6tGKmV5qi6gtpehVutUy5YwZXU8vQAUCyY6JAwJUl2VkVvdpppl"
    "CFWebsOoMlg20Ltg7CkPhFK1BKD6gABhsi+yys/6QfXn93/E+l/J";

// cloud_sync [sharp]  source: src/file/cloud_sync/materialiconssharp/24px.svg
static const char file_sharp_cloud_sync_b64z[] =
    "eJxVUstu2zAQ/BVC59WKXD5V2D5Ul15yKuC7o6iiUVUOHFUK8vUdyijSgo+luLMzQ1KHt3VU77+m+e1Y"
    "5WV5/dI027bxZvl2HxvRWjdAVGqYL8/TUD9f+p/j/fZ7fjlW87ApjSYOvVJ5uI55OVZlvV6H7evt/Vj9"
    "k9+uL0ve06fDeDrch35RP67TBKLbPPxf/4ltTodm3AvQXy9LVlB+EsOejOM29bVmLaRLsI/gCZPpgBEy"
    "li2ZlmMgg6+Eua8NOyCFA4DJ1pZNIAFLB7SEwmt2tAeuxKh6TYYDUmwd2dKmwH6X7rGXSIPAgxjwssD4"
    "LsIpPUzSp98P9WQ0OeiskGy7yCFSZDgL1LJtqRh96MUIfzGRLaKCGufOxmVZwze31pKFo+08a1TAjCNX"
    "FPYgnaPEEgn7njwbiD9EIS+aQq5LsYJ3h+sphxZ2BkraYIWD+qmW/V47A4cJ1oIrMjhLYge6ANM+nI0G"
    "1dnlcA4ff99qH/hpTn8A5VyOrw==";

// cloud_upload [sharp]  source: src/file/cloud_upload/materialiconssharp/24px.svg
static const char file_sharp_cloud_upload_b64z[] =
    "eJxNUDFuwzAM/AqhXTQlUbRVxBnaJUvW7kXiRgZcO2gMK/DrS2UqCBwPvCN10OGx3eD5M82P3uR1vb81"
    "TSkFS8Dl99Z4ImrUYSAP4y2vvfFsYBuH8r48e0NA4BnqrIzXNb/k4+H+tWa49uaseva8eT7RJ+0Gvsdp"
    "6s28zINp/tlcwhDBERJ/uA6lBcGYwEUUBgbnFRI6p01Q4DWOdaXTDfAYWFkQDaM3kqudLwQBg1NVEkit"
    "7MLFY1tt0XrU3NFGIKXCChQtY9spSGVJ9rPTt8PG2fJm+dRO1a+Vbdhr/voxxz9/0U1h";

// create_new_folder [sharp]  source: src/file/create_new_folder/materialiconssharp/24px.svg
static const char file_sharp_create_new_folder_b64z[] =
    "eJxNjk0LgzAQRP/KsveYdROkLY2Hnrz06r2gdQPxgxoS8ddXe+ptePMY5r6mAbYxTKtDiXG5aZ1zLrIp"
    "5s+gmYj0YSBI7weJDtkiJN/nx7w5JCBgCyfLvovyq+v78ooCncPn0QvbxLahlnaEtw/B4TRPPeo/jRmq"
    "puSgWHHDqayEqa32URm4iDLJiOKkzBkVi2mvwgczifdz5vxXfwEQWjlk";

// difference [sharp]  source: src/file/difference/materialiconssharp/24px.svg
static const char file_sharp_difference_b64z[] =
    "eJxVUMGOwiAQ/RXCuS0wLbiatoc9edAr96os01ipqSwYv14wMe5mJpOX997MS6a9BUvul8ndOoreXzeM"
    "xRirWFfzYhlwzllyUGLccJhMeRiOZ7vMv+7UUWci4amgSU0JmtGi72jGYTTxe7539I8ex5PHl9y3tm8X"
    "c/TkZ5ymdGh25v/+x8v6ltnXwnXwSFLsXnwVUG9BrxCCaFA0GuoH2QtZiK2quNipQqxRSL3aZS5LqkpA"
    "YqlCCai0kG9yjSUESENnlE9qiZlJxOMdnj/QPwE651RC";

// download [sharp]  source: src/file/download/materialiconssharp/24px.svg
static const char file_sharp_download_b64z[] =
    "eJxNjrsOgzAQBH/ldD34MCaECFOkckNLHwnCWTIPBctGfH0gVbTdzqy09RZG2Cc3bxrZ+/UhRIwxjXm6"
    "fEYhiUicBgIPdmSvUSqEYIf4XHaNBARSwdVF23v+4aZeX56h19ienKUKUhnq6EB4W+c0zss8oPjTsgoq"
    "TlSXmyrcTOFKOJOUR1tAdg+SMxUSaYrjGl1vmi82uTPu";

// download_done [sharp]  source: src/file/download_done/materialiconssharp/24px.svg
static const char file_sharp_download_done_b64z[] =
    "eJxNjrsOgzAQBH/ldL3P5jAQIkyRioK06SOFYEvmoWBhxNcHUqXYZna02mpZe9gGPy4GbQjzVcoYI8WU"
    "pk8vWSklDwPBdq63wSBrhNV18TZtBhUoYA0ni+4V7K+uq/kZLLwM3o/esl5ZN+qhdoS3897gOI0dyj8t"
    "g+Rik8NrslXwPmjKBVPRHlxR4VkkVAJTfqZNCtCegUVJGkpK93Pq/Fh/AbQCN6Y=";

// download_for_offline [sharp]  source: src/file/download_for_offline/materialiconssharp/24px.svg
static const char file_sharp_download_for_offline_b64z[] =
    "eJxVUMFuwjAM/ZUo56SJQ0YEanvYLlw4IXEvEJJqWYra0CC+HrdjGsiW9eT3nm25HEZHbj8hDhX1KV3W"
    "QuSci7wout4JJaUUqKDExuYQLD80x2/Xd9d4qmi0mUgMpTEp8bZ1PlV0wmNr82d3q+gLn9tT8jNdl64u"
    "e3tM5NyGgIO6aN/9/1pRl8LNhkuTPMG1W1BMfS0LvWII2BOAGvSEQP7mAJI/GxzkDkzxAbOMqTvZAmB/"
    "v/Rq1H4RuGYaC9cbgIk0DMzGjFx5FIG5/x0xfaJ+AN6uUvw=";

// downloading [sharp]  source: src/file/downloading/materialiconssharp/24px.svg
static const char file_sharp_downloading_b64z[] =
    "eJxVkk9zgjAQxb9KhnOyZENCpKMeysVDPXWmd/9QcErRUSqOn74vQasdMSy72d97WZiezrW4fLfdaZY0"
    "fX94SdNhGGjIaH+sU6O1TrEjEVW3WreVWq82X/Vx/9NtZ0lXDULjZyyuRDTVrm76WRLi864aXveXWfJU"
    "H3bbvonl+bSeT4/Vphefu7YFaN9V//sfe9P5NK1jA67Dqm8ElJc8ocxISyYvOaeJlRlpJ9mRZmnIIMxw"
    "1+6MxWyYbC418QQ5XyDyORoKyZSbtwfqKpZcUJFJ5ib0iY3SZBRCVqwyyCA2rBwaYhtLT1yih72coCIR"
    "eicLclbeSQEat8Jn0cIJkljgCSREwZMOdJj4o4smqJpy5LEN/kcZHBEneBADPhvFxrNGGmzL6JdlwEXb"
    "bVDL4iLKG2ZE3vE+ji2ybljz4eHk7Ba+ddK1TrkFxxo/S8KydtB0qlAWs8UNRXfCiJEii4nERNwtSh9e"
    "lSWXS4v5FZg9hN5jFlCLpxv9en/58Y+vcP4LdvWgOw==";

// drive_file_move [sharp]  source: src/file/drive_file_move/materialiconssharp/24px.svg
static const char file_sharp_drive_file_move_b64z[] =
    "eJxVT70OgyAQfhXCLIKnsT9Rh04OdXXXSsGUolEKxqcvmjRtc99wue8vl81WoOWp9Jxjacx4ptQ5F7o4"
    "HCZBgTFGvQIjrptWcdI2t4eYhpfucqy5Q8wPJB4YSd4LaXK87bbn7jIsOf7hXd8ZudNFJops4jeD7r1S"
    "PmjQ/N//1dIio2I3jI2RyNdWAEFaRqAIECjBRqkEVqcrqiIIooMlcXm0BGRSn1QSJNf9un6Ctm+KN5/z"
    "Rs4=";

// drive_file_move_rtl [sharp]  source: src/file/drive_file_move_rtl/materialiconssharp/24px.svg
static const char file_sharp_drive_file_move_rtl_b64z[] =
    "eJxVTssOgyAQ/BXCuQisRJNGPPTkxat3H1RMKRqlYPz6Yi9ts7PJJDM7O8XmR7Q/jd0k1s4tV0pDCElI"
    "k3kdKTDGaHRgpGzbGUW6tn+M6/yyg8RWBcTigIjASKtp1E7ik/tJhdu8S/yjh2lw+iOXxap6h+6TMTFl"
    "tur/+GukZbG0TqP4rAa4ZBUHQ4BABZ5nGliTHajmcOG5IYIIE9enWnjQRDQ8P86As375Bo3SQvY=";

// drive_file_rename_outline [sharp]  source: src/file/drive_file_rename_outline/materialiconssharp/24px.svg
static const char file_sharp_drive_file_rename_outline_b64z[] =
    "eJxlUNFugzAM/BUrT5tETQKEwAQ87E9omwY0SBBkDf37GTS2VVMcXyTf5WxXy93AOg52qVnn/fQWxyEE"
    "DCm62cQJ5zwmBgNt2/OgT+f28mFm92mvNbM6AKeTZBQMOt2bztdse997Hd7dWrM/9dBffbeXm8o01awv"
    "Hm79MNBHzupn/S83bqrY7AKKyQ0P4yxMrreeGhYyEjkIESXkcmSRb6J/1AR5HikUJaREwUQSkiBHJTcU"
    "EgvScix3z727oyOJKQM/t3a5uXms2dj6uV9fOCquBJy+8RkKclBJUeoTT0GkmKlcvv4MlqIsGdB+RIZZ"
    "weBRswx5cUy7X1p78wXMR3B4";

// drive_folder_upload [sharp]  source: src/file/drive_folder_upload/materialiconssharp/24px.svg
static const char file_sharp_drive_folder_upload_b64z[] =
    "eJxVT70OwiAQfhXCXAocpDGmdHBi0NW9WoRGpKYiGJ9eamLU3Ddc7vvLtbdk0ePiw01hF+N1TWnOuc6i"
    "nmZLgTFGiwIjE/qDN+TQH892nu5hUDiYjFgZkAUYOTNaFxVe9jSavJkeCv/weRyie9Nda7t2NseITqP3"
    "JWgK5t//1dKupfZtuPbRoVK7A6gazcETIKAh8cYB2zdPtOOi4iJJRyARqVde1owTueVNOWsunp+w5aPu"
    "BbSIR3k=";

// file_download [sharp]  source: src/file/file_download/materialiconssharp/24px.svg
static const char file_sharp_file_download_b64z[] =
    "eJxVjzEPgjAQhf9K0xkoFBAxtIMTg6zuILUl1pZAbQm/3kJi1NwNl3vve5erZsvB8pRqJlAYM54Qcs5F"
    "Lo30xBGO4xh5BwRMtZ1kYdfeHnzSL9UTqJgDsS+c+YZAsIELQ+A224G5s14I/NHd0Buxy7TitJrYzYD7"
    "IKUP0or9818vohXiOzC2RgB/tknKoBRhdk3r0h7qXBZBcdl2K2jyIDlaLJLMhrjO1w+9vUDftXtEcw==";

// file_download_done [sharp]  source: src/file/file_download_done/materialiconssharp/24px.svg
static const char file_sharp_file_download_done_b64z[] =
    "eJxVkNtuwjAMhl/FynXmnBpop7YXexMOWRotJFXJCLz9TLUxkG3J1u/DJ/fni4frKabzwKZS5nchaq1Y"
    "DebFCy2lFNTBwKXdPrq3/e7w5Zf8nY4DS66CJNMNOYPJBT+Vgd3zS3D1I18H9qTXcCzTKo+9H/vFHQp8"
    "hhhpUU7udf6/V4y98OsA+ZzjzecEcw6pELCWqAy32ChQLW41b6BDa7gyqDqwqFveYmfBYLvlSqLZ/Oob"
    "lPq+eoV4HH7cVYRA8JbBjYr2D2IN+sb4AxVuVfk=";

// file_download_off [sharp]  source: src/file/file_download_off/materialiconssharp/24px.svg
static const char file_sharp_file_download_off_b64z[] =
    "eJxVUE2PwiAQ/SuEM+WrLRXT9rAnD3jde1UsjUhNZYvx1y/jHlbD5GWG997MZNr7OqLH1Yd7h12Mty1j"
    "KSWaSjovI5Occ5YVGNkwHLwtDsPxMi7zTzh1ONiEeH6yyoGRs9PoYochXyebvuZHh9/4NJ2ie9F9u9hj"
    "ROfJ+9xlDvbT/C9kfXsbokN52F4TRUXzXTq1Klf5oqS1JgDmj3mivRRUaPJCI+lGEAAjaKlJRaU0ICN6"
    "V/uGNJ5nawFgRA3/YrOrV+mEzIWXVIFbCWTemj5hIThH/wuGP1MR";

// file_open [sharp]  source: src/file/file_open/materialiconssharp/24px.svg
static const char file_sharp_file_open_b64z[] =
    "eJxVUMFuwyAM/RXEmQAmkIYpyWGnHNJr7mnLICpLqpSFql8/qDRtk61ny37Pttzcd4sen365t9iFcHtj"
    "LMZIY0nXzTLBOWeJgZFZppM3xWk6X+22fi2XFi8mIp5MyOQYOTNbF1qc83028X19tPhPP86X4F7trrFd"
    "s5lzQB+z92nQupj/+l8u6xpmX4LbFBxKa48giejlLrgD2IvaqbEecu2JjlASPZZUDVBTRXQPZS4eiABa"
    "VSNUTqW4C1cIKqQXVCuSwRdAJZAMA2gCOiWek0zq4fD8OSJ/ovsGjBRT1w==";

// file_upload [sharp]  source: src/file/file_upload/materialiconssharp/24px.svg
static const char file_sharp_file_upload_b64z[] =
    "eJxVj00OwiAQha9CWEuhlVZj2i5cudBD9AcZIkLTIjQ9vbSJUTOzmMz33ptMOXmJ5qc2U4XBueFEaQgh"
    "CfvEjpJmjDEaFRgJ07RakLbpHnK0L9NX2IiAWKyMx8YIhJLgKrzOXolwtnOFf3hQvYMN16Wsy1F0Dt2V"
    "1jHIGvHv/2ppXVK5GYbGAYpnb/kuZcB9AYUnBXBNDuRwXZcLWtnRZ5ByT7JLvnzs6w/1GwSrROY=";

// folder [sharp]  source: src/file/folder/materialiconssharp/24px.svg
static const char file_sharp_folder_b64z[] =
    "eJxNzTELgzAQhuG/ctyuOa/BoRiHTlm6uhdMc4FURUMi/vpqp67f+8DXbdnD/onTZlBSWu5KlVLqcqvn"
    "1SsmInUKBHHBSzLIGiEHVx7zbpCAgDVcWwljkl/uu+WVBEaDz7ML68za0kAHwjvEaHCaJ4fqjzUE2nJu"
    "WmEaWttwrLji4zLXef8F6vQvZQ==";

// folder_copy [sharp]  source: src/file/folder_copy/materialiconssharp/24px.svg
static const char file_sharp_folder_copy_b64z[] =
    "eJxVT7sOwjAM/BUrc9s8Wp5qOzAxwMpeICQRIalKaApfj6lAgHw+WbLPPpfXXsFwse5aER1Cu6Q0xpjF"
    "PPOdooIxRnGCgHTN3sp03xzOqvM3d6yIkxEYhigQBLQ0SoeKvOreyLjyQ0V++tEcgx7bdanqspOHACdj"
    "LS7yTv7rv7O0LqkaBYjW27vyDlpvXEDDeTIFPqbgINib+QJypJe0bYIGtLoVeVLodGFTkYr1JGN8M0n4"
    "TPP5rnh8boyJz9ZPva1OYg==";

// folder_delete [sharp]  source: src/file/folder_delete/materialiconssharp/24px.svg
static const char file_sharp_folder_delete_b64z[] =
    "eJxVj0sPgjAMx7/KsjOwrYKvAAdPXLxyR50rcQ6CczN+ejeNr7Rp+vj927S8OEVuZ20uFUVrxzVj3vvM"
    "z7JhUgw45ywQlEjT7bRMd93+pKbhag4VNdITHgzy4JSg7BXaisbc9dJvhltFf+a+P1h8jutS1eUk95Yc"
    "e63DosHIf/2XZXXJ1FMwdhZJOLsFSOZO5A20OS41JNAA3MlWzLMiEbxdYQpONCKErEDRigUWLi1eOW8i"
    "9qFjN9BpjtDG4v6+F5+uHyIlUHo=";

// folder_off [sharp]  source: src/file/folder_off/materialiconssharp/24px.svg
static const char file_sharp_folder_off_b64z[] =
    "eJxdkN1uwyAMhV/F4poZMFm6TEku9ib9oQSNQZSy0r19nUjVtso2PpLPhyz3l6uH21dMl0FMpczvStVa"
    "sVrMi1ektVbsEODS/hDdy2F//PRL/k6nQSRXQXNQwylgcsFPZRCrvgZXP/JtEH/mNZzKtI3H3o/94o4F"
    "ziFG/ign95//9aqxV34DOOccf3xOMOeQCi9sSLZgtGygxTfLjUiaDs1uFe3KPhOERnKBxraTFl8NkGyY"
    "5UYazI7ZVZDGppNk0bLBIEt+HrtsxUcZ76V6Vmw=";

// folder_open [sharp]  source: src/file/folder_open/materialiconssharp/24px.svg
static const char file_sharp_folder_open_b64z[] =
    "eJxNjrsKwzAQBH/luN7W6SJECJGLVGrSug/Y8Qn8IhaS8ddHTpV2Z3bZ+5YG2Kdx3hxKjOtNqZxznS/1"
    "8hkUE5EqBoL0YZDokA1CCn1+LLtDAgI2cGY5dFF+uLmvryjQOXwWLmwSG08tHQjvMI4O52XuUf1pzGC9"
    "5rHiij0nbYWptcdUMWj2pr2KtkmXgVI63zRfMbwz4w==";

// folder_shared [sharp]  source: src/file/folder_shared/materialiconssharp/24px.svg
static const char file_sharp_folder_shared_b64z[] =
    "eJxNTz2PwzAI/SuIHRsTK+2d6g6dstza/dTm4kj5qBrLrvLrz3TqADx4Dz04bXmA1zwtW8CY0uPb2lKK"
    "KY1Zn4MVZrZVgRD7cYgpoHiEPPblsr4CMjCIB52V8Z7imz6fHr8pwj3gT+Wj+Cy+4yvvCH/jNAVc1qVH"
    "+yETgbZzMpGQdJJdG4Wv7T7TAZqbM05dwHzVJBtpJdGoUDdAi/b77OEY6ZjJ3ZicaRoQ0x4q6Uk2DxVD"
    "PTa7Xd31rfM/ofVCYQ==";

// folder_zip [sharp]  source: src/file/folder_zip/materialiconssharp/24px.svg
static const char file_sharp_folder_zip_b64z[] =
    "eJxdT8sOgyAQ/BXCWQS2jTGNeOjJi1fvPiiYUjRKxfTri6ZNH9lHZjMzu9lsXhRab8bOAmvnxhOl3vvY"
    "H+JhUhQYYzQoMJK2bowkTd1e1TTcbSewlR6xEHAMiZGWvdJO4A0vvfTnYRX4i/d95/RO55nKs0m2Dl16"
    "Y8Kiwcpf/0dL84yq3TDWTqNwtuQQJYYAgQIWnmhgVVJweKCSpxEHTWABvRV5NbKN5A9W6a6BKjjfR7ZP"
    "8yfyi09V";

// format_overline [sharp]  source: src/file/format_overline/materialiconssharp/24px.svg
static const char file_sharp_format_overline_b64z[] =
    "eJxVUE1vgzAM/StRzs4XAaVUwGG79NLTpN1bmgU0BhVkpOqvn003bZOT+Nl+70VJtayB3T6Gcal5F+N1"
    "r1RKSSYrpzmoTGutkMGZH0/nwYvzqX0P8/Q5Xmo++sQ0Rpbj4qzzfehizQmvvU9P063mf+apv8RuGzdV"
    "aKrZt5G99cOARtPo/+t/uaqpVNgE11PsGF57NCXYNTsUr/Zgyjs7mgxcK6zcOdDCgZXGYnKthq1HNTiK"
    "xYlHIdwzmhhNhSmI5IBcHmZmJwvWikzmJRrmskCozQZwv5SyMIAHKTAt2AMiAAEimJyU5ALfbvefZ9Bf"
    "Nl9wfF78";

// grid_view [sharp]  source: src/file/grid_view/materialiconssharp/24px.svg
static const char file_sharp_grid_view_b64z[] =
    "eJyNkE0OwiAQha9C2NuhrQtjgIU36Q8CEcFQLPX2TptU68pmmMlL5nsPAh9GTaa784OgJqXHGSDnXOS6"
    "CFFDxRgDJChRvmmdOrRNd9MxPH0vqFeZMKzqiIcSo6w2SdBZj1blS5gE3eyz7ZNZ1pJryaPqErla5zAo"
    "ePXr/7IgOejFsHpW7vTBUOFVNSWvecIurvwPlnsTy23k/Nql8dvkG/RRZY4=";

// newspaper [sharp]  source: src/file/newspaper/materialiconssharp/24px.svg
static const char file_sharp_newspaper_b64z[] =
    "eJxdkM1ygyAUhV+FYY3CBX876qKrLMzWvTEUnFLMGCqZPH3R2ibtXObO5ZzvwEB1XRS6fRh7rbF27vJC"
    "qfc+9iKeZkU5Y4wGAiNp+5OR0akf3tU8fdpzja30iIXiSVgYaTkq7Wq8zsso/et0q/GT78ez05vdVKqp"
    "Zjk49DYaEw6arPybf7C0qajaApfeaRSuPXJOhIkgznKythaKdRQt5CTZ9mksxI5kO/Ivsif2wDffilXc"
    "hEAvUAyM/BYyPPRO3NERgEB5SJYo03kHZVCCBaWO8iXiz1L6kNJdgkPSFRqyDuD+87T1f5svrHZnHQ==";

// request_quote [sharp]  source: src/file/request_quote/materialiconssharp/24px.svg
static const char file_sharp_request_quote_b64z[] =
    "eJxVT01vwjAM/StRzk3z0WQrqO1hpx7g2nuBLK4oKSpZgvj1OHDYJlvWs9/zV3OLjtwvs7+1FEK4bjlP"
    "KZWpKpfVcSWE4KigxPrxMFt2GI9nty4//tRSbxMRaEqjUwJ2chBamnGcbPpa7i39w6fpFOBFd43rmtUe"
    "A/me5hkHLd7+7//V8q65jgEI7ttLXaheRyVAfgz1LqcPspemkAqYjhJ0NMAUAgxM9pvIFNbeyIAaNpBJ"
    "NchXX1XUQ1WanfwsTVH3snrkbRxvyy93T7KFUNs=";

// rule_folder [sharp]  source: src/file/rule_folder/materialiconssharp/24px.svg
static const char file_sharp_rule_folder_b64z[] =
    "eJxVkMFuwyAQRH8FcbaBBYybyvahpxzItXcnocYqtSOHmihfX6Cp4gq0Gg1vZ8U213VAty83XVtsvb+8"
    "UhpCIEGQeRkoZ4zRSGBkpv7oTHnsT5/DMn9P5xZPJiAWD5fxYmTNOFjf4qTX0YS3+dbizXsYz97m564Z"
    "umYxJ48+Rudi0DyZ//1PlnbNpfcWxXkHzgu1B+5KXvI9X0FZzt7VHR1q8iIKULoqQBCoHRAJZSpZFVkJ"
    "UskylaenH30xAepsCg27AiSpdjo6VdQKaVDJiniuaQ6IP0hmSGQHNgzLXbAJYjn6l3kMu6ff0biLtOLu"
    "B1muZF4=";

// snippet_folder [sharp]  source: src/file/snippet_folder/materialiconssharp/24px.svg
static const char file_sharp_snippet_folder_b64z[] =
    "eJxVT01vwyAM/SuIM59moemU5NBTLr3mnrYMojJSpRSq/vpBL9vkD1l+z352d08WPb99uPfYxXj75Dzn"
    "zLJi62Y5CCF4YWBkwnzyhp7m89Vu6yNcehxMRqIYfBTHyJnFutjjWqfF5MP67PEfPC+X6N7w0Nmh28w5"
    "oq/F+7JoDeb//C+XD91tjg4VvaMEoj0FCiMkqR2ISY8SXugo90TuPNVETHunWOOBNaTEJHcVbVjbEilK"
    "XzINpKakmGo9VUQk2oxvxqtq8XJZfXj4AYupThE=";

// text_snippet [sharp]  source: src/file/text_snippet/materialiconssharp/24px.svg
static const char file_sharp_text_snippet_b64z[] =
    "eJxVT7sOgzAM/JUoM5AHFYEKGDqxsLLzSBPUNCBIE8TXN1SqaGUP9t35bOerFWB7Kr0WUBozXxFyzkUu"
    "jqZFIIoxRl4BAddtp3jYtf1DLNNLDwXU3AHsg158QiD5KKQp4FHbkbvbtBXwh3fjYOSHLnNR5gvvDbiP"
    "SnmjSfP/+VOLynxujQR+X01JkKkwCZMqtiSVJG2yHdQsYJJZWrGG+Y6wgLCK2ZBKghvyheITivfDFPkT"
    "js/KNw8DSho=";

// topic [sharp]  source: src/file/topic/materialiconssharp/24px.svg
static const char file_sharp_topic_b64z[] =
    "eJxVT8sOgyAQ/BXCWQW2hphGPfTkxat3HxRMKRqlYPr1hfbQNruHzczsTKbcnUTHXZu9wsra9UyI9z7z"
    "p2zZJAFKKQkKjITpBy3SoR9vclseZqqwER7RMJCHxUiJWSpb4Xi7WfjLclT4h/fzZNWbrktZl5sYLbrO"
    "WgejxYj//6+W1OXaW4VCXssg4TqFFBpwjCugHW8YPFHL8oTxhrsUVNExHpEiYfBBGHRBFI1IiI1t6heU"
    "kkaq";

// upload [sharp]  source: src/file/upload/materialiconssharp/24px.svg
static const char file_sharp_upload_b64z[] =
    "eJxNjr0OwjAQg1/ldHuaI4RUoKYDUxdWdqSWXqT0RzRKqj49CRPyZn+23GxxhH3y82aRQ1hvUqaUqnSu"
    "ls8oFRHJTCDw4EYOFpVGiG5I92W3SECgNBQvuT7wL26b9RUYeouPnLPSUemOnnQgvJ33FudlHlD+YVc4"
    "GTZRGNZe1EVQs47mmEQe51Ne6C5RqKO0yp32C3ZFNJk=";

// upload_file [sharp]  source: src/file/upload_file/materialiconssharp/24px.svg
static const char file_sharp_upload_file_b64z[] =
    "eJxVT70OgjAQfpWmM/SPQtAAgxMDrOygtSXWYrC2xKe3YIyau+Hu+7tccXcSLFdt7iVU1t72GHvvkU/Q"
    "NEvMCCE4KCAQph+0iIf+eJHz9DCnEhrhAQnFeGgIlBilsiVcZzcKf5iWEv7wfjxZtdFVIatiFkcLzqPW"
    "IWgy4t//1eKqwHIz3HqrQDjbUh6xmjtGFM26vFnXJ2hpEtHUcRUzF/M61xwRGvOGZgGuafJW7LoEpQ3N"
    "URrtVvATv/5YvQDTG0t9";

// workspaces [sharp]  source: src/file/workspaces/materialiconssharp/24px.svg
static const char file_sharp_workspaces_b64z[] =
    "eJyNkM9uwyAMxl8FcTbhr7ZsSnJozz31CdKUQdSMVAktVZ++hmraJu0w2diWvu+HEc16deT2OYW1pT7G"
    "8zvnKaUq6WpeHFdCCI4OSmzoD5Nlh344uWW+hGNLg01EYCiDSYm3o/OxpXm+jjZt5ltLf+hpPEZf5K5x"
    "XbPYIZKPcZrwojnY3/y3l3cNdwXAPPfRE9y8ewGpB6YqBYIZkFWN1azYweRYDSszM/saPVJDBu5kJxXo"
    "7RtKGlDGXsPrn5g0yGnI/ozViJP/LVTiubEw96/3l4Mf2T0AWHBfBQ==";

static const BaseSVGIcon kIcons[] = {
    { "file", OUTLINED, "approval", "src/file/approval/materialiconsoutlined/24px.svg", file_outlined_approval_b64z },
    { "file", OUTLINED, "attach_email", "src/file/attach_email/materialiconsoutlined/24px.svg", file_outlined_attach_email_b64z },
    { "file", OUTLINED, "attachment", "src/file/attachment/materialiconsoutlined/24px.svg", file_outlined_attachment_b64z },
    { "file", OUTLINED, "cloud", "src/file/cloud/materialiconsoutlined/24px.svg", file_outlined_cloud_b64z },
    { "file", OUTLINED, "cloud_circle", "src/file/cloud_circle/materialiconsoutlined/24px.svg", file_outlined_cloud_circle_b64z },
    { "file", OUTLINED, "cloud_done", "src/file/cloud_done/materialiconsoutlined/24px.svg", file_outlined_cloud_done_b64z },
    { "file", OUTLINED, "cloud_download", "src/file/cloud_download/materialiconsoutlined/24px.svg", file_outlined_cloud_download_b64z },
    { "file", OUTLINED, "cloud_off", "src/file/cloud_off/materialiconsoutlined/24px.svg", file_outlined_cloud_off_b64z },
    { "file", OUTLINED, "cloud_queue", "src/file/cloud_queue/materialiconsoutlined/24px.svg", file_outlined_cloud_queue_b64z },
    { "file", OUTLINED, "cloud_sync", "src/file/cloud_sync/materialiconsoutlined/24px.svg", file_outlined_cloud_sync_b64z },
    { "file", OUTLINED, "cloud_upload", "src/file/cloud_upload/materialiconsoutlined/24px.svg", file_outlined_cloud_upload_b64z },
    { "file", OUTLINED, "create_new_folder", "src/file/create_new_folder/materialiconsoutlined/24px.svg", file_outlined_create_new_folder_b64z },
    { "file", OUTLINED, "difference", "src/file/difference/materialiconsoutlined/24px.svg", file_outlined_difference_b64z },
    { "file", OUTLINED, "download", "src/file/download/materialiconsoutlined/24px.svg", file_outlined_download_b64z },
    { "file", OUTLINED, "download_done", "src/file/download_done/materialiconsoutlined/24px.svg", file_outlined_download_done_b64z },
    { "file", OUTLINED, "download_for_offline", "src/file/download_for_offline/materialiconsoutlined/24px.svg", file_outlined_download_for_offline_b64z },
    { "file", OUTLINED, "downloading", "src/file/downloading/materialiconsoutlined/24px.svg", file_outlined_downloading_b64z },
    { "file", OUTLINED, "drive_file_move", "src/file/drive_file_move/materialiconsoutlined/24px.svg", file_outlined_drive_file_move_b64z },
    { "file", OUTLINED, "drive_file_move_rtl", "src/file/drive_file_move_rtl/materialiconsoutlined/24px.svg", file_outlined_drive_file_move_rtl_b64z },
    { "file", OUTLINED, "drive_file_rename_outline", "src/file/drive_file_rename_outline/materialiconsoutlined/24px.svg", file_outlined_drive_file_rename_outline_b64z },
    { "file", OUTLINED, "drive_folder_upload", "src/file/drive_folder_upload/materialiconsoutlined/24px.svg", file_outlined_drive_folder_upload_b64z },
    { "file", OUTLINED, "file_download", "src/file/file_download/materialiconsoutlined/24px.svg", file_outlined_file_download_b64z },
    { "file", OUTLINED, "file_download_done", "src/file/file_download_done/materialiconsoutlined/24px.svg", file_outlined_file_download_done_b64z },
    { "file", OUTLINED, "file_download_off", "src/file/file_download_off/materialiconsoutlined/24px.svg", file_outlined_file_download_off_b64z },
    { "file", OUTLINED, "file_open", "src/file/file_open/materialiconsoutlined/24px.svg", file_outlined_file_open_b64z },
    { "file", OUTLINED, "file_upload", "src/file/file_upload/materialiconsoutlined/24px.svg", file_outlined_file_upload_b64z },
    { "file", OUTLINED, "folder", "src/file/folder/materialiconsoutlined/24px.svg", file_outlined_folder_b64z },
    { "file", OUTLINED, "folder_copy", "src/file/folder_copy/materialiconsoutlined/24px.svg", file_outlined_folder_copy_b64z },
    { "file", OUTLINED, "folder_delete", "src/file/folder_delete/materialiconsoutlined/24px.svg", file_outlined_folder_delete_b64z },
    { "file", OUTLINED, "folder_off", "src/file/folder_off/materialiconsoutlined/24px.svg", file_outlined_folder_off_b64z },
    { "file", OUTLINED, "folder_open", "src/file/folder_open/materialiconsoutlined/24px.svg", file_outlined_folder_open_b64z },
    { "file", OUTLINED, "folder_shared", "src/file/folder_shared/materialiconsoutlined/24px.svg", file_outlined_folder_shared_b64z },
    { "file", OUTLINED, "folder_zip", "src/file/folder_zip/materialiconsoutlined/24px.svg", file_outlined_folder_zip_b64z },
    { "file", OUTLINED, "format_overline", "src/file/format_overline/materialiconsoutlined/24px.svg", file_outlined_format_overline_b64z },
    { "file", OUTLINED, "grid_view", "src/file/grid_view/materialiconsoutlined/24px.svg", file_outlined_grid_view_b64z },
    { "file", OUTLINED, "newspaper", "src/file/newspaper/materialiconsoutlined/24px.svg", file_outlined_newspaper_b64z },
    { "file", OUTLINED, "request_quote", "src/file/request_quote/materialiconsoutlined/24px.svg", file_outlined_request_quote_b64z },
    { "file", OUTLINED, "rule_folder", "src/file/rule_folder/materialiconsoutlined/24px.svg", file_outlined_rule_folder_b64z },
    { "file", OUTLINED, "snippet_folder", "src/file/snippet_folder/materialiconsoutlined/24px.svg", file_outlined_snippet_folder_b64z },
    { "file", OUTLINED, "text_snippet", "src/file/text_snippet/materialiconsoutlined/24px.svg", file_outlined_text_snippet_b64z },
    { "file", OUTLINED, "topic", "src/file/topic/materialiconsoutlined/24px.svg", file_outlined_topic_b64z },
    { "file", OUTLINED, "upload", "src/file/upload/materialiconsoutlined/24px.svg", file_outlined_upload_b64z },
    { "file", OUTLINED, "upload_file", "src/file/upload_file/materialiconsoutlined/24px.svg", file_outlined_upload_file_b64z },
    { "file", OUTLINED, "workspaces", "src/file/workspaces/materialiconsoutlined/24px.svg", file_outlined_workspaces_b64z },
    { "file", ROUNDED, "approval", "src/file/approval/materialiconsround/24px.svg", file_rounded_approval_b64z },
    { "file", ROUNDED, "attach_email", "src/file/attach_email/materialiconsround/24px.svg", file_rounded_attach_email_b64z },
    { "file", ROUNDED, "attachment", "src/file/attachment/materialiconsround/24px.svg", file_rounded_attachment_b64z },
    { "file", ROUNDED, "cloud", "src/file/cloud/materialiconsround/24px.svg", file_rounded_cloud_b64z },
    { "file", ROUNDED, "cloud_circle", "src/file/cloud_circle/materialiconsround/24px.svg", file_rounded_cloud_circle_b64z },
    { "file", ROUNDED, "cloud_done", "src/file/cloud_done/materialiconsround/24px.svg", file_rounded_cloud_done_b64z },
    { "file", ROUNDED, "cloud_download", "src/file/cloud_download/materialiconsround/24px.svg", file_rounded_cloud_download_b64z },
    { "file", ROUNDED, "cloud_off", "src/file/cloud_off/materialiconsround/24px.svg", file_rounded_cloud_off_b64z },
    { "file", ROUNDED, "cloud_queue", "src/file/cloud_queue/materialiconsround/24px.svg", file_rounded_cloud_queue_b64z },
    { "file", ROUNDED, "cloud_sync", "src/file/cloud_sync/materialiconsround/24px.svg", file_rounded_cloud_sync_b64z },
    { "file", ROUNDED, "cloud_upload", "src/file/cloud_upload/materialiconsround/24px.svg", file_rounded_cloud_upload_b64z },
    { "file", ROUNDED, "create_new_folder", "src/file/create_new_folder/materialiconsround/24px.svg", file_rounded_create_new_folder_b64z },
    { "file", ROUNDED, "difference", "src/file/difference/materialiconsround/24px.svg", file_rounded_difference_b64z },
    { "file", ROUNDED, "download", "src/file/download/materialiconsround/24px.svg", file_rounded_download_b64z },
    { "file", ROUNDED, "download_done", "src/file/download_done/materialiconsround/24px.svg", file_rounded_download_done_b64z },
    { "file", ROUNDED, "download_for_offline", "src/file/download_for_offline/materialiconsround/24px.svg", file_rounded_download_for_offline_b64z },
    { "file", ROUNDED, "downloading", "src/file/downloading/materialiconsround/24px.svg", file_rounded_downloading_b64z },
    { "file", ROUNDED, "drive_file_move", "src/file/drive_file_move/materialiconsround/24px.svg", file_rounded_drive_file_move_b64z },
    { "file", ROUNDED, "drive_file_move_rtl", "src/file/drive_file_move_rtl/materialiconsround/24px.svg", file_rounded_drive_file_move_rtl_b64z },
    { "file", ROUNDED, "drive_file_rename_outline", "src/file/drive_file_rename_outline/materialiconsround/24px.svg", file_rounded_drive_file_rename_outline_b64z },
    { "file", ROUNDED, "drive_folder_upload", "src/file/drive_folder_upload/materialiconsround/24px.svg", file_rounded_drive_folder_upload_b64z },
    { "file", ROUNDED, "file_download", "src/file/file_download/materialiconsround/24px.svg", file_rounded_file_download_b64z },
    { "file", ROUNDED, "file_download_done", "src/file/file_download_done/materialiconsround/24px.svg", file_rounded_file_download_done_b64z },
    { "file", ROUNDED, "file_download_off", "src/file/file_download_off/materialiconsround/24px.svg", file_rounded_file_download_off_b64z },
    { "file", ROUNDED, "file_open", "src/file/file_open/materialiconsround/24px.svg", file_rounded_file_open_b64z },
    { "file", ROUNDED, "file_upload", "src/file/file_upload/materialiconsround/24px.svg", file_rounded_file_upload_b64z },
    { "file", ROUNDED, "folder", "src/file/folder/materialiconsround/24px.svg", file_rounded_folder_b64z },
    { "file", ROUNDED, "folder_copy", "src/file/folder_copy/materialiconsround/24px.svg", file_rounded_folder_copy_b64z },
    { "file", ROUNDED, "folder_delete", "src/file/folder_delete/materialiconsround/24px.svg", file_rounded_folder_delete_b64z },
    { "file", ROUNDED, "folder_off", "src/file/folder_off/materialiconsround/24px.svg", file_rounded_folder_off_b64z },
    { "file", ROUNDED, "folder_open", "src/file/folder_open/materialiconsround/24px.svg", file_rounded_folder_open_b64z },
    { "file", ROUNDED, "folder_shared", "src/file/folder_shared/materialiconsround/24px.svg", file_rounded_folder_shared_b64z },
    { "file", ROUNDED, "folder_zip", "src/file/folder_zip/materialiconsround/24px.svg", file_rounded_folder_zip_b64z },
    { "file", ROUNDED, "format_overline", "src/file/format_overline/materialiconsround/24px.svg", file_rounded_format_overline_b64z },
    { "file", ROUNDED, "grid_view", "src/file/grid_view/materialiconsround/24px.svg", file_rounded_grid_view_b64z },
    { "file", ROUNDED, "newspaper", "src/file/newspaper/materialiconsround/24px.svg", file_rounded_newspaper_b64z },
    { "file", ROUNDED, "request_quote", "src/file/request_quote/materialiconsround/24px.svg", file_rounded_request_quote_b64z },
    { "file", ROUNDED, "rule_folder", "src/file/rule_folder/materialiconsround/24px.svg", file_rounded_rule_folder_b64z },
    { "file", ROUNDED, "snippet_folder", "src/file/snippet_folder/materialiconsround/24px.svg", file_rounded_snippet_folder_b64z },
    { "file", ROUNDED, "text_snippet", "src/file/text_snippet/materialiconsround/24px.svg", file_rounded_text_snippet_b64z },
    { "file", ROUNDED, "topic", "src/file/topic/materialiconsround/24px.svg", file_rounded_topic_b64z },
    { "file", ROUNDED, "upload", "src/file/upload/materialiconsround/24px.svg", file_rounded_upload_b64z },
    { "file", ROUNDED, "upload_file", "src/file/upload_file/materialiconsround/24px.svg", file_rounded_upload_file_b64z },
    { "file", ROUNDED, "workspaces", "src/file/workspaces/materialiconsround/24px.svg", file_rounded_workspaces_b64z },
    { "file", SHARP, "approval", "src/file/approval/materialiconssharp/24px.svg", file_sharp_approval_b64z },
    { "file", SHARP, "attach_email", "src/file/attach_email/materialiconssharp/24px.svg", file_sharp_attach_email_b64z },
    { "file", SHARP, "attachment", "src/file/attachment/materialiconssharp/24px.svg", file_sharp_attachment_b64z },
    { "file", SHARP, "cloud", "src/file/cloud/materialiconssharp/24px.svg", file_sharp_cloud_b64z },
    { "file", SHARP, "cloud_circle", "src/file/cloud_circle/materialiconssharp/24px.svg", file_sharp_cloud_circle_b64z },
    { "file", SHARP, "cloud_done", "src/file/cloud_done/materialiconssharp/24px.svg", file_sharp_cloud_done_b64z },
    { "file", SHARP, "cloud_download", "src/file/cloud_download/materialiconssharp/24px.svg", file_sharp_cloud_download_b64z },
    { "file", SHARP, "cloud_off", "src/file/cloud_off/materialiconssharp/24px.svg", file_sharp_cloud_off_b64z },
    { "file", SHARP, "cloud_queue", "src/file/cloud_queue/materialiconssharp/24px.svg", file_sharp_cloud_queue_b64z },
    { "file", SHARP, "cloud_sync", "src/file/cloud_sync/materialiconssharp/24px.svg", file_sharp_cloud_sync_b64z },
    { "file", SHARP, "cloud_upload", "src/file/cloud_upload/materialiconssharp/24px.svg", file_sharp_cloud_upload_b64z },
    { "file", SHARP, "create_new_folder", "src/file/create_new_folder/materialiconssharp/24px.svg", file_sharp_create_new_folder_b64z },
    { "file", SHARP, "difference", "src/file/difference/materialiconssharp/24px.svg", file_sharp_difference_b64z },
    { "file", SHARP, "download", "src/file/download/materialiconssharp/24px.svg", file_sharp_download_b64z },
    { "file", SHARP, "download_done", "src/file/download_done/materialiconssharp/24px.svg", file_sharp_download_done_b64z },
    { "file", SHARP, "download_for_offline", "src/file/download_for_offline/materialiconssharp/24px.svg", file_sharp_download_for_offline_b64z },
    { "file", SHARP, "downloading", "src/file/downloading/materialiconssharp/24px.svg", file_sharp_downloading_b64z },
    { "file", SHARP, "drive_file_move", "src/file/drive_file_move/materialiconssharp/24px.svg", file_sharp_drive_file_move_b64z },
    { "file", SHARP, "drive_file_move_rtl", "src/file/drive_file_move_rtl/materialiconssharp/24px.svg", file_sharp_drive_file_move_rtl_b64z },
    { "file", SHARP, "drive_file_rename_outline", "src/file/drive_file_rename_outline/materialiconssharp/24px.svg", file_sharp_drive_file_rename_outline_b64z },
    { "file", SHARP, "drive_folder_upload", "src/file/drive_folder_upload/materialiconssharp/24px.svg", file_sharp_drive_folder_upload_b64z },
    { "file", SHARP, "file_download", "src/file/file_download/materialiconssharp/24px.svg", file_sharp_file_download_b64z },
    { "file", SHARP, "file_download_done", "src/file/file_download_done/materialiconssharp/24px.svg", file_sharp_file_download_done_b64z },
    { "file", SHARP, "file_download_off", "src/file/file_download_off/materialiconssharp/24px.svg", file_sharp_file_download_off_b64z },
    { "file", SHARP, "file_open", "src/file/file_open/materialiconssharp/24px.svg", file_sharp_file_open_b64z },
    { "file", SHARP, "file_upload", "src/file/file_upload/materialiconssharp/24px.svg", file_sharp_file_upload_b64z },
    { "file", SHARP, "folder", "src/file/folder/materialiconssharp/24px.svg", file_sharp_folder_b64z },
    { "file", SHARP, "folder_copy", "src/file/folder_copy/materialiconssharp/24px.svg", file_sharp_folder_copy_b64z },
    { "file", SHARP, "folder_delete", "src/file/folder_delete/materialiconssharp/24px.svg", file_sharp_folder_delete_b64z },
    { "file", SHARP, "folder_off", "src/file/folder_off/materialiconssharp/24px.svg", file_sharp_folder_off_b64z },
    { "file", SHARP, "folder_open", "src/file/folder_open/materialiconssharp/24px.svg", file_sharp_folder_open_b64z },
    { "file", SHARP, "folder_shared", "src/file/folder_shared/materialiconssharp/24px.svg", file_sharp_folder_shared_b64z },
    { "file", SHARP, "folder_zip", "src/file/folder_zip/materialiconssharp/24px.svg", file_sharp_folder_zip_b64z },
    { "file", SHARP, "format_overline", "src/file/format_overline/materialiconssharp/24px.svg", file_sharp_format_overline_b64z },
    { "file", SHARP, "grid_view", "src/file/grid_view/materialiconssharp/24px.svg", file_sharp_grid_view_b64z },
    { "file", SHARP, "newspaper", "src/file/newspaper/materialiconssharp/24px.svg", file_sharp_newspaper_b64z },
    { "file", SHARP, "request_quote", "src/file/request_quote/materialiconssharp/24px.svg", file_sharp_request_quote_b64z },
    { "file", SHARP, "rule_folder", "src/file/rule_folder/materialiconssharp/24px.svg", file_sharp_rule_folder_b64z },
    { "file", SHARP, "snippet_folder", "src/file/snippet_folder/materialiconssharp/24px.svg", file_sharp_snippet_folder_b64z },
    { "file", SHARP, "text_snippet", "src/file/text_snippet/materialiconssharp/24px.svg", file_sharp_text_snippet_b64z },
    { "file", SHARP, "topic", "src/file/topic/materialiconssharp/24px.svg", file_sharp_topic_b64z },
    { "file", SHARP, "upload", "src/file/upload/materialiconssharp/24px.svg", file_sharp_upload_b64z },
    { "file", SHARP, "upload_file", "src/file/upload_file/materialiconssharp/24px.svg", file_sharp_upload_file_b64z },
    { "file", SHARP, "workspaces", "src/file/workspaces/materialiconssharp/24px.svg", file_sharp_workspaces_b64z },
};

static const int kIconCount = (int)(sizeof(kIcons) / sizeof(kIcons[0]));

} // namespace file

#endif // UPP_MATERIAL_SYMBOLS_ICONS_FILE_H
